published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15646954469"
date = "2025-06-14"

[pkg.forc]
version = "0.68.7+nightly.20250614.e0724422c6"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250614/forc-binaries-0.68.7%2Bnightly.20250614.e0724422c6-darwin_amd64.tar.gz"
hash = "28255fc6d7b6253ec44c7ece2fbe49eca7d1a497d8e6573b4d9b1a4c87cebdb1"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250614/forc-binaries-0.68.7%2Bnightly.20250614.e0724422c6-darwin_arm64.tar.gz"
hash = "464923b6c2f82e88d64eb4b6b01d549de9e43b4e820597a2f18a94c4c9f291ed"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250614/forc-binaries-0.68.7%2Bnightly.20250614.e0724422c6-linux_amd64.tar.gz"
hash = "cc911ba2acc8e37e7b721b56147bf2610d7955e6fdf8c066276d5dbb7c237b92"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250614/forc-binaries-0.68.7%2Bnightly.20250614.e0724422c6-linux_arm64.tar.gz"
hash = "51d38cbcf78fd10e4082f8a6ba8abfd7d7ab958c227c31733758a5fdaed38661"

[pkg.forc-wallet]
version = "0.15.0+nightly.20250614.bddda681d3"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250614/forc-wallet-0.15.0%2Bnightly.20250614.bddda681d3-aarch64-apple-darwin.tar.gz"
hash = "64602af8d22379635991de299a5582c3325d34bf31588212c9dcdb90052f7783"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250614/forc-wallet-0.15.0%2Bnightly.20250614.bddda681d3-aarch64-unknown-linux-gnu.tar.gz"
hash = "baf3af45e36a36602fbd786fcbe65ff566231f93f5a6e6e24168a2ef3d6efb88"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250614/forc-wallet-0.15.0%2Bnightly.20250614.bddda681d3-x86_64-apple-darwin.tar.gz"
hash = "9c6771d40555cfa02a813018c6589ae62d99fef4b6ddef17568a3937983a9864"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250614/forc-wallet-0.15.0%2Bnightly.20250614.bddda681d3-x86_64-unknown-linux-gnu.tar.gz"
hash = "39055010cc56b6253380d0e71c1f28598ee1015286361805e290e0d779ebea46"

[pkg.fuel-core]
version = "0.44.0+nightly.20250614.6b6dd4a997"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250614/fuel-core-0.44.0%2Bnightly.20250614.6b6dd4a997-aarch64-apple-darwin.tar.gz"
hash = "42642181a9335d74aabf1a0c734f00f8e291fcb1fdad2cf3bebee1ab5929cbef"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250614/fuel-core-0.44.0%2Bnightly.20250614.6b6dd4a997-aarch64-unknown-linux-gnu.tar.gz"
hash = "f6657155e467c03c33dfd2608942f697195823764a45ede4d0b38afa8c66bf5b"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250614/fuel-core-0.44.0%2Bnightly.20250614.6b6dd4a997-x86_64-unknown-linux-gnu.tar.gz"
hash = "7af9b954e80e19a53cc7b2630b17628782d451a5b0d280a7b991d9bb49fae001"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250614.6b6dd4a997"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250614/fuel-core-0.44.0%2Bnightly.20250614.6b6dd4a997-aarch64-apple-darwin.tar.gz"
hash = "42642181a9335d74aabf1a0c734f00f8e291fcb1fdad2cf3bebee1ab5929cbef"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250614/fuel-core-0.44.0%2Bnightly.20250614.6b6dd4a997-aarch64-unknown-linux-gnu.tar.gz"
hash = "f6657155e467c03c33dfd2608942f697195823764a45ede4d0b38afa8c66bf5b"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250614/fuel-core-0.44.0%2Bnightly.20250614.6b6dd4a997-x86_64-unknown-linux-gnu.tar.gz"
hash = "7af9b954e80e19a53cc7b2630b17628782d451a5b0d280a7b991d9bb49fae001"
