published_by = "https://github.com/FuelLabs/fuelup/actions/runs/18299265647"
date = "2025-10-07"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251007.6ba79bc6fb"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251007/forc-wallet-0.15.2%2Bnightly.20251007.6ba79bc6fb-aarch64-apple-darwin.tar.gz"
hash = "4a5e0420b407b0780dd9367862d791e9e50edc64791c95d43968d1a4180c6a50"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251007/forc-wallet-0.15.2%2Bnightly.20251007.6ba79bc6fb-aarch64-unknown-linux-gnu.tar.gz"
hash = "09344b8ce57612512a925692c08d4e11b015c2bfb1114a6dc34a05b21322f08f"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251007/forc-wallet-0.15.2%2Bnightly.20251007.6ba79bc6fb-x86_64-apple-darwin.tar.gz"
hash = "cfe81e15f89983981317d8481998581b41e16fc7e45a42bd787dcc13db1c80a0"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251007/forc-wallet-0.15.2%2Bnightly.20251007.6ba79bc6fb-x86_64-unknown-linux-gnu.tar.gz"
hash = "c25d69a22274f9f2485bfcf0cefeccda542347d38dbf51cf2e9abbc8e5007c65"
