published_by = "https://github.com/FuelLabs/fuelup/actions/runs/14073481466"
date = "2025-03-26"

[pkg.forc]
version = "0.67.0+nightly.20250326.b28af85532"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250326/forc-binaries-0.67.0%2Bnightly.20250326.b28af85532-darwin_amd64.tar.gz"
hash = "45a7ad49aee9e7e93265b366770d9b6e36f6f56da2e69a9030eae4c2e76b30b6"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250326/forc-binaries-0.67.0%2Bnightly.20250326.b28af85532-darwin_arm64.tar.gz"
hash = "6b2b5fab7bb16bb68d7b96d8aac51fa713491795452d79dde4e7263ea6c27060"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250326/forc-binaries-0.67.0%2Bnightly.20250326.b28af85532-linux_amd64.tar.gz"
hash = "d43ba67dd676b2004060f612a70c8e8909cd3e7a0ed4a98b00c4995a2fee037a"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250326/forc-binaries-0.67.0%2Bnightly.20250326.b28af85532-linux_arm64.tar.gz"
hash = "da3f409426ae4352c01b00f1f64ba139b412407a35d6dbb7c278ff0e45274253"

[pkg.forc-wallet]
version = "0.13.0+nightly.20250326.90a8cb2dc4"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250326/forc-wallet-0.13.0%2Bnightly.20250326.90a8cb2dc4-aarch64-apple-darwin.tar.gz"
hash = "d942a5ef19501912b6d73927822692c75598765b4656b8b072e623cb43e8fedb"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250326/forc-wallet-0.13.0%2Bnightly.20250326.90a8cb2dc4-aarch64-unknown-linux-gnu.tar.gz"
hash = "c64cf89eecf5a122ab39a968c7a139857cae3aecd2001093ae456e01ff0cf28f"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250326/forc-wallet-0.13.0%2Bnightly.20250326.90a8cb2dc4-x86_64-apple-darwin.tar.gz"
hash = "b3c7128e72043dc33708ff162d749e7fb0c5dc2915185cb905e2da21d0f21bbe"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250326/forc-wallet-0.13.0%2Bnightly.20250326.90a8cb2dc4-x86_64-unknown-linux-gnu.tar.gz"
hash = "a5259eb60a2e6131e2b49fba7d2c889b2762ac30157e1835132f0fdd4520649c"
