published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15264670512"
date = "2025-05-27"

[pkg.forc]
version = "0.68.5+nightly.20250527.d972e423ac"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250527/forc-binaries-0.68.5%2Bnightly.20250527.d972e423ac-darwin_amd64.tar.gz"
hash = "158c7936f0e5c66327f205b56c6ae7fefc8023ec6f45014c24bcde0c76a8f0ac"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250527/forc-binaries-0.68.5%2Bnightly.20250527.d972e423ac-darwin_arm64.tar.gz"
hash = "5c5f1a2646f3f340ab6754a392546fe7f3b0ca19d6d591c8b00eab52d203b1e7"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250527/forc-binaries-0.68.5%2Bnightly.20250527.d972e423ac-linux_amd64.tar.gz"
hash = "f9413e8d2632e6b2e4433660aaa6171663fb42222f5f4da897401677f9397774"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250527/forc-binaries-0.68.5%2Bnightly.20250527.d972e423ac-linux_arm64.tar.gz"
hash = "846b2b9f7b6c6b7863f543b52200db93fd68e6a81dc4c1ed7931cf7777a1bf1c"

[pkg.forc-wallet]
version = "0.14.0+nightly.20250527.24883eb126"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250527/forc-wallet-0.14.0%2Bnightly.20250527.24883eb126-aarch64-apple-darwin.tar.gz"
hash = "25a019ceccf1f90dcf583369a78852c9b1648b364c42a47360438eaa175c14be"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250527/forc-wallet-0.14.0%2Bnightly.20250527.24883eb126-aarch64-unknown-linux-gnu.tar.gz"
hash = "e52cd18c9e116e12cb57a399a1743fd5a2e80595d3ead4f89b5ea21b035f1197"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250527/forc-wallet-0.14.0%2Bnightly.20250527.24883eb126-x86_64-apple-darwin.tar.gz"
hash = "af27792b11481634be32301238246467be4d425259c97c65e5e2d2fa46641f8d"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250527/forc-wallet-0.14.0%2Bnightly.20250527.24883eb126-x86_64-unknown-linux-gnu.tar.gz"
hash = "20d2b78fb8064740c9f1983ee9efc474612f0dee253e835bab14069af87db0ff"

[pkg.fuel-core]
version = "0.44.0+nightly.20250527.85b2356d51"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250527/fuel-core-0.44.0%2Bnightly.20250527.85b2356d51-aarch64-apple-darwin.tar.gz"
hash = "33aec03003d43d69765e3748f63d80b5480c59b7bdf21901e5b966298e0be3de"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250527/fuel-core-0.44.0%2Bnightly.20250527.85b2356d51-aarch64-unknown-linux-gnu.tar.gz"
hash = "72d58bccf413e2c9eff26c0a447017a55a3df0b5a7de9f6dcb9e9124c8f7e022"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250527.85b2356d51"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250527/fuel-core-0.44.0%2Bnightly.20250527.85b2356d51-aarch64-apple-darwin.tar.gz"
hash = "33aec03003d43d69765e3748f63d80b5480c59b7bdf21901e5b966298e0be3de"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250527/fuel-core-0.44.0%2Bnightly.20250527.85b2356d51-aarch64-unknown-linux-gnu.tar.gz"
hash = "72d58bccf413e2c9eff26c0a447017a55a3df0b5a7de9f6dcb9e9124c8f7e022"
