published_by = "https://github.com/FuelLabs/fuelup/actions/runs/10841415319"
date = "2024-09-13"

[pkg.forc]
version = "0.63.5+nightly.20240913.0fa1b9a4bc"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240913/forc-binaries-0.63.5%2Bnightly.20240913.0fa1b9a4bc-darwin_amd64.tar.gz"
hash = "8a7b8a27238d74240961b0ba7f9ba096734c7d491b6c72fed23a274894c9c9e7"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240913/forc-binaries-0.63.5%2Bnightly.20240913.0fa1b9a4bc-darwin_arm64.tar.gz"
hash = "d69e68437da4368f20cb96419104e305e70781965bb895a753e22d9a6cbcf7a3"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240913/forc-binaries-0.63.5%2Bnightly.20240913.0fa1b9a4bc-linux_amd64.tar.gz"
hash = "4e985a095045c28ab78c1fbec1aca19abf94f8465639dc6d4b89bd9126f2d655"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240913/forc-binaries-0.63.5%2Bnightly.20240913.0fa1b9a4bc-linux_arm64.tar.gz"
hash = "e152b4b0b96b446c7900afc30cd0d564e6a804882a5ad0d888dd3dd204af9237"

[pkg.forc-wallet]
version = "0.9.0+nightly.20240913.29d9b25c2c"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240913/forc-wallet-0.9.0%2Bnightly.20240913.29d9b25c2c-aarch64-apple-darwin.tar.gz"
hash = "aac9447ffaad48956886237794f239469e283d445fddf1d4387f629a7776b352"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240913/forc-wallet-0.9.0%2Bnightly.20240913.29d9b25c2c-aarch64-unknown-linux-gnu.tar.gz"
hash = "38b18a84a74cb7165361f45d92bc49d6f4591bff1cc4f70f12e66549d709c52d"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240913/forc-wallet-0.9.0%2Bnightly.20240913.29d9b25c2c-x86_64-apple-darwin.tar.gz"
hash = "23d96c6d899c4221c68d74c227a0b802124b2ab7b73a15094125e03a41e512ef"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240913/forc-wallet-0.9.0%2Bnightly.20240913.29d9b25c2c-x86_64-unknown-linux-gnu.tar.gz"
hash = "69534711f28e7a253a53d599c67e58cd9943235c71fa0282d341f39d29b39757"

[pkg.fuel-core]
version = "0.35.0+nightly.20240913.f308bae9c9"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240913/fuel-core-0.35.0%2Bnightly.20240913.f308bae9c9-aarch64-apple-darwin.tar.gz"
hash = "2ece37f388d2ccb2c7cf4774e8173e910e0785df6c2200daa212ab3ebe40628c"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240913/fuel-core-0.35.0%2Bnightly.20240913.f308bae9c9-aarch64-unknown-linux-gnu.tar.gz"
hash = "48e8f49d263412f17af4b2eebb2c383145530e294bae5ba0057b3ac289544bba"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240913/fuel-core-0.35.0%2Bnightly.20240913.f308bae9c9-x86_64-unknown-linux-gnu.tar.gz"
hash = "2bdd1a42dddc37eaadc4cd7dbf98aef629f89e5bf02ade71961eeb826206ed37"

[pkg.fuel-core-keygen]
version = "0.35.0+nightly.20240913.f308bae9c9"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240913/fuel-core-0.35.0%2Bnightly.20240913.f308bae9c9-aarch64-apple-darwin.tar.gz"
hash = "2ece37f388d2ccb2c7cf4774e8173e910e0785df6c2200daa212ab3ebe40628c"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240913/fuel-core-0.35.0%2Bnightly.20240913.f308bae9c9-aarch64-unknown-linux-gnu.tar.gz"
hash = "48e8f49d263412f17af4b2eebb2c383145530e294bae5ba0057b3ac289544bba"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240913/fuel-core-0.35.0%2Bnightly.20240913.f308bae9c9-x86_64-unknown-linux-gnu.tar.gz"
hash = "2bdd1a42dddc37eaadc4cd7dbf98aef629f89e5bf02ade71961eeb826206ed37"
