published_by = "https://github.com/FuelLabs/fuelup/actions/runs/17704595200"
date = "2025-09-14"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250914.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250914/forc-wallet-0.15.1%2Bnightly.20250914.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "e80ed7fcd230356a066c75d23e0b4dc159067d50e97d9480e20b7415c660d91b"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250914/forc-wallet-0.15.1%2Bnightly.20250914.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "f63b6a596e6478c50d4e4317e6415434f965630b90e4365799199d7369ef9eb3"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250914/forc-wallet-0.15.1%2Bnightly.20250914.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "03af0be1ca0dd2cfb9dbce47032a5ff45f5a05cbeb73edb10901bf292f8594e9"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250914/forc-wallet-0.15.1%2Bnightly.20250914.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "d45b69fb6a746883c5e948577c130380e4abf793e8e2440ecf4108d386eff2f4"
