published_by = "https://github.com/FuelLabs/fuelup/actions/runs/21343285363"
date = "2026-01-26"

[pkg.forc]
version = "0.70.1+nightly.20260126.20b32cfb44"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/forc-binaries-0.70.1%2Bnightly.20260126.20b32cfb44-darwin_amd64.tar.gz"
hash = "73f4e44c5c05f1d61dd30eb0b6ee3a6ead3e4a32db8780d7405795b60f7a499d"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/forc-binaries-0.70.1%2Bnightly.20260126.20b32cfb44-darwin_arm64.tar.gz"
hash = "7b15cb36b31a5156e9af0c16ae171c0269adc08d28a6d14b36fa4bb46b307c4e"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/forc-binaries-0.70.1%2Bnightly.20260126.20b32cfb44-linux_amd64.tar.gz"
hash = "7b5f2be2229244c6fd6eae0616d1aea829e14fed6d1b03fe3c530c39fba6abb4"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/forc-binaries-0.70.1%2Bnightly.20260126.20b32cfb44-linux_arm64.tar.gz"
hash = "a16098f677afa6fe78a20495dd778f2d8be4715ce86beedf32f54fa1a6a43602"

[pkg.forc-crypto]
version = "0.71.0+nightly.20260126.54cf9da7d3"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/forc-crypto-0.71.0%2Bnightly.20260126.54cf9da7d3-darwin_amd64.tar.gz"
hash = "2213d13852482e0e6cf2891b2375d3f6091781a7b0e959bacc3bf746c4c52307"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/forc-crypto-0.71.0%2Bnightly.20260126.54cf9da7d3-darwin_arm64.tar.gz"
hash = "18cd72e776d9885668540d9defd288055b8918cfdaed77c7d5a9223b3969101c"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/forc-crypto-0.71.0%2Bnightly.20260126.54cf9da7d3-linux_amd64.tar.gz"
hash = "c11592d10de7827db867826a0698b17e5f69a05c44e59274e8880a49c15bdaab"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/forc-crypto-0.71.0%2Bnightly.20260126.54cf9da7d3-linux_arm64.tar.gz"
hash = "f216caafc8c1724747ecdc3f1935d77f248705d8635308c28b1d078e3524675f"

[pkg.forc-node]
version = "0.71.2+nightly.20260126.54cf9da7d3"

[pkg.forc-node.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/forc-node-0.71.2%2Bnightly.20260126.54cf9da7d3-darwin_amd64.tar.gz"
hash = "0c758849ce5dd431e0662c49be3e4266164a685684f7b504a080036524957740"

[pkg.forc-node.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/forc-node-0.71.2%2Bnightly.20260126.54cf9da7d3-darwin_arm64.tar.gz"
hash = "ec05d5ed4e0eba305cf6d4711692ec08846efd37c11b751eebd591b3f8da57e8"

[pkg.forc-node.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/forc-node-0.71.2%2Bnightly.20260126.54cf9da7d3-linux_amd64.tar.gz"
hash = "3edd48cbdff4c7b2cab348b2a1215ca8ef6ca17ab48dfce22b5080e5f949ba5b"

[pkg.forc-node.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/forc-node-0.71.2%2Bnightly.20260126.54cf9da7d3-linux_arm64.tar.gz"
hash = "a44158534a3d24c401e383157920ebb221fde440cc5293006ccb113978ae595e"

[pkg.forc-wallet]
version = "0.16.2+nightly.20260126.54cf9da7d3"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/forc-wallet-0.16.2%2Bnightly.20260126.54cf9da7d3-darwin_amd64.tar.gz"
hash = "7dc8074d99a028183e1df854fc787e133ca94bea6322b9126b809b38bc3ca253"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/forc-wallet-0.16.2%2Bnightly.20260126.54cf9da7d3-darwin_arm64.tar.gz"
hash = "23c0e4b3622d88c292010094cf57477499554dfb15953d8962fce633ce8b553d"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/forc-wallet-0.16.2%2Bnightly.20260126.54cf9da7d3-linux_amd64.tar.gz"
hash = "cca505b797ed41296cfa8bf303a9ff30ea60b6341e009412038ea8757b4e3b61"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/forc-wallet-0.16.2%2Bnightly.20260126.54cf9da7d3-linux_arm64.tar.gz"
hash = "c681b5007b248de51673d20022685555cd264b45bd2894518ffc8c1c2d516926"

[pkg.fuel-core]
version = "0.47.1+nightly.20260126.579e1c2d78"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/fuel-core-0.47.1%2Bnightly.20260126.579e1c2d78-aarch64-apple-darwin.tar.gz"
hash = "f7070761e8dc9d9a8915bb2f37ff25126df1a50b6a74d440e8df471afa0f7076"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/fuel-core-0.47.1%2Bnightly.20260126.579e1c2d78-aarch64-unknown-linux-gnu.tar.gz"
hash = "53f9d43cad41791ced8bd692b1fc2e6c6d5da7476b1700b6b31c1e712f5f96fc"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/fuel-core-0.47.1%2Bnightly.20260126.579e1c2d78-x86_64-apple-darwin.tar.gz"
hash = "026044eed8e7155183f74b19f9dd4cf0d5e74ad849451d23af343cdd5e61c6f4"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/fuel-core-0.47.1%2Bnightly.20260126.579e1c2d78-x86_64-unknown-linux-gnu.tar.gz"
hash = "b8e852c249bc24d754ec8c561bdca924caf7f5de7119b35e94c1af46a7802dae"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20260126.579e1c2d78"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/fuel-core-0.47.1%2Bnightly.20260126.579e1c2d78-aarch64-apple-darwin.tar.gz"
hash = "f7070761e8dc9d9a8915bb2f37ff25126df1a50b6a74d440e8df471afa0f7076"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/fuel-core-0.47.1%2Bnightly.20260126.579e1c2d78-aarch64-unknown-linux-gnu.tar.gz"
hash = "53f9d43cad41791ced8bd692b1fc2e6c6d5da7476b1700b6b31c1e712f5f96fc"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/fuel-core-0.47.1%2Bnightly.20260126.579e1c2d78-x86_64-apple-darwin.tar.gz"
hash = "026044eed8e7155183f74b19f9dd4cf0d5e74ad849451d23af343cdd5e61c6f4"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260126/fuel-core-0.47.1%2Bnightly.20260126.579e1c2d78-x86_64-unknown-linux-gnu.tar.gz"
hash = "b8e852c249bc24d754ec8c561bdca924caf7f5de7119b35e94c1af46a7802dae"
