published_by = "https://github.com/FuelLabs/fuelup/actions/runs/19317449945"
date = "2025-11-13"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251113.279124d992"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251113/forc-wallet-0.15.2%2Bnightly.20251113.279124d992-aarch64-apple-darwin.tar.gz"
hash = "979720509816dc96e72edf1a4138613c4753bcbc000154fc1f7ba89e1de3dcaa"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251113/forc-wallet-0.15.2%2Bnightly.20251113.279124d992-aarch64-unknown-linux-gnu.tar.gz"
hash = "f9c2ec329db5bf55d823ed52ce3843c91d4f8b9184567cedd703dc8cc0603dac"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251113/forc-wallet-0.15.2%2Bnightly.20251113.279124d992-x86_64-apple-darwin.tar.gz"
hash = "903b1304daeda1b619102cf4662be202560341bcc718e331bae19240b2e5eb8e"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251113/forc-wallet-0.15.2%2Bnightly.20251113.279124d992-x86_64-unknown-linux-gnu.tar.gz"
hash = "b12cc723a885b278d3a440c97ee48a3298431893d121d3a0ef89ee1e519736a8"
