published_by = "https://github.com/FuelLabs/fuelup/actions/runs/13610746465"
date = "2025-03-02"

[pkg.forc]
version = "0.66.7+nightly.20250302.3d8eebac42"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250302/forc-binaries-0.66.7%2Bnightly.20250302.3d8eebac42-darwin_amd64.tar.gz"
hash = "49f3a691e9be7acca78cce924ae8ba07e266568b74210c5a14c9d06d4187b070"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250302/forc-binaries-0.66.7%2Bnightly.20250302.3d8eebac42-darwin_arm64.tar.gz"
hash = "8388c81f67384c3485d2fd8188edf7179afe47d984a2f8e4d46a8947cee9cb4c"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250302/forc-binaries-0.66.7%2Bnightly.20250302.3d8eebac42-linux_amd64.tar.gz"
hash = "2c9f4e2ea60761d3719f6767ce5dcb85a0c36ae5af26c3baae569b43f91b9ae0"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250302/forc-binaries-0.66.7%2Bnightly.20250302.3d8eebac42-linux_arm64.tar.gz"
hash = "2f00dfc4b645e352fc0467d86dcf752aa31e195f71669f36c7ff466c043d335c"

[pkg.forc-wallet]
version = "0.12.0+nightly.20250302.8d59dbc462"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250302/forc-wallet-0.12.0%2Bnightly.20250302.8d59dbc462-aarch64-apple-darwin.tar.gz"
hash = "ac3c1735b59be1cd197483bb97770463403975ed263a69893e3799f251393bda"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250302/forc-wallet-0.12.0%2Bnightly.20250302.8d59dbc462-aarch64-unknown-linux-gnu.tar.gz"
hash = "988341ea3d7e629f718f8d471b8912a1d3ada1fd3f537a9c24b2cda864105653"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250302/forc-wallet-0.12.0%2Bnightly.20250302.8d59dbc462-x86_64-apple-darwin.tar.gz"
hash = "b5c105e4ceb7b9b359cefcf5c03f94a71c6541eb53206fa6b07c23f5eb52c675"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250302/forc-wallet-0.12.0%2Bnightly.20250302.8d59dbc462-x86_64-unknown-linux-gnu.tar.gz"
hash = "ff32d4738de41d28c4ac506aa27c3a3e31c267c36f7ea6b1aabdcbd8853fe3e7"

[pkg.fuel-core]
version = "0.41.6+nightly.20250302.3cf86ab5b8"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250302/fuel-core-0.41.6%2Bnightly.20250302.3cf86ab5b8-aarch64-apple-darwin.tar.gz"
hash = "c8c6803b8fb792b00bda113245695b513432d5a984531e3f10a00af31234cd2a"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250302/fuel-core-0.41.6%2Bnightly.20250302.3cf86ab5b8-aarch64-unknown-linux-gnu.tar.gz"
hash = "d624d723e8eee805971546292cbad4fa4f8e2803bb11894e530286a903637b00"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250302/fuel-core-0.41.6%2Bnightly.20250302.3cf86ab5b8-x86_64-apple-darwin.tar.gz"
hash = "cc09c4f6e0123598cbd3be9cc562c729cd77aeb18dfef36666e939f16cac9f0f"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250302/fuel-core-0.41.6%2Bnightly.20250302.3cf86ab5b8-x86_64-unknown-linux-gnu.tar.gz"
hash = "6bdc85151fee97241cacfc46e90f301b2b8fffb72bfb63e843c9dd44f32e0758"

[pkg.fuel-core-keygen]
version = "0.41.6+nightly.20250302.3cf86ab5b8"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250302/fuel-core-0.41.6%2Bnightly.20250302.3cf86ab5b8-aarch64-apple-darwin.tar.gz"
hash = "c8c6803b8fb792b00bda113245695b513432d5a984531e3f10a00af31234cd2a"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250302/fuel-core-0.41.6%2Bnightly.20250302.3cf86ab5b8-aarch64-unknown-linux-gnu.tar.gz"
hash = "d624d723e8eee805971546292cbad4fa4f8e2803bb11894e530286a903637b00"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250302/fuel-core-0.41.6%2Bnightly.20250302.3cf86ab5b8-x86_64-apple-darwin.tar.gz"
hash = "cc09c4f6e0123598cbd3be9cc562c729cd77aeb18dfef36666e939f16cac9f0f"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250302/fuel-core-0.41.6%2Bnightly.20250302.3cf86ab5b8-x86_64-unknown-linux-gnu.tar.gz"
hash = "6bdc85151fee97241cacfc46e90f301b2b8fffb72bfb63e843c9dd44f32e0758"
