published_by = "https://github.com/FuelLabs/fuelup/actions/runs/10068913596"
date = "2024-07-24"

[pkg.forc]
version = "0.62.0+nightly.20240724.508554547f"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240724/forc-binaries-0.62.0%2Bnightly.20240724.508554547f-darwin_amd64.tar.gz"
hash = "7db0264a07c3847d93d71c06814dfefd09d02ea38ef0c52322c8e696431cfeef"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240724/forc-binaries-0.62.0%2Bnightly.20240724.508554547f-darwin_arm64.tar.gz"
hash = "52a0812a4f8bc9e7e7251b24f152023256653d9cb021de428670c177b9769074"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240724/forc-binaries-0.62.0%2Bnightly.20240724.508554547f-linux_amd64.tar.gz"
hash = "bf74c097a2fa2df49aaa67d6f3611031b83142524eacc87e4565ec1b5c56cac7"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240724/forc-binaries-0.62.0%2Bnightly.20240724.508554547f-linux_arm64.tar.gz"
hash = "7b44d0c17feccfd5ac8fb9faec2dbcfe62a49113eccb9202c14f433eacead101"

[pkg.forc-wallet]
version = "0.8.2+nightly.20240724.76e9796cbe"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240724/forc-wallet-0.8.2%2Bnightly.20240724.76e9796cbe-aarch64-apple-darwin.tar.gz"
hash = "28e7caf075774aa426f0611ebc549ea567db9be77ff6bc07efb4c1d0c9b56ae9"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240724/forc-wallet-0.8.2%2Bnightly.20240724.76e9796cbe-aarch64-unknown-linux-gnu.tar.gz"
hash = "feca6628d6ce98406989b3bfc33ef0706f240cac00f78ef61ec6f43e9b11ac1e"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240724/forc-wallet-0.8.2%2Bnightly.20240724.76e9796cbe-x86_64-apple-darwin.tar.gz"
hash = "ac2c22b09678317cdc9da4606d6c09eace58b7d245430227bbc60906840b5b52"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240724/forc-wallet-0.8.2%2Bnightly.20240724.76e9796cbe-x86_64-unknown-linux-gnu.tar.gz"
hash = "0f0b570523ec9b8534ffe796bb948a501d088ade9ab5450c74d6a9ca610486fa"

[pkg.fuel-core]
version = "0.31.0+nightly.20240724.25f269eab6"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240724/fuel-core-0.31.0%2Bnightly.20240724.25f269eab6-aarch64-apple-darwin.tar.gz"
hash = "2fac4bd720d6600db6de0af90918809d55c90c6d0adc5654702854c54ca0db5c"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240724/fuel-core-0.31.0%2Bnightly.20240724.25f269eab6-aarch64-unknown-linux-gnu.tar.gz"
hash = "ed9667d9d8d729834365caec97ff61817a2035302a574a6c44a2a5fe2da27bc4"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240724/fuel-core-0.31.0%2Bnightly.20240724.25f269eab6-x86_64-apple-darwin.tar.gz"
hash = "f172b9a758b50fd16b435c5e17066152a82145e33de45efcff1e78b4542c09e1"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240724/fuel-core-0.31.0%2Bnightly.20240724.25f269eab6-x86_64-unknown-linux-gnu.tar.gz"
hash = "bc9f98271299e711f371455c6c2954a38936c1477f363397c91fcdef765d2c90"

[pkg.fuel-core-keygen]
version = "0.31.0+nightly.20240724.25f269eab6"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240724/fuel-core-0.31.0%2Bnightly.20240724.25f269eab6-aarch64-apple-darwin.tar.gz"
hash = "2fac4bd720d6600db6de0af90918809d55c90c6d0adc5654702854c54ca0db5c"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240724/fuel-core-0.31.0%2Bnightly.20240724.25f269eab6-aarch64-unknown-linux-gnu.tar.gz"
hash = "ed9667d9d8d729834365caec97ff61817a2035302a574a6c44a2a5fe2da27bc4"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240724/fuel-core-0.31.0%2Bnightly.20240724.25f269eab6-x86_64-apple-darwin.tar.gz"
hash = "f172b9a758b50fd16b435c5e17066152a82145e33de45efcff1e78b4542c09e1"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240724/fuel-core-0.31.0%2Bnightly.20240724.25f269eab6-x86_64-unknown-linux-gnu.tar.gz"
hash = "bc9f98271299e711f371455c6c2954a38936c1477f363397c91fcdef765d2c90"
