published_by = "https://github.com/FuelLabs/fuelup/actions/runs/17873453446"
date = "2025-09-20"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250920.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250920/forc-wallet-0.15.1%2Bnightly.20250920.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "202a73f58ad364697eafa6d0f15921de1357d497c7821f337c47213fe3621984"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250920/forc-wallet-0.15.1%2Bnightly.20250920.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "2c46218f4964f9d2cdc2f5cfa28da50c2cca836d0e99b682e2b0256a572c8327"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250920/forc-wallet-0.15.1%2Bnightly.20250920.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "e8f81f864866103c116ef3a49fbc8f0590b59cfd7c663113769c521bf80c0cfa"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250920/forc-wallet-0.15.1%2Bnightly.20250920.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "cc41b1edf0f6b59ee5a778b05a221e1549120d15376b391859d8c1a8f998503b"
