published_by = "https://github.com/FuelLabs/fuelup/actions/runs/18639311667"
date = "2025-10-20"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251020.279124d992"

[pkg.forc-wallet.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251020/forc-wallet-0.15.2%2Bnightly.20251020.279124d992-aarch64-apple-darwin.tar.gz"
hash = "93f06513a5b3923c1df160b6e51430b0257efcc9552d3b645cfd59a4ba6676e9"

[pkg.forc-wallet.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251020/forc-wallet-0.15.2%2Bnightly.20251020.279124d992-aarch64-unknown-linux-gnu.tar.gz"
hash = "c95655c01a32a8609c21cc1035ec8a17b7487a4086cdf0f653b1b0f412c5f881"

[pkg.forc-wallet.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251020/forc-wallet-0.15.2%2Bnightly.20251020.279124d992-x86_64-apple-darwin.tar.gz"
hash = "849444e3998840688c0013411303291eb104390ed66e2e08f8d37b31dacc53eb"

[pkg.forc-wallet.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251020/forc-wallet-0.15.2%2Bnightly.20251020.279124d992-x86_64-unknown-linux-gnu.tar.gz"
hash = "ee181371ec4a5e2668ed1223c0b3b634c0e6d901fa77050263583825e939dd29"
