published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15456287862"
date = "2025-06-05"

[pkg.forc]
version = "0.68.7+nightly.20250605.58bf38ef9c"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250605/forc-binaries-0.68.7%2Bnightly.20250605.58bf38ef9c-darwin_amd64.tar.gz"
hash = "1aa3c9e08322a881f80675ab956f0e13a961f252be45141b5c83c0c383d99fbe"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250605/forc-binaries-0.68.7%2Bnightly.20250605.58bf38ef9c-darwin_arm64.tar.gz"
hash = "6dca2bab53403ba988dc75469798373e26b53b2f21de103dca89a5f61943879a"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250605/forc-binaries-0.68.7%2Bnightly.20250605.58bf38ef9c-linux_amd64.tar.gz"
hash = "21700eb1c17f9ce0e1238649e98a768a1786fcae44501d79d08d5b8c14b78957"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250605/forc-binaries-0.68.7%2Bnightly.20250605.58bf38ef9c-linux_arm64.tar.gz"
hash = "1a5ad22442af41b19e953428daba241171c52f667f7b7324f00dc06dd49a1cdd"

[pkg.forc-wallet]
version = "0.14.0+nightly.20250605.24883eb126"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250605/forc-wallet-0.14.0%2Bnightly.20250605.24883eb126-aarch64-apple-darwin.tar.gz"
hash = "0d4b517750ef120baa0b848a3071c4bbe70bdb34d01e173b78762ef67989eaf1"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250605/forc-wallet-0.14.0%2Bnightly.20250605.24883eb126-aarch64-unknown-linux-gnu.tar.gz"
hash = "88796d4c3cb07861d1998c200662603b08bb7600e0460d7b275834c9875cfdb9"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250605/forc-wallet-0.14.0%2Bnightly.20250605.24883eb126-x86_64-apple-darwin.tar.gz"
hash = "98d87e5cd325627654cb8f5c5fe025cdf075bfbe8165ae747c40ae2f331876dc"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250605/forc-wallet-0.14.0%2Bnightly.20250605.24883eb126-x86_64-unknown-linux-gnu.tar.gz"
hash = "9a6b8731602669091f5b2f67c56a9482eb115ef48f9eed63175406ddce4c68b7"

[pkg.fuel-core]
version = "0.44.0+nightly.20250605.49d0309dd1"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250605/fuel-core-0.44.0%2Bnightly.20250605.49d0309dd1-aarch64-apple-darwin.tar.gz"
hash = "39e8dfa56f64c78b042583328f68037beda5539671a70ad5121743d0f1cac37b"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250605/fuel-core-0.44.0%2Bnightly.20250605.49d0309dd1-aarch64-unknown-linux-gnu.tar.gz"
hash = "e3837deba6e7df51c3977b77873bf1caf31eaa4360a01aed270c3e3a396c65f1"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250605.49d0309dd1"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250605/fuel-core-0.44.0%2Bnightly.20250605.49d0309dd1-aarch64-apple-darwin.tar.gz"
hash = "39e8dfa56f64c78b042583328f68037beda5539671a70ad5121743d0f1cac37b"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250605/fuel-core-0.44.0%2Bnightly.20250605.49d0309dd1-aarch64-unknown-linux-gnu.tar.gz"
hash = "e3837deba6e7df51c3977b77873bf1caf31eaa4360a01aed270c3e3a396c65f1"
