published_by = "https://github.com/FuelLabs/fuelup/actions/runs/18766770587"
date = "2025-10-24"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251024.279124d992"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251024/forc-wallet-0.15.2%2Bnightly.20251024.279124d992-aarch64-apple-darwin.tar.gz"
hash = "04e05cb98c4222fddcc8f700a06ee1bb8ee930d55fbdf48906e9532edf29fcd0"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251024/forc-wallet-0.15.2%2Bnightly.20251024.279124d992-aarch64-unknown-linux-gnu.tar.gz"
hash = "0fa3b87605620d9fc27b4bd8129c88b266de120090fce865a5d73aecc701efdb"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251024/forc-wallet-0.15.2%2Bnightly.20251024.279124d992-x86_64-apple-darwin.tar.gz"
hash = "f2466c4e0cf59d421122425c20ee3ff10729194e7281bec78615df3bbb24351c"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251024/forc-wallet-0.15.2%2Bnightly.20251024.279124d992-x86_64-unknown-linux-gnu.tar.gz"
hash = "30c5c34dc4b11889b494d53c75ed8d9108c289e7ba2ef08a32d2fb2710cf88ab"
