published_by = "https://github.com/FuelLabs/fuelup/actions/runs/17196608000"
date = "2025-08-25"

[pkg.forc]
version = "0.69.1+nightly.20250825.a347631478"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250825/forc-binaries-0.69.1%2Bnightly.20250825.a347631478-darwin_amd64.tar.gz"
hash = "f80215b105524ab479babf10bfc272a14f344c8361f6b4fdf58dd5566af8ac37"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250825/forc-binaries-0.69.1%2Bnightly.20250825.a347631478-darwin_arm64.tar.gz"
hash = "f3d33905a261f39e8c0ee415938b1c3a84d37bdf52b8a1d81e3825d82e5ad1a8"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250825/forc-binaries-0.69.1%2Bnightly.20250825.a347631478-linux_amd64.tar.gz"
hash = "c58cc01bfe9adf151270942f20a34839301754791bd7a67cf92700572cd0553c"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250825/forc-binaries-0.69.1%2Bnightly.20250825.a347631478-linux_arm64.tar.gz"
hash = "c7e77ae071a7f97e8200af5d20df554d1be6e743e5b45f38b1e2b5fe97fae3b7"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250825.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250825/forc-wallet-0.15.1%2Bnightly.20250825.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "27d330eb45a7dfa46170af0136f050ee1949ed7bf4bfdbbf51175a123519d260"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250825/forc-wallet-0.15.1%2Bnightly.20250825.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "c16cd061f00aa8d22d925499869c8cabda62c8c043a763d7ac8e9cb36acf9010"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250825/forc-wallet-0.15.1%2Bnightly.20250825.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "febc91a0e97b79fead168f4780950a624b514789daf18204224df842fe367fb3"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250825/forc-wallet-0.15.1%2Bnightly.20250825.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "5d91056ba4f3dfbc17e402433f639fac4ab54f93932dca41a655b1336b266cf4"

[pkg.fuel-core]
version = "0.46.0+nightly.20250825.33238c6e10"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250825/fuel-core-0.46.0%2Bnightly.20250825.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "da9c983603f20eaff260648db50f0fcae009e6f083810f7903ad7cab2eb8c634"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250825/fuel-core-0.46.0%2Bnightly.20250825.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "3a7ee0800789e4cefaa076590a78f7cbf5c35b3849b399c8ac1f11cd4c116e96"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250825/fuel-core-0.46.0%2Bnightly.20250825.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "6cfc5a11c72077e8dba502fbb8446b43c4b773ceb27aa0526fee0c118148d5c6"

[pkg.fuel-core-keygen]
version = "0.46.0+nightly.20250825.33238c6e10"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250825/fuel-core-0.46.0%2Bnightly.20250825.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "da9c983603f20eaff260648db50f0fcae009e6f083810f7903ad7cab2eb8c634"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250825/fuel-core-0.46.0%2Bnightly.20250825.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "3a7ee0800789e4cefaa076590a78f7cbf5c35b3849b399c8ac1f11cd4c116e96"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250825/fuel-core-0.46.0%2Bnightly.20250825.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "6cfc5a11c72077e8dba502fbb8446b43c4b773ceb27aa0526fee0c118148d5c6"
