published_by = "https://github.com/FuelLabs/fuelup/actions/runs/17994137881"
date = "2025-09-25"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250925.9fea98d095"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250925/forc-wallet-0.15.1%2Bnightly.20250925.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "9a2076c500b056956b111c9dd6ccded34cc2f6d3a256fbf38c3e5e14d4ade752"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250925/forc-wallet-0.15.1%2Bnightly.20250925.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "38142f8ad6ec7ff1ba3ca5bef93083b03ab37bb713ac448bb26f4e957901b0e2"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250925/forc-wallet-0.15.1%2Bnightly.20250925.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "66cf480d70c0d69bffffbd17d65f5ceb7e325a6f722d0241f31dee27edbbf8ec"
