published_by = "https://github.com/FuelLabs/fuelup/actions/runs/17312121117"
date = "2025-08-29"

[pkg.forc]
version = "0.69.1+nightly.20250829.d49cf8e92c"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250829/forc-binaries-0.69.1%2Bnightly.20250829.d49cf8e92c-darwin_amd64.tar.gz"
hash = "93098da0edb55956ef9768cbdfbff1384c5b974b550a512488c7f8181a01be61"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250829/forc-binaries-0.69.1%2Bnightly.20250829.d49cf8e92c-darwin_arm64.tar.gz"
hash = "3000fe79d37662e94a93d46cf9e6c639f2c53505868f3e21a9920475aa486f37"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250829/forc-binaries-0.69.1%2Bnightly.20250829.d49cf8e92c-linux_amd64.tar.gz"
hash = "44afe9f53d04e56d586657a6b49ec86b45e10a499892e82e22d40b67095d1087"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250829/forc-binaries-0.69.1%2Bnightly.20250829.d49cf8e92c-linux_arm64.tar.gz"
hash = "196d8b931c141569e266d14fef004df13e958b3e9bee902b1e72bb98b4acc085"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250829.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250829/forc-wallet-0.15.1%2Bnightly.20250829.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "e58b93b6329393b59ffcd1dbdaf29f11d555090543174488c9d7f7b76d9db265"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250829/forc-wallet-0.15.1%2Bnightly.20250829.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "9e5e35d15eecb9edf67d6bd06da4fad7ee7142a215bae0b560365540ffff6483"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250829/forc-wallet-0.15.1%2Bnightly.20250829.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "f2ed030ab49f2f52593948aa3de17420d75fe4dccc237b3a4d5ae50a64a3f2a2"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250829/forc-wallet-0.15.1%2Bnightly.20250829.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "7dae8dc175048f2786f3e8477ecd9b5ccaf533d12146b290bf1b70ec780a1ce1"

[pkg.fuel-core]
version = "0.46.0+nightly.20250829.33238c6e10"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250829/fuel-core-0.46.0%2Bnightly.20250829.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "358d10de304af3c47a6ddb870acc2bbb6c5692f4e45808922a09af9dc6ab5399"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250829/fuel-core-0.46.0%2Bnightly.20250829.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "65c788579f2d4f759b8bf3beb7fd5a5db577e166a11730944a51d983b59a079c"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250829/fuel-core-0.46.0%2Bnightly.20250829.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "af826e30ceb90fd595926d186d59a8de386cffc3f82e5ef3dded7ab6821733a3"

[pkg.fuel-core-keygen]
version = "0.46.0+nightly.20250829.33238c6e10"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250829/fuel-core-0.46.0%2Bnightly.20250829.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "358d10de304af3c47a6ddb870acc2bbb6c5692f4e45808922a09af9dc6ab5399"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250829/fuel-core-0.46.0%2Bnightly.20250829.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "65c788579f2d4f759b8bf3beb7fd5a5db577e166a11730944a51d983b59a079c"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250829/fuel-core-0.46.0%2Bnightly.20250829.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "af826e30ceb90fd595926d186d59a8de386cffc3f82e5ef3dded7ab6821733a3"
