published_by = "https://github.com/FuelLabs/fuelup/actions/runs/18180558794"
date = "2025-10-02"

[pkg.forc-wallet]
version = "0.15.1+nightly.20251002.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251002/forc-wallet-0.15.1%2Bnightly.20251002.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "e09420871d528f4b58c2f7ff6e69d683312d8f8801aade6edb6441c2449803f0"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251002/forc-wallet-0.15.1%2Bnightly.20251002.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "453873721e2bcd2a66963be134d58e13974c3cd46f9d20d9f0eb6573a9706bd1"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251002/forc-wallet-0.15.1%2Bnightly.20251002.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "e1664a9ab42ea5d96809b356b9a4132e07e309384321957a31babbf20a3f94e1"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251002/forc-wallet-0.15.1%2Bnightly.20251002.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "9e9a8365cd468697a544fb9dd123934f51ccb9d3cb4c241f7f158741bca42ed9"
