published_by = "https://github.com/FuelLabs/fuelup/actions/runs/16459292093"
date = "2025-07-23"

[pkg.forc]
version = "0.69.1+nightly.20250723.a5e61488da"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250723/forc-binaries-0.69.1%2Bnightly.20250723.a5e61488da-darwin_amd64.tar.gz"
hash = "e68f19e2f4f7b53b5ee028528e19908156fcbfe1a9224e83901a16b7b31b1dcd"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250723/forc-binaries-0.69.1%2Bnightly.20250723.a5e61488da-darwin_arm64.tar.gz"
hash = "bb1d886e42cec988c9fb3665c783d290cfb6014898b84017882708a4c395fcd1"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250723/forc-binaries-0.69.1%2Bnightly.20250723.a5e61488da-linux_amd64.tar.gz"
hash = "26bf0139f8975eac1c26249378aee925f9c77d6146d90a58fb80497405ce7682"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250723/forc-binaries-0.69.1%2Bnightly.20250723.a5e61488da-linux_arm64.tar.gz"
hash = "1d46242f2a74fad8028ba55c77f488cc3aec4ca0bbc83fd9b61635a963d4462f"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250723.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250723/forc-wallet-0.15.1%2Bnightly.20250723.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "866e562c6e9f0714ef5e0d19db5ed49fa5d1a92bfe4fd43cf55e763e42883936"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250723/forc-wallet-0.15.1%2Bnightly.20250723.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "c37b951bef5a99ca02244abb2a3c15d2023e174c120183b4cb7d472918ab2b03"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250723/forc-wallet-0.15.1%2Bnightly.20250723.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "828315853c4dcbb8e14ac4c617340af0d3de329e7bdd7a15073b26361ca56d1d"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250723/forc-wallet-0.15.1%2Bnightly.20250723.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "fb7a5ad110ce7bdcd47162c75b1ceac082e0c841ccec60ccfc0566929df1d77e"

[pkg.fuel-core]
version = "0.44.0+nightly.20250723.5108c931a7"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250723/fuel-core-0.44.0%2Bnightly.20250723.5108c931a7-aarch64-apple-darwin.tar.gz"
hash = "b3f64dde606868c3497c17acbba1758668fa300150373676aeec27579d6d00c2"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250723/fuel-core-0.44.0%2Bnightly.20250723.5108c931a7-aarch64-unknown-linux-gnu.tar.gz"
hash = "a8a3c4d2bd7cc293fa932c8a6274b78c7f6011ca0e0c6a6bbf4aacdd18560b2e"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250723/fuel-core-0.44.0%2Bnightly.20250723.5108c931a7-x86_64-unknown-linux-gnu.tar.gz"
hash = "174911a51aa81b633a8d31d2025c0c4992ce10b391affc538d08bdbd1e6bfb39"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250723.5108c931a7"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250723/fuel-core-0.44.0%2Bnightly.20250723.5108c931a7-aarch64-apple-darwin.tar.gz"
hash = "b3f64dde606868c3497c17acbba1758668fa300150373676aeec27579d6d00c2"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250723/fuel-core-0.44.0%2Bnightly.20250723.5108c931a7-aarch64-unknown-linux-gnu.tar.gz"
hash = "a8a3c4d2bd7cc293fa932c8a6274b78c7f6011ca0e0c6a6bbf4aacdd18560b2e"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250723/fuel-core-0.44.0%2Bnightly.20250723.5108c931a7-x86_64-unknown-linux-gnu.tar.gz"
hash = "174911a51aa81b633a8d31d2025c0c4992ce10b391affc538d08bdbd1e6bfb39"
