published_by = "https://github.com/FuelLabs/fuelup/actions/runs/11079910675"
date = "2024-09-28"

[pkg.forc]
version = "0.64.0+nightly.20240928.344f1c55c9"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240928/forc-binaries-0.64.0%2Bnightly.20240928.344f1c55c9-darwin_amd64.tar.gz"
hash = "38c54b2d72f8a888202733d4a9d4ab217de87cfd88ea482d5d1ec1e6b4600afc"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240928/forc-binaries-0.64.0%2Bnightly.20240928.344f1c55c9-darwin_arm64.tar.gz"
hash = "aa35b69c0688649438754e2d1e6f714cf7b5819c26352b0322abedd13b7bd68c"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240928/forc-binaries-0.64.0%2Bnightly.20240928.344f1c55c9-linux_amd64.tar.gz"
hash = "6a6648a2ae2d0e62ad2f141d8dda159eaf1c501d8cce68b6df46c7513693c6da"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240928/forc-binaries-0.64.0%2Bnightly.20240928.344f1c55c9-linux_arm64.tar.gz"
hash = "31c681988b57e9a3ca2b29f9d46e07d29eb5434293be849653d8f08acccb4875"

[pkg.forc-wallet]
version = "0.9.1+nightly.20240928.c49415c671"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240928/forc-wallet-0.9.1%2Bnightly.20240928.c49415c671-aarch64-apple-darwin.tar.gz"
hash = "3974c54a13765a440d71c7e63dc9a9ec79be6a837d77040af100d3d70819e7cb"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240928/forc-wallet-0.9.1%2Bnightly.20240928.c49415c671-aarch64-unknown-linux-gnu.tar.gz"
hash = "cb1933e0fc0e60ab652987a61d4416b4d0a944fe0a7e1076f49f2f907874eba9"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240928/forc-wallet-0.9.1%2Bnightly.20240928.c49415c671-x86_64-apple-darwin.tar.gz"
hash = "a63adf172f58e8b5e4717f0692132175cf8436972e33293c5feac70a977e6874"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240928/forc-wallet-0.9.1%2Bnightly.20240928.c49415c671-x86_64-unknown-linux-gnu.tar.gz"
hash = "859633f4a938cdcc880c3b024eebf3ca9477af497cbd2222f561ecc0bb29891d"

[pkg.fuel-core]
version = "0.36.0+nightly.20240928.4a55b7de69"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240928/fuel-core-0.36.0%2Bnightly.20240928.4a55b7de69-aarch64-apple-darwin.tar.gz"
hash = "1a6b01ad85d0c8268e7b5352f13765cb7baa7c9819915e6a29beef931601acb6"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240928/fuel-core-0.36.0%2Bnightly.20240928.4a55b7de69-aarch64-unknown-linux-gnu.tar.gz"
hash = "69a14520e12cad27c6a7a1a41f554efa6ad931ef791084f27245cdf6f530a1f6"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240928/fuel-core-0.36.0%2Bnightly.20240928.4a55b7de69-x86_64-unknown-linux-gnu.tar.gz"
hash = "051561c1c4130e1cb80c11947ecacfcbb7deda3a192491ceadc3f8f3f81aff73"

[pkg.fuel-core-keygen]
version = "0.36.0+nightly.20240928.4a55b7de69"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240928/fuel-core-0.36.0%2Bnightly.20240928.4a55b7de69-aarch64-apple-darwin.tar.gz"
hash = "1a6b01ad85d0c8268e7b5352f13765cb7baa7c9819915e6a29beef931601acb6"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240928/fuel-core-0.36.0%2Bnightly.20240928.4a55b7de69-aarch64-unknown-linux-gnu.tar.gz"
hash = "69a14520e12cad27c6a7a1a41f554efa6ad931ef791084f27245cdf6f530a1f6"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240928/fuel-core-0.36.0%2Bnightly.20240928.4a55b7de69-x86_64-unknown-linux-gnu.tar.gz"
hash = "051561c1c4130e1cb80c11947ecacfcbb7deda3a192491ceadc3f8f3f81aff73"
