published_by = "https://github.com/FuelLabs/fuelup/actions/runs/21771729771"
date = "2026-02-07"

[pkg.forc]
version = "0.70.1+nightly.20260207.f0a848ddd6"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-binaries-0.70.1%2Bnightly.20260207.f0a848ddd6-darwin_amd64.tar.gz"
hash = "21e1ecae9847a200d3d2ba6294d66f37bf86135ebc9db5c8f209f9422b4957b7"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-binaries-0.70.1%2Bnightly.20260207.f0a848ddd6-darwin_arm64.tar.gz"
hash = "dc55df51fa1fba23fff6f1ebe11dbc26ce9e2c32b6864ea534a6459d9da56e15"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-binaries-0.70.1%2Bnightly.20260207.f0a848ddd6-linux_amd64.tar.gz"
hash = "761aef2d7a2bfdfae07ac4bb82892522b7dc3c28947b102e947cb00aa2bf3012"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-binaries-0.70.1%2Bnightly.20260207.f0a848ddd6-linux_arm64.tar.gz"
hash = "9e8a6affc6e2974d9fee5720b7d85d71cdd427ab44904da60a724ae69a80d9f3"

[pkg.forc-client]
version = "0.71.1+nightly.20260207.063e4c5c49"

[pkg.forc-client.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-client-0.71.1%2Bnightly.20260207.063e4c5c49-darwin_amd64.tar.gz"
hash = "18ecaa94f7093679fc303584411d4a28c1de50fa477d979148c84bc56e22b9b8"

[pkg.forc-client.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-client-0.71.1%2Bnightly.20260207.063e4c5c49-darwin_arm64.tar.gz"
hash = "f5c4e7b92aec7ddffca8749cc67e2f18cfa26a7fb6f8d4e5694186e49e6d0b4b"

[pkg.forc-client.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-client-0.71.1%2Bnightly.20260207.063e4c5c49-linux_amd64.tar.gz"
hash = "9565ccf46206112d0ce24bfe26ed61bc45a154188b0f93a9f8ad0e5a033733a8"

[pkg.forc-client.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-client-0.71.1%2Bnightly.20260207.063e4c5c49-linux_arm64.tar.gz"
hash = "d0affa5f437a8e48de1f0d9796e328ab9fb1c233543394a9175133d3ea100e89"

[pkg.forc-crypto]
version = "0.71.0+nightly.20260207.063e4c5c49"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-crypto-0.71.0%2Bnightly.20260207.063e4c5c49-darwin_amd64.tar.gz"
hash = "0d03b55012926d6576f0f0741c329be971f5aeccd64d7bc51845b12073060249"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-crypto-0.71.0%2Bnightly.20260207.063e4c5c49-darwin_arm64.tar.gz"
hash = "852a33ca7c7049de83107bc2c5e9af4e8155534b0897d63a657d01b2f0486baf"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-crypto-0.71.0%2Bnightly.20260207.063e4c5c49-linux_amd64.tar.gz"
hash = "8ec688490e42554e490de8fcd6d08a36abee12b7e87c405d7691a77fd7ed4165"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-crypto-0.71.0%2Bnightly.20260207.063e4c5c49-linux_arm64.tar.gz"
hash = "530630ed1a58fba26076be16ba9755c5239570add2f0920601173e2f080bb48b"

[pkg.forc-node]
version = "0.71.2+nightly.20260207.063e4c5c49"

[pkg.forc-node.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-node-0.71.2%2Bnightly.20260207.063e4c5c49-darwin_amd64.tar.gz"
hash = "f595677718d7267a727f525c24ab758c6b8a6ee3c61af32606b0c610cfbb0517"

[pkg.forc-node.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-node-0.71.2%2Bnightly.20260207.063e4c5c49-darwin_arm64.tar.gz"
hash = "2542c7d8fcf99897e5975646bfa99bcefd9f4e5d12b1425966bdb5072c40dcaf"

[pkg.forc-node.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-node-0.71.2%2Bnightly.20260207.063e4c5c49-linux_amd64.tar.gz"
hash = "16bb9149996c7c715151422c546fd58cb621d130fe38f5d8ddc03defe8651276"

[pkg.forc-node.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-node-0.71.2%2Bnightly.20260207.063e4c5c49-linux_arm64.tar.gz"
hash = "f65bb89be3131ecbe8d76887982d80806660501c0603a726d7318827e4e79515"

[pkg.forc-wallet]
version = "0.16.2+nightly.20260207.063e4c5c49"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-wallet-0.16.2%2Bnightly.20260207.063e4c5c49-darwin_amd64.tar.gz"
hash = "d3e1e19f8d89433ecc0f307c373493909619c69c59509cff2961076a0829a027"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-wallet-0.16.2%2Bnightly.20260207.063e4c5c49-darwin_arm64.tar.gz"
hash = "32b5d71e2cbacb35c2a32950a5081ac3fad45c8d6c55588ce4d1aad368349863"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-wallet-0.16.2%2Bnightly.20260207.063e4c5c49-linux_amd64.tar.gz"
hash = "fc16b8f7181d90d620845de47d6a15bf92f3610eb2d06378434805be9d0c7823"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/forc-wallet-0.16.2%2Bnightly.20260207.063e4c5c49-linux_arm64.tar.gz"
hash = "0877076a0a94bf54700c585a17c912f669282a2adb0b9082866da46a4433c938"

[pkg.fuel-core]
version = "0.47.1+nightly.20260207.697e692a08"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/fuel-core-0.47.1%2Bnightly.20260207.697e692a08-aarch64-unknown-linux-gnu.tar.gz"
hash = "39e37edfd08a873573cc72e44d11703fff8466106b9a0cae7f4877370fb6c8a1"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/fuel-core-0.47.1%2Bnightly.20260207.697e692a08-x86_64-unknown-linux-gnu.tar.gz"
hash = "839fc19b2ae8ec43ccc110d92318f5dbd7d2cdcf8755a34c421e26ebc6985f82"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20260207.697e692a08"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/fuel-core-0.47.1%2Bnightly.20260207.697e692a08-aarch64-unknown-linux-gnu.tar.gz"
hash = "39e37edfd08a873573cc72e44d11703fff8466106b9a0cae7f4877370fb6c8a1"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260207/fuel-core-0.47.1%2Bnightly.20260207.697e692a08-x86_64-unknown-linux-gnu.tar.gz"
hash = "839fc19b2ae8ec43ccc110d92318f5dbd7d2cdcf8755a34c421e26ebc6985f82"
