published_by = "https://github.com/FuelLabs/fuelup/actions/runs/18082926348"
date = "2025-09-29"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250929.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250929/forc-wallet-0.15.1%2Bnightly.20250929.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "0afb5e500ba5d7819f4b8797421183c6e7ae9cc27ac7d3743da71f453d474e58"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250929/forc-wallet-0.15.1%2Bnightly.20250929.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "5d087d3721ce9b78c6313458f04c729150ab9eeb4f29017554bfe4e182f38f4d"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250929/forc-wallet-0.15.1%2Bnightly.20250929.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "3a85340da9b17951201da08c142f8477c0278dfb721d305a10fadc94b7c6874b"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250929/forc-wallet-0.15.1%2Bnightly.20250929.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "ced848f2e649bbd455f8ba84a94bd000c6dba7cf7d46fe628bddc40c3fbf1c45"
