published_by = "https://github.com/FuelLabs/fuelup/actions/runs/20513762577"
date = "2025-12-26"

[pkg.forc]
version = "0.70.1+nightly.20251226.cc8f867043"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/forc-binaries-0.70.1%2Bnightly.20251226.cc8f867043-darwin_amd64.tar.gz"
hash = "ddcbfdd8e7e6caebe33c194929d11927613f1f961ba6db51ff96112bdd12d34c"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/forc-binaries-0.70.1%2Bnightly.20251226.cc8f867043-darwin_arm64.tar.gz"
hash = "2cf624fafccaf5ab6bf758f049b13ebb32b4da0e0119524883a8ab825f671f49"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/forc-binaries-0.70.1%2Bnightly.20251226.cc8f867043-linux_amd64.tar.gz"
hash = "24a5e407031e6c6de3ac8768aff5b86941bf8a05de326355d8f8ed6ef8f1ad9d"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/forc-binaries-0.70.1%2Bnightly.20251226.cc8f867043-linux_arm64.tar.gz"
hash = "ff0b9a8b6dabcff83df620f243ea2106eeb9b56bdf6fa3693530d54ff720aa94"

[pkg.forc-crypto]
version = "0.71.0+nightly.20251226.c10463b0cb"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/forc-crypto-0.71.0%2Bnightly.20251226.c10463b0cb-darwin_amd64.tar.gz"
hash = "17f766f6c33e09a0af99b46c77da9267268ebf251bc2235bc6515196c16782d1"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/forc-crypto-0.71.0%2Bnightly.20251226.c10463b0cb-darwin_arm64.tar.gz"
hash = "0d19c2f9d7186fda7acdb287f51e59d48a59a42f5577952fb3584aee6c6668ac"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/forc-crypto-0.71.0%2Bnightly.20251226.c10463b0cb-linux_amd64.tar.gz"
hash = "55a6ce78fdcf3c96fb35a43b2962d944011ed3b3a773ecdd010bf7bb416c82eb"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/forc-crypto-0.71.0%2Bnightly.20251226.c10463b0cb-linux_arm64.tar.gz"
hash = "02ea0b2dfd8ba0e1edcc90e2645589327aa7c80bc620c6ee3da53eeb2521b251"

[pkg.forc-wallet]
version = "0.16.2+nightly.20251226.c10463b0cb"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/forc-wallet-0.16.2%2Bnightly.20251226.c10463b0cb-darwin_amd64.tar.gz"
hash = "6029f66aa3f9e8ba0e61c35154a75f6dbbaa32028d261e74a91ac89388c64386"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/forc-wallet-0.16.2%2Bnightly.20251226.c10463b0cb-darwin_arm64.tar.gz"
hash = "df7df8bd7297824bd17a2d779dbaf825965464af547f54c765e447c692c1d61d"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/forc-wallet-0.16.2%2Bnightly.20251226.c10463b0cb-linux_amd64.tar.gz"
hash = "c9cfb23f9b893df362130d21bd387cc712863014b1714a8492030b2596d57f45"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/forc-wallet-0.16.2%2Bnightly.20251226.c10463b0cb-linux_arm64.tar.gz"
hash = "a9395b34329ee76be24ad6435219e1ae51acd13c872b56e8d08c86e8df8d98c3"

[pkg.fuel-core]
version = "0.47.1+nightly.20251226.6889ed156b"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/fuel-core-0.47.1%2Bnightly.20251226.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "6c831789a8485ffdd39c815357f06abdc31e6d3629192ee96de3b4ab785a2f0e"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/fuel-core-0.47.1%2Bnightly.20251226.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "ae9ea31c81ff1204ce5379fed468b6c260d5787eb2cfe718365a53e49e43eead"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/fuel-core-0.47.1%2Bnightly.20251226.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "b4b6dfee875e78acbd3bc208c1df170821a7d29b191bf8b3881769564fb827ae"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/fuel-core-0.47.1%2Bnightly.20251226.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "e5890b072fd4e263c379e8a1276b10a2a210787e26157a6070f055511a0f1af0"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20251226.6889ed156b"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/fuel-core-0.47.1%2Bnightly.20251226.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "6c831789a8485ffdd39c815357f06abdc31e6d3629192ee96de3b4ab785a2f0e"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/fuel-core-0.47.1%2Bnightly.20251226.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "ae9ea31c81ff1204ce5379fed468b6c260d5787eb2cfe718365a53e49e43eead"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/fuel-core-0.47.1%2Bnightly.20251226.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "b4b6dfee875e78acbd3bc208c1df170821a7d29b191bf8b3881769564fb827ae"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251226/fuel-core-0.47.1%2Bnightly.20251226.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "e5890b072fd4e263c379e8a1276b10a2a210787e26157a6070f055511a0f1af0"
