published_by = "https://github.com/FuelLabs/fuelup/actions/runs/20734781267"
date = "2026-01-06"

[pkg.forc]
version = "0.70.1+nightly.20260106.cc8f867043"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/forc-binaries-0.70.1%2Bnightly.20260106.cc8f867043-darwin_amd64.tar.gz"
hash = "4bc5cd5dfaf51203ee0da2552571879e91ab5ebe6baa141b211198af5c1ee98a"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/forc-binaries-0.70.1%2Bnightly.20260106.cc8f867043-darwin_arm64.tar.gz"
hash = "7dfaa722fb6ce40dd0908cd3ff1ba2d2743fdc45821333ef418807d7252860aa"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/forc-binaries-0.70.1%2Bnightly.20260106.cc8f867043-linux_amd64.tar.gz"
hash = "31ed0e6d9bb5c4bcc7dfd80b7533b8261790b4b99dbf4a637cbfb03eea0c334e"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/forc-binaries-0.70.1%2Bnightly.20260106.cc8f867043-linux_arm64.tar.gz"
hash = "0c1f4e0d357703b89408aa9307c4f3ccce2469fbd6cbea087e1d87a21ad65866"

[pkg.forc-crypto]
version = "0.71.0+nightly.20260106.c10463b0cb"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/forc-crypto-0.71.0%2Bnightly.20260106.c10463b0cb-darwin_amd64.tar.gz"
hash = "f38818d7ba603603afec80df4e51871aa33637792d55ad8c25e0f5253277038c"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/forc-crypto-0.71.0%2Bnightly.20260106.c10463b0cb-darwin_arm64.tar.gz"
hash = "52128224692f526a2696a0f2a9bc757101c31f887dc08b2ab56aec8aadf338c5"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/forc-crypto-0.71.0%2Bnightly.20260106.c10463b0cb-linux_amd64.tar.gz"
hash = "0ae96814c385cf7d21a4fa8648e557b47da5943bfce7353d6b6bf0f244995d2a"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/forc-crypto-0.71.0%2Bnightly.20260106.c10463b0cb-linux_arm64.tar.gz"
hash = "a755001c1f3886927c0f993fff831759f7971ee75dfc732bb8cbf6ba1a81ad8a"

[pkg.forc-wallet]
version = "0.16.2+nightly.20260106.c10463b0cb"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/forc-wallet-0.16.2%2Bnightly.20260106.c10463b0cb-darwin_amd64.tar.gz"
hash = "dbec988c09354ca942d14a992525c46eb7ec36095ead8c31c06f86d6c291ec5c"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/forc-wallet-0.16.2%2Bnightly.20260106.c10463b0cb-darwin_arm64.tar.gz"
hash = "af2cddf9c68c34f2cecf98c0be0da8e5816b93639a8b29e72a7f1a97608cdc12"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/forc-wallet-0.16.2%2Bnightly.20260106.c10463b0cb-linux_amd64.tar.gz"
hash = "89e3dcb729193c1e006b67cffd68f386e201f6b840a04a389803d8fef4d1adf0"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/forc-wallet-0.16.2%2Bnightly.20260106.c10463b0cb-linux_arm64.tar.gz"
hash = "cf9d0d3b4e8370728507c56aecd54aaff12685fe798b4bbecaae3c9d67f465cc"

[pkg.fuel-core]
version = "0.47.1+nightly.20260106.6889ed156b"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/fuel-core-0.47.1%2Bnightly.20260106.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "f7407095c1ec72047e4f97e84c639b1520d9fb85886754be5dff5e714cb89432"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/fuel-core-0.47.1%2Bnightly.20260106.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "ee64b95cc456e636f8639b24ef88404ad095aee8b2e48a9ec333317040855d0b"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/fuel-core-0.47.1%2Bnightly.20260106.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "d8fbd6a2bc5c515c763f566a316f45307b4e3f6ba872f2fbdfad5f73c109f42b"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/fuel-core-0.47.1%2Bnightly.20260106.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "ca36e15cffcbaeb320e098ad0f2cc1682b827563af7db4cde4c6ab6eac6aa2fc"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20260106.6889ed156b"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/fuel-core-0.47.1%2Bnightly.20260106.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "f7407095c1ec72047e4f97e84c639b1520d9fb85886754be5dff5e714cb89432"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/fuel-core-0.47.1%2Bnightly.20260106.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "ee64b95cc456e636f8639b24ef88404ad095aee8b2e48a9ec333317040855d0b"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/fuel-core-0.47.1%2Bnightly.20260106.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "d8fbd6a2bc5c515c763f566a316f45307b4e3f6ba872f2fbdfad5f73c109f42b"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260106/fuel-core-0.47.1%2Bnightly.20260106.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "ca36e15cffcbaeb320e098ad0f2cc1682b827563af7db4cde4c6ab6eac6aa2fc"
