published_by = "https://github.com/FuelLabs/fuelup/actions/runs/21554247699"
date = "2026-02-01"

[pkg.forc]
version = "0.70.1+nightly.20260201.755013907a"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/forc-binaries-0.70.1%2Bnightly.20260201.755013907a-darwin_amd64.tar.gz"
hash = "a64d34f3839d9da88d30dba99dfa4f1a417990e0f587ae7dc4a8b32c74abd8af"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/forc-binaries-0.70.1%2Bnightly.20260201.755013907a-darwin_arm64.tar.gz"
hash = "90ab24124661079fd511036278eaeee38ac5fec28b7bfe68553b686b5a0d4ef7"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/forc-binaries-0.70.1%2Bnightly.20260201.755013907a-linux_amd64.tar.gz"
hash = "8a28f5c86b8ac4d568ea44045c2ea5324b56919b1b96c2363cc7ec514d96be71"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/forc-binaries-0.70.1%2Bnightly.20260201.755013907a-linux_arm64.tar.gz"
hash = "79ad539ee88420f7a26e3560733560190971866e8a69df493b20cb17e37ce24b"

[pkg.forc-crypto]
version = "0.71.0+nightly.20260201.1a6613558d"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/forc-crypto-0.71.0%2Bnightly.20260201.1a6613558d-darwin_amd64.tar.gz"
hash = "d9d5669fbb43c2e3867d25bacf6ee4108fd24d880cb7f424c1b167b9d56338e3"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/forc-crypto-0.71.0%2Bnightly.20260201.1a6613558d-darwin_arm64.tar.gz"
hash = "62f678cd350bdaa6fa0638a46fe329c1f464b0f88238fec2ed4e61dd4f96d6ac"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/forc-crypto-0.71.0%2Bnightly.20260201.1a6613558d-linux_amd64.tar.gz"
hash = "2e8bfe4429f16b1ec8fcb006ad1f7eacf30d3f658ca81e3d3fa22ab85d2f0c2d"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/forc-crypto-0.71.0%2Bnightly.20260201.1a6613558d-linux_arm64.tar.gz"
hash = "f1fc2d12cc2de81e8a61da14ceb9a18e4f5d29c401560f84c80717fb186de937"

[pkg.forc-node]
version = "0.71.2+nightly.20260201.1a6613558d"

[pkg.forc-node.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/forc-node-0.71.2%2Bnightly.20260201.1a6613558d-darwin_amd64.tar.gz"
hash = "7bf1aff439ad5cb8cde2ca3d9b4a636125466f6b32282de3c7cc5e2edeb8f821"

[pkg.forc-node.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/forc-node-0.71.2%2Bnightly.20260201.1a6613558d-darwin_arm64.tar.gz"
hash = "0957d6756ab3a864483847c82987b4f37f07fe3827801ab0733b3d9185cab786"

[pkg.forc-node.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/forc-node-0.71.2%2Bnightly.20260201.1a6613558d-linux_amd64.tar.gz"
hash = "91ecd7063646971210baa64d150ada5fddf8a2b882acdab6d39fa7290a7e7238"

[pkg.forc-node.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/forc-node-0.71.2%2Bnightly.20260201.1a6613558d-linux_arm64.tar.gz"
hash = "8b0438402ff8ac6f99209a66ac88083221a72bba6cb6da1e293fbd6298b18db2"

[pkg.forc-wallet]
version = "0.16.2+nightly.20260201.1a6613558d"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/forc-wallet-0.16.2%2Bnightly.20260201.1a6613558d-darwin_amd64.tar.gz"
hash = "d0edbab11a45c3b85bae1a44ff781334387775a0c662cfc581fbe4cededb59e2"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/forc-wallet-0.16.2%2Bnightly.20260201.1a6613558d-darwin_arm64.tar.gz"
hash = "c7e217db1bf3d465256a5ad19a57d5282e5a0d002de0e65177e1af8ffb576930"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/forc-wallet-0.16.2%2Bnightly.20260201.1a6613558d-linux_amd64.tar.gz"
hash = "7e84d6bd1f967580bce07337651bafb719b8fd4cc427ea040e8143b2b0e32f68"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/forc-wallet-0.16.2%2Bnightly.20260201.1a6613558d-linux_arm64.tar.gz"
hash = "67dd0149b33f12164a2435420ddba3a11084866795301ef39368899496feaef9"

[pkg.fuel-core]
version = "0.47.1+nightly.20260201.697e692a08"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/fuel-core-0.47.1%2Bnightly.20260201.697e692a08-aarch64-apple-darwin.tar.gz"
hash = "74ff713f3721eee82298b89a0e43b3c5ea53016e553da7b710ce01707d2a52fe"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/fuel-core-0.47.1%2Bnightly.20260201.697e692a08-aarch64-unknown-linux-gnu.tar.gz"
hash = "76553c5298bc2c8d02fb6bed903b6679c3d3843f215dacf3937fdfbfa9df250b"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/fuel-core-0.47.1%2Bnightly.20260201.697e692a08-x86_64-unknown-linux-gnu.tar.gz"
hash = "358f7b6025692a153393a039327754fa0d0af803780dae5c37465c131c05b10e"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20260201.697e692a08"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/fuel-core-0.47.1%2Bnightly.20260201.697e692a08-aarch64-apple-darwin.tar.gz"
hash = "74ff713f3721eee82298b89a0e43b3c5ea53016e553da7b710ce01707d2a52fe"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/fuel-core-0.47.1%2Bnightly.20260201.697e692a08-aarch64-unknown-linux-gnu.tar.gz"
hash = "76553c5298bc2c8d02fb6bed903b6679c3d3843f215dacf3937fdfbfa9df250b"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260201/fuel-core-0.47.1%2Bnightly.20260201.697e692a08-x86_64-unknown-linux-gnu.tar.gz"
hash = "358f7b6025692a153393a039327754fa0d0af803780dae5c37465c131c05b10e"
