published_by = "https://github.com/FuelLabs/fuelup/actions/runs/19005447496"
date = "2025-11-02"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251102.279124d992"

[pkg.forc-wallet.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251102/forc-wallet-0.15.2%2Bnightly.20251102.279124d992-aarch64-apple-darwin.tar.gz"
hash = "9fd2331cbc0eef590059a0662e29ad3f611dc5627b469b134d93467d78a90222"

[pkg.forc-wallet.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251102/forc-wallet-0.15.2%2Bnightly.20251102.279124d992-aarch64-unknown-linux-gnu.tar.gz"
hash = "5bd0d58e07b4db71c707b1878d235393b93c620680d1dce072f0cda424236f40"

[pkg.forc-wallet.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251102/forc-wallet-0.15.2%2Bnightly.20251102.279124d992-x86_64-apple-darwin.tar.gz"
hash = "5b773e835a1eba1a327c7e91f7dc3aa9dca75ea4bce8e94f73ba06947894a814"

[pkg.forc-wallet.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251102/forc-wallet-0.15.2%2Bnightly.20251102.279124d992-x86_64-unknown-linux-gnu.tar.gz"
hash = "77741331fe6eb0d7bfc841f84969181eaa4185679d355d402d794acc61acb17f"
