published_by = "https://github.com/FuelLabs/fuelup/actions/runs/21122287143"
date = "2026-01-19"

[pkg.forc]
version = "0.70.1+nightly.20260119.20b32cfb44"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/forc-binaries-0.70.1%2Bnightly.20260119.20b32cfb44-darwin_amd64.tar.gz"
hash = "d7a8ca1ea0480843c7e9dbfbbc787bcc74135d4ecbf6a7ccfe72695f3b9bb7ce"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/forc-binaries-0.70.1%2Bnightly.20260119.20b32cfb44-darwin_arm64.tar.gz"
hash = "5024cbeea06fd54b22e445deebfa98736c3f0472093da23c8e6bc6839aca9f80"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/forc-binaries-0.70.1%2Bnightly.20260119.20b32cfb44-linux_amd64.tar.gz"
hash = "c3913e0cda106c791abbb1c868b5d01d40f9c0fbd161f047a6cb24002e8aff5d"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/forc-binaries-0.70.1%2Bnightly.20260119.20b32cfb44-linux_arm64.tar.gz"
hash = "2b7a050997ea1a87b245812a94446325df6e5094b21ce28fe1adced152385bab"

[pkg.forc-crypto]
version = "0.71.0+nightly.20260119.54cf9da7d3"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/forc-crypto-0.71.0%2Bnightly.20260119.54cf9da7d3-darwin_amd64.tar.gz"
hash = "6c9498a9bf4e7b6bdfca8a71573842d142a5b3a87ab53706eb37cf952a04a85e"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/forc-crypto-0.71.0%2Bnightly.20260119.54cf9da7d3-darwin_arm64.tar.gz"
hash = "d5b4481a19b5620e1355965cedce7f95461c70359e2738b4d36b21e2a0bcd47d"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/forc-crypto-0.71.0%2Bnightly.20260119.54cf9da7d3-linux_amd64.tar.gz"
hash = "dbd6a3918fcda1aff04c7fe42e1c0a56ced5427ca5ac9a67b8af01e9b8705843"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/forc-crypto-0.71.0%2Bnightly.20260119.54cf9da7d3-linux_arm64.tar.gz"
hash = "0ed2506874b65d3c37b663630f5e2eedf449475e3d1dc094038102b01df51836"

[pkg.forc-node]
version = "0.71.2+nightly.20260119.54cf9da7d3"

[pkg.forc-node.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/forc-node-0.71.2%2Bnightly.20260119.54cf9da7d3-darwin_amd64.tar.gz"
hash = "4c66e8794c686dd3bbbae1f954f63e70f7ef96f3649c7664064e6398cd9ade4c"

[pkg.forc-node.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/forc-node-0.71.2%2Bnightly.20260119.54cf9da7d3-darwin_arm64.tar.gz"
hash = "ff79a4c30911c04cd29dcf44e29a8a8199ee8c6dfd020fe0d7c03964f7097179"

[pkg.forc-node.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/forc-node-0.71.2%2Bnightly.20260119.54cf9da7d3-linux_amd64.tar.gz"
hash = "42fd34183f5c123e3ae3d482cf253551337f2fdcbf5b0785ac589f3d0f8a14e8"

[pkg.forc-node.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/forc-node-0.71.2%2Bnightly.20260119.54cf9da7d3-linux_arm64.tar.gz"
hash = "4c435a775c29fb87c2499b5bf0b13d8201e86b463240030bc178728a3bdee850"

[pkg.forc-wallet]
version = "0.16.2+nightly.20260119.54cf9da7d3"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/forc-wallet-0.16.2%2Bnightly.20260119.54cf9da7d3-darwin_amd64.tar.gz"
hash = "29badf8e0fc8b9c03d722f3f01be5ac2695829f8e72eed08cc5dd230e2312ba7"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/forc-wallet-0.16.2%2Bnightly.20260119.54cf9da7d3-darwin_arm64.tar.gz"
hash = "d9c300b0e8ad4c39c14e62ad289b1b951cb58f85702d38cfc1c5ed49558df3d7"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/forc-wallet-0.16.2%2Bnightly.20260119.54cf9da7d3-linux_amd64.tar.gz"
hash = "9552077e2e7013d10c6488e1a81858bf24d7a454af53f439d10ffbe2b40db75d"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/forc-wallet-0.16.2%2Bnightly.20260119.54cf9da7d3-linux_arm64.tar.gz"
hash = "8704007a6def04ee864a368db07acdc61a330e218441f213121faa6f29284dbb"

[pkg.fuel-core]
version = "0.47.1+nightly.20260119.6889ed156b"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/fuel-core-0.47.1%2Bnightly.20260119.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "3cb6f2861466c4822471bba0c067013101b0fd782a6606d2b634f5d0f43e0190"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/fuel-core-0.47.1%2Bnightly.20260119.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "46704816efe165a9dc649ca1bf7936e2cde437fbddca762c57e1983dc2e94830"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/fuel-core-0.47.1%2Bnightly.20260119.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "74bc4ad5ec79952490bdd4f6e4522b4aca197ed81b7c25e9ace68b5364a355f5"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/fuel-core-0.47.1%2Bnightly.20260119.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "a23463e64bf1e25dace87e52d9f1129e2cca58cfd6484a65eebc6f38329868f4"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20260119.6889ed156b"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/fuel-core-0.47.1%2Bnightly.20260119.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "3cb6f2861466c4822471bba0c067013101b0fd782a6606d2b634f5d0f43e0190"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/fuel-core-0.47.1%2Bnightly.20260119.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "46704816efe165a9dc649ca1bf7936e2cde437fbddca762c57e1983dc2e94830"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/fuel-core-0.47.1%2Bnightly.20260119.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "74bc4ad5ec79952490bdd4f6e4522b4aca197ed81b7c25e9ace68b5364a355f5"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260119/fuel-core-0.47.1%2Bnightly.20260119.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "a23463e64bf1e25dace87e52d9f1129e2cca58cfd6484a65eebc6f38329868f4"
