published_by = "https://github.com/FuelLabs/fuelup/actions/runs/20630520732"
date = "2026-01-01"

[pkg.forc]
version = "0.70.1+nightly.20260101.cc8f867043"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260101/forc-binaries-0.70.1%2Bnightly.20260101.cc8f867043-darwin_amd64.tar.gz"
hash = "1e8874a8367abe0f7586bd3ce63f953b8b4ed3873655f896e2f2f7a585ba8a46"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260101/forc-binaries-0.70.1%2Bnightly.20260101.cc8f867043-darwin_arm64.tar.gz"
hash = "7388dcb92388d551f33eb851917d5c3a561f24ac3f05e387557c994c17e287eb"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260101/forc-binaries-0.70.1%2Bnightly.20260101.cc8f867043-linux_amd64.tar.gz"
hash = "fdbd5177b653b61ed2e670922d07ff47e0b7b8720785024c531c9becf91de390"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260101/forc-binaries-0.70.1%2Bnightly.20260101.cc8f867043-linux_arm64.tar.gz"
hash = "960134d860e35d3d8d8cdbec01ae13ae4dee7f34b2204bbcee6d258c380a518c"

[pkg.fuel-core]
version = "0.47.1+nightly.20260101.6889ed156b"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260101/fuel-core-0.47.1%2Bnightly.20260101.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "5ca7b619512c85fe5562e45777d492506f22b3007ffd562f658af07915480d94"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260101/fuel-core-0.47.1%2Bnightly.20260101.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "33d93afed5f1ff9ab84d61aaa684f6e76786d0c948ad43ab3a9c0358da90eded"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260101/fuel-core-0.47.1%2Bnightly.20260101.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "01bc5dbbf2d4cbf54be8d109c1c4c1581e01fcf4c668d2283f7da686efce476f"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260101/fuel-core-0.47.1%2Bnightly.20260101.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "c84f208cb7d380f18ce46920ab757c951c960ad01198da567a4aa95f157a5d1d"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20260101.6889ed156b"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260101/fuel-core-0.47.1%2Bnightly.20260101.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "5ca7b619512c85fe5562e45777d492506f22b3007ffd562f658af07915480d94"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260101/fuel-core-0.47.1%2Bnightly.20260101.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "33d93afed5f1ff9ab84d61aaa684f6e76786d0c948ad43ab3a9c0358da90eded"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260101/fuel-core-0.47.1%2Bnightly.20260101.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "01bc5dbbf2d4cbf54be8d109c1c4c1581e01fcf4c668d2283f7da686efce476f"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260101/fuel-core-0.47.1%2Bnightly.20260101.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "c84f208cb7d380f18ce46920ab757c951c960ad01198da567a4aa95f157a5d1d"
