published_by = "https://github.com/FuelLabs/fuelup/actions/runs/20496845339"
date = "2025-12-25"

[pkg.forc]
version = "0.70.1+nightly.20251225.cc8f867043"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/forc-binaries-0.70.1%2Bnightly.20251225.cc8f867043-darwin_amd64.tar.gz"
hash = "912ad9aec660212a8d6a6f2b22b7936718e21edeba176b204f0cc531be4efff9"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/forc-binaries-0.70.1%2Bnightly.20251225.cc8f867043-darwin_arm64.tar.gz"
hash = "a7dea4eef585bca1511976b748e9c07a99e6b7453a87bf603081ee0bb207195a"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/forc-binaries-0.70.1%2Bnightly.20251225.cc8f867043-linux_amd64.tar.gz"
hash = "c651aea32952c93da8d6177f01fe3a0cd15681e0c11f69d0875a8da27cf4cbd4"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/forc-binaries-0.70.1%2Bnightly.20251225.cc8f867043-linux_arm64.tar.gz"
hash = "98eca92790bfd7e66caa7476abd217d1d8025938ec262334a71113a495680645"

[pkg.forc-crypto]
version = "0.71.0+nightly.20251225.c10463b0cb"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/forc-crypto-0.71.0%2Bnightly.20251225.c10463b0cb-darwin_amd64.tar.gz"
hash = "55a1706d3aea0d858c9e1f3045b8370525c51e1a4f4d69172f2fe07414238c24"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/forc-crypto-0.71.0%2Bnightly.20251225.c10463b0cb-darwin_arm64.tar.gz"
hash = "e1dae5239d60992a7cdbb6701fb0cee004731419e9eab3ccf47dde4635b673e9"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/forc-crypto-0.71.0%2Bnightly.20251225.c10463b0cb-linux_amd64.tar.gz"
hash = "fc4621d86a00a152e82d323c0659db33540a2bba3b679a4d0c57813ba5a866a1"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/forc-crypto-0.71.0%2Bnightly.20251225.c10463b0cb-linux_arm64.tar.gz"
hash = "88696102c657be765ee2648a63fed457999a41f4119464fc8a0540201cba90cf"

[pkg.forc-wallet]
version = "0.16.2+nightly.20251225.c10463b0cb"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/forc-wallet-0.16.2%2Bnightly.20251225.c10463b0cb-darwin_amd64.tar.gz"
hash = "2626d872e7345fc9b31d85b61dda633d39897b245b05b60faf151dfbf9a47796"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/forc-wallet-0.16.2%2Bnightly.20251225.c10463b0cb-darwin_arm64.tar.gz"
hash = "645666d9f936e818056c62ce3153915f8361a38cbea725f169188fa304a4313f"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/forc-wallet-0.16.2%2Bnightly.20251225.c10463b0cb-linux_amd64.tar.gz"
hash = "892ccf604429070e863f8ed4e32c400d7f46b8effa0b77b3be3be9e7c7e94aec"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/forc-wallet-0.16.2%2Bnightly.20251225.c10463b0cb-linux_arm64.tar.gz"
hash = "904babe4ddab687efcada5f97467adb98c395e5c954f32219db41f454207ecb2"

[pkg.fuel-core]
version = "0.47.1+nightly.20251225.6889ed156b"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/fuel-core-0.47.1%2Bnightly.20251225.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "acb890a98ed9018d0c1c58aaa715c04418e1f1b987b2278b4a5c4ec89bc57dff"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/fuel-core-0.47.1%2Bnightly.20251225.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "4c37c08cea5d339fc2abc474a0a81210eeeae64e09a2d5650ad39697ca70d25a"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/fuel-core-0.47.1%2Bnightly.20251225.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "2a29e28bedb65f6af1da6ac04b9877e0d2488556fcc7aba037fb7e9e36eefb86"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/fuel-core-0.47.1%2Bnightly.20251225.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "2249b449bea3d0b5137b25a19d8188e4cbda58e668d1fb4336667b7a5be566c2"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20251225.6889ed156b"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/fuel-core-0.47.1%2Bnightly.20251225.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "acb890a98ed9018d0c1c58aaa715c04418e1f1b987b2278b4a5c4ec89bc57dff"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/fuel-core-0.47.1%2Bnightly.20251225.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "4c37c08cea5d339fc2abc474a0a81210eeeae64e09a2d5650ad39697ca70d25a"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/fuel-core-0.47.1%2Bnightly.20251225.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "2a29e28bedb65f6af1da6ac04b9877e0d2488556fcc7aba037fb7e9e36eefb86"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251225/fuel-core-0.47.1%2Bnightly.20251225.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "2249b449bea3d0b5137b25a19d8188e4cbda58e668d1fb4336667b7a5be566c2"
