published_by = "https://github.com/FuelLabs/fuelup/actions/runs/20184626731"
date = "2025-12-13"

[pkg.forc]
version = "0.70.1+nightly.20251213.5e179b304e"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/forc-binaries-0.70.1%2Bnightly.20251213.5e179b304e-darwin_amd64.tar.gz"
hash = "96a04ee1e26e696bc3d05b70d900328cb37e9f3acb51c59c936336084bf43643"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/forc-binaries-0.70.1%2Bnightly.20251213.5e179b304e-darwin_arm64.tar.gz"
hash = "4165a506fb35b6325ed20287467cd43465fbeb39a28ee9350e56a6834ac0ba40"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/forc-binaries-0.70.1%2Bnightly.20251213.5e179b304e-linux_amd64.tar.gz"
hash = "81131da9f75c2a773a8f4475a2684a09be5d079029aed5ad3bd8a2efa5ced9c4"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/forc-binaries-0.70.1%2Bnightly.20251213.5e179b304e-linux_arm64.tar.gz"
hash = "f4590ed154207611f4df482e7d7fb0d254f29f1bbcb71472d6b07745910a75fa"

[pkg.forc-crypto]
version = "0.71.0+nightly.20251213.c10463b0cb"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/forc-crypto-0.71.0%2Bnightly.20251213.c10463b0cb-darwin_amd64.tar.gz"
hash = "c98f9fba145d5ec1c509ca8e4feee90fc4772fc5d5a2d033505de9e7f76fcd3e"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/forc-crypto-0.71.0%2Bnightly.20251213.c10463b0cb-darwin_arm64.tar.gz"
hash = "a3cb1f04e2f410ba37b3403b75ba01918786783571b79666fe17d0fb3edad539"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/forc-crypto-0.71.0%2Bnightly.20251213.c10463b0cb-linux_amd64.tar.gz"
hash = "f09453f25e5fd2962fbab9f24b6e74c0a3d15aa41f7bc4428f66adb3a4018ebd"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/forc-crypto-0.71.0%2Bnightly.20251213.c10463b0cb-linux_arm64.tar.gz"
hash = "45301fa59f8edf50df804bfddfb7b0942131f13e4ad7bf4534009bc923750c8a"

[pkg.forc-wallet]
version = "0.16.2+nightly.20251213.c10463b0cb"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/forc-wallet-0.16.2%2Bnightly.20251213.c10463b0cb-darwin_amd64.tar.gz"
hash = "c1f41d05643840ae59e65a0dc153ffe0db83f206552f9c5f1f5add672c745fd0"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/forc-wallet-0.16.2%2Bnightly.20251213.c10463b0cb-darwin_arm64.tar.gz"
hash = "f28cb2630a0203837e0f3b9ece54673498329bb7bdc7851e35fc193a4013e8a6"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/forc-wallet-0.16.2%2Bnightly.20251213.c10463b0cb-linux_amd64.tar.gz"
hash = "24029d62274be17f958361ac9f8d3d2d77ad5c02de007eab37b20575b48b6ba8"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/forc-wallet-0.16.2%2Bnightly.20251213.c10463b0cb-linux_arm64.tar.gz"
hash = "e575989762d6bac8c605656fe41da9c26bd7454bd1d8b660dd72a72e0830b348"

[pkg.fuel-core]
version = "0.47.1+nightly.20251213.6889ed156b"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/fuel-core-0.47.1%2Bnightly.20251213.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "6dc6e3c3e213e0040af76c70b58b3b796c9f9e2870c25de7f6a225b64964fc59"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/fuel-core-0.47.1%2Bnightly.20251213.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "fa34db0d9dca66a3e26463127106813eead28a26fe4d66b54b946cbb32967c13"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/fuel-core-0.47.1%2Bnightly.20251213.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "5362677caabad8f280679a3ed69cbf7c0f2e2908efc6dda108978efb743189de"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/fuel-core-0.47.1%2Bnightly.20251213.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "2cbd0fe03f52b98e387138b03ae8489050021639abc35a625b94c58ec5f4810c"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20251213.6889ed156b"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/fuel-core-0.47.1%2Bnightly.20251213.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "6dc6e3c3e213e0040af76c70b58b3b796c9f9e2870c25de7f6a225b64964fc59"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/fuel-core-0.47.1%2Bnightly.20251213.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "fa34db0d9dca66a3e26463127106813eead28a26fe4d66b54b946cbb32967c13"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/fuel-core-0.47.1%2Bnightly.20251213.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "5362677caabad8f280679a3ed69cbf7c0f2e2908efc6dda108978efb743189de"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251213/fuel-core-0.47.1%2Bnightly.20251213.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "2cbd0fe03f52b98e387138b03ae8489050021639abc35a625b94c58ec5f4810c"
