published_by = "https://github.com/FuelLabs/fuelup/actions/runs/21232482984"
date = "2026-01-22"

[pkg.forc]
version = "0.70.1+nightly.20260122.20b32cfb44"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/forc-binaries-0.70.1%2Bnightly.20260122.20b32cfb44-darwin_amd64.tar.gz"
hash = "6d7633b80ae84b48f2047f3b148398d9723ead10f7072005bb59d60559c8dab1"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/forc-binaries-0.70.1%2Bnightly.20260122.20b32cfb44-darwin_arm64.tar.gz"
hash = "02a9d5f7f1b37d0c5d74e8435846c30cd2aa0812bc447ce03757f780752c40e8"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/forc-binaries-0.70.1%2Bnightly.20260122.20b32cfb44-linux_amd64.tar.gz"
hash = "324664d28c957bac708b934eced6e91a690e2d4754c91b05d58e00877d9e8ec7"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/forc-binaries-0.70.1%2Bnightly.20260122.20b32cfb44-linux_arm64.tar.gz"
hash = "f56c27261d48d77c140694b35134ce7cea8590bfa77c5d41cc3ca387cff982f6"

[pkg.forc-crypto]
version = "0.71.0+nightly.20260122.54cf9da7d3"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/forc-crypto-0.71.0%2Bnightly.20260122.54cf9da7d3-darwin_amd64.tar.gz"
hash = "ad2f196d718f5b1db364cedf4b2440a8db0fbdb401a8217e159f3815ee98dd82"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/forc-crypto-0.71.0%2Bnightly.20260122.54cf9da7d3-darwin_arm64.tar.gz"
hash = "bf0de1649880159d6d102946ae3d17ee0c25cebac5e32bb3a9607cd494e7fb5a"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/forc-crypto-0.71.0%2Bnightly.20260122.54cf9da7d3-linux_amd64.tar.gz"
hash = "6bf7c7f5ce4aba4c12b83d4216bec599b1d1cc3c7050750dab054e01ec2dbc8d"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/forc-crypto-0.71.0%2Bnightly.20260122.54cf9da7d3-linux_arm64.tar.gz"
hash = "fb5fe0bc0fa24cf80f283b0f7adcd7ed151596c182136ebcc7ece2d06c11f095"

[pkg.forc-node]
version = "0.71.2+nightly.20260122.54cf9da7d3"

[pkg.forc-node.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/forc-node-0.71.2%2Bnightly.20260122.54cf9da7d3-darwin_amd64.tar.gz"
hash = "529eb1422dbde712285160bf0807bf6a7663f4cadd7f017c7a3157872444bb10"

[pkg.forc-node.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/forc-node-0.71.2%2Bnightly.20260122.54cf9da7d3-darwin_arm64.tar.gz"
hash = "fa841adb890ae12d4810d06d4036af7b7f80968394ed4b4442c7d90d12c3b01b"

[pkg.forc-node.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/forc-node-0.71.2%2Bnightly.20260122.54cf9da7d3-linux_amd64.tar.gz"
hash = "2b2bf758059284fd25c2a890c4756787426f378232c973ac3ed81d6d3015d40b"

[pkg.forc-node.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/forc-node-0.71.2%2Bnightly.20260122.54cf9da7d3-linux_arm64.tar.gz"
hash = "11bb335b0f26b7fc912279e0fca6b22649450f56d611a1f76cd2d9349b3d2a74"

[pkg.forc-wallet]
version = "0.16.2+nightly.20260122.54cf9da7d3"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/forc-wallet-0.16.2%2Bnightly.20260122.54cf9da7d3-darwin_amd64.tar.gz"
hash = "5cdfed2b3c1f18f7414738938051e29563f128e6d99cdb3f95c1bd3e6133f698"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/forc-wallet-0.16.2%2Bnightly.20260122.54cf9da7d3-darwin_arm64.tar.gz"
hash = "990c83feed523ba293901e8365e3087f763060efc958b5cc9ad6866b0562d988"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/forc-wallet-0.16.2%2Bnightly.20260122.54cf9da7d3-linux_amd64.tar.gz"
hash = "de0617b14d3975689a07e04f75f81e12ef44972aaeaca36bce4817741868d59d"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/forc-wallet-0.16.2%2Bnightly.20260122.54cf9da7d3-linux_arm64.tar.gz"
hash = "2e3f3b8fbe1c7648a265da54471d7e417f49918eb0eb0f3e69e882cd05b2f828"

[pkg.fuel-core]
version = "0.47.1+nightly.20260122.cc5bbc1573"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/fuel-core-0.47.1%2Bnightly.20260122.cc5bbc1573-aarch64-unknown-linux-gnu.tar.gz"
hash = "3f7fd4da42cbc559976c677f882cb162657bbc7ddf50d73421f9e1936ca9ac9a"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/fuel-core-0.47.1%2Bnightly.20260122.cc5bbc1573-x86_64-apple-darwin.tar.gz"
hash = "2f334aab8b9b08e6179280641f1f782984ca3a0d952f1769995bd49e6a948e21"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/fuel-core-0.47.1%2Bnightly.20260122.cc5bbc1573-x86_64-unknown-linux-gnu.tar.gz"
hash = "527fc1503e3aad2d8849983a1beb78c8946bd93eb34e0346e54f174829bfc5b4"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20260122.cc5bbc1573"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/fuel-core-0.47.1%2Bnightly.20260122.cc5bbc1573-aarch64-unknown-linux-gnu.tar.gz"
hash = "3f7fd4da42cbc559976c677f882cb162657bbc7ddf50d73421f9e1936ca9ac9a"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/fuel-core-0.47.1%2Bnightly.20260122.cc5bbc1573-x86_64-apple-darwin.tar.gz"
hash = "2f334aab8b9b08e6179280641f1f782984ca3a0d952f1769995bd49e6a948e21"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260122/fuel-core-0.47.1%2Bnightly.20260122.cc5bbc1573-x86_64-unknown-linux-gnu.tar.gz"
hash = "527fc1503e3aad2d8849983a1beb78c8946bd93eb34e0346e54f174829bfc5b4"
