published_by = "https://github.com/FuelLabs/fuelup/actions/runs/21735250028"
date = "2026-02-06"

[pkg.forc]
version = "0.70.1+nightly.20260206.f0a848ddd6"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-binaries-0.70.1%2Bnightly.20260206.f0a848ddd6-darwin_amd64.tar.gz"
hash = "3a9fdf1e53c5ba4212ede8b24ec17d6b97e7737f527ce07e3cc353482bab77f7"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-binaries-0.70.1%2Bnightly.20260206.f0a848ddd6-darwin_arm64.tar.gz"
hash = "3fc2689e88749eb1651ad850fa2ba7c1f2b2c278dd9d1a3b0d3f4e9af5ce12ef"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-binaries-0.70.1%2Bnightly.20260206.f0a848ddd6-linux_amd64.tar.gz"
hash = "42026e8a829c5f96a9dafe2015616e9e219347d45be484a1bef2c4f7ea208bae"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-binaries-0.70.1%2Bnightly.20260206.f0a848ddd6-linux_arm64.tar.gz"
hash = "fd0aa062dd09fb1cec25233befcf34e7fa277ee829a36b5e53346b0ca9d703a6"

[pkg.forc-client]
version = "0.71.1+nightly.20260206.063e4c5c49"

[pkg.forc-client.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-client-0.71.1%2Bnightly.20260206.063e4c5c49-darwin_amd64.tar.gz"
hash = "e188e75143d18a08ee36b76635229759db4768af69d4e49a70d41d12dec04adb"

[pkg.forc-client.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-client-0.71.1%2Bnightly.20260206.063e4c5c49-darwin_arm64.tar.gz"
hash = "05438c46cca28b7d4bf34e5b24c50a29be10f8bd744922c081becc0ce94dc371"

[pkg.forc-client.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-client-0.71.1%2Bnightly.20260206.063e4c5c49-linux_amd64.tar.gz"
hash = "dc68e2097346ac5baa549bb4eb5f1ea2890a4b84e73db18fa82ce3b43fa4f504"

[pkg.forc-client.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-client-0.71.1%2Bnightly.20260206.063e4c5c49-linux_arm64.tar.gz"
hash = "dd9e67b1efa58a3ba47cbd2661de8c1a57701c6aa61a8d0ee3871a73e0ecf9f1"

[pkg.forc-crypto]
version = "0.71.0+nightly.20260206.063e4c5c49"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-crypto-0.71.0%2Bnightly.20260206.063e4c5c49-darwin_amd64.tar.gz"
hash = "5d99dede3a64143923449b85b2019861fcb58954c61769b2b0a2c7b36fd433d1"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-crypto-0.71.0%2Bnightly.20260206.063e4c5c49-darwin_arm64.tar.gz"
hash = "faf85dad59f919803b387bc74bc5c46aef8368a78bd035158babbc5a3ad1ee4f"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-crypto-0.71.0%2Bnightly.20260206.063e4c5c49-linux_amd64.tar.gz"
hash = "2fc8b14752ca3c519856d05d5889da7e192278476f6b11c3f6a90d0665c78149"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-crypto-0.71.0%2Bnightly.20260206.063e4c5c49-linux_arm64.tar.gz"
hash = "252727c7f7cc1d30d14ee6d538d9677009d690f2d6cc317766453ff73b8e2e06"

[pkg.forc-node]
version = "0.71.2+nightly.20260206.063e4c5c49"

[pkg.forc-node.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-node-0.71.2%2Bnightly.20260206.063e4c5c49-darwin_amd64.tar.gz"
hash = "760fa912ffd51c3f7f3379966dcaf3723bae9b2efbacbff20d42ac2ff99436b0"

[pkg.forc-node.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-node-0.71.2%2Bnightly.20260206.063e4c5c49-darwin_arm64.tar.gz"
hash = "b636e423a822bce7eb4d280b2e79bbfc041ccbab66461ee5ea425a6fa6aade6d"

[pkg.forc-node.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-node-0.71.2%2Bnightly.20260206.063e4c5c49-linux_amd64.tar.gz"
hash = "173fed1e2cd663565e1bf44050d003d9003bacff0e70a02ea88ff04dd3e17843"

[pkg.forc-node.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-node-0.71.2%2Bnightly.20260206.063e4c5c49-linux_arm64.tar.gz"
hash = "ca583db6c1741990c705b1abc1956a2c6ff4ccf78a3e022dc2f10c8181aea7d6"

[pkg.forc-wallet]
version = "0.16.2+nightly.20260206.063e4c5c49"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-wallet-0.16.2%2Bnightly.20260206.063e4c5c49-darwin_amd64.tar.gz"
hash = "7bc0a47a4f7869a49204802e9c3c9483226145cd4deac7b6ade1951c61b72e7f"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-wallet-0.16.2%2Bnightly.20260206.063e4c5c49-darwin_arm64.tar.gz"
hash = "3e0ed7f8ef913b6de331d4d485f93f5e274f423e008e4f2ea72faef6b74c42b5"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-wallet-0.16.2%2Bnightly.20260206.063e4c5c49-linux_amd64.tar.gz"
hash = "50917dc17ef1c090438c263a442296b58112fc472e4f618f0de6dab12f2b5a4a"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/forc-wallet-0.16.2%2Bnightly.20260206.063e4c5c49-linux_arm64.tar.gz"
hash = "a991d172f42dca234c090c366457ee7655cba135f8e2cc72344b9a4fb6d20371"

[pkg.fuel-core]
version = "0.47.1+nightly.20260206.697e692a08"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/fuel-core-0.47.1%2Bnightly.20260206.697e692a08-aarch64-apple-darwin.tar.gz"
hash = "c714e99a545e6dd449eac9667375c07b3ef5aee321b85c60e753d80005b69f8d"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/fuel-core-0.47.1%2Bnightly.20260206.697e692a08-aarch64-unknown-linux-gnu.tar.gz"
hash = "0209c2447d9c553485dae4d15d3856299f7c174151962a2f3113edcad10ae7b0"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/fuel-core-0.47.1%2Bnightly.20260206.697e692a08-x86_64-apple-darwin.tar.gz"
hash = "86dacdc7dc785afe0895ea34293c753830ee81eb798168940c0f495f0d98d296"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/fuel-core-0.47.1%2Bnightly.20260206.697e692a08-x86_64-unknown-linux-gnu.tar.gz"
hash = "3dd0a076d6b78825e85b0d6d1ea433ab931ece3c6a2e11e1a8e51a9d961b1d4e"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20260206.697e692a08"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/fuel-core-0.47.1%2Bnightly.20260206.697e692a08-aarch64-apple-darwin.tar.gz"
hash = "c714e99a545e6dd449eac9667375c07b3ef5aee321b85c60e753d80005b69f8d"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/fuel-core-0.47.1%2Bnightly.20260206.697e692a08-aarch64-unknown-linux-gnu.tar.gz"
hash = "0209c2447d9c553485dae4d15d3856299f7c174151962a2f3113edcad10ae7b0"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/fuel-core-0.47.1%2Bnightly.20260206.697e692a08-x86_64-apple-darwin.tar.gz"
hash = "86dacdc7dc785afe0895ea34293c753830ee81eb798168940c0f495f0d98d296"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260206/fuel-core-0.47.1%2Bnightly.20260206.697e692a08-x86_64-unknown-linux-gnu.tar.gz"
hash = "3dd0a076d6b78825e85b0d6d1ea433ab931ece3c6a2e11e1a8e51a9d961b1d4e"
