date = "2025-12-12"

[pkg.forc]
version = "0.70.2"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway/releases/download/v0.70.2/forc-binaries-linux_amd64.tar.gz"
hash = "68bbffa638c4623d63c9ffb3accbce1d64610a87ac35c30cacba93f58bf5fc85"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway/releases/download/v0.70.2/forc-binaries-linux_arm64.tar.gz"
hash = "9cc66450ecd9237fb840ee344737dd4b9cc1d8eaf376f5a0edf91683d010ad75"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway/releases/download/v0.70.2/forc-binaries-darwin_amd64.tar.gz"
hash = "dc5add89220f597c2db501a02617c635f48da2632abb20e804ab67f5a02f9432"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway/releases/download/v0.70.2/forc-binaries-darwin_arm64.tar.gz"
hash = "9aea90eba501866cb039d51af3b1268c855929f9ef409917e766eac6d838d66f"

[pkg.forc-crypto]
version = "0.71.0"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-crypto-0.71.0/forc-crypto-0.71.0-linux_amd64.tar.gz"
hash = "b04b825bee1e3696dedad8b91e1343efb101cc914bea7c41a6b9374b87eabd83"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-crypto-0.71.0/forc-crypto-0.71.0-linux_arm64.tar.gz"
hash = "ffdf6a1135bb5d393b065cb211fbc34ecc2b8781df775db48cece0de08f8720c"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-crypto-0.71.0/forc-crypto-0.71.0-darwin_amd64.tar.gz"
hash = "bf18a50d1eb60857b5230e8a362afa314be1423ca67b8f76cccce67e0a2de034"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-crypto-0.71.0/forc-crypto-0.71.0-darwin_arm64.tar.gz"
hash = "5ee26f1344824e62389e30f8dcba480bd5cb942111e6e73e54cd00264679e143"

[pkg.forc-wallet]
version = "0.16.2"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-wallet-0.16.2/forc-wallet-0.16.2-linux_amd64.tar.gz"
hash = "dfd85361748fac36e280f1b2b0e480972161e3cb4f9a9c0dd449935bbdc99d16"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-wallet-0.16.2/forc-wallet-0.16.2-linux_arm64.tar.gz"
hash = "887bf1e5a85980e28b849a09197121b2abb54539b59c8ce99f7fda01d565f74b"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-wallet-0.16.2/forc-wallet-0.16.2-darwin_amd64.tar.gz"
hash = "3f9b679f69c5deb2258da3bf60d42174542f7b9a5459b2f24098e9342a4c2be8"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-wallet-0.16.2/forc-wallet-0.16.2-darwin_arm64.tar.gz"
hash = "6be8866714be9c9cff5db28a7b332a82abce88833196b4363f07609e4265195b"

[pkg.fuel-core]
version = "0.47.1"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.47.1/fuel-core-0.47.1-aarch64-unknown-linux-gnu.tar.gz"
hash = "83274f72e20376c54ea9d21a6f5327263e5b7e0516e348382b99ee47771c51cf"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.47.1/fuel-core-0.47.1-x86_64-unknown-linux-gnu.tar.gz"
hash = "fb0f77bb310c639aa19af6d92c9b31310ba04a0bef4a312596472c9a0e004a28"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.47.1/fuel-core-0.47.1-aarch64-apple-darwin.tar.gz"
hash = "96e0c8d52384c6e3168317f7bf4a9e57dc2a7c725a598aed800af12bf1d9da9d"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.47.1/fuel-core-0.47.1-x86_64-apple-darwin.tar.gz"
hash = "b936c42c778ed39774973cbc0fd3a224da8f3d671954d9d09081ff2b0414e96e"

[pkg.fuel-core-keygen]
version = "0.47.1"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.47.1/fuel-core-0.47.1-aarch64-unknown-linux-gnu.tar.gz"
hash = "83274f72e20376c54ea9d21a6f5327263e5b7e0516e348382b99ee47771c51cf"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.47.1/fuel-core-0.47.1-x86_64-unknown-linux-gnu.tar.gz"
hash = "fb0f77bb310c639aa19af6d92c9b31310ba04a0bef4a312596472c9a0e004a28"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.47.1/fuel-core-0.47.1-aarch64-apple-darwin.tar.gz"
hash = "96e0c8d52384c6e3168317f7bf4a9e57dc2a7c725a598aed800af12bf1d9da9d"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.47.1/fuel-core-0.47.1-x86_64-apple-darwin.tar.gz"
hash = "b936c42c778ed39774973cbc0fd3a224da8f3d671954d9d09081ff2b0414e96e"
