date = "2025-12-11"

[pkg.forc]
version = "0.70.1"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway/releases/download/v0.70.1/forc-binaries-linux_amd64.tar.gz"
hash = "6cbdcecf65ff3ab3c8e1932516c00cce6518db9e9632960b54aebb3b647ad73d"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway/releases/download/v0.70.1/forc-binaries-linux_arm64.tar.gz"
hash = "6dc1066282f2ffc84e5d563840218fe029ee4e57ce5fbaf7b6929a783d04947f"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway/releases/download/v0.70.1/forc-binaries-darwin_amd64.tar.gz"
hash = "0940bdbc6a92da84d23540375c3a64fd1db443f80d5e1cc169936910829cce82"

[pkg.forc-crypto]
version = "0.71.0"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-crypto-0.71.0/forc-crypto-0.71.0-darwin_amd64.tar.gz"
hash = "bf18a50d1eb60857b5230e8a362afa314be1423ca67b8f76cccce67e0a2de034"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-crypto-0.71.0/forc-crypto-0.71.0-darwin_arm64.tar.gz"
hash = "5ee26f1344824e62389e30f8dcba480bd5cb942111e6e73e54cd00264679e143"

[pkg.forc-wallet]
version = "0.16.2"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-wallet-0.16.2/forc-wallet-0.16.2-darwin_amd64.tar.gz"
hash = "3f9b679f69c5deb2258da3bf60d42174542f7b9a5459b2f24098e9342a4c2be8"

[pkg.fuel-core]
version = "0.46.0"

[pkg.fuel-core-keygen]
version = "0.46.0"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.46.0/fuel-core-0.46.0-aarch64-unknown-linux-gnu.tar.gz"
hash = "7682aa7f6bc9393f4849a92b4a59e5079eb9ef68b7aef6fdae562c3d4b539039"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.46.0/fuel-core-0.46.0-x86_64-unknown-linux-gnu.tar.gz"
hash = "4ff71d5428c21fd6a8c84967b804c2bbc36ccb7f457a4023018a653a40a88c16"
