published_by = "https://github.com/FuelLabs/fuelup/actions/runs/19283393991"
date = "2025-11-12"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251112.279124d992"

[pkg.forc-wallet.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251112/forc-wallet-0.15.2%2Bnightly.20251112.279124d992-aarch64-apple-darwin.tar.gz"
hash = "2acc5f8172dbb3aecd0b0ff86a392a34d9b8b4d7a0675ebf3696f41bf11da561"

[pkg.forc-wallet.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251112/forc-wallet-0.15.2%2Bnightly.20251112.279124d992-aarch64-unknown-linux-gnu.tar.gz"
hash = "e38815facc0ee2b0cd3ba20a20214df81308744d2ef3ff2b60190c2e04bb2c50"

[pkg.forc-wallet.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251112/forc-wallet-0.15.2%2Bnightly.20251112.279124d992-x86_64-apple-darwin.tar.gz"
hash = "49e44f7f2a1af7f6b9d33f5f2b16cbb059c15d366e15d559c4df6dc88d94f374"

[pkg.forc-wallet.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251112/forc-wallet-0.15.2%2Bnightly.20251112.279124d992-x86_64-unknown-linux-gnu.tar.gz"
hash = "23f8c133393ba0770c795be7d871491ed283631b1f23db7f83787b600086df92"
