published_by = "https://github.com/FuelLabs/fuelup/actions/runs/19201390010"
date = "2025-11-09"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251109.279124d992"

[pkg.forc-wallet.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251109/forc-wallet-0.15.2%2Bnightly.20251109.279124d992-aarch64-apple-darwin.tar.gz"
hash = "c3d6ac6cfcbd385b89f6b3df228cc11571094243c19f83c8d78125528ab6a40d"

[pkg.forc-wallet.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251109/forc-wallet-0.15.2%2Bnightly.20251109.279124d992-aarch64-unknown-linux-gnu.tar.gz"
hash = "bb03aa67054d2a4f859bf021f5abe4e6a5ac2aaf97b238138b5dc2351401fc08"

[pkg.forc-wallet.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251109/forc-wallet-0.15.2%2Bnightly.20251109.279124d992-x86_64-apple-darwin.tar.gz"
hash = "d3174952a1d511cd5a9a02246b26ae2589c31da836e4c10c5714bfae3570eedf"

[pkg.forc-wallet.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251109/forc-wallet-0.15.2%2Bnightly.20251109.279124d992-x86_64-unknown-linux-gnu.tar.gz"
hash = "ab2cf8358a64a0f64a8011b502cd1c3037ae8cab0efebd4263ff6c3198af5a19"
