published_by = "https://github.com/FuelLabs/fuelup/actions/runs/21271227930"
date = "2026-01-23"

[pkg.forc]
version = "0.70.1+nightly.20260123.20b32cfb44"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/forc-binaries-0.70.1%2Bnightly.20260123.20b32cfb44-darwin_amd64.tar.gz"
hash = "b9e44f149e4744eea1d744289cb64e8ed4acf7ebde20417043051dfddcf6aa9e"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/forc-binaries-0.70.1%2Bnightly.20260123.20b32cfb44-darwin_arm64.tar.gz"
hash = "8ff70f2ce8da22cd466b159b63ca7d087b45caf065b089cbb686f1c35cb227b4"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/forc-binaries-0.70.1%2Bnightly.20260123.20b32cfb44-linux_amd64.tar.gz"
hash = "489db010efa84397c63a0158b053ed4a3cf055a9699cefb6845f1351921047fc"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/forc-binaries-0.70.1%2Bnightly.20260123.20b32cfb44-linux_arm64.tar.gz"
hash = "21c26334946e0f393b9423c89c661bbcf2e0a5854243b648980dea7cc982b73f"

[pkg.forc-crypto]
version = "0.71.0+nightly.20260123.54cf9da7d3"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/forc-crypto-0.71.0%2Bnightly.20260123.54cf9da7d3-darwin_amd64.tar.gz"
hash = "90db55bc584b6d2664b8381c2e5555c075ae28ece7362cc617434aab4bcd9c89"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/forc-crypto-0.71.0%2Bnightly.20260123.54cf9da7d3-darwin_arm64.tar.gz"
hash = "3575b0d20457a6761bfc38ecdd66f2db5aa68c6a06748c809a50c5782f38609d"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/forc-crypto-0.71.0%2Bnightly.20260123.54cf9da7d3-linux_amd64.tar.gz"
hash = "19c3ee770ef1016e97ce4956720476c7b279ae2bc521c3f94bb25f99d528cc58"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/forc-crypto-0.71.0%2Bnightly.20260123.54cf9da7d3-linux_arm64.tar.gz"
hash = "4ac7dd0a57c608e5560a06054f741308cc04ded3789c0b25f92c7344bc15803e"

[pkg.forc-node]
version = "0.71.2+nightly.20260123.54cf9da7d3"

[pkg.forc-node.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/forc-node-0.71.2%2Bnightly.20260123.54cf9da7d3-darwin_amd64.tar.gz"
hash = "28c255e8755f5e2ca9f10425d5caba9b4fc8a836b5c38b8464ecda16cdca24a8"

[pkg.forc-node.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/forc-node-0.71.2%2Bnightly.20260123.54cf9da7d3-darwin_arm64.tar.gz"
hash = "3009dffce2949c462fad48051aa96938752e4edc87edb3695c71f51a8acb1e2d"

[pkg.forc-node.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/forc-node-0.71.2%2Bnightly.20260123.54cf9da7d3-linux_amd64.tar.gz"
hash = "389a626f9d5d33ffa4244db3542df676d4a3188a1a7d26bc7a73dbcc1dd26c5c"

[pkg.forc-node.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/forc-node-0.71.2%2Bnightly.20260123.54cf9da7d3-linux_arm64.tar.gz"
hash = "7b947d46e8c336aaa82d6a679c19c0e293d393f6c06d15f0847e97f8c2b97922"

[pkg.forc-wallet]
version = "0.16.2+nightly.20260123.54cf9da7d3"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/forc-wallet-0.16.2%2Bnightly.20260123.54cf9da7d3-darwin_amd64.tar.gz"
hash = "d6067c40c2f0ea16f6972e853a62a5b0251762f1645bc145ab6881f1f6798564"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/forc-wallet-0.16.2%2Bnightly.20260123.54cf9da7d3-darwin_arm64.tar.gz"
hash = "31999268388c73fc62fd815ba22c44c0648470d952ac76f0fb6692c73b13283a"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/forc-wallet-0.16.2%2Bnightly.20260123.54cf9da7d3-linux_amd64.tar.gz"
hash = "4a1b1addf4cccbbca9eb71189c4dc6ad4de79a441c2f2bb4c762506e39485506"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/forc-wallet-0.16.2%2Bnightly.20260123.54cf9da7d3-linux_arm64.tar.gz"
hash = "17b6c44fa3a86491d553991f34e76e5cdfeaa51ef907af75b5bda392869e8628"

[pkg.fuel-core]
version = "0.47.1+nightly.20260123.579e1c2d78"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/fuel-core-0.47.1%2Bnightly.20260123.579e1c2d78-aarch64-apple-darwin.tar.gz"
hash = "6c7a47a33c543284de1d507a94a24587c1d9641cf80dd246bcf6e3437fef26f2"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/fuel-core-0.47.1%2Bnightly.20260123.579e1c2d78-aarch64-unknown-linux-gnu.tar.gz"
hash = "11576f888134d8d44e958b61856f47ae82aa98781c0f60254e897f1b80236b08"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/fuel-core-0.47.1%2Bnightly.20260123.579e1c2d78-x86_64-unknown-linux-gnu.tar.gz"
hash = "7f3e5bc7281a84e2db002eea5bb927ddeee4b8c0e8d170820367deb157f73a15"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20260123.579e1c2d78"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/fuel-core-0.47.1%2Bnightly.20260123.579e1c2d78-aarch64-apple-darwin.tar.gz"
hash = "6c7a47a33c543284de1d507a94a24587c1d9641cf80dd246bcf6e3437fef26f2"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/fuel-core-0.47.1%2Bnightly.20260123.579e1c2d78-aarch64-unknown-linux-gnu.tar.gz"
hash = "11576f888134d8d44e958b61856f47ae82aa98781c0f60254e897f1b80236b08"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260123/fuel-core-0.47.1%2Bnightly.20260123.579e1c2d78-x86_64-unknown-linux-gnu.tar.gz"
hash = "7f3e5bc7281a84e2db002eea5bb927ddeee4b8c0e8d170820367deb157f73a15"
