[component.forc]
name = "forc"
tarball_prefix = "forc-binaries"
executables = ["forc"]
repository_url = "https://github.com/FuelLabs/sway"
targets = ["linux_amd64", "linux_arm64", "darwin_amd64", "darwin_arm64"]
publish = true

[component.forc-fmt]
name = "forc-fmt"
tarball_prefix = "forc-binaries"
is_plugin = true
executables = ["forc-fmt"]
repository_url = "https://github.com/FuelLabs/sway"
targets = ["linux_amd64", "linux_arm64", "darwin_amd64", "darwin_arm64"]

[component.forc-lsp]
name = "forc-lsp"
tarball_prefix = "forc-binaries"
is_plugin = true
executables = ["forc-lsp"]
repository_url = "https://github.com/FuelLabs/sway"
targets = ["linux_amd64", "linux_arm64", "darwin_amd64", "darwin_arm64"]

[component.forc-explore]
name = "forc-explore"
tarball_prefix = "forc-binaries"
is_plugin = true
executables = ["forc-explore"]
repository_url = "https://github.com/FuelLabs/sway"
targets = ["linux_amd64", "linux_arm64", "darwin_amd64", "darwin_arm64"]

[component.forc-client]
name = "forc-client"
tarball_prefix = "forc-binaries"
is_plugin = true
executables = ["forc-deploy", "forc-run"]
repository_url = "https://github.com/FuelLabs/sway"
targets = ["linux_amd64", "linux_arm64", "darwin_amd64", "darwin_arm64"]
publish = true

[component.fuel-core]
name = "fuel-core"
tarball_prefix = "fuel-core"
executables = ["fuel-core"]
repository_url = "https://github.com/FuelLabs/fuel-core"
targets = [ "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin" ]
publish = true
