[component.forc]
name = "forc"
tarball_prefix = "forc-binaries"
executables = ["forc", "forc-fmt", "forc-lsp", "forc-doc"]
repository_name = "sway"
targets = ["linux_amd64", "linux_arm64", "darwin_amd64", "darwin_arm64"]
publish = true

[component.forc-doc]
name = "forc-doc"
tarball_prefix = "forc-binaries"
is_plugin = true
executables = ["forc-doc"]
repository_name = "sway"
targets = ["linux_amd64", "linux_arm64", "darwin_amd64", "darwin_arm64"]

[component.forc-fmt]
name = "forc-fmt"
tarball_prefix = "forc-binaries"
is_plugin = true
executables = ["forc-fmt"]
repository_name = "sway"
targets = ["linux_amd64", "linux_arm64", "darwin_amd64", "darwin_arm64"]

[component.forc-lsp]
name = "forc-lsp"
tarball_prefix = "forc-binaries"
is_plugin = true
executables = ["forc-lsp"]
repository_name = "sway"
targets = ["linux_amd64", "linux_arm64", "darwin_amd64", "darwin_arm64"]

[component.forc-explore]
name = "forc-explore"
tarball_prefix = "forc-explore"
is_plugin = true
executables = ["forc-explore"]
repository_name = "forc-explorer"
targets = [ "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin" ]
publish = true

[component.forc-client]
name = "forc-client"
tarball_prefix = "forc-client"
is_plugin = true
executables = ["forc-deploy", "forc-run"]
repository_name = "forc-client"
targets = [ "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin" ]

[component.fuel-core]
name = "fuel-core"
tarball_prefix = "fuel-core"
executables = ["fuel-core"]
repository_name = "fuel-core"
targets = [ "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin" ]
publish = true

[component.forc-wallet]
name = "forc-wallet"
tarball_prefix = "forc-wallet"
is_plugin = true
executables = ["forc-wallet"]
repository_name = "forc-wallet"
targets = [ "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin" ]
publish = true

[component.fuel-indexer]
name = "fuel-indexer"
tarball_prefix = "fuel-indexer"
executables = ["fuel-indexer"]
repository_name = "fuel-indexer"
targets = [ "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin" ]
publish = true

[component.forc-index]
name = "forc-index"
tarball_prefix = "forc-index"
is_plugin = true
executables = ["forc-index"]
repository_name = "fuel-indexer"
targets = [ "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin" ]
publish = true
