published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15314153557"
date = "2025-05-29"

[pkg.forc]
version = "0.68.6+nightly.20250529.ac52806415"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250529/forc-binaries-0.68.6%2Bnightly.20250529.ac52806415-darwin_amd64.tar.gz"
hash = "399aa05ef27f4dd9a2663478cfd31f52b820079fe0d9a20b1859fb7598ab8b7a"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250529/forc-binaries-0.68.6%2Bnightly.20250529.ac52806415-darwin_arm64.tar.gz"
hash = "a6b7443db1803e4efa6e8810bab0ffdeb57ad9840913490e074989e0fda5c473"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250529/forc-binaries-0.68.6%2Bnightly.20250529.ac52806415-linux_amd64.tar.gz"
hash = "6ecd8eabfe783c7cd2a070900ab8a7c0247675f3c7867ea5c2757f617341db02"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250529/forc-binaries-0.68.6%2Bnightly.20250529.ac52806415-linux_arm64.tar.gz"
hash = "942332f0e3a8ed46c2b4137f0508e89d8746fc7e281129e5dfcd918970168c1b"

[pkg.forc-wallet]
version = "0.14.0+nightly.20250529.24883eb126"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250529/forc-wallet-0.14.0%2Bnightly.20250529.24883eb126-aarch64-apple-darwin.tar.gz"
hash = "a48cc0c383b4b2d15f890f7e5fb9d9de725c6a5277f1eac4038eb13e59262053"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250529/forc-wallet-0.14.0%2Bnightly.20250529.24883eb126-aarch64-unknown-linux-gnu.tar.gz"
hash = "79d4420af30f3efbf03bb284559df5a77b6f20b715fca1b8da6a88df3a50a0de"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250529/forc-wallet-0.14.0%2Bnightly.20250529.24883eb126-x86_64-apple-darwin.tar.gz"
hash = "0e136be6a03c8875c62990cf504889fd8f553592307934263a0571e7fd76fbca"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250529/forc-wallet-0.14.0%2Bnightly.20250529.24883eb126-x86_64-unknown-linux-gnu.tar.gz"
hash = "b9a0e400db5143efb6289fb1208294248dcabe4523668ae7c18b2a4b63ccb24a"

[pkg.fuel-core]
version = "0.44.0+nightly.20250529.85b2356d51"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250529/fuel-core-0.44.0%2Bnightly.20250529.85b2356d51-aarch64-apple-darwin.tar.gz"
hash = "6b93f75f425bf5bc51435fc264fac191d2c29cc47aaeb95924cf2a2136dcdc9d"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250529/fuel-core-0.44.0%2Bnightly.20250529.85b2356d51-aarch64-unknown-linux-gnu.tar.gz"
hash = "bb3d73ee75ba2b49689128bcb0b4b4c9087e3b4a8851e830486ea6189e28afad"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250529.85b2356d51"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250529/fuel-core-0.44.0%2Bnightly.20250529.85b2356d51-aarch64-apple-darwin.tar.gz"
hash = "6b93f75f425bf5bc51435fc264fac191d2c29cc47aaeb95924cf2a2136dcdc9d"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250529/fuel-core-0.44.0%2Bnightly.20250529.85b2356d51-aarch64-unknown-linux-gnu.tar.gz"
hash = "bb3d73ee75ba2b49689128bcb0b4b4c9087e3b4a8851e830486ea6189e28afad"
