published_by = "https://github.com/FuelLabs/fuelup/actions/runs/9736643143"
date = "2024-07-01"

[pkg.forc]
version = "0.61.0+nightly.20240701.fc2a90b78e"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/forc-binaries-0.61.0%2Bnightly.20240701.fc2a90b78e-darwin_amd64.tar.gz"
hash = "16b3f5855c1ed2f139bb2ca9cb8a172d50a8c1da1c235d4571d2ff37c51c041a"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/forc-binaries-0.61.0%2Bnightly.20240701.fc2a90b78e-darwin_arm64.tar.gz"
hash = "19b422d67e11de5773923faadb9ea905d8b43cd3bd4a8fb18bd12eef1ffb4b32"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/forc-binaries-0.61.0%2Bnightly.20240701.fc2a90b78e-linux_amd64.tar.gz"
hash = "21aa989c888759a3be42662d967e9ab36f582492676511a11e61d84230078d2b"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/forc-binaries-0.61.0%2Bnightly.20240701.fc2a90b78e-linux_arm64.tar.gz"
hash = "914f1ab42c8e58f20ea20dd6020eb387e78adcfc0100baa5e857f11550acac55"

[pkg.forc-explore]
version = "0.28.1+nightly.20240701.4bb7392eed"

[pkg.forc-explore.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/forc-explore-0.28.1%2Bnightly.20240701.4bb7392eed-aarch64-apple-darwin.tar.gz"
hash = "c449eba0c472cb9c13d3ed21c6073c5ca533f251fd5c69ceb3065cffc51ed8b2"

[pkg.forc-explore.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/forc-explore-0.28.1%2Bnightly.20240701.4bb7392eed-aarch64-unknown-linux-gnu.tar.gz"
hash = "f390010b654a74163b754fe34a97b0c4736629c1c75bcc0b4244920668e299b0"

[pkg.forc-explore.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/forc-explore-0.28.1%2Bnightly.20240701.4bb7392eed-x86_64-apple-darwin.tar.gz"
hash = "03f856dfb6d7cce44509bc612d55e9cbd1386253d4781cd2b5a6e5392d35bfc0"

[pkg.forc-explore.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/forc-explore-0.28.1%2Bnightly.20240701.4bb7392eed-x86_64-unknown-linux-gnu.tar.gz"
hash = "3fee11238f878845f75a91101f69abe0f2d4c39eac0f62674f9bc22905a907b6"

[pkg.forc-wallet]
version = "0.8.1+nightly.20240701.ab41cd516d"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/forc-wallet-0.8.1%2Bnightly.20240701.ab41cd516d-aarch64-apple-darwin.tar.gz"
hash = "1631482d4e7d7bcd7ac581a395d247e133860a1152880a57c4d515e0cef4d562"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/forc-wallet-0.8.1%2Bnightly.20240701.ab41cd516d-aarch64-unknown-linux-gnu.tar.gz"
hash = "63afcebd16b77290c4135194e2f131496caf0edc3e75d8561b9773d2b051088f"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/forc-wallet-0.8.1%2Bnightly.20240701.ab41cd516d-x86_64-apple-darwin.tar.gz"
hash = "82c49cf48cf8972ef5d97e5b1b93f329252df2ec2b62b6c9ac8f8f0f95f95392"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/forc-wallet-0.8.1%2Bnightly.20240701.ab41cd516d-x86_64-unknown-linux-gnu.tar.gz"
hash = "a607b852d497397185f0eb267ba0eed44e27e6a0e4841e62c2f15aebbd5bd44d"

[pkg.fuel-core]
version = "0.30.0+nightly.20240701.ca47981d64"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/fuel-core-0.30.0%2Bnightly.20240701.ca47981d64-aarch64-apple-darwin.tar.gz"
hash = "52d2704c7aeab7b8ad6cc3facef3cc0e8736db39cd684c0a52084fcb9b61844f"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/fuel-core-0.30.0%2Bnightly.20240701.ca47981d64-aarch64-unknown-linux-gnu.tar.gz"
hash = "250e34514367eb8608c605f72f7582efefa852333cdfff84ac2d5273b785a75c"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/fuel-core-0.30.0%2Bnightly.20240701.ca47981d64-x86_64-apple-darwin.tar.gz"
hash = "2f306fb1ebd60259e4d8d8d765ec907069cf3c0f5bc53e2b2a3b408cdf9b5058"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/fuel-core-0.30.0%2Bnightly.20240701.ca47981d64-x86_64-unknown-linux-gnu.tar.gz"
hash = "40ddefa6a0accf4b02433341fad6b9346b7b6653005fd57b82bd28e6ca4a7a97"

[pkg.fuel-core-keygen]
version = "0.30.0+nightly.20240701.ca47981d64"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/fuel-core-0.30.0%2Bnightly.20240701.ca47981d64-aarch64-apple-darwin.tar.gz"
hash = "52d2704c7aeab7b8ad6cc3facef3cc0e8736db39cd684c0a52084fcb9b61844f"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/fuel-core-0.30.0%2Bnightly.20240701.ca47981d64-aarch64-unknown-linux-gnu.tar.gz"
hash = "250e34514367eb8608c605f72f7582efefa852333cdfff84ac2d5273b785a75c"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/fuel-core-0.30.0%2Bnightly.20240701.ca47981d64-x86_64-apple-darwin.tar.gz"
hash = "2f306fb1ebd60259e4d8d8d765ec907069cf3c0f5bc53e2b2a3b408cdf9b5058"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240701/fuel-core-0.30.0%2Bnightly.20240701.ca47981d64-x86_64-unknown-linux-gnu.tar.gz"
hash = "40ddefa6a0accf4b02433341fad6b9346b7b6653005fd57b82bd28e6ca4a7a97"
