published_by = "https://github.com/FuelLabs/fuelup/actions/runs/9753480509"
date = "2024-07-02"

[pkg.forc]
version = "0.61.0+nightly.20240702.65dbd34e71"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/forc-binaries-0.61.0%2Bnightly.20240702.65dbd34e71-darwin_amd64.tar.gz"
hash = "c96dd262e865ba824a055bcb5202caf82387cc9e474c4736dac67274d59f941e"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/forc-binaries-0.61.0%2Bnightly.20240702.65dbd34e71-darwin_arm64.tar.gz"
hash = "883f00895253999d4be1c97f47d6c63305c258cbcad5ca50c348d9116f75fb9f"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/forc-binaries-0.61.0%2Bnightly.20240702.65dbd34e71-linux_amd64.tar.gz"
hash = "db96890001bf25db4c2bd83ca149bfde18d420cfeaf138153ec2d6110bc2b13a"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/forc-binaries-0.61.0%2Bnightly.20240702.65dbd34e71-linux_arm64.tar.gz"
hash = "48cd5a83589df96395c84adca8c4723219889788b0a49892836f3302bc2afc52"

[pkg.forc-explore]
version = "0.28.1+nightly.20240702.4bb7392eed"

[pkg.forc-explore.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/forc-explore-0.28.1%2Bnightly.20240702.4bb7392eed-aarch64-apple-darwin.tar.gz"
hash = "d404d82ea98f84aa44fc9ab2c2ab51f0c36ca02a02c68695299c5f2fc4555cfd"

[pkg.forc-explore.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/forc-explore-0.28.1%2Bnightly.20240702.4bb7392eed-aarch64-unknown-linux-gnu.tar.gz"
hash = "bc11cefe3ec67a41a57b82ece1203eb0422400408c42670fbcafd371e8b60047"

[pkg.forc-explore.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/forc-explore-0.28.1%2Bnightly.20240702.4bb7392eed-x86_64-apple-darwin.tar.gz"
hash = "a45eb21cac00ddcc62c01244f18af2d284c4bb173d1d55fd658bacca040200a5"

[pkg.forc-explore.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/forc-explore-0.28.1%2Bnightly.20240702.4bb7392eed-x86_64-unknown-linux-gnu.tar.gz"
hash = "2c490fe9cc0a672cb153fb1e092421b7464a1f7a6204d9c342e55264eab7510f"

[pkg.forc-wallet]
version = "0.8.1+nightly.20240702.ab41cd516d"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/forc-wallet-0.8.1%2Bnightly.20240702.ab41cd516d-aarch64-apple-darwin.tar.gz"
hash = "12417f79f6404479d714081a67a090f96bacd274755cb7ef303f942602e2cf3e"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/forc-wallet-0.8.1%2Bnightly.20240702.ab41cd516d-aarch64-unknown-linux-gnu.tar.gz"
hash = "65ad020641b07acafb6537499e29134cea7a2308ce6ddf27163625a9b6d40057"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/forc-wallet-0.8.1%2Bnightly.20240702.ab41cd516d-x86_64-apple-darwin.tar.gz"
hash = "b2aa7ada2ec673c51efb9c123ed7974b5e3eaea0c4b7547027c7086e44c29150"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/forc-wallet-0.8.1%2Bnightly.20240702.ab41cd516d-x86_64-unknown-linux-gnu.tar.gz"
hash = "9d184f82eee5130fe81ed653ab43ad43cbde105d51dd981efeb7d57eeaaf400a"

[pkg.fuel-core]
version = "0.30.0+nightly.20240702.1fe81ca3ba"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/fuel-core-0.30.0%2Bnightly.20240702.1fe81ca3ba-aarch64-apple-darwin.tar.gz"
hash = "86bae4304335a39c1786f7d42ee33a23c8e004a7027c5ff1e50f39f343aa5209"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/fuel-core-0.30.0%2Bnightly.20240702.1fe81ca3ba-aarch64-unknown-linux-gnu.tar.gz"
hash = "aaca198e99b64f5ef55801e5a562b725d0a556c09ef5fdd6218e8d989e95eb3c"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/fuel-core-0.30.0%2Bnightly.20240702.1fe81ca3ba-x86_64-apple-darwin.tar.gz"
hash = "9b7eca7b9435e9d551174f1d464b7a3de0578323dbb4cfe26dcf61fc1a76cbe1"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/fuel-core-0.30.0%2Bnightly.20240702.1fe81ca3ba-x86_64-unknown-linux-gnu.tar.gz"
hash = "4ad229f9a98727b427c93fe4dfdcd10f87cc782ee1ff0ef70a4eed944296509a"

[pkg.fuel-core-keygen]
version = "0.30.0+nightly.20240702.1fe81ca3ba"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/fuel-core-0.30.0%2Bnightly.20240702.1fe81ca3ba-aarch64-apple-darwin.tar.gz"
hash = "86bae4304335a39c1786f7d42ee33a23c8e004a7027c5ff1e50f39f343aa5209"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/fuel-core-0.30.0%2Bnightly.20240702.1fe81ca3ba-aarch64-unknown-linux-gnu.tar.gz"
hash = "aaca198e99b64f5ef55801e5a562b725d0a556c09ef5fdd6218e8d989e95eb3c"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/fuel-core-0.30.0%2Bnightly.20240702.1fe81ca3ba-x86_64-apple-darwin.tar.gz"
hash = "9b7eca7b9435e9d551174f1d464b7a3de0578323dbb4cfe26dcf61fc1a76cbe1"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240702/fuel-core-0.30.0%2Bnightly.20240702.1fe81ca3ba-x86_64-unknown-linux-gnu.tar.gz"
hash = "4ad229f9a98727b427c93fe4dfdcd10f87cc782ee1ff0ef70a4eed944296509a"
