published_by = "https://github.com/FuelLabs/fuelup/actions/runs/13231701084"
date = "2025-02-10"

[pkg.forc]
version = "0.66.7+nightly.20250210.1fdf63069d"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250210/forc-binaries-0.66.7%2Bnightly.20250210.1fdf63069d-darwin_amd64.tar.gz"
hash = "830aec75fa723b138ca8e4bd7d6519def3cb26ef507bda286731171dab017a50"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250210/forc-binaries-0.66.7%2Bnightly.20250210.1fdf63069d-darwin_arm64.tar.gz"
hash = "f1cc2541f2d8f9d81265707752c47c28c066de3268dbebc5f41337e9a619d925"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250210/forc-binaries-0.66.7%2Bnightly.20250210.1fdf63069d-linux_amd64.tar.gz"
hash = "0b47cb35c3bb0803e5b6b971c150bf6187088068bb90c0f520b34097cd4d8d60"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250210/forc-binaries-0.66.7%2Bnightly.20250210.1fdf63069d-linux_arm64.tar.gz"
hash = "bc174de23b4b9f9105394f81e58cefd0faa246a9ec7f787e96d2aa435bcec91c"

[pkg.forc-wallet]
version = "0.12.0+nightly.20250210.8d59dbc462"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250210/forc-wallet-0.12.0%2Bnightly.20250210.8d59dbc462-aarch64-apple-darwin.tar.gz"
hash = "a1e4afc06934849f6dd2a2f693494720abb5277a2bcfbc87dd66d002637bded7"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250210/forc-wallet-0.12.0%2Bnightly.20250210.8d59dbc462-aarch64-unknown-linux-gnu.tar.gz"
hash = "b05eaa7b8197d7d8fb60824df382cd9b7c2b00d02dc2bbe1f3128cbf45c45b56"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250210/forc-wallet-0.12.0%2Bnightly.20250210.8d59dbc462-x86_64-apple-darwin.tar.gz"
hash = "1cd21429c5583f98ca6ea020793163ccf9bd61edd0761b6a3ba26e442f6cf24c"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250210/forc-wallet-0.12.0%2Bnightly.20250210.8d59dbc462-x86_64-unknown-linux-gnu.tar.gz"
hash = "f25d3269968a4b45e28614277d55c3e38d854a1f312b44d11166a88b1aebb1a4"

[pkg.fuel-core]
version = "0.41.6+nightly.20250210.8224289197"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250210/fuel-core-0.41.6%2Bnightly.20250210.8224289197-aarch64-apple-darwin.tar.gz"
hash = "b4bd57355e27a0f699c71edc485f24bdd431b7860b6d57372901fd55530052a9"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250210/fuel-core-0.41.6%2Bnightly.20250210.8224289197-aarch64-unknown-linux-gnu.tar.gz"
hash = "f47d00948c5605a1e2314516b31a15a84f8b8f33b9c6588847ef2decbd71967c"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250210/fuel-core-0.41.6%2Bnightly.20250210.8224289197-x86_64-apple-darwin.tar.gz"
hash = "60d8f259ed5e537583e8e7f7606506b744afc3460e10a4ad6989e61f7eef219b"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250210/fuel-core-0.41.6%2Bnightly.20250210.8224289197-x86_64-unknown-linux-gnu.tar.gz"
hash = "3da1ce33429a44ca31616de2d218382eb76699a04ba003ad492d11bf98753a89"

[pkg.fuel-core-keygen]
version = "0.41.6+nightly.20250210.8224289197"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250210/fuel-core-0.41.6%2Bnightly.20250210.8224289197-aarch64-apple-darwin.tar.gz"
hash = "b4bd57355e27a0f699c71edc485f24bdd431b7860b6d57372901fd55530052a9"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250210/fuel-core-0.41.6%2Bnightly.20250210.8224289197-aarch64-unknown-linux-gnu.tar.gz"
hash = "f47d00948c5605a1e2314516b31a15a84f8b8f33b9c6588847ef2decbd71967c"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250210/fuel-core-0.41.6%2Bnightly.20250210.8224289197-x86_64-apple-darwin.tar.gz"
hash = "60d8f259ed5e537583e8e7f7606506b744afc3460e10a4ad6989e61f7eef219b"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250210/fuel-core-0.41.6%2Bnightly.20250210.8224289197-x86_64-unknown-linux-gnu.tar.gz"
hash = "3da1ce33429a44ca31616de2d218382eb76699a04ba003ad492d11bf98753a89"
