published_by = "https://github.com/FuelLabs/fuelup/actions/runs/18330930876"
date = "2025-10-08"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251008.279124d992"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251008/forc-wallet-0.15.2%2Bnightly.20251008.279124d992-aarch64-apple-darwin.tar.gz"
hash = "a2f21a993fb105247f86848e610099f0596e71d7f34c5efcd93c00008721661c"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251008/forc-wallet-0.15.2%2Bnightly.20251008.279124d992-aarch64-unknown-linux-gnu.tar.gz"
hash = "9d5b73686de946847f7aa73a135b0ae71867257c8d13581f500b5ddf995ffbad"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251008/forc-wallet-0.15.2%2Bnightly.20251008.279124d992-x86_64-apple-darwin.tar.gz"
hash = "c8f452dbdeeebf790861e8a65cf670dc6e1f99025837ef385944e03d7cd354f9"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251008/forc-wallet-0.15.2%2Bnightly.20251008.279124d992-x86_64-unknown-linux-gnu.tar.gz"
hash = "6e988a478d14168ed26aeb330ec2fe16a6a9998decc19480e003193fa48cb7ae"
