published_by = "https://github.com/FuelLabs/fuelup/actions/runs/16485556270"
date = "2025-07-24"

[pkg.forc]
version = "0.69.1+nightly.20250724.22d858682b"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250724/forc-binaries-0.69.1%2Bnightly.20250724.22d858682b-darwin_amd64.tar.gz"
hash = "7b4e465b92a7de0341dcc645a285d200326f4e83a1f1bb51d8a382df664a8daa"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250724/forc-binaries-0.69.1%2Bnightly.20250724.22d858682b-darwin_arm64.tar.gz"
hash = "78e6a622bc23e4bbf17994d3c4f99c0d94d022150a06bad916036d65b5e4c75c"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250724/forc-binaries-0.69.1%2Bnightly.20250724.22d858682b-linux_amd64.tar.gz"
hash = "7df6c7387579a8ef77a1906f490cbb73d7af003daac8a3f35cec8fa5b774afb8"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250724/forc-binaries-0.69.1%2Bnightly.20250724.22d858682b-linux_arm64.tar.gz"
hash = "462d87b7fe6e7b908a9b8ea1dab011a4016a0accb4abdeeb595ab6c3440593a7"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250724.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250724/forc-wallet-0.15.1%2Bnightly.20250724.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "ef87fe7d464f63c9250bdf78509523e7ef7abeb13c729b7c5487683288946ebe"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250724/forc-wallet-0.15.1%2Bnightly.20250724.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "0d9ce41c9eac9157852b7c0a023aeb12bff95f3f9a2a92b634d7dae96ab15075"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250724/forc-wallet-0.15.1%2Bnightly.20250724.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "e6332e78682a2623a4adaedbcb19253346a5ec7bdef5fac6ba47132e19ca0a6a"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250724/forc-wallet-0.15.1%2Bnightly.20250724.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "de88bc89989d2c6a9dff5fed4a97adc9d21b163f6659667c42326f0ca081da7e"

[pkg.fuel-core]
version = "0.44.0+nightly.20250724.5108c931a7"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250724/fuel-core-0.44.0%2Bnightly.20250724.5108c931a7-aarch64-apple-darwin.tar.gz"
hash = "eb38407a8b373b8154d039a690c67ccd03ea269a5a4394733e8d29a9be824eeb"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250724/fuel-core-0.44.0%2Bnightly.20250724.5108c931a7-aarch64-unknown-linux-gnu.tar.gz"
hash = "fc55db2a0e8ec277e4207ef8ba11b69b39f06e7d98e6b1e74fb27dfe3da02ba5"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250724/fuel-core-0.44.0%2Bnightly.20250724.5108c931a7-x86_64-unknown-linux-gnu.tar.gz"
hash = "52fe2621170d9f5c8caeee7759abf2dca6e5efdedb7dcdb5057a6ba9aa6e9876"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250724.5108c931a7"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250724/fuel-core-0.44.0%2Bnightly.20250724.5108c931a7-aarch64-apple-darwin.tar.gz"
hash = "eb38407a8b373b8154d039a690c67ccd03ea269a5a4394733e8d29a9be824eeb"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250724/fuel-core-0.44.0%2Bnightly.20250724.5108c931a7-aarch64-unknown-linux-gnu.tar.gz"
hash = "fc55db2a0e8ec277e4207ef8ba11b69b39f06e7d98e6b1e74fb27dfe3da02ba5"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250724/fuel-core-0.44.0%2Bnightly.20250724.5108c931a7-x86_64-unknown-linux-gnu.tar.gz"
hash = "52fe2621170d9f5c8caeee7759abf2dca6e5efdedb7dcdb5057a6ba9aa6e9876"
