published_by = "https://github.com/FuelLabs/fuelup/actions/runs/13599525191"
date = "2025-03-01"

[pkg.forc]
version = "0.66.7+nightly.20250301.b7d15399f9"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250301/forc-binaries-0.66.7%2Bnightly.20250301.b7d15399f9-darwin_amd64.tar.gz"
hash = "af2c932c01a34d591a724a3b21f910408e8a240f27f8b696c8f6bac7844eb881"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250301/forc-binaries-0.66.7%2Bnightly.20250301.b7d15399f9-darwin_arm64.tar.gz"
hash = "a3110baa64c288feaa63945be9b5cff1997ed9b37dcc3a40c9a1ee1e6459b0d8"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250301/forc-binaries-0.66.7%2Bnightly.20250301.b7d15399f9-linux_amd64.tar.gz"
hash = "4ed650da18b81a9e3637fee0bda9c68a4b03454a5f2b9aa9afd1bc4b76aa2258"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250301/forc-binaries-0.66.7%2Bnightly.20250301.b7d15399f9-linux_arm64.tar.gz"
hash = "79b34eb129a9f372dbb8081989a567becd5bed5c52208ded7c5d64d59c7cecb7"

[pkg.forc-wallet]
version = "0.12.0+nightly.20250301.8d59dbc462"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250301/forc-wallet-0.12.0%2Bnightly.20250301.8d59dbc462-aarch64-apple-darwin.tar.gz"
hash = "5a5d7f31a495676c716daee1d78576b5ff4d3d273b0caf3bb4525a570aa35df2"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250301/forc-wallet-0.12.0%2Bnightly.20250301.8d59dbc462-aarch64-unknown-linux-gnu.tar.gz"
hash = "70cdd8d1c6f20f5f0391d072bb38802c5e39e83e92549e89306e86198b4e6ab8"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250301/forc-wallet-0.12.0%2Bnightly.20250301.8d59dbc462-x86_64-apple-darwin.tar.gz"
hash = "14c5f53743680c216d30770aa36aa2643d01e525eb5187f65312ab68b82a939c"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250301/forc-wallet-0.12.0%2Bnightly.20250301.8d59dbc462-x86_64-unknown-linux-gnu.tar.gz"
hash = "579c28b02e45a534552243f4261bf2b5a80f4840167fadb0f2cd9ef7b06bf89b"

[pkg.fuel-core]
version = "0.41.6+nightly.20250301.3cf86ab5b8"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250301/fuel-core-0.41.6%2Bnightly.20250301.3cf86ab5b8-aarch64-apple-darwin.tar.gz"
hash = "71b3f83448638eab25920a55ea7ed33c4fc1663e1ac87809a585c13fa493faf4"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250301/fuel-core-0.41.6%2Bnightly.20250301.3cf86ab5b8-aarch64-unknown-linux-gnu.tar.gz"
hash = "81a84131191594619f3f055429ddf56c43079f20edae59a659e0be7806e67324"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250301/fuel-core-0.41.6%2Bnightly.20250301.3cf86ab5b8-x86_64-apple-darwin.tar.gz"
hash = "823b29ae9c7e6a582e6942c98fceac4f6e803be7be5054e887819783e5ac346a"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250301/fuel-core-0.41.6%2Bnightly.20250301.3cf86ab5b8-x86_64-unknown-linux-gnu.tar.gz"
hash = "1162c089ed47716581fc5c89391561ff41896e0e08f42880c72f790451acd40f"

[pkg.fuel-core-keygen]
version = "0.41.6+nightly.20250301.3cf86ab5b8"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250301/fuel-core-0.41.6%2Bnightly.20250301.3cf86ab5b8-aarch64-apple-darwin.tar.gz"
hash = "71b3f83448638eab25920a55ea7ed33c4fc1663e1ac87809a585c13fa493faf4"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250301/fuel-core-0.41.6%2Bnightly.20250301.3cf86ab5b8-aarch64-unknown-linux-gnu.tar.gz"
hash = "81a84131191594619f3f055429ddf56c43079f20edae59a659e0be7806e67324"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250301/fuel-core-0.41.6%2Bnightly.20250301.3cf86ab5b8-x86_64-apple-darwin.tar.gz"
hash = "823b29ae9c7e6a582e6942c98fceac4f6e803be7be5054e887819783e5ac346a"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250301/fuel-core-0.41.6%2Bnightly.20250301.3cf86ab5b8-x86_64-unknown-linux-gnu.tar.gz"
hash = "1162c089ed47716581fc5c89391561ff41896e0e08f42880c72f790451acd40f"
