published_by = "https://github.com/FuelLabs/fuelup/actions/runs/16688389790"
date = "2025-08-02"

[pkg.forc]
version = "0.69.1+nightly.20250802.05e667dfc9"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250802/forc-binaries-0.69.1%2Bnightly.20250802.05e667dfc9-darwin_amd64.tar.gz"
hash = "adbd0cd8822bb742801d4fc379a1ececfbc28c3b6e7f6c9dd7893a1bcc581ecc"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250802/forc-binaries-0.69.1%2Bnightly.20250802.05e667dfc9-darwin_arm64.tar.gz"
hash = "6f813484e02a90a2ca55d1268347207dcb8ec0d0b821bdd146b1b8c47b314da4"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250802/forc-binaries-0.69.1%2Bnightly.20250802.05e667dfc9-linux_amd64.tar.gz"
hash = "ee29c09f7a77376f68dbc650b2277261df3d82d1fd71e2e8d3598dff5949ad59"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250802/forc-binaries-0.69.1%2Bnightly.20250802.05e667dfc9-linux_arm64.tar.gz"
hash = "3e4f161f259c44064a9cfc7c0823f433e6ba1cd6e259eb5193e98eb9270fd64a"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250802.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250802/forc-wallet-0.15.1%2Bnightly.20250802.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "47287a57995301cf13632657733a71c4bba54bb2a959eabc94ef4e39bfffcde3"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250802/forc-wallet-0.15.1%2Bnightly.20250802.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "cec630a21741a05b9cb5096aee47c9668571777e06ba2008a5c50a3be9286e36"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250802/forc-wallet-0.15.1%2Bnightly.20250802.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "be10e888edb7e48ea954231f82f84b6786b39b38513894328bded7ebb2c9c297"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250802/forc-wallet-0.15.1%2Bnightly.20250802.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "20fcdd15641267cc8bcac2fe4e161f6fe7bb0b613b98992731206e8966250225"

[pkg.fuel-core]
version = "0.45.1+nightly.20250802.01d562e577"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250802/fuel-core-0.45.1%2Bnightly.20250802.01d562e577-aarch64-apple-darwin.tar.gz"
hash = "6ff6b5b0a7cd5603b6a4b9898d21c00911af18b952f86939c6e6c6de9a122590"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250802/fuel-core-0.45.1%2Bnightly.20250802.01d562e577-aarch64-unknown-linux-gnu.tar.gz"
hash = "52f8eb0c273ddcbcd6ebbd4ee703921fc3bad9439f295a8ef829a0585610fc99"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250802/fuel-core-0.45.1%2Bnightly.20250802.01d562e577-x86_64-unknown-linux-gnu.tar.gz"
hash = "77e045218f4f33c363eff67b5aff64d4057bdc9e8a6bb0cac34d0498e3f3b451"

[pkg.fuel-core-keygen]
version = "0.45.1+nightly.20250802.01d562e577"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250802/fuel-core-0.45.1%2Bnightly.20250802.01d562e577-aarch64-apple-darwin.tar.gz"
hash = "6ff6b5b0a7cd5603b6a4b9898d21c00911af18b952f86939c6e6c6de9a122590"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250802/fuel-core-0.45.1%2Bnightly.20250802.01d562e577-aarch64-unknown-linux-gnu.tar.gz"
hash = "52f8eb0c273ddcbcd6ebbd4ee703921fc3bad9439f295a8ef829a0585610fc99"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250802/fuel-core-0.45.1%2Bnightly.20250802.01d562e577-x86_64-unknown-linux-gnu.tar.gz"
hash = "77e045218f4f33c363eff67b5aff64d4057bdc9e8a6bb0cac34d0498e3f3b451"
