published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15176012453"
date = "2025-05-22"

[pkg.forc]
version = "0.68.5+nightly.20250522.a70254b279"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250522/forc-binaries-0.68.5%2Bnightly.20250522.a70254b279-darwin_amd64.tar.gz"
hash = "db489d21fce27549565633ec6125ea27890a977a7161904d774c07b17c1808dc"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250522/forc-binaries-0.68.5%2Bnightly.20250522.a70254b279-darwin_arm64.tar.gz"
hash = "9cf9c21df528c245af08e0b408556e60f112ac62803441c5e7caa0065ca38ee1"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250522/forc-binaries-0.68.5%2Bnightly.20250522.a70254b279-linux_amd64.tar.gz"
hash = "2b08b9e84b2103c29669e3f312010167744372715a01985e3590d8eb6ddbaa9b"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250522/forc-binaries-0.68.5%2Bnightly.20250522.a70254b279-linux_arm64.tar.gz"
hash = "43a4917724dd27d0391b7eb5c4bbc8163171ceadcc9af56ea59e6f20091b17db"

[pkg.forc-wallet]
version = "0.14.0+nightly.20250522.24883eb126"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250522/forc-wallet-0.14.0%2Bnightly.20250522.24883eb126-aarch64-apple-darwin.tar.gz"
hash = "3499d25c13d1966c8e2f2bb7e8b86190c4f619bad718df10a4e55659721e9e3d"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250522/forc-wallet-0.14.0%2Bnightly.20250522.24883eb126-aarch64-unknown-linux-gnu.tar.gz"
hash = "37ad066c66f6f9b280dad9a2bf0ee9a30675e07dd32723704970fc70822ec8e9"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250522/forc-wallet-0.14.0%2Bnightly.20250522.24883eb126-x86_64-apple-darwin.tar.gz"
hash = "5b8af0d110e1664ff122b6909c092e7a33b3fdfc7f4257f064fbb0501f714ad2"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250522/forc-wallet-0.14.0%2Bnightly.20250522.24883eb126-x86_64-unknown-linux-gnu.tar.gz"
hash = "455214bdfbc5f470092973f64c79dd3c9097c347696612775baea5e8568767e0"

[pkg.fuel-core]
version = "0.43.0+nightly.20250522.cb7b83291d"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250522/fuel-core-0.43.0%2Bnightly.20250522.cb7b83291d-aarch64-apple-darwin.tar.gz"
hash = "6ff1c9545decc585e92448b60fb9e8e66a3acaa1079e601ffbad0657ed2a5e3e"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250522/fuel-core-0.43.0%2Bnightly.20250522.cb7b83291d-aarch64-unknown-linux-gnu.tar.gz"
hash = "1a8ed312dc9ff1d74b3ac5b5abf365d7a755314945cb3c7e735cbbca1b73c81b"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250522/fuel-core-0.43.0%2Bnightly.20250522.cb7b83291d-x86_64-unknown-linux-gnu.tar.gz"
hash = "91bdd518b441c819f496befe83c6e9bf4b4e82b76c004a3f208bcb2280ac462f"

[pkg.fuel-core-keygen]
version = "0.43.0+nightly.20250522.cb7b83291d"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250522/fuel-core-0.43.0%2Bnightly.20250522.cb7b83291d-aarch64-apple-darwin.tar.gz"
hash = "6ff1c9545decc585e92448b60fb9e8e66a3acaa1079e601ffbad0657ed2a5e3e"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250522/fuel-core-0.43.0%2Bnightly.20250522.cb7b83291d-aarch64-unknown-linux-gnu.tar.gz"
hash = "1a8ed312dc9ff1d74b3ac5b5abf365d7a755314945cb3c7e735cbbca1b73c81b"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250522/fuel-core-0.43.0%2Bnightly.20250522.cb7b83291d-x86_64-unknown-linux-gnu.tar.gz"
hash = "91bdd518b441c819f496befe83c6e9bf4b4e82b76c004a3f208bcb2280ac462f"
