published_by = "https://github.com/FuelLabs/fuelup/actions/runs/17481034717"
date = "2025-09-05"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250905.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250905/forc-wallet-0.15.1%2Bnightly.20250905.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "7065f30eade51ddc1af6427c2cfbbec9e1dfa0157251a50cf3ca3f71474635d8"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250905/forc-wallet-0.15.1%2Bnightly.20250905.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "ca0accdd01279ae22127bcb439306a3e1a5c11d63782df7bf95151f1b975ac4a"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250905/forc-wallet-0.15.1%2Bnightly.20250905.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "3799472d79a7f2add3652fd8bf6da84697a315192841201b03623e537791119d"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250905/forc-wallet-0.15.1%2Bnightly.20250905.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "33f6f80cedbbccaa0f7c262c755ca973e127dcd65134c317a490c45f603ad2e5"

[pkg.fuel-core]
version = "0.46.0+nightly.20250905.33238c6e10"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250905/fuel-core-0.46.0%2Bnightly.20250905.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "2271174e08b7722ed2e11ea4b3bd8a7c1ccce79876425346e731aa5211a003dd"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250905/fuel-core-0.46.0%2Bnightly.20250905.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "646bc7e495091fe34489f0b4a4729daf5c01cb675f532f103c9c785c9e939e4d"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250905/fuel-core-0.46.0%2Bnightly.20250905.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "9d9e9036793fb013abf86883fd58b34ea3e2131fe3f561f64ae5105ab6d807bd"

[pkg.fuel-core-keygen]
version = "0.46.0+nightly.20250905.33238c6e10"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250905/fuel-core-0.46.0%2Bnightly.20250905.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "2271174e08b7722ed2e11ea4b3bd8a7c1ccce79876425346e731aa5211a003dd"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250905/fuel-core-0.46.0%2Bnightly.20250905.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "646bc7e495091fe34489f0b4a4729daf5c01cb675f532f103c9c785c9e939e4d"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250905/fuel-core-0.46.0%2Bnightly.20250905.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "9d9e9036793fb013abf86883fd58b34ea3e2131fe3f561f64ae5105ab6d807bd"
