published_by = "https://github.com/FuelLabs/fuelup/actions/runs/13556875506"
date = "2025-02-27"

[pkg.forc]
version = "0.66.7+nightly.20250227.49d0eb48df"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250227/forc-binaries-0.66.7%2Bnightly.20250227.49d0eb48df-darwin_amd64.tar.gz"
hash = "a82148bba5382512622a95967749a4afbe178829f817337a7caff15964d8feaf"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250227/forc-binaries-0.66.7%2Bnightly.20250227.49d0eb48df-darwin_arm64.tar.gz"
hash = "4a222e400fa53724f3787844bdb3df7eb356c23454a5f2b6b9ff792d80522485"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250227/forc-binaries-0.66.7%2Bnightly.20250227.49d0eb48df-linux_amd64.tar.gz"
hash = "439a5a6b3c2c98f6e0fc6d6ce2b16ba3fd611c25619fdb41471bbf6b033169fd"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250227/forc-binaries-0.66.7%2Bnightly.20250227.49d0eb48df-linux_arm64.tar.gz"
hash = "e67f1f1c3c4d940492f3c466a3f8ce1e7f42c855f675620e37745af4a16ede2a"

[pkg.forc-wallet]
version = "0.12.0+nightly.20250227.8d59dbc462"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250227/forc-wallet-0.12.0%2Bnightly.20250227.8d59dbc462-aarch64-apple-darwin.tar.gz"
hash = "09c76d54ce02f7efa0311b92456a6c367d7af0b2c5aaa1a57b56cccaf89b02fe"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250227/forc-wallet-0.12.0%2Bnightly.20250227.8d59dbc462-aarch64-unknown-linux-gnu.tar.gz"
hash = "e574d2e1e08b1ae3f1027893b0ac00ca11612d98903e06f0d19c37e8955fafa6"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250227/forc-wallet-0.12.0%2Bnightly.20250227.8d59dbc462-x86_64-apple-darwin.tar.gz"
hash = "357a91bbaf33092e786944e34c0d928e21ca81ff9cf8093b495026d2c0d7b4af"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250227/forc-wallet-0.12.0%2Bnightly.20250227.8d59dbc462-x86_64-unknown-linux-gnu.tar.gz"
hash = "122f0068c1eeaa95f92a90aa62468f7d4a7df2054c917584d96c1536ecd07e3a"

[pkg.fuel-core]
version = "0.41.6+nightly.20250227.6ba3483d37"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250227/fuel-core-0.41.6%2Bnightly.20250227.6ba3483d37-aarch64-apple-darwin.tar.gz"
hash = "d999f966d6f0f9b015af91389215c76d9a2f6b16fe4727b32f74a39c31fd1072"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250227/fuel-core-0.41.6%2Bnightly.20250227.6ba3483d37-aarch64-unknown-linux-gnu.tar.gz"
hash = "818b48600909fe8569bafc2e6ae0c63d27394a7dd0395e94b5b354041b594eb2"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250227/fuel-core-0.41.6%2Bnightly.20250227.6ba3483d37-x86_64-apple-darwin.tar.gz"
hash = "ce734f864d2025baef48092c6efe78efcfd399cfa03356556099243a11bfbe5f"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250227/fuel-core-0.41.6%2Bnightly.20250227.6ba3483d37-x86_64-unknown-linux-gnu.tar.gz"
hash = "17e17f2daf98b47da3df183ea8c23817940d8f2af60a02ec28b9d633fed9f9c0"

[pkg.fuel-core-keygen]
version = "0.41.6+nightly.20250227.6ba3483d37"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250227/fuel-core-0.41.6%2Bnightly.20250227.6ba3483d37-aarch64-apple-darwin.tar.gz"
hash = "d999f966d6f0f9b015af91389215c76d9a2f6b16fe4727b32f74a39c31fd1072"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250227/fuel-core-0.41.6%2Bnightly.20250227.6ba3483d37-aarch64-unknown-linux-gnu.tar.gz"
hash = "818b48600909fe8569bafc2e6ae0c63d27394a7dd0395e94b5b354041b594eb2"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250227/fuel-core-0.41.6%2Bnightly.20250227.6ba3483d37-x86_64-apple-darwin.tar.gz"
hash = "ce734f864d2025baef48092c6efe78efcfd399cfa03356556099243a11bfbe5f"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250227/fuel-core-0.41.6%2Bnightly.20250227.6ba3483d37-x86_64-unknown-linux-gnu.tar.gz"
hash = "17e17f2daf98b47da3df183ea8c23817940d8f2af60a02ec28b9d633fed9f9c0"
