published_by = "https://github.com/FuelLabs/fuelup/actions/runs/13381374850"
date = "2025-02-18"

[pkg.forc]
version = "0.66.7+nightly.20250218.d8854fad08"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250218/forc-binaries-0.66.7%2Bnightly.20250218.d8854fad08-darwin_amd64.tar.gz"
hash = "bfb5d1e0e157aea3a3caa7d99721e7004d4189a4d44c14cd0c298225a1be9bff"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250218/forc-binaries-0.66.7%2Bnightly.20250218.d8854fad08-darwin_arm64.tar.gz"
hash = "fd638577abc30aded28eb283dc1d002d45a259d202e849baac42334ed64811a2"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250218/forc-binaries-0.66.7%2Bnightly.20250218.d8854fad08-linux_amd64.tar.gz"
hash = "afe84957cb3a3d53d926721143ceb4b20520c5bb90ab8741f019533dc2366e8a"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250218/forc-binaries-0.66.7%2Bnightly.20250218.d8854fad08-linux_arm64.tar.gz"
hash = "65471a81072b0eb9d1460210a75f331efd7c3046dbf09653b80ba9d664d039d3"

[pkg.forc-wallet]
version = "0.12.0+nightly.20250218.8d59dbc462"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250218/forc-wallet-0.12.0%2Bnightly.20250218.8d59dbc462-aarch64-apple-darwin.tar.gz"
hash = "7433a93541cfb81229139654dd0cce342a8bb8ab463ea29206d5e81bfe49ac09"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250218/forc-wallet-0.12.0%2Bnightly.20250218.8d59dbc462-aarch64-unknown-linux-gnu.tar.gz"
hash = "3571547e33320459735306fd4abf423f0c0a58c99800fa34a20603502d2fc824"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250218/forc-wallet-0.12.0%2Bnightly.20250218.8d59dbc462-x86_64-apple-darwin.tar.gz"
hash = "2a20ff264bc555e42740ded1d784e56d4993749ff9ce9724064a40b8326c4218"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250218/forc-wallet-0.12.0%2Bnightly.20250218.8d59dbc462-x86_64-unknown-linux-gnu.tar.gz"
hash = "69249dbf78d22a76cb94ed17a783625b0404fb5cbafb928f1799410b98196e44"

[pkg.fuel-core]
version = "0.41.6+nightly.20250218.c0975a0caa"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250218/fuel-core-0.41.6%2Bnightly.20250218.c0975a0caa-aarch64-apple-darwin.tar.gz"
hash = "6415c97caab36e2a2f251666015c407e19eabb614e107858e46eb4599d322d42"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250218/fuel-core-0.41.6%2Bnightly.20250218.c0975a0caa-aarch64-unknown-linux-gnu.tar.gz"
hash = "720e7d622cabd5000efc2a76ad87ab95f30ae461b02209b71c6ee4e50002da37"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250218/fuel-core-0.41.6%2Bnightly.20250218.c0975a0caa-x86_64-apple-darwin.tar.gz"
hash = "4bb135de65ab57ede2ba24ceabe917f5eceb426d0d40bc4d8b0146d14870d9e9"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250218/fuel-core-0.41.6%2Bnightly.20250218.c0975a0caa-x86_64-unknown-linux-gnu.tar.gz"
hash = "b2dd73a1d9e3b4f7ef2faaa8dc049077ddf4cbfdbfcde9f5ecbb87b45e5298e1"

[pkg.fuel-core-keygen]
version = "0.41.6+nightly.20250218.c0975a0caa"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250218/fuel-core-0.41.6%2Bnightly.20250218.c0975a0caa-aarch64-apple-darwin.tar.gz"
hash = "6415c97caab36e2a2f251666015c407e19eabb614e107858e46eb4599d322d42"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250218/fuel-core-0.41.6%2Bnightly.20250218.c0975a0caa-aarch64-unknown-linux-gnu.tar.gz"
hash = "720e7d622cabd5000efc2a76ad87ab95f30ae461b02209b71c6ee4e50002da37"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250218/fuel-core-0.41.6%2Bnightly.20250218.c0975a0caa-x86_64-apple-darwin.tar.gz"
hash = "4bb135de65ab57ede2ba24ceabe917f5eceb426d0d40bc4d8b0146d14870d9e9"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250218/fuel-core-0.41.6%2Bnightly.20250218.c0975a0caa-x86_64-unknown-linux-gnu.tar.gz"
hash = "b2dd73a1d9e3b4f7ef2faaa8dc049077ddf4cbfdbfcde9f5ecbb87b45e5298e1"
