published_by = "https://github.com/FuelLabs/fuelup/actions/runs/12061331867"
date = "2024-11-28"

[pkg.forc]
version = "0.66.5+nightly.20241128.bcd15c3d6e"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241128/forc-binaries-0.66.5%2Bnightly.20241128.bcd15c3d6e-darwin_amd64.tar.gz"
hash = "8e1be7d64d51da538754795f55656c850a088e41e60d952a5f36dbfc6b00cae6"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241128/forc-binaries-0.66.5%2Bnightly.20241128.bcd15c3d6e-darwin_arm64.tar.gz"
hash = "73ad5492f4f2e2245f6b05e67d4bff60b195e90c345309bcc7fa1048c9f9e163"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241128/forc-binaries-0.66.5%2Bnightly.20241128.bcd15c3d6e-linux_amd64.tar.gz"
hash = "48cbeb18d574920d7fc6f9ad1d85a41254cb9bf50a737c7417a649c9e0754a5a"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241128/forc-binaries-0.66.5%2Bnightly.20241128.bcd15c3d6e-linux_arm64.tar.gz"
hash = "ebbb5e648a4b8bd0304b88d7b015caa8973d0c9ae8c917f36d55b6209f667c1a"

[pkg.forc-wallet]
version = "0.11.1+nightly.20241128.f4052012e0"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241128/forc-wallet-0.11.1%2Bnightly.20241128.f4052012e0-aarch64-apple-darwin.tar.gz"
hash = "651e4028550b6b5a07426e86e135a5329317409037e571a219d4e2083f8a5998"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241128/forc-wallet-0.11.1%2Bnightly.20241128.f4052012e0-aarch64-unknown-linux-gnu.tar.gz"
hash = "fcb0b3a0358914b3b7748c5e0e28706e32b41170137aa07d33d95dc34cafe367"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241128/forc-wallet-0.11.1%2Bnightly.20241128.f4052012e0-x86_64-apple-darwin.tar.gz"
hash = "af45e68cb469c402f5ae671590c23c3da670c0b54dc1b28364cb5d0694944982"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241128/forc-wallet-0.11.1%2Bnightly.20241128.f4052012e0-x86_64-unknown-linux-gnu.tar.gz"
hash = "27a99e8e62248992bc336ec57f4d9884eb440da29fd242eb797e8fbe01c227fc"

[pkg.fuel-core]
version = "0.40.0+nightly.20241128.90b72a09f5"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241128/fuel-core-0.40.0%2Bnightly.20241128.90b72a09f5-aarch64-apple-darwin.tar.gz"
hash = "65cd2a2ec3e235d625c27d1b7b6c7b78f5205f252190be6ee14dfc8c3f438382"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241128/fuel-core-0.40.0%2Bnightly.20241128.90b72a09f5-aarch64-unknown-linux-gnu.tar.gz"
hash = "b029df1362fd57731cecd46f8a4d1c63425104d59ebc6abc8b3da33a3a3b5233"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241128/fuel-core-0.40.0%2Bnightly.20241128.90b72a09f5-x86_64-apple-darwin.tar.gz"
hash = "740b8c54ee9fcc5831533af8bd089756a9b8806bfd4aac4454255f2afb45526e"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241128/fuel-core-0.40.0%2Bnightly.20241128.90b72a09f5-x86_64-unknown-linux-gnu.tar.gz"
hash = "6ddf07d2bffa68a2ac5c05839b3e7d3184a73f1a078339b7fecaefdd95752e53"

[pkg.fuel-core-keygen]
version = "0.40.0+nightly.20241128.90b72a09f5"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241128/fuel-core-0.40.0%2Bnightly.20241128.90b72a09f5-aarch64-apple-darwin.tar.gz"
hash = "65cd2a2ec3e235d625c27d1b7b6c7b78f5205f252190be6ee14dfc8c3f438382"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241128/fuel-core-0.40.0%2Bnightly.20241128.90b72a09f5-aarch64-unknown-linux-gnu.tar.gz"
hash = "b029df1362fd57731cecd46f8a4d1c63425104d59ebc6abc8b3da33a3a3b5233"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241128/fuel-core-0.40.0%2Bnightly.20241128.90b72a09f5-x86_64-apple-darwin.tar.gz"
hash = "740b8c54ee9fcc5831533af8bd089756a9b8806bfd4aac4454255f2afb45526e"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241128/fuel-core-0.40.0%2Bnightly.20241128.90b72a09f5-x86_64-unknown-linux-gnu.tar.gz"
hash = "6ddf07d2bffa68a2ac5c05839b3e7d3184a73f1a078339b7fecaefdd95752e53"
