published_by = "https://github.com/FuelLabs/fuelup/actions/runs/10397247902"
date = "2024-08-15"

[pkg.forc]
version = "0.62.0+nightly.20240815.4c2c384302"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240815/forc-binaries-0.62.0%2Bnightly.20240815.4c2c384302-darwin_amd64.tar.gz"
hash = "2910d99e35d729f872b46781cbc105ab6589eaa082c7ccdb2dd125d8e1d6095d"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240815/forc-binaries-0.62.0%2Bnightly.20240815.4c2c384302-darwin_arm64.tar.gz"
hash = "843e9322c06480dade8c246d9e250340d54783cd7529e3b2457abc8d4af615a5"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240815/forc-binaries-0.62.0%2Bnightly.20240815.4c2c384302-linux_amd64.tar.gz"
hash = "dafb9f465dc1bc930e4bcdf3c1228a7cca52dc0492f086363c28b1dbb06af8a4"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240815/forc-binaries-0.62.0%2Bnightly.20240815.4c2c384302-linux_arm64.tar.gz"
hash = "ef1b9796ceef79b62afbed9a91c39d05b9a478bfe65e32c0118acca7b4a1d5d7"

[pkg.forc-wallet]
version = "0.9.0+nightly.20240815.29d9b25c2c"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240815/forc-wallet-0.9.0%2Bnightly.20240815.29d9b25c2c-aarch64-apple-darwin.tar.gz"
hash = "b3340c9531ad63775f9e1bea533bd066c57747b8dc3f22d16cc31ba61d320e00"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240815/forc-wallet-0.9.0%2Bnightly.20240815.29d9b25c2c-aarch64-unknown-linux-gnu.tar.gz"
hash = "3080db15d3b45e25fa6a88086ce856ae036c3f82729664e6e3ab23a7507808fc"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240815/forc-wallet-0.9.0%2Bnightly.20240815.29d9b25c2c-x86_64-apple-darwin.tar.gz"
hash = "b928b0e035847bff2024b26e49b2a9bdcf40d259097822bbae19205f9db5e128"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240815/forc-wallet-0.9.0%2Bnightly.20240815.29d9b25c2c-x86_64-unknown-linux-gnu.tar.gz"
hash = "52de7e062877ec5984a74c31528bd8d609faf8e914ce2e4643846cfb28a4504f"
