published_by = "https://github.com/FuelLabs/fuelup/actions/runs/19217771945"
date = "2025-11-10"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251110.279124d992"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251110/forc-wallet-0.15.2%2Bnightly.20251110.279124d992-aarch64-apple-darwin.tar.gz"
hash = "9dde6cf0c36b6b5ce01bb4bb6ce542ff434dc141bbe6e8c7307ef4edd3ab1677"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251110/forc-wallet-0.15.2%2Bnightly.20251110.279124d992-aarch64-unknown-linux-gnu.tar.gz"
hash = "dc0375755c3ef6bd04504cdcae46d6a10528f00808e819fcd768b36c4ab3af99"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251110/forc-wallet-0.15.2%2Bnightly.20251110.279124d992-x86_64-apple-darwin.tar.gz"
hash = "fc6c230c214f188d0fe68d07fbd8762ba753deea44b629b48da82c4c6e4040ca"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251110/forc-wallet-0.15.2%2Bnightly.20251110.279124d992-x86_64-unknown-linux-gnu.tar.gz"
hash = "6df6bf8373f61e05874d95f826eca1c6d33d9cc598ee525f180603ff70858257"
