published_by = "https://github.com/FuelLabs/fuelup/actions/runs/10986157177"
date = "2024-09-23"

[pkg.forc]
version = "0.63.6+nightly.20240923.1d50da1a4b"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240923/forc-binaries-0.63.6%2Bnightly.20240923.1d50da1a4b-darwin_amd64.tar.gz"
hash = "67edb080d3293b798ff2ed6ba4b219a921934fe03836639cc11c9aa4e7f49c64"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240923/forc-binaries-0.63.6%2Bnightly.20240923.1d50da1a4b-darwin_arm64.tar.gz"
hash = "60836c1064d15608062bab02be54e048bf1b577590f0235627bc79c0dbc926eb"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240923/forc-binaries-0.63.6%2Bnightly.20240923.1d50da1a4b-linux_amd64.tar.gz"
hash = "426bd92ea2e88d12b74f35b6f3a4dbc5006c8495fad7c916e6b8aa8c8f9cd06c"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240923/forc-binaries-0.63.6%2Bnightly.20240923.1d50da1a4b-linux_arm64.tar.gz"
hash = "2798d1436bbce91f04c929733bf65cf4484b8ed55fbd6e3a49b615924ba7b0e3"

[pkg.forc-wallet]
version = "0.9.0+nightly.20240923.5c30466f2b"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240923/forc-wallet-0.9.0%2Bnightly.20240923.5c30466f2b-aarch64-apple-darwin.tar.gz"
hash = "54c5fca510164a9805090c9a1a855046ed255f9f03fa291af2083e5b1cb1ae85"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240923/forc-wallet-0.9.0%2Bnightly.20240923.5c30466f2b-aarch64-unknown-linux-gnu.tar.gz"
hash = "15c7ca889a8c85695e0dc079430d20cd40ccef63be45be64378d8007f1363be5"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240923/forc-wallet-0.9.0%2Bnightly.20240923.5c30466f2b-x86_64-apple-darwin.tar.gz"
hash = "7910b84dde2e6e8370bdd50d872173a9a1c2c72315e1f8e72e3f3816940cf0b9"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240923/forc-wallet-0.9.0%2Bnightly.20240923.5c30466f2b-x86_64-unknown-linux-gnu.tar.gz"
hash = "deb904ce46f2f147fecd42e263e8fe7ceaaaf77d1a238ed1efd380663ee8e508"

[pkg.fuel-core]
version = "0.36.0+nightly.20240923.ca6a705bc2"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240923/fuel-core-0.36.0%2Bnightly.20240923.ca6a705bc2-aarch64-apple-darwin.tar.gz"
hash = "a1d9b30deca470d41ea71a63ec09eeb65d58bddfa3e28123a24b950860e2e3e4"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240923/fuel-core-0.36.0%2Bnightly.20240923.ca6a705bc2-aarch64-unknown-linux-gnu.tar.gz"
hash = "3ef143a896dad951ab35187967b01519eeee73c9b9399927bb5b554243f81fcb"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240923/fuel-core-0.36.0%2Bnightly.20240923.ca6a705bc2-x86_64-unknown-linux-gnu.tar.gz"
hash = "c170b6f3e349611632fa98922e7c7826815e5184688e9cf636c0eec602f31ae0"

[pkg.fuel-core-keygen]
version = "0.36.0+nightly.20240923.ca6a705bc2"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240923/fuel-core-0.36.0%2Bnightly.20240923.ca6a705bc2-aarch64-apple-darwin.tar.gz"
hash = "a1d9b30deca470d41ea71a63ec09eeb65d58bddfa3e28123a24b950860e2e3e4"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240923/fuel-core-0.36.0%2Bnightly.20240923.ca6a705bc2-aarch64-unknown-linux-gnu.tar.gz"
hash = "3ef143a896dad951ab35187967b01519eeee73c9b9399927bb5b554243f81fcb"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240923/fuel-core-0.36.0%2Bnightly.20240923.ca6a705bc2-x86_64-unknown-linux-gnu.tar.gz"
hash = "c170b6f3e349611632fa98922e7c7826815e5184688e9cf636c0eec602f31ae0"
