published_by = "https://github.com/FuelLabs/fuelup/actions/runs/12522561380"
date = "2024-12-28"

[pkg.forc]
version = "0.66.5+nightly.20241228.cf7b6664b5"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241228/forc-binaries-0.66.5%2Bnightly.20241228.cf7b6664b5-darwin_amd64.tar.gz"
hash = "e89ef7acbd8561757387f10a0afbb140ae5bdfe53e993f1560f411a7f554d5aa"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241228/forc-binaries-0.66.5%2Bnightly.20241228.cf7b6664b5-darwin_arm64.tar.gz"
hash = "a351429476575ac385b0b016c46f1e4635d355c2b30b121a86e774c948552f2d"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241228/forc-binaries-0.66.5%2Bnightly.20241228.cf7b6664b5-linux_amd64.tar.gz"
hash = "02c4e1bf0648f8a5f1dc9fb90e3800e4832c599585c5ccc2b891240761105628"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241228/forc-binaries-0.66.5%2Bnightly.20241228.cf7b6664b5-linux_arm64.tar.gz"
hash = "e29aaf7f592b969140cd9d2731fb6435f96e07094e8d167f153ab3dad0347e0e"

[pkg.forc-wallet]
version = "0.11.1+nightly.20241228.f4052012e0"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241228/forc-wallet-0.11.1%2Bnightly.20241228.f4052012e0-aarch64-apple-darwin.tar.gz"
hash = "af665e6180b4b6654ff34c505578c55f4b9e9279497253ac946015e2a8b62030"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241228/forc-wallet-0.11.1%2Bnightly.20241228.f4052012e0-aarch64-unknown-linux-gnu.tar.gz"
hash = "158737fdc0242dbe6b50276174153c8ae56581b80b108bea38f45aebaa6ab35b"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241228/forc-wallet-0.11.1%2Bnightly.20241228.f4052012e0-x86_64-apple-darwin.tar.gz"
hash = "0291d82b2d37b019a8a7f80793daa49711833ecd30904c02da186fe79e2f4c3c"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241228/forc-wallet-0.11.1%2Bnightly.20241228.f4052012e0-x86_64-unknown-linux-gnu.tar.gz"
hash = "ddb0cbefddf20c832656bb76baddece759626f0879aaaace9f2f8a8d22d448a9"

[pkg.fuel-core]
version = "0.40.0+nightly.20241228.d6e4bb9e33"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241228/fuel-core-0.40.0%2Bnightly.20241228.d6e4bb9e33-aarch64-apple-darwin.tar.gz"
hash = "bddaeea7f77d1e25b15127b3bc28ed71cb2657f3277fc2536a9059dc7b97b8e6"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241228/fuel-core-0.40.0%2Bnightly.20241228.d6e4bb9e33-aarch64-unknown-linux-gnu.tar.gz"
hash = "1688985016d84b4da6647a301cd619d4e3d5ccc6c9ee18187aef5bcf90c1891f"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241228/fuel-core-0.40.0%2Bnightly.20241228.d6e4bb9e33-x86_64-apple-darwin.tar.gz"
hash = "c0c1b393bd7defe864590e42e7299dd307cf354d93b71a7841c8bbe6d208ed97"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241228/fuel-core-0.40.0%2Bnightly.20241228.d6e4bb9e33-x86_64-unknown-linux-gnu.tar.gz"
hash = "bf2d722d0fb88237d5878b7b80eacb295922d0c6d1b065626212f7e916f3140f"

[pkg.fuel-core-keygen]
version = "0.40.0+nightly.20241228.d6e4bb9e33"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241228/fuel-core-0.40.0%2Bnightly.20241228.d6e4bb9e33-aarch64-apple-darwin.tar.gz"
hash = "bddaeea7f77d1e25b15127b3bc28ed71cb2657f3277fc2536a9059dc7b97b8e6"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241228/fuel-core-0.40.0%2Bnightly.20241228.d6e4bb9e33-aarch64-unknown-linux-gnu.tar.gz"
hash = "1688985016d84b4da6647a301cd619d4e3d5ccc6c9ee18187aef5bcf90c1891f"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241228/fuel-core-0.40.0%2Bnightly.20241228.d6e4bb9e33-x86_64-apple-darwin.tar.gz"
hash = "c0c1b393bd7defe864590e42e7299dd307cf354d93b71a7841c8bbe6d208ed97"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241228/fuel-core-0.40.0%2Bnightly.20241228.d6e4bb9e33-x86_64-unknown-linux-gnu.tar.gz"
hash = "bf2d722d0fb88237d5878b7b80eacb295922d0c6d1b065626212f7e916f3140f"
