published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15987501288"
date = "2025-07-01"

[pkg.forc]
version = "0.69.0+nightly.20250701.0cae7a3195"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250701/forc-binaries-0.69.0%2Bnightly.20250701.0cae7a3195-darwin_amd64.tar.gz"
hash = "312622ebd47ac9871c6ec02acca6c48f4d8057ca41b38175365755e4b9fd1d1b"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250701/forc-binaries-0.69.0%2Bnightly.20250701.0cae7a3195-darwin_arm64.tar.gz"
hash = "71269f903bc383233c4436607f564594481a9febe3911ad47456c601090299b3"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250701/forc-binaries-0.69.0%2Bnightly.20250701.0cae7a3195-linux_amd64.tar.gz"
hash = "a18c92a6eda6b4f6a452b17e6801456020c56c4459f0371c304a30699716af5a"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250701/forc-binaries-0.69.0%2Bnightly.20250701.0cae7a3195-linux_arm64.tar.gz"
hash = "d11ad3fdebb8244584810bdcc3c3d0cabffe6c33e5735f910339321fe6d4a523"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250701.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250701/forc-wallet-0.15.1%2Bnightly.20250701.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "f444a9e52cc40e7d1723fdc54a5b7b589475119489f82828ab3ba9e4ff2e0e10"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250701/forc-wallet-0.15.1%2Bnightly.20250701.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "463f9eb2c3b6532834ff29e476fc01a787ab7bbe40e1e90f72e72a873dd6bdcc"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250701/forc-wallet-0.15.1%2Bnightly.20250701.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "9fff9dc0fec4df5961b4bc4784eab2854efb1d54e17f504602f88b58b8ab069c"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250701/forc-wallet-0.15.1%2Bnightly.20250701.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "be0480c74e47e63b1f871f16a28fd27a7e376e625438d2119b1b937d109b559b"

[pkg.fuel-core]
version = "0.44.0+nightly.20250701.cee716ff92"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250701/fuel-core-0.44.0%2Bnightly.20250701.cee716ff92-aarch64-apple-darwin.tar.gz"
hash = "ff395f455ccc7108d88dc2cc6130d9751e1c0ba5d340070ec70a03b9c4a70abd"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250701/fuel-core-0.44.0%2Bnightly.20250701.cee716ff92-aarch64-unknown-linux-gnu.tar.gz"
hash = "be2701690976cc197c4faa567542203aac7a87221e2427daf738e4f964190719"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250701/fuel-core-0.44.0%2Bnightly.20250701.cee716ff92-x86_64-unknown-linux-gnu.tar.gz"
hash = "66b0db8ea87417ba65c82cc2de4f05e03cca85d0801b39c1598c75b8b5664610"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250701.cee716ff92"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250701/fuel-core-0.44.0%2Bnightly.20250701.cee716ff92-aarch64-apple-darwin.tar.gz"
hash = "ff395f455ccc7108d88dc2cc6130d9751e1c0ba5d340070ec70a03b9c4a70abd"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250701/fuel-core-0.44.0%2Bnightly.20250701.cee716ff92-aarch64-unknown-linux-gnu.tar.gz"
hash = "be2701690976cc197c4faa567542203aac7a87221e2427daf738e4f964190719"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250701/fuel-core-0.44.0%2Bnightly.20250701.cee716ff92-x86_64-unknown-linux-gnu.tar.gz"
hash = "66b0db8ea87417ba65c82cc2de4f05e03cca85d0801b39c1598c75b8b5664610"
