published_by = "https://github.com/FuelLabs/fuelup/actions/runs/10675039588"
date = "2024-09-03"

[pkg.forc]
version = "0.63.3+nightly.20240903.d781832b4a"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240903/forc-binaries-0.63.3%2Bnightly.20240903.d781832b4a-darwin_amd64.tar.gz"
hash = "e614404aab2ce5c2433d98db7f8636043b9a49d8db42fe4ec484cee6452bbb46"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240903/forc-binaries-0.63.3%2Bnightly.20240903.d781832b4a-darwin_arm64.tar.gz"
hash = "839a3239cd5be23982a489b1705cf868dfb6949b46f49da6c65021c2443106f8"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240903/forc-binaries-0.63.3%2Bnightly.20240903.d781832b4a-linux_amd64.tar.gz"
hash = "ad6675d281a62941d1b669157d3ca055cb5d3d9cbde9c16372d8f834d572d05f"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240903/forc-binaries-0.63.3%2Bnightly.20240903.d781832b4a-linux_arm64.tar.gz"
hash = "5b07b0de3518a22c4736f12fdf52d116a5f78838f2dbce2e72577a79c48c777a"

[pkg.forc-wallet]
version = "0.9.0+nightly.20240903.29d9b25c2c"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240903/forc-wallet-0.9.0%2Bnightly.20240903.29d9b25c2c-aarch64-apple-darwin.tar.gz"
hash = "255278847fb1e749cd3a05766f7672ac0e8dd73801ec70c4ad84da735d712b4d"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240903/forc-wallet-0.9.0%2Bnightly.20240903.29d9b25c2c-aarch64-unknown-linux-gnu.tar.gz"
hash = "9f40eb4c2e3e269e6b06948f14c1c409e1edfe6fde402b72bb726f6c23daf143"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240903/forc-wallet-0.9.0%2Bnightly.20240903.29d9b25c2c-x86_64-apple-darwin.tar.gz"
hash = "ed147d5bbeda16abdede67aa6c044f562b2beeff5ff2f9700e8b175ebf550bcb"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240903/forc-wallet-0.9.0%2Bnightly.20240903.29d9b25c2c-x86_64-unknown-linux-gnu.tar.gz"
hash = "300f79a5d6b89072c0c40d54f144bb7b15d574a4782a5c6ac822e38f3db92719"

[pkg.fuel-core]
version = "0.35.0+nightly.20240903.dfa76d7851"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240903/fuel-core-0.35.0%2Bnightly.20240903.dfa76d7851-aarch64-apple-darwin.tar.gz"
hash = "7e8c3034884f553ab8ac757c50dbe96dc3d490151005178f991eac2f429b62bd"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240903/fuel-core-0.35.0%2Bnightly.20240903.dfa76d7851-aarch64-unknown-linux-gnu.tar.gz"
hash = "fb5fd9dc47dca73521a4678f6e5fea9b096990080a82b8b465abd5ed09bcc3fb"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240903/fuel-core-0.35.0%2Bnightly.20240903.dfa76d7851-x86_64-unknown-linux-gnu.tar.gz"
hash = "5b543384b9393ebb5451ddf9a98b46460f05862dd31493285cb24c9576fc4486"

[pkg.fuel-core-keygen]
version = "0.35.0+nightly.20240903.dfa76d7851"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240903/fuel-core-0.35.0%2Bnightly.20240903.dfa76d7851-aarch64-apple-darwin.tar.gz"
hash = "7e8c3034884f553ab8ac757c50dbe96dc3d490151005178f991eac2f429b62bd"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240903/fuel-core-0.35.0%2Bnightly.20240903.dfa76d7851-aarch64-unknown-linux-gnu.tar.gz"
hash = "fb5fd9dc47dca73521a4678f6e5fea9b096990080a82b8b465abd5ed09bcc3fb"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240903/fuel-core-0.35.0%2Bnightly.20240903.dfa76d7851-x86_64-unknown-linux-gnu.tar.gz"
hash = "5b543384b9393ebb5451ddf9a98b46460f05862dd31493285cb24c9576fc4486"
