published_by = "https://github.com/FuelLabs/fuelup/actions/runs/10803318651"
date = "2024-09-11"

[pkg.forc]
version = "0.63.5+nightly.20240911.56997219cb"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240911/forc-binaries-0.63.5%2Bnightly.20240911.56997219cb-darwin_amd64.tar.gz"
hash = "923e14c581fb25ea0f6dce2e97d9b166aff64d32116de9994d3207d7409f3de9"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240911/forc-binaries-0.63.5%2Bnightly.20240911.56997219cb-darwin_arm64.tar.gz"
hash = "5a55186cf5b23ea88997bfcf32950bad51c3c572768f2ea91f5dda6409a90d1c"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240911/forc-binaries-0.63.5%2Bnightly.20240911.56997219cb-linux_amd64.tar.gz"
hash = "3c4873c2f23ce6988a122a792ccf095cd3b9a651214b15b661210465cae20745"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240911/forc-binaries-0.63.5%2Bnightly.20240911.56997219cb-linux_arm64.tar.gz"
hash = "fb14b24c4fc3c829f3f2c6af0d0e823cc554b500b72e453f182453be2b10a26c"

[pkg.forc-wallet]
version = "0.9.0+nightly.20240911.29d9b25c2c"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240911/forc-wallet-0.9.0%2Bnightly.20240911.29d9b25c2c-aarch64-apple-darwin.tar.gz"
hash = "9a9f604578a526e7afdaea89d70739ee0d2a00625c2106933eadfb125239e1a5"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240911/forc-wallet-0.9.0%2Bnightly.20240911.29d9b25c2c-aarch64-unknown-linux-gnu.tar.gz"
hash = "0a6a893d34d1ffce048a18edf9041d483de1f06277d6bd0d0c21c6c7e0044b1e"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240911/forc-wallet-0.9.0%2Bnightly.20240911.29d9b25c2c-x86_64-apple-darwin.tar.gz"
hash = "291ef391acc8f9a883720125ba046e81025bf47bf917c991d6f479d9773d3237"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240911/forc-wallet-0.9.0%2Bnightly.20240911.29d9b25c2c-x86_64-unknown-linux-gnu.tar.gz"
hash = "af7b81bc1372c77e738e2bc9fb0ce05add5b51eb3dd5c6dd7c9ee5300b84b0e7"

[pkg.fuel-core]
version = "0.35.0+nightly.20240911.ce857cf064"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240911/fuel-core-0.35.0%2Bnightly.20240911.ce857cf064-aarch64-apple-darwin.tar.gz"
hash = "c2009ee795243cee8766858fadfc5fde1f7f5d7248fc654f61402b4ff191e2a3"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240911/fuel-core-0.35.0%2Bnightly.20240911.ce857cf064-aarch64-unknown-linux-gnu.tar.gz"
hash = "6c27fe677526ed9badcadbb56a1467b86acc3626216f69fa4af814ebe6880139"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240911/fuel-core-0.35.0%2Bnightly.20240911.ce857cf064-x86_64-unknown-linux-gnu.tar.gz"
hash = "a7fde4f59f7865a94ca6d75cc22bee7de25918da0174a6ca3a5f04c17f65dcd3"

[pkg.fuel-core-keygen]
version = "0.35.0+nightly.20240911.ce857cf064"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240911/fuel-core-0.35.0%2Bnightly.20240911.ce857cf064-aarch64-apple-darwin.tar.gz"
hash = "c2009ee795243cee8766858fadfc5fde1f7f5d7248fc654f61402b4ff191e2a3"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240911/fuel-core-0.35.0%2Bnightly.20240911.ce857cf064-aarch64-unknown-linux-gnu.tar.gz"
hash = "6c27fe677526ed9badcadbb56a1467b86acc3626216f69fa4af814ebe6880139"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240911/fuel-core-0.35.0%2Bnightly.20240911.ce857cf064-x86_64-unknown-linux-gnu.tar.gz"
hash = "a7fde4f59f7865a94ca6d75cc22bee7de25918da0174a6ca3a5f04c17f65dcd3"
