published_by = "https://github.com/FuelLabs/fuelup/actions/runs/13534513183"
date = "2025-02-26"

[pkg.forc]
version = "0.66.7+nightly.20250226.a090937bef"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250226/forc-binaries-0.66.7%2Bnightly.20250226.a090937bef-darwin_amd64.tar.gz"
hash = "7a9c3a76b5347fb97b4945b2d56938326f7964185a6c677a703763ae533c2866"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250226/forc-binaries-0.66.7%2Bnightly.20250226.a090937bef-darwin_arm64.tar.gz"
hash = "c3982a3b36bb20d8e19fd981ef3b8dd9ed514e63c3c844157671030624dc5cd9"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250226/forc-binaries-0.66.7%2Bnightly.20250226.a090937bef-linux_amd64.tar.gz"
hash = "675ffb7fc15dae3fd31e40e8e80012555c92da4a270118f253c9b5e0bb3c702b"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250226/forc-binaries-0.66.7%2Bnightly.20250226.a090937bef-linux_arm64.tar.gz"
hash = "93c77d68463c0223c0cbbe403ced4a5ea0a07c1add06af6fd29a86d6fee40a05"

[pkg.forc-wallet]
version = "0.12.0+nightly.20250226.8d59dbc462"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250226/forc-wallet-0.12.0%2Bnightly.20250226.8d59dbc462-aarch64-apple-darwin.tar.gz"
hash = "6b55697bb933a5077424e30c077ec7e67b36913b9ca6fd9a85befce09c1600ed"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250226/forc-wallet-0.12.0%2Bnightly.20250226.8d59dbc462-aarch64-unknown-linux-gnu.tar.gz"
hash = "fbf91a61530dc591ffefe3b6e87666c5d13db789ba3d9efb7924b2095662b3bb"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250226/forc-wallet-0.12.0%2Bnightly.20250226.8d59dbc462-x86_64-apple-darwin.tar.gz"
hash = "d65ff6275024db4f03740593ab60e52b9d7f70d519bc3a11744114d76a5a9a6d"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250226/forc-wallet-0.12.0%2Bnightly.20250226.8d59dbc462-x86_64-unknown-linux-gnu.tar.gz"
hash = "557b349619a831365f57ec6be344091b836ef050b20de435e99a2f2064414bf9"

[pkg.fuel-core]
version = "0.41.6+nightly.20250226.e19f3a75d5"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250226/fuel-core-0.41.6%2Bnightly.20250226.e19f3a75d5-aarch64-apple-darwin.tar.gz"
hash = "646bf3770482a113f9de14d43498bb5c894925373e661fc75df1e9f9f60504f7"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250226/fuel-core-0.41.6%2Bnightly.20250226.e19f3a75d5-aarch64-unknown-linux-gnu.tar.gz"
hash = "1443eabcf23de5d59948bcc22a7cd7a79f44ac9c0aefed3f50514c636d2e5364"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250226/fuel-core-0.41.6%2Bnightly.20250226.e19f3a75d5-x86_64-apple-darwin.tar.gz"
hash = "3292349157f7e072debf17171ec151b5bbea5bcabae487d32f1d3268c40a6f93"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250226/fuel-core-0.41.6%2Bnightly.20250226.e19f3a75d5-x86_64-unknown-linux-gnu.tar.gz"
hash = "12df543904bb7596f13e7f3f31ce19211877106a8629181c935e535833d519ac"

[pkg.fuel-core-keygen]
version = "0.41.6+nightly.20250226.e19f3a75d5"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250226/fuel-core-0.41.6%2Bnightly.20250226.e19f3a75d5-aarch64-apple-darwin.tar.gz"
hash = "646bf3770482a113f9de14d43498bb5c894925373e661fc75df1e9f9f60504f7"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250226/fuel-core-0.41.6%2Bnightly.20250226.e19f3a75d5-aarch64-unknown-linux-gnu.tar.gz"
hash = "1443eabcf23de5d59948bcc22a7cd7a79f44ac9c0aefed3f50514c636d2e5364"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250226/fuel-core-0.41.6%2Bnightly.20250226.e19f3a75d5-x86_64-apple-darwin.tar.gz"
hash = "3292349157f7e072debf17171ec151b5bbea5bcabae487d32f1d3268c40a6f93"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250226/fuel-core-0.41.6%2Bnightly.20250226.e19f3a75d5-x86_64-unknown-linux-gnu.tar.gz"
hash = "12df543904bb7596f13e7f3f31ce19211877106a8629181c935e535833d519ac"
