published_by = "https://github.com/FuelLabs/fuelup/actions/runs/17015116092"
date = "2025-08-17"

[pkg.forc]
version = "0.69.1+nightly.20250817.fe9bbe39b9"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250817/forc-binaries-0.69.1%2Bnightly.20250817.fe9bbe39b9-darwin_amd64.tar.gz"
hash = "4f352504fa1f16590f11b78b91189ed8049ddbde26c7de382c26fe81f82a9bdd"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250817/forc-binaries-0.69.1%2Bnightly.20250817.fe9bbe39b9-darwin_arm64.tar.gz"
hash = "64c9a31dee33837701de68f9953782a07e51e3032e3366649647e3f613d82d48"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250817/forc-binaries-0.69.1%2Bnightly.20250817.fe9bbe39b9-linux_amd64.tar.gz"
hash = "015aa059df682ddfcbc27fa48955a5f0662edb056924f2b824194ffb582d4f5e"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250817/forc-binaries-0.69.1%2Bnightly.20250817.fe9bbe39b9-linux_arm64.tar.gz"
hash = "e558ba813898e333b40f66fe4f19727c3d3f4b89aeb3e07c99a02885869c4f9e"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250817.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250817/forc-wallet-0.15.1%2Bnightly.20250817.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "d6d97ac4e3cc2d6d96eede98afc35a2bcefadc976cfd8865a7a16aaf4f3c0a5f"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250817/forc-wallet-0.15.1%2Bnightly.20250817.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "b41e4e153f247f1a89bb8ad9a1c705d5d26237af4313d2b0156cd9eae2afd040"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250817/forc-wallet-0.15.1%2Bnightly.20250817.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "7cfd32cdf8128fdd7689bef95bb7adf402e5a75b46d8e37f0348f23fc73222ac"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250817/forc-wallet-0.15.1%2Bnightly.20250817.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "3559e969f994e2d1fdc23490a33d28d29eabbeb536f1234ddd37cdab99464797"

[pkg.fuel-core]
version = "0.46.0+nightly.20250817.33238c6e10"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250817/fuel-core-0.46.0%2Bnightly.20250817.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "a36f18464bbc3b8a960ef2774e4e0b8c75362f4d3955b4d333fa4f4174d28c7f"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250817/fuel-core-0.46.0%2Bnightly.20250817.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "f50b48ddceb7443db987ae41c2bc749b79f177cacf063259adba35948b86a19a"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250817/fuel-core-0.46.0%2Bnightly.20250817.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "8ada301caee42cf14ef2d68b385b6b61b8f22f46513f269fc48cb5b0337ab987"

[pkg.fuel-core-keygen]
version = "0.46.0+nightly.20250817.33238c6e10"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250817/fuel-core-0.46.0%2Bnightly.20250817.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "a36f18464bbc3b8a960ef2774e4e0b8c75362f4d3955b4d333fa4f4174d28c7f"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250817/fuel-core-0.46.0%2Bnightly.20250817.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "f50b48ddceb7443db987ae41c2bc749b79f177cacf063259adba35948b86a19a"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250817/fuel-core-0.46.0%2Bnightly.20250817.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "8ada301caee42cf14ef2d68b385b6b61b8f22f46513f269fc48cb5b0337ab987"
