published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15381795349"
date = "2025-06-02"

[pkg.forc]
version = "0.68.6+nightly.20250602.d6804729c9"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250602/forc-binaries-0.68.6%2Bnightly.20250602.d6804729c9-darwin_amd64.tar.gz"
hash = "342e642f1a18298f6bb459cf04d599f2191b6f8a91b541207d3a6fa3e1be9123"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250602/forc-binaries-0.68.6%2Bnightly.20250602.d6804729c9-darwin_arm64.tar.gz"
hash = "64fb9d61356e7c337a0f67ed5f8987775c237bdd29f3c5e8c63c5629495e9be3"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250602/forc-binaries-0.68.6%2Bnightly.20250602.d6804729c9-linux_amd64.tar.gz"
hash = "ff4fa6e788c15cc3cf6329d15a383633bd7c1a1a1c70cf277165fd3fbdc5a634"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250602/forc-binaries-0.68.6%2Bnightly.20250602.d6804729c9-linux_arm64.tar.gz"
hash = "4bb444774f2f880cbba22796d6c0a287d67aef6e80b3a800d0c993188dd320c0"

[pkg.forc-wallet]
version = "0.14.0+nightly.20250602.24883eb126"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250602/forc-wallet-0.14.0%2Bnightly.20250602.24883eb126-aarch64-apple-darwin.tar.gz"
hash = "09ecd07de8f44e971301d0051ff54b42307a0fd6f13cbdda057a22229ca9b421"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250602/forc-wallet-0.14.0%2Bnightly.20250602.24883eb126-aarch64-unknown-linux-gnu.tar.gz"
hash = "9aecda7bb5e32782a548f088e1ca1e905d00a5f2d1544998ecda756ee0e2a016"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250602/forc-wallet-0.14.0%2Bnightly.20250602.24883eb126-x86_64-apple-darwin.tar.gz"
hash = "7d8330277ce6aa3c03d2f5e0cc171a9b710148803372fd170a8481e1a8f2cbf9"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250602/forc-wallet-0.14.0%2Bnightly.20250602.24883eb126-x86_64-unknown-linux-gnu.tar.gz"
hash = "3ab3539c8b6097b25a6bbdebb97d1b7c7871107bfcf3a8446ebaf10945c9c660"

[pkg.fuel-core]
version = "0.44.0+nightly.20250602.49d0309dd1"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250602/fuel-core-0.44.0%2Bnightly.20250602.49d0309dd1-aarch64-apple-darwin.tar.gz"
hash = "dee52f4c4d194f670e52c1c7fbac8ee9b5660aa269fd2c7676f57a08306e113d"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250602/fuel-core-0.44.0%2Bnightly.20250602.49d0309dd1-aarch64-unknown-linux-gnu.tar.gz"
hash = "830b56d6d0e22a12dcc1e03739ae9bd2e2ffd4eebfb5472a1031136207286b41"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250602.49d0309dd1"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250602/fuel-core-0.44.0%2Bnightly.20250602.49d0309dd1-aarch64-apple-darwin.tar.gz"
hash = "dee52f4c4d194f670e52c1c7fbac8ee9b5660aa269fd2c7676f57a08306e113d"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250602/fuel-core-0.44.0%2Bnightly.20250602.49d0309dd1-aarch64-unknown-linux-gnu.tar.gz"
hash = "830b56d6d0e22a12dcc1e03739ae9bd2e2ffd4eebfb5472a1031136207286b41"
