published_by = "https://github.com/FuelLabs/fuelup/actions/runs/17661783592"
date = "2025-09-12"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250912.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250912/forc-wallet-0.15.1%2Bnightly.20250912.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "f2cbdc7afda8ccf662a6f64c3da24be447cebe2fbccdb93b86dfbbc40fa89521"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250912/forc-wallet-0.15.1%2Bnightly.20250912.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "04447e2c1d15f473818d268f69b854921bb59043d59b955f61ae27249075d0c1"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250912/forc-wallet-0.15.1%2Bnightly.20250912.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "b2ec924b8da9a29f36526a61e5522a470d2794b084d9fe6c94a767800c5a01b0"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250912/forc-wallet-0.15.1%2Bnightly.20250912.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "fa72f770d6a46b1e6d5f57ea873745d4b28e8baa3326905d9c5600610a5b6122"
