published_by = "https://github.com/FuelLabs/fuelup/actions/runs/13022835601"
date = "2025-01-29"

[pkg.forc]
version = "0.66.6+nightly.20250129.3b8efe9f73"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250129/forc-binaries-0.66.6%2Bnightly.20250129.3b8efe9f73-darwin_amd64.tar.gz"
hash = "be32e0b747f510c6d38c753c7e052e0a230911184cf8e02865f5ad6d6d5418b5"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250129/forc-binaries-0.66.6%2Bnightly.20250129.3b8efe9f73-darwin_arm64.tar.gz"
hash = "99acee5df7a25581c2fe1a966f6b5eaed4f92905ba444abb251cbf462b36dfb7"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250129/forc-binaries-0.66.6%2Bnightly.20250129.3b8efe9f73-linux_amd64.tar.gz"
hash = "bcdcb87377c1a71ab41206c6cf29eb186042a4805b3e15d0576adcde7df9ac32"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250129/forc-binaries-0.66.6%2Bnightly.20250129.3b8efe9f73-linux_arm64.tar.gz"
hash = "3acbda5dc9802b08765837eb875d8a5cf32d47e12620613ddd8d3f1814a99024"

[pkg.forc-wallet]
version = "0.12.0+nightly.20250129.8d59dbc462"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250129/forc-wallet-0.12.0%2Bnightly.20250129.8d59dbc462-aarch64-apple-darwin.tar.gz"
hash = "33d2069e81f7b5ba9e89247f80fc97a3c2fef4d12cc3cbc1d99b885c767e6d21"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250129/forc-wallet-0.12.0%2Bnightly.20250129.8d59dbc462-aarch64-unknown-linux-gnu.tar.gz"
hash = "dec50851f1c573912a069c32cd2f62ce2db5486b3dac7dcce195115a50188fa2"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250129/forc-wallet-0.12.0%2Bnightly.20250129.8d59dbc462-x86_64-apple-darwin.tar.gz"
hash = "8909e367c7b61140e245a652891642c3d26ce71f12fcc163dd98522d6eaae3d7"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250129/forc-wallet-0.12.0%2Bnightly.20250129.8d59dbc462-x86_64-unknown-linux-gnu.tar.gz"
hash = "f2a4ee4cc2be97615ccb0f1d0619bd2d01d4fa542ef321ebf64929f3290d14c4"

[pkg.fuel-core]
version = "0.41.4+nightly.20250129.4aed8f5bb4"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250129/fuel-core-0.41.4%2Bnightly.20250129.4aed8f5bb4-aarch64-apple-darwin.tar.gz"
hash = "10fb00950e82cd3e96af6fee588f9e57a610af21706d79cd859a925291aeb07f"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250129/fuel-core-0.41.4%2Bnightly.20250129.4aed8f5bb4-aarch64-unknown-linux-gnu.tar.gz"
hash = "677accf15d9a25ec2baf7df3ab31e2b62d2a5b6840a3f024a06a92dc191caac2"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250129/fuel-core-0.41.4%2Bnightly.20250129.4aed8f5bb4-x86_64-apple-darwin.tar.gz"
hash = "221f9313670023a6abeeebc953ea839c1697d05b2831a110bcafbe522e161b20"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250129/fuel-core-0.41.4%2Bnightly.20250129.4aed8f5bb4-x86_64-unknown-linux-gnu.tar.gz"
hash = "a0485f8c93e32b76cc2f4b279f9861a62bb48f371836195bed03913b7f36211d"

[pkg.fuel-core-keygen]
version = "0.41.4+nightly.20250129.4aed8f5bb4"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250129/fuel-core-0.41.4%2Bnightly.20250129.4aed8f5bb4-aarch64-apple-darwin.tar.gz"
hash = "10fb00950e82cd3e96af6fee588f9e57a610af21706d79cd859a925291aeb07f"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250129/fuel-core-0.41.4%2Bnightly.20250129.4aed8f5bb4-aarch64-unknown-linux-gnu.tar.gz"
hash = "677accf15d9a25ec2baf7df3ab31e2b62d2a5b6840a3f024a06a92dc191caac2"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250129/fuel-core-0.41.4%2Bnightly.20250129.4aed8f5bb4-x86_64-apple-darwin.tar.gz"
hash = "221f9313670023a6abeeebc953ea839c1697d05b2831a110bcafbe522e161b20"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250129/fuel-core-0.41.4%2Bnightly.20250129.4aed8f5bb4-x86_64-unknown-linux-gnu.tar.gz"
hash = "a0485f8c93e32b76cc2f4b279f9861a62bb48f371836195bed03913b7f36211d"
