published_by = "https://github.com/FuelLabs/fuelup/actions/runs/20200709032"
date = "2025-12-14"

[pkg.forc]
version = "0.70.1+nightly.20251214.5e179b304e"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/forc-binaries-0.70.1%2Bnightly.20251214.5e179b304e-darwin_amd64.tar.gz"
hash = "ba71662694b6459480d238e19664e541af9f564d966dda61ddf70db4d3c22520"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/forc-binaries-0.70.1%2Bnightly.20251214.5e179b304e-darwin_arm64.tar.gz"
hash = "a9d093e59a073d6ff8ab5b8e3c2b51a540581db752ba03426192f0840662a6c8"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/forc-binaries-0.70.1%2Bnightly.20251214.5e179b304e-linux_amd64.tar.gz"
hash = "451741838f0802233e55ea90d4f1daaaaa4d04a806b66d88f295316426a0d0bd"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/forc-binaries-0.70.1%2Bnightly.20251214.5e179b304e-linux_arm64.tar.gz"
hash = "4d38e6b94758204eef980009fb77c5248ea9eeb63dd303453b6a118f56c649d8"

[pkg.forc-crypto]
version = "0.71.0+nightly.20251214.c10463b0cb"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/forc-crypto-0.71.0%2Bnightly.20251214.c10463b0cb-darwin_amd64.tar.gz"
hash = "28ed9f4c7aa7ae10b92ddadf762af85a6da5594f153c2cc4d16fff8ba2e51f93"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/forc-crypto-0.71.0%2Bnightly.20251214.c10463b0cb-darwin_arm64.tar.gz"
hash = "1b31a284cdaac513ed8e2d005fdc9d9d3b720bcc2a19d802df12a499d802f5f7"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/forc-crypto-0.71.0%2Bnightly.20251214.c10463b0cb-linux_amd64.tar.gz"
hash = "3ce1cfbc26e87f61ef5be3697616cf45656de10df5d16032ba5f359adb8f2127"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/forc-crypto-0.71.0%2Bnightly.20251214.c10463b0cb-linux_arm64.tar.gz"
hash = "e708afe25e13606f4e44667cd1f29428116d3634db66717b496d280aab657c14"

[pkg.forc-wallet]
version = "0.16.2+nightly.20251214.c10463b0cb"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/forc-wallet-0.16.2%2Bnightly.20251214.c10463b0cb-darwin_amd64.tar.gz"
hash = "9122ec27072dff226bcc9b04b0d21437b78c9496aceadbbf15e9374dba8f7016"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/forc-wallet-0.16.2%2Bnightly.20251214.c10463b0cb-darwin_arm64.tar.gz"
hash = "92dd8be5d130666d19b7b16858ea4475d5775849e6e627b33f1fd57f36d0dd89"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/forc-wallet-0.16.2%2Bnightly.20251214.c10463b0cb-linux_amd64.tar.gz"
hash = "4d03cf60bcb2c77c51c02c55eb6ec46a21e819038f71ed6c8d4f7d5186cf736e"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/forc-wallet-0.16.2%2Bnightly.20251214.c10463b0cb-linux_arm64.tar.gz"
hash = "a8a4655a4bbcae95a07a9013b1aa3212dadb5e0fdd08b2a9426494d2d95e2b59"

[pkg.fuel-core]
version = "0.47.1+nightly.20251214.6889ed156b"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/fuel-core-0.47.1%2Bnightly.20251214.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "6a4a257dbfc08ed64056ee0522b6ba76eb930998e42ef8a5ded50735a3a0f172"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/fuel-core-0.47.1%2Bnightly.20251214.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "27d59f3ec9c3223185147537478758c1ed63d11a130b985f7a6566015eb44436"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/fuel-core-0.47.1%2Bnightly.20251214.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "04dbee8569299bcf3d6e5c36f11e73e843c4a527475c6bf7027c924f67e59946"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/fuel-core-0.47.1%2Bnightly.20251214.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "eae9bf3e93c1be9c801bae3eaf8f965fa1298600f72212851cb0f2cdf8802722"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20251214.6889ed156b"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/fuel-core-0.47.1%2Bnightly.20251214.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "6a4a257dbfc08ed64056ee0522b6ba76eb930998e42ef8a5ded50735a3a0f172"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/fuel-core-0.47.1%2Bnightly.20251214.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "27d59f3ec9c3223185147537478758c1ed63d11a130b985f7a6566015eb44436"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/fuel-core-0.47.1%2Bnightly.20251214.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "04dbee8569299bcf3d6e5c36f11e73e843c4a527475c6bf7027c924f67e59946"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251214/fuel-core-0.47.1%2Bnightly.20251214.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "eae9bf3e93c1be9c801bae3eaf8f965fa1298600f72212851cb0f2cdf8802722"
