published_by = "https://github.com/FuelLabs/fuelup/actions/runs/10428401508"
date = "2024-08-17"

[pkg.forc]
version = "0.62.0+nightly.20240817.9c49bc972b"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240817/forc-binaries-0.62.0%2Bnightly.20240817.9c49bc972b-darwin_amd64.tar.gz"
hash = "de80f4b165dc2f96d02331a79767e0139791ec357a40171545a2cd716fabeeeb"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240817/forc-binaries-0.62.0%2Bnightly.20240817.9c49bc972b-darwin_arm64.tar.gz"
hash = "b71391d5358c3f7daf171a192fc99f9b5dcc212d4836624706fa2ef52f624cb2"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240817/forc-binaries-0.62.0%2Bnightly.20240817.9c49bc972b-linux_amd64.tar.gz"
hash = "568a6e5be92d50d0021242f585a3402374e657fa0deb98f8a9126593b4d030bd"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240817/forc-binaries-0.62.0%2Bnightly.20240817.9c49bc972b-linux_arm64.tar.gz"
hash = "3d60d57c54a736db68307c0321a32d8a49c2de65a57b3b6f8ac0f2d134dc7ec6"

[pkg.forc-wallet]
version = "0.9.0+nightly.20240817.29d9b25c2c"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240817/forc-wallet-0.9.0%2Bnightly.20240817.29d9b25c2c-aarch64-apple-darwin.tar.gz"
hash = "326512626eafc683beb4689048b90a19090ebba79dbf643a0a46d31517f3e62b"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240817/forc-wallet-0.9.0%2Bnightly.20240817.29d9b25c2c-aarch64-unknown-linux-gnu.tar.gz"
hash = "4945d0160a1cc3276e118857f055e4764152bb6880e906dda02279c42cfcce27"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240817/forc-wallet-0.9.0%2Bnightly.20240817.29d9b25c2c-x86_64-apple-darwin.tar.gz"
hash = "5f0b751a3392d697dbcebc5cd586fde5b40b97004e5bf5066d720a561ea839c9"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240817/forc-wallet-0.9.0%2Bnightly.20240817.29d9b25c2c-x86_64-unknown-linux-gnu.tar.gz"
hash = "7b321636313ce794894db800c47590afce6906b33161621b159684a73f42eb72"

[pkg.fuel-core]
version = "0.32.1+nightly.20240817.9de2c08cfd"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240817/fuel-core-0.32.1%2Bnightly.20240817.9de2c08cfd-aarch64-apple-darwin.tar.gz"
hash = "f27f22e1c6e1ce8d8982ee5cbf9992d0043850b9b2bfffab8d469a3687e20312"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240817/fuel-core-0.32.1%2Bnightly.20240817.9de2c08cfd-aarch64-unknown-linux-gnu.tar.gz"
hash = "d7e5234f1c98eaf49bbcb1091f77a0d752d26dc1640b78960cae52d409f89bec"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240817/fuel-core-0.32.1%2Bnightly.20240817.9de2c08cfd-x86_64-apple-darwin.tar.gz"
hash = "fbc5fbc57db7a8b606f55a67ae5576b257bce8674a839064858cef89737a5a5b"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240817/fuel-core-0.32.1%2Bnightly.20240817.9de2c08cfd-x86_64-unknown-linux-gnu.tar.gz"
hash = "b3482f9b4d11a217cbf197c14bb5bc50da8f719052015fba29f8dcfe6910c8af"

[pkg.fuel-core-keygen]
version = "0.32.1+nightly.20240817.9de2c08cfd"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240817/fuel-core-0.32.1%2Bnightly.20240817.9de2c08cfd-aarch64-apple-darwin.tar.gz"
hash = "f27f22e1c6e1ce8d8982ee5cbf9992d0043850b9b2bfffab8d469a3687e20312"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240817/fuel-core-0.32.1%2Bnightly.20240817.9de2c08cfd-aarch64-unknown-linux-gnu.tar.gz"
hash = "d7e5234f1c98eaf49bbcb1091f77a0d752d26dc1640b78960cae52d409f89bec"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240817/fuel-core-0.32.1%2Bnightly.20240817.9de2c08cfd-x86_64-apple-darwin.tar.gz"
hash = "fbc5fbc57db7a8b606f55a67ae5576b257bce8674a839064858cef89737a5a5b"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240817/fuel-core-0.32.1%2Bnightly.20240817.9de2c08cfd-x86_64-unknown-linux-gnu.tar.gz"
hash = "b3482f9b4d11a217cbf197c14bb5bc50da8f719052015fba29f8dcfe6910c8af"
