published_by = "https://github.com/FuelLabs/fuelup/actions/runs/13889599024"
date = "2025-03-17"

[pkg.forc]
version = "0.67.0+nightly.20250317.eb287f405d"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250317/forc-binaries-0.67.0%2Bnightly.20250317.eb287f405d-darwin_amd64.tar.gz"
hash = "c0d889a756682506b4b4bbbda41d3bc10a6993e7c9c40533828fc21d7a8899f3"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250317/forc-binaries-0.67.0%2Bnightly.20250317.eb287f405d-darwin_arm64.tar.gz"
hash = "ef9200fc6669fe09084a2dcfd2e40ab95721d6e13632ba8016b3a73997072c2d"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250317/forc-binaries-0.67.0%2Bnightly.20250317.eb287f405d-linux_amd64.tar.gz"
hash = "d4050142fa11fd308d48533e61f540579919f14aff902e5e36ec2bb739b1c8f9"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250317/forc-binaries-0.67.0%2Bnightly.20250317.eb287f405d-linux_arm64.tar.gz"
hash = "0609e3032a3f3d224d552a29de866cd19699ae48518956ca187bb3f17a26e1c0"

[pkg.forc-wallet]
version = "0.12.0+nightly.20250317.8d59dbc462"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250317/forc-wallet-0.12.0%2Bnightly.20250317.8d59dbc462-aarch64-apple-darwin.tar.gz"
hash = "f3340c05836b2fd4bcbdbf6e7e61dda371ef8fcb1c4544edec0aa8f747934540"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250317/forc-wallet-0.12.0%2Bnightly.20250317.8d59dbc462-aarch64-unknown-linux-gnu.tar.gz"
hash = "5b258aca1f36359796d5cbea70dc75369ec8bee88b888a4b079368b8174b5a47"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250317/forc-wallet-0.12.0%2Bnightly.20250317.8d59dbc462-x86_64-apple-darwin.tar.gz"
hash = "3d269140b9e3abec6d4688fa6828bc60d6fc547909a9d7aa0e737f3352059a7d"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250317/forc-wallet-0.12.0%2Bnightly.20250317.8d59dbc462-x86_64-unknown-linux-gnu.tar.gz"
hash = "1eef292d88129c8f72292e22f73efd0605dc854179f65519e7253ff241737598"

[pkg.fuel-core]
version = "0.41.6+nightly.20250317.b759e4da95"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250317/fuel-core-0.41.6%2Bnightly.20250317.b759e4da95-aarch64-apple-darwin.tar.gz"
hash = "880d9443ee55ac33f3ac1e8735bbbf020987da85f7d935990b9512ad6fe77f84"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250317/fuel-core-0.41.6%2Bnightly.20250317.b759e4da95-aarch64-unknown-linux-gnu.tar.gz"
hash = "687c5902e9a304eb182216c440646b1badb7cb3d6c067ade923b423556ae08cb"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250317/fuel-core-0.41.6%2Bnightly.20250317.b759e4da95-x86_64-apple-darwin.tar.gz"
hash = "e86f42404d3b7ba980a4d9c4226298de3e1532d5942755a92066955bee37b931"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250317/fuel-core-0.41.6%2Bnightly.20250317.b759e4da95-x86_64-unknown-linux-gnu.tar.gz"
hash = "56c5950ee090b0941e4ec19c97290da7eab8cac08a91b9d468ee7052701f134a"

[pkg.fuel-core-keygen]
version = "0.41.6+nightly.20250317.b759e4da95"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250317/fuel-core-0.41.6%2Bnightly.20250317.b759e4da95-aarch64-apple-darwin.tar.gz"
hash = "880d9443ee55ac33f3ac1e8735bbbf020987da85f7d935990b9512ad6fe77f84"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250317/fuel-core-0.41.6%2Bnightly.20250317.b759e4da95-aarch64-unknown-linux-gnu.tar.gz"
hash = "687c5902e9a304eb182216c440646b1badb7cb3d6c067ade923b423556ae08cb"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250317/fuel-core-0.41.6%2Bnightly.20250317.b759e4da95-x86_64-apple-darwin.tar.gz"
hash = "e86f42404d3b7ba980a4d9c4226298de3e1532d5942755a92066955bee37b931"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250317/fuel-core-0.41.6%2Bnightly.20250317.b759e4da95-x86_64-unknown-linux-gnu.tar.gz"
hash = "56c5950ee090b0941e4ec19c97290da7eab8cac08a91b9d468ee7052701f134a"
