published_by = "https://github.com/FuelLabs/fuelup/actions/runs/12487994011"
date = "2024-12-25"

[pkg.forc]
version = "0.66.5+nightly.20241225.cf7b6664b5"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241225/forc-binaries-0.66.5%2Bnightly.20241225.cf7b6664b5-darwin_amd64.tar.gz"
hash = "e3ad5a71257c7a95e1142c922781e47827e318f3f57ae90374fd088f14b37726"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241225/forc-binaries-0.66.5%2Bnightly.20241225.cf7b6664b5-darwin_arm64.tar.gz"
hash = "b611f7974a34d87d4d60be2f56378a328f96d11250c1132c5394d50f176b33f6"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241225/forc-binaries-0.66.5%2Bnightly.20241225.cf7b6664b5-linux_amd64.tar.gz"
hash = "232777faf600a538683312f2c452500045727fa823cfe3dd49b0a8b1c5b008d3"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241225/forc-binaries-0.66.5%2Bnightly.20241225.cf7b6664b5-linux_arm64.tar.gz"
hash = "caefbd0bb47190c96a5542de2b7cc866372990241c317ccccb797e19b1489633"

[pkg.forc-wallet]
version = "0.11.1+nightly.20241225.f4052012e0"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241225/forc-wallet-0.11.1%2Bnightly.20241225.f4052012e0-aarch64-apple-darwin.tar.gz"
hash = "226f228c658740b149485c911dc82f169454bb82d352f78df784fe318f364836"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241225/forc-wallet-0.11.1%2Bnightly.20241225.f4052012e0-aarch64-unknown-linux-gnu.tar.gz"
hash = "1fa5d712cd6583b2d65f881d2892fcdd6700aaf2115b050c9c82bc7d71294acc"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241225/forc-wallet-0.11.1%2Bnightly.20241225.f4052012e0-x86_64-apple-darwin.tar.gz"
hash = "feb8d543b7308f6ac74dce1e0b6be4acef380c655626e886b1b8cb80c8ee839a"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241225/forc-wallet-0.11.1%2Bnightly.20241225.f4052012e0-x86_64-unknown-linux-gnu.tar.gz"
hash = "e5f517bd9f21d484155b944ed0cd0a838f3c29bf1b33b7e21fbe9d93af8534ea"

[pkg.fuel-core]
version = "0.40.0+nightly.20241225.d6e4bb9e33"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241225/fuel-core-0.40.0%2Bnightly.20241225.d6e4bb9e33-aarch64-apple-darwin.tar.gz"
hash = "34a0346dd111b57d4e809c73370dea78e94944150719a40ea3a283920819e764"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241225/fuel-core-0.40.0%2Bnightly.20241225.d6e4bb9e33-aarch64-unknown-linux-gnu.tar.gz"
hash = "edc69d2caf72641f3f895e854801911e1a6b8356f449aaf02faa82eb84c65547"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241225/fuel-core-0.40.0%2Bnightly.20241225.d6e4bb9e33-x86_64-apple-darwin.tar.gz"
hash = "35ca954a8dc982ee7573d28b8b16ec1457ce60d5d80a20cc8b0aa5b3b811a172"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241225/fuel-core-0.40.0%2Bnightly.20241225.d6e4bb9e33-x86_64-unknown-linux-gnu.tar.gz"
hash = "bf304ef001db52d306f7ee26c448e46da2f50a5d3d4bdcc6fc68a5bc670b1b4e"

[pkg.fuel-core-keygen]
version = "0.40.0+nightly.20241225.d6e4bb9e33"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241225/fuel-core-0.40.0%2Bnightly.20241225.d6e4bb9e33-aarch64-apple-darwin.tar.gz"
hash = "34a0346dd111b57d4e809c73370dea78e94944150719a40ea3a283920819e764"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241225/fuel-core-0.40.0%2Bnightly.20241225.d6e4bb9e33-aarch64-unknown-linux-gnu.tar.gz"
hash = "edc69d2caf72641f3f895e854801911e1a6b8356f449aaf02faa82eb84c65547"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241225/fuel-core-0.40.0%2Bnightly.20241225.d6e4bb9e33-x86_64-apple-darwin.tar.gz"
hash = "35ca954a8dc982ee7573d28b8b16ec1457ce60d5d80a20cc8b0aa5b3b811a172"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241225/fuel-core-0.40.0%2Bnightly.20241225.d6e4bb9e33-x86_64-unknown-linux-gnu.tar.gz"
hash = "bf304ef001db52d306f7ee26c448e46da2f50a5d3d4bdcc6fc68a5bc670b1b4e"
