published_by = "https://github.com/FuelLabs/fuelup/actions/runs/14676278340"
date = "2025-04-26"

[pkg.forc]
version = "0.68.1+nightly.20250426.eb57cbf284"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250426/forc-binaries-0.68.1%2Bnightly.20250426.eb57cbf284-darwin_amd64.tar.gz"
hash = "5e5b833cbcd893a03c8e2810809696a863edb15957a199a21ff6506316e374ef"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250426/forc-binaries-0.68.1%2Bnightly.20250426.eb57cbf284-darwin_arm64.tar.gz"
hash = "e383baea35f8c0240017dd251f85bdf777cc9cdfc5eb5d4f1c2493179954910b"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250426/forc-binaries-0.68.1%2Bnightly.20250426.eb57cbf284-linux_amd64.tar.gz"
hash = "ea223252ea46d9596d3a9ebe757ab18ca0b76c76832d002b93b426dbfc0512a3"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250426/forc-binaries-0.68.1%2Bnightly.20250426.eb57cbf284-linux_arm64.tar.gz"
hash = "13d625047a4a4ed2f5c70e5db861623375d0a9a8d86108da344e5801812056af"

[pkg.forc-wallet]
version = "0.14.0+nightly.20250426.9015e09f45"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250426/forc-wallet-0.14.0%2Bnightly.20250426.9015e09f45-aarch64-apple-darwin.tar.gz"
hash = "002edc18460011065a29bf9de895a5aef529089c6e3bb9c456cfb0b8776240ba"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250426/forc-wallet-0.14.0%2Bnightly.20250426.9015e09f45-aarch64-unknown-linux-gnu.tar.gz"
hash = "e7b71eda0d35fe55d6a84d895813a86e5929614438440431dc9a04e30c68d0de"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250426/forc-wallet-0.14.0%2Bnightly.20250426.9015e09f45-x86_64-apple-darwin.tar.gz"
hash = "e4de34221c5e157af7426915258e47f9153d9b9f9eddd81d1e7d5d938c498b74"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250426/forc-wallet-0.14.0%2Bnightly.20250426.9015e09f45-x86_64-unknown-linux-gnu.tar.gz"
hash = "a869aae89a26650f2a535dce938702113c9add77eda9b83f82495e98f722fe12"

[pkg.fuel-core]
version = "0.43.0+nightly.20250426.47b84ca7f6"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250426/fuel-core-0.43.0%2Bnightly.20250426.47b84ca7f6-aarch64-apple-darwin.tar.gz"
hash = "8f13bf182d30e71d6c195c17c0761fb4008e121197dbcbd250a0dbb9e030f042"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250426/fuel-core-0.43.0%2Bnightly.20250426.47b84ca7f6-aarch64-unknown-linux-gnu.tar.gz"
hash = "c78fb980a9809773faef66582330cb9663306837d30be0b7b84f3e311bce6db4"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250426/fuel-core-0.43.0%2Bnightly.20250426.47b84ca7f6-x86_64-unknown-linux-gnu.tar.gz"
hash = "837634721de665fb52cee30617855263434e9c67d84011a93ef194d84f3863c0"

[pkg.fuel-core-keygen]
version = "0.43.0+nightly.20250426.47b84ca7f6"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250426/fuel-core-0.43.0%2Bnightly.20250426.47b84ca7f6-aarch64-apple-darwin.tar.gz"
hash = "8f13bf182d30e71d6c195c17c0761fb4008e121197dbcbd250a0dbb9e030f042"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250426/fuel-core-0.43.0%2Bnightly.20250426.47b84ca7f6-aarch64-unknown-linux-gnu.tar.gz"
hash = "c78fb980a9809773faef66582330cb9663306837d30be0b7b84f3e311bce6db4"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250426/fuel-core-0.43.0%2Bnightly.20250426.47b84ca7f6-x86_64-unknown-linux-gnu.tar.gz"
hash = "837634721de665fb52cee30617855263434e9c67d84011a93ef194d84f3863c0"
