published_by = "https://github.com/FuelLabs/fuelup/actions/runs/17420322426"
date = "2025-09-03"

[pkg.forc]
version = "0.69.1+nightly.20250903.1e04b80c3a"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250903/forc-binaries-0.69.1%2Bnightly.20250903.1e04b80c3a-darwin_amd64.tar.gz"
hash = "261941dbd22bbcc1c61a9b084dc4788103ef3afb1d65ce5edd74250525625470"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250903/forc-binaries-0.69.1%2Bnightly.20250903.1e04b80c3a-darwin_arm64.tar.gz"
hash = "1ca5945bd5dcfaeb75312b43cf065ebb883a240c7cb06a3982559ccd01508be0"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250903/forc-binaries-0.69.1%2Bnightly.20250903.1e04b80c3a-linux_amd64.tar.gz"
hash = "602639d56a3d62af6f2290a4b831c7d161927cf5e56d26f0de0e906094760d9f"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250903/forc-binaries-0.69.1%2Bnightly.20250903.1e04b80c3a-linux_arm64.tar.gz"
hash = "af3462b1e6dffa4979ad2eb214870b2a71f726ee32af9a42982d7b778dd9dd92"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250903.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250903/forc-wallet-0.15.1%2Bnightly.20250903.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "fa995f87fe32d0cf85f14786a445b1397b6f0b0620ad0b5d8304f519df5428b9"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250903/forc-wallet-0.15.1%2Bnightly.20250903.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "e09c6011f5199deb48fc921887130b6dc10392a71f914a7a7a624e26ac5de85f"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250903/forc-wallet-0.15.1%2Bnightly.20250903.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "cf9b36bea018e58ee11c6d70d57ca68b9534ba544ad35cd07cf830e9a237b044"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250903/forc-wallet-0.15.1%2Bnightly.20250903.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "f2cee497fac9a60c743137e7cc4c556d6a60850c5c926b6f598b2723dd3502bb"

[pkg.fuel-core]
version = "0.46.0+nightly.20250903.33238c6e10"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250903/fuel-core-0.46.0%2Bnightly.20250903.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "32c7e832c7f97c25580154f949f0ec273f38ac1b60fce7c084dd8723efc6ba5a"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250903/fuel-core-0.46.0%2Bnightly.20250903.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "3ab82c1ea369eb55379f9cfab35590adfa7840d49acac3de4f71090c867f03b2"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250903/fuel-core-0.46.0%2Bnightly.20250903.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "60e1bd8065d420daab1acf664ed2bdf6a44dda88e9fa3471cb1c32d4657c2ae4"

[pkg.fuel-core-keygen]
version = "0.46.0+nightly.20250903.33238c6e10"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250903/fuel-core-0.46.0%2Bnightly.20250903.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "32c7e832c7f97c25580154f949f0ec273f38ac1b60fce7c084dd8723efc6ba5a"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250903/fuel-core-0.46.0%2Bnightly.20250903.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "3ab82c1ea369eb55379f9cfab35590adfa7840d49acac3de4f71090c867f03b2"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250903/fuel-core-0.46.0%2Bnightly.20250903.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "60e1bd8065d420daab1acf664ed2bdf6a44dda88e9fa3471cb1c32d4657c2ae4"
