published_by = "https://github.com/FuelLabs/fuelup/actions/runs/17845784121"
date = "2025-09-19"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250919.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250919/forc-wallet-0.15.1%2Bnightly.20250919.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "022e74ab7172287c944dd728a82933b156ccaff3cf8a8012e4c18ac95f1be553"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250919/forc-wallet-0.15.1%2Bnightly.20250919.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "a3bc032917545422c425ea190d3b6b5fcb760d6d67c6bf587235999fb6af8d11"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250919/forc-wallet-0.15.1%2Bnightly.20250919.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "5f985c5f0dfb64a716d5c80751f1544595fc4abf3b60194d1b6a879f635a10b5"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250919/forc-wallet-0.15.1%2Bnightly.20250919.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "9fc3dd42fae6140b2a2df9269ea1ff0477888005d830f8b4104b204405434106"
