published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15801565794"
date = "2025-06-22"

[pkg.forc]
version = "0.68.8+nightly.20250622.83154ab661"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250622/forc-binaries-0.68.8%2Bnightly.20250622.83154ab661-darwin_amd64.tar.gz"
hash = "a5274be8157bbd213573081e5b8a04e43272f01d913c68e3e572bb0c20521878"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250622/forc-binaries-0.68.8%2Bnightly.20250622.83154ab661-darwin_arm64.tar.gz"
hash = "602a95acd938c32b98cd0b2ee8dba450d32824f0df75786633e3d05cbeb84fec"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250622/forc-binaries-0.68.8%2Bnightly.20250622.83154ab661-linux_amd64.tar.gz"
hash = "465b1aada1a3a6b7b20c24d999493d1f08ea1f9711c596593dc70ae3fd76a1ee"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250622/forc-binaries-0.68.8%2Bnightly.20250622.83154ab661-linux_arm64.tar.gz"
hash = "9ea5f047aadff03b7e4ad4237d04a46b1b777e142083abefe4e987c41d02ffb5"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250622.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250622/forc-wallet-0.15.1%2Bnightly.20250622.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "dcf0702538f6159aa16a33763369553451f2c15c7cd5711efab29fdea1e1044e"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250622/forc-wallet-0.15.1%2Bnightly.20250622.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "48d075554dfad00e5f09c4b4770959b205ac8f558b17191692fc6fe3c9cee2e7"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250622/forc-wallet-0.15.1%2Bnightly.20250622.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "2845427983f512a41bfde500cc9a40a81b86f20b9046f05beb380d0a3bad21e5"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250622/forc-wallet-0.15.1%2Bnightly.20250622.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "02fb96844ade3d4e93e013b306dfd5be7ab9f8a7c3e8124c2a54ae9c97d36f6d"

[pkg.fuel-core]
version = "0.44.0+nightly.20250622.5dae42bafd"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250622/fuel-core-0.44.0%2Bnightly.20250622.5dae42bafd-aarch64-apple-darwin.tar.gz"
hash = "8552a5253b28afb14da3c2498090d1007b2513899312843ac02da5f57c4078c8"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250622/fuel-core-0.44.0%2Bnightly.20250622.5dae42bafd-aarch64-unknown-linux-gnu.tar.gz"
hash = "c3010426e36c2d2c23f582741cc7203417cc61bbf1fd9373263fad07f3df1891"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250622/fuel-core-0.44.0%2Bnightly.20250622.5dae42bafd-x86_64-unknown-linux-gnu.tar.gz"
hash = "bf06fded7c43b8660e545a462d9d0aa2f140a65c08dfe650bce31bf913a18d51"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250622.5dae42bafd"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250622/fuel-core-0.44.0%2Bnightly.20250622.5dae42bafd-aarch64-apple-darwin.tar.gz"
hash = "8552a5253b28afb14da3c2498090d1007b2513899312843ac02da5f57c4078c8"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250622/fuel-core-0.44.0%2Bnightly.20250622.5dae42bafd-aarch64-unknown-linux-gnu.tar.gz"
hash = "c3010426e36c2d2c23f582741cc7203417cc61bbf1fd9373263fad07f3df1891"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250622/fuel-core-0.44.0%2Bnightly.20250622.5dae42bafd-x86_64-unknown-linux-gnu.tar.gz"
hash = "bf06fded7c43b8660e545a462d9d0aa2f140a65c08dfe650bce31bf913a18d51"
