published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15658052162"
date = "2025-06-15"

[pkg.forc]
version = "0.68.7+nightly.20250615.e0724422c6"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250615/forc-binaries-0.68.7%2Bnightly.20250615.e0724422c6-darwin_amd64.tar.gz"
hash = "515163eacb864d12ec8f80d3926c5247eee70fc75b405b5656c37e7e9cfcf176"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250615/forc-binaries-0.68.7%2Bnightly.20250615.e0724422c6-darwin_arm64.tar.gz"
hash = "df09fb6c7f7b72c8fc487331bba8b48f733a9759f71f2274c34ab89f0cc79be0"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250615/forc-binaries-0.68.7%2Bnightly.20250615.e0724422c6-linux_amd64.tar.gz"
hash = "6b34e6c785cdd5491eab6a4aa9a8a65e59a6c057d2e41caf93e4732984821b88"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250615/forc-binaries-0.68.7%2Bnightly.20250615.e0724422c6-linux_arm64.tar.gz"
hash = "1bf546aaee9bfa02ae2ccaac17bd61af1047747e2fff204487f07ba6051ea265"

[pkg.forc-wallet]
version = "0.15.0+nightly.20250615.bddda681d3"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250615/forc-wallet-0.15.0%2Bnightly.20250615.bddda681d3-aarch64-apple-darwin.tar.gz"
hash = "4d6e84c2a2ca0ee23c53e65dcffa301f124e39a0c281d53fad9fd8778d6877d6"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250615/forc-wallet-0.15.0%2Bnightly.20250615.bddda681d3-aarch64-unknown-linux-gnu.tar.gz"
hash = "eea5018df9aa67792519aaf41b220b4815c69d98c1035535cb6128743a60463d"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250615/forc-wallet-0.15.0%2Bnightly.20250615.bddda681d3-x86_64-apple-darwin.tar.gz"
hash = "dd610bae35730bd9b9b878a44800a80c87ede1a2310c0f641832c58984383cd1"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250615/forc-wallet-0.15.0%2Bnightly.20250615.bddda681d3-x86_64-unknown-linux-gnu.tar.gz"
hash = "9428c17af9ac76b8f16ec66a48d9b47afe71fb882c1bce8c1ceaa48f60c463a9"

[pkg.fuel-core]
version = "0.44.0+nightly.20250615.6b6dd4a997"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250615/fuel-core-0.44.0%2Bnightly.20250615.6b6dd4a997-aarch64-apple-darwin.tar.gz"
hash = "8dd996550b8f3f189a84613f0565a24ca2067cf0af4fd456abfab6d9267d5685"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250615/fuel-core-0.44.0%2Bnightly.20250615.6b6dd4a997-aarch64-unknown-linux-gnu.tar.gz"
hash = "feedb7e2e17afc48cb9afa586d7cb8c9c292d303070f5d80ecd1ee4e1d4d1272"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250615/fuel-core-0.44.0%2Bnightly.20250615.6b6dd4a997-x86_64-unknown-linux-gnu.tar.gz"
hash = "94ae91878a8b55a9b490dab33b9e118176531b768c41d66151bfd1651fa3c1a9"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250615.6b6dd4a997"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250615/fuel-core-0.44.0%2Bnightly.20250615.6b6dd4a997-aarch64-apple-darwin.tar.gz"
hash = "8dd996550b8f3f189a84613f0565a24ca2067cf0af4fd456abfab6d9267d5685"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250615/fuel-core-0.44.0%2Bnightly.20250615.6b6dd4a997-aarch64-unknown-linux-gnu.tar.gz"
hash = "feedb7e2e17afc48cb9afa586d7cb8c9c292d303070f5d80ecd1ee4e1d4d1272"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250615/fuel-core-0.44.0%2Bnightly.20250615.6b6dd4a997-x86_64-unknown-linux-gnu.tar.gz"
hash = "94ae91878a8b55a9b490dab33b9e118176531b768c41d66151bfd1651fa3c1a9"
