published_by = "https://github.com/FuelLabs/fuelup/actions/runs/18826985471"
date = "2025-10-27"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251027.279124d992"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251027/forc-wallet-0.15.2%2Bnightly.20251027.279124d992-aarch64-apple-darwin.tar.gz"
hash = "8236dd4c78dd013b51fcc3fd7b5c35cea88a18cffe4b7b0ee2050b757c830c1a"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251027/forc-wallet-0.15.2%2Bnightly.20251027.279124d992-aarch64-unknown-linux-gnu.tar.gz"
hash = "290cbb012646dc8b0b668d85b1fccccc26ebc4c46c6da1df5a3bd6a88beb232b"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251027/forc-wallet-0.15.2%2Bnightly.20251027.279124d992-x86_64-apple-darwin.tar.gz"
hash = "f97d4d38ff6fc4ffb3e04b0cf6ca0729f1f8c4a277ef9ec8281fab8031e82fe7"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251027/forc-wallet-0.15.2%2Bnightly.20251027.279124d992-x86_64-unknown-linux-gnu.tar.gz"
hash = "3311666783ee61d9556a7c189f440a73c799867003eceac884c76acb01924eac"
