published_by = "https://github.com/FuelLabs/fuelup/actions/runs/16233518308"
date = "2025-07-12"

[pkg.forc]
version = "0.69.0+nightly.20250712.8b7524666b"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250712/forc-binaries-0.69.0%2Bnightly.20250712.8b7524666b-darwin_amd64.tar.gz"
hash = "57f5938d3f894bf06fae970ed8f50d24ce59429e102efa831ae65bb3b4d267a1"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250712/forc-binaries-0.69.0%2Bnightly.20250712.8b7524666b-darwin_arm64.tar.gz"
hash = "98c05280eefa82aa7316ad157fe8465d5bce44a89117f56ea5522871c47fbdb4"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250712/forc-binaries-0.69.0%2Bnightly.20250712.8b7524666b-linux_amd64.tar.gz"
hash = "0ff43df6300931133329f017035d0e42eb158bab192fe9a41183a351781cd497"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250712/forc-binaries-0.69.0%2Bnightly.20250712.8b7524666b-linux_arm64.tar.gz"
hash = "1f1e4cd5af19e8e61671f53434b2f7aff416792374ff7dffbeab24a410883747"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250712.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250712/forc-wallet-0.15.1%2Bnightly.20250712.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "330acbe01daa82f34ca7f153e9aae3a970db712cd39e1380edcabdaca49a9093"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250712/forc-wallet-0.15.1%2Bnightly.20250712.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "ce9091db4b4c5a55224bdf9c4cc6f1ca635c30e20dada0076b38c9d5ab2dc196"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250712/forc-wallet-0.15.1%2Bnightly.20250712.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "49453afb56197635a95e7f26731986167f510b506b447c849cd3f9307187cf43"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250712/forc-wallet-0.15.1%2Bnightly.20250712.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "0fcde798fa8a20577848cd18dbc90c0b3df77c8fbbd10fcb0ceb62b6deb70345"

[pkg.fuel-core]
version = "0.44.0+nightly.20250712.a08b48499c"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250712/fuel-core-0.44.0%2Bnightly.20250712.a08b48499c-aarch64-apple-darwin.tar.gz"
hash = "0ffb13642a766b070074b236612023b4800045b25fe4d7a5103bdcd18061e05f"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250712/fuel-core-0.44.0%2Bnightly.20250712.a08b48499c-aarch64-unknown-linux-gnu.tar.gz"
hash = "e5fcbc71d2246abb673e5e7080a07979a05030680dbbc252cd8eb4719172b3a0"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250712/fuel-core-0.44.0%2Bnightly.20250712.a08b48499c-x86_64-unknown-linux-gnu.tar.gz"
hash = "3efecb5f6a5075415f8ca0fd3c6b329e81cc87f72972ccf0e4cab74886633cf9"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250712.a08b48499c"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250712/fuel-core-0.44.0%2Bnightly.20250712.a08b48499c-aarch64-apple-darwin.tar.gz"
hash = "0ffb13642a766b070074b236612023b4800045b25fe4d7a5103bdcd18061e05f"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250712/fuel-core-0.44.0%2Bnightly.20250712.a08b48499c-aarch64-unknown-linux-gnu.tar.gz"
hash = "e5fcbc71d2246abb673e5e7080a07979a05030680dbbc252cd8eb4719172b3a0"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250712/fuel-core-0.44.0%2Bnightly.20250712.a08b48499c-x86_64-unknown-linux-gnu.tar.gz"
hash = "3efecb5f6a5075415f8ca0fd3c6b329e81cc87f72972ccf0e4cab74886633cf9"
