published_by = "https://github.com/FuelLabs/fuelup/actions/runs/17390620196"
date = "2025-09-02"

[pkg.forc]
version = "0.69.1+nightly.20250902.0aef56aa59"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250902/forc-binaries-0.69.1%2Bnightly.20250902.0aef56aa59-darwin_amd64.tar.gz"
hash = "44ceed38fc25dc3ee1cc21a22cd7eaf4d7b9e44358e02e297e61bd0537b44cd0"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250902/forc-binaries-0.69.1%2Bnightly.20250902.0aef56aa59-darwin_arm64.tar.gz"
hash = "d7055efaec1126410479e75b85dfc0aaa123293db65bb8d0c4b53ee19da49ea6"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250902/forc-binaries-0.69.1%2Bnightly.20250902.0aef56aa59-linux_amd64.tar.gz"
hash = "2687f56af6aa912b38c14d4b3075442c5a4f99acff31b8660d91f8f6dcd86c25"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250902/forc-binaries-0.69.1%2Bnightly.20250902.0aef56aa59-linux_arm64.tar.gz"
hash = "e64a6401cbc73da1ed9a4a74b423d9f093415c4fa82b7232409851450cf09066"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250902.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250902/forc-wallet-0.15.1%2Bnightly.20250902.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "648ea10d90776902e21c62fe12777b2e3ff1090e6cd04d0592d6ed9121752088"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250902/forc-wallet-0.15.1%2Bnightly.20250902.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "d23e3a266a01b11a7236bc22c9af97d82ac806753e733d789adf9ea92f3f294b"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250902/forc-wallet-0.15.1%2Bnightly.20250902.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "29288ecac2c98a9b040decfac971d89576671f602e65ced98cb20e934725962e"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250902/forc-wallet-0.15.1%2Bnightly.20250902.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "4c6ef85398731ebe2169402997b9c1d509352f4bfb291bb3ecb1db0ac0a8d508"

[pkg.fuel-core]
version = "0.46.0+nightly.20250902.33238c6e10"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250902/fuel-core-0.46.0%2Bnightly.20250902.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "13a722b10f8ee7c84a41284dd9d4cc46f604eae577303c913726669c6add2cd4"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250902/fuel-core-0.46.0%2Bnightly.20250902.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "20bb3d162ad07e09b7625cb1faa6eaa07a34520e992572f3b726048f736e4fe6"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250902/fuel-core-0.46.0%2Bnightly.20250902.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "52e25405c56ba2a42adec68bfbdae5cafac914e11fa09c79278950e7a4974bd9"

[pkg.fuel-core-keygen]
version = "0.46.0+nightly.20250902.33238c6e10"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250902/fuel-core-0.46.0%2Bnightly.20250902.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "13a722b10f8ee7c84a41284dd9d4cc46f604eae577303c913726669c6add2cd4"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250902/fuel-core-0.46.0%2Bnightly.20250902.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "20bb3d162ad07e09b7625cb1faa6eaa07a34520e992572f3b726048f736e4fe6"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250902/fuel-core-0.46.0%2Bnightly.20250902.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "52e25405c56ba2a42adec68bfbdae5cafac914e11fa09c79278950e7a4974bd9"
