published_by = "https://github.com/FuelLabs/fuelup/actions/runs/17114551251"
date = "2025-08-21"

[pkg.forc]
version = "0.69.1+nightly.20250821.f59835a78a"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250821/forc-binaries-0.69.1%2Bnightly.20250821.f59835a78a-darwin_amd64.tar.gz"
hash = "4fbfc7227ef79d5404fc3a73e74b9f2cc5bb3b09a85ca5681b5172af09930439"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250821/forc-binaries-0.69.1%2Bnightly.20250821.f59835a78a-darwin_arm64.tar.gz"
hash = "76630295f01a85ee0b85ea57e129b43a2a93b206f69d39e65e970814743fc42e"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250821/forc-binaries-0.69.1%2Bnightly.20250821.f59835a78a-linux_amd64.tar.gz"
hash = "573f8ec173513779d4d9dae46a13adf9b9d28bae5f827d503f427f5df32fbbd3"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250821/forc-binaries-0.69.1%2Bnightly.20250821.f59835a78a-linux_arm64.tar.gz"
hash = "b63135e213fb22536a745f6120631ee9eddc2c29b6cf3462c240be1f3141a4a8"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250821.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250821/forc-wallet-0.15.1%2Bnightly.20250821.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "2cda1c216f95ada09813486b1e20c9669f929619c5b14558b71cd47b76b10a9b"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250821/forc-wallet-0.15.1%2Bnightly.20250821.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "29aa42e2e0596e152d67388950aaf5c0a18822163b73fecebdb402da181f273c"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250821/forc-wallet-0.15.1%2Bnightly.20250821.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "94c4617e04d4d8bbbb7892423bc6be2156de66f6bee6e4848abcfb31e7cfa4b3"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250821/forc-wallet-0.15.1%2Bnightly.20250821.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "d4f251059897e7fe084f8f9a468c3beac9c655a551bb8960c42c18788fe7de7c"

[pkg.fuel-core]
version = "0.46.0+nightly.20250821.33238c6e10"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250821/fuel-core-0.46.0%2Bnightly.20250821.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "cf2a6842a36c25cf1e05624ce7cb0f9546655b3b7e1b4476b399e9386cae858d"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250821/fuel-core-0.46.0%2Bnightly.20250821.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "62d645e01d3c3580693a0be996be8066060a4dd2904af2885f071b3201df2b8e"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250821/fuel-core-0.46.0%2Bnightly.20250821.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "555f37e4e74497867e5c19f2e6a6eddec8adf654010bf258a79b35dd01a691d3"

[pkg.fuel-core-keygen]
version = "0.46.0+nightly.20250821.33238c6e10"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250821/fuel-core-0.46.0%2Bnightly.20250821.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "cf2a6842a36c25cf1e05624ce7cb0f9546655b3b7e1b4476b399e9386cae858d"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250821/fuel-core-0.46.0%2Bnightly.20250821.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "62d645e01d3c3580693a0be996be8066060a4dd2904af2885f071b3201df2b8e"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250821/fuel-core-0.46.0%2Bnightly.20250821.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "555f37e4e74497867e5c19f2e6a6eddec8adf654010bf258a79b35dd01a691d3"
