published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15502796610"
date = "2025-06-07"

[pkg.forc]
version = "0.68.7+nightly.20250607.fe8a3ef37a"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250607/forc-binaries-0.68.7%2Bnightly.20250607.fe8a3ef37a-darwin_amd64.tar.gz"
hash = "81e3f40359a3f5dc62b5a8b1debf3acc131cf0955ec5146a3447bfd5c22e18a3"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250607/forc-binaries-0.68.7%2Bnightly.20250607.fe8a3ef37a-darwin_arm64.tar.gz"
hash = "03eb91dfbe2a2d4054a832a99d3fe29bef3327cdb7e56329b66e5dd9117306c1"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250607/forc-binaries-0.68.7%2Bnightly.20250607.fe8a3ef37a-linux_amd64.tar.gz"
hash = "054718d0eea92c1c32c75c005259cb377782afb83ae0d1df42be3833d5987dfe"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250607/forc-binaries-0.68.7%2Bnightly.20250607.fe8a3ef37a-linux_arm64.tar.gz"
hash = "6fd453e0a74fd8b7438f28fa4f83c72e5e28ded1d5d295aa3ee95fd614f8d1b7"

[pkg.forc-wallet]
version = "0.14.0+nightly.20250607.24883eb126"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250607/forc-wallet-0.14.0%2Bnightly.20250607.24883eb126-aarch64-apple-darwin.tar.gz"
hash = "06a86e55ec10abf1a6786df0ab31639739903fdfe27ce89eacee821938a303a9"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250607/forc-wallet-0.14.0%2Bnightly.20250607.24883eb126-aarch64-unknown-linux-gnu.tar.gz"
hash = "df7bffd079c377c5066e9fe166bea1a20369a2f204e8415a2238f9cf2d06bdcb"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250607/forc-wallet-0.14.0%2Bnightly.20250607.24883eb126-x86_64-apple-darwin.tar.gz"
hash = "9c8f22cc0f3d3d383b54e1ee771cf09b33218b619e5cda1d0e9a0c2fab11abad"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250607/forc-wallet-0.14.0%2Bnightly.20250607.24883eb126-x86_64-unknown-linux-gnu.tar.gz"
hash = "20ccf51f1f3733aeae515d546cbb1098603f208ec4683e2c5097ee7feed41393"

[pkg.fuel-core]
version = "0.44.0+nightly.20250607.49d0309dd1"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250607/fuel-core-0.44.0%2Bnightly.20250607.49d0309dd1-aarch64-apple-darwin.tar.gz"
hash = "92675f5c494ca559961c14c690efcb8171a5c145d8ab2c9a5df5280c8839ad0c"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250607/fuel-core-0.44.0%2Bnightly.20250607.49d0309dd1-aarch64-unknown-linux-gnu.tar.gz"
hash = "fe903d1d017f38c6a03b50895994c6a7846ad287d2b93c728328fe6e180fbd0f"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250607.49d0309dd1"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250607/fuel-core-0.44.0%2Bnightly.20250607.49d0309dd1-aarch64-apple-darwin.tar.gz"
hash = "92675f5c494ca559961c14c690efcb8171a5c145d8ab2c9a5df5280c8839ad0c"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250607/fuel-core-0.44.0%2Bnightly.20250607.49d0309dd1-aarch64-unknown-linux-gnu.tar.gz"
hash = "fe903d1d017f38c6a03b50895994c6a7846ad287d2b93c728328fe6e180fbd0f"
