published_by = "https://github.com/FuelLabs/fuelup/actions/runs/19398397069"
date = "2025-11-16"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251116.74d8ce58f0"

[pkg.forc-wallet.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251116/forc-wallet-0.15.2%2Bnightly.20251116.74d8ce58f0-aarch64-apple-darwin.tar.gz"
hash = "e29d93faaf6743ac5e74e8437f3d4c374931a093d25fd3d31ae489437d665e83"

[pkg.forc-wallet.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251116/forc-wallet-0.15.2%2Bnightly.20251116.74d8ce58f0-aarch64-unknown-linux-gnu.tar.gz"
hash = "3588aeef70148181804074e0b86da1ce215812017f1421e59a8d759a1bab3683"

[pkg.forc-wallet.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251116/forc-wallet-0.15.2%2Bnightly.20251116.74d8ce58f0-x86_64-apple-darwin.tar.gz"
hash = "0bdde1d28e1190d745c1e9273686968d235e871fa72d5bdc7755883a643e88ea"

[pkg.forc-wallet.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251116/forc-wallet-0.15.2%2Bnightly.20251116.74d8ce58f0-x86_64-unknown-linux-gnu.tar.gz"
hash = "3350a18874dd3559d2db79f845148705a5fb7442dd643c2052c1fc59ef081e7e"
