published_by = "https://github.com/FuelLabs/fuelup/actions/runs/19620582104"
date = "2025-11-24"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251124.74d8ce58f0"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251124/forc-wallet-0.15.2%2Bnightly.20251124.74d8ce58f0-aarch64-apple-darwin.tar.gz"
hash = "4ece6578d92ada5f8179cd968a874834cfc611f4e34ce6c5bea70bd41564ff64"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251124/forc-wallet-0.15.2%2Bnightly.20251124.74d8ce58f0-aarch64-unknown-linux-gnu.tar.gz"
hash = "a788b8baf65dfca10bacd2b891125f564d957a02c82d6e9d58a0af86d88fe2e6"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251124/forc-wallet-0.15.2%2Bnightly.20251124.74d8ce58f0-x86_64-apple-darwin.tar.gz"
hash = "245e43c14cc2540e3a529703f3485526187eb84feff8731b52d2e8b20d18776f"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251124/forc-wallet-0.15.2%2Bnightly.20251124.74d8ce58f0-x86_64-unknown-linux-gnu.tar.gz"
hash = "44f1853a59b995fd9112ed18fca14c4399bf9f78d1340039f7ddafb6e8fd21c5"
