published_by = "https://github.com/FuelLabs/fuelup/actions/runs/11546094689"
date = "2024-10-28"

[pkg.forc]
version = "0.66.2+nightly.20241028.34b70f2beb"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241028/forc-binaries-0.66.2%2Bnightly.20241028.34b70f2beb-darwin_amd64.tar.gz"
hash = "13c546dffe4607b6cdb1bc72c8ed036501c5648b646cc2d6c14d755d110fdadc"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241028/forc-binaries-0.66.2%2Bnightly.20241028.34b70f2beb-darwin_arm64.tar.gz"
hash = "e01b54df0e65907c2001670720c57a286335e650b537cc7ae425060662ca8c7c"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241028/forc-binaries-0.66.2%2Bnightly.20241028.34b70f2beb-linux_amd64.tar.gz"
hash = "1c25d0195e81bc4ed3bd1dc8841871efd62675f3aad0866a6a331c1e860c5fd3"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241028/forc-binaries-0.66.2%2Bnightly.20241028.34b70f2beb-linux_arm64.tar.gz"
hash = "ef2458b74e89afd691c7d33a417f2c32d19f2cdb85e993b95f051da97351d630"

[pkg.forc-wallet]
version = "0.11.0+nightly.20241028.152bfb48c3"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241028/forc-wallet-0.11.0%2Bnightly.20241028.152bfb48c3-aarch64-apple-darwin.tar.gz"
hash = "6fa672fa9c748f6593bae62166972cb0baf98f1d584a11dccf93e97efc48374a"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241028/forc-wallet-0.11.0%2Bnightly.20241028.152bfb48c3-aarch64-unknown-linux-gnu.tar.gz"
hash = "f734d4f15edc83dc93261685bc25418d6f9cf26da70fe72364f251f40424a510"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241028/forc-wallet-0.11.0%2Bnightly.20241028.152bfb48c3-x86_64-apple-darwin.tar.gz"
hash = "d6d6075837bd1221a357571d221e8da9b55027263a17d8f90792e269b3b50a77"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241028/forc-wallet-0.11.0%2Bnightly.20241028.152bfb48c3-x86_64-unknown-linux-gnu.tar.gz"
hash = "342a43172c9ad14b6bf503c6a7658c3ba5813001aa9f325215afe3149fc51216"

[pkg.fuel-core]
version = "0.40.0+nightly.20241028.eea8c60525"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241028/fuel-core-0.40.0%2Bnightly.20241028.eea8c60525-aarch64-apple-darwin.tar.gz"
hash = "079f6fd219772c98c0806842a844f0c312010ceba623e41c5cd5fb106f949dd4"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241028/fuel-core-0.40.0%2Bnightly.20241028.eea8c60525-aarch64-unknown-linux-gnu.tar.gz"
hash = "378913390ac070b3e5cdd66ccd3ece64de9b3d977a19bf44390c172b8f624e18"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241028/fuel-core-0.40.0%2Bnightly.20241028.eea8c60525-x86_64-unknown-linux-gnu.tar.gz"
hash = "97977880feb3213d8aacdffcf964e3d0de07a021b4123acc6b466a69a215d535"

[pkg.fuel-core-keygen]
version = "0.40.0+nightly.20241028.eea8c60525"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241028/fuel-core-0.40.0%2Bnightly.20241028.eea8c60525-aarch64-apple-darwin.tar.gz"
hash = "079f6fd219772c98c0806842a844f0c312010ceba623e41c5cd5fb106f949dd4"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241028/fuel-core-0.40.0%2Bnightly.20241028.eea8c60525-aarch64-unknown-linux-gnu.tar.gz"
hash = "378913390ac070b3e5cdd66ccd3ece64de9b3d977a19bf44390c172b8f624e18"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241028/fuel-core-0.40.0%2Bnightly.20241028.eea8c60525-x86_64-unknown-linux-gnu.tar.gz"
hash = "97977880feb3213d8aacdffcf964e3d0de07a021b4123acc6b466a69a215d535"
