published_by = "https://github.com/FuelLabs/fuelup/actions/runs/12839556661"
date = "2025-01-18"

[pkg.forc]
version = "0.66.5+nightly.20250118.9cd1b3913d"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250118/forc-binaries-0.66.5%2Bnightly.20250118.9cd1b3913d-darwin_amd64.tar.gz"
hash = "8dc737e73d0039a245d5af95283d324035137f16aa1fb4d0e075b6c35f028a85"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250118/forc-binaries-0.66.5%2Bnightly.20250118.9cd1b3913d-darwin_arm64.tar.gz"
hash = "585990423cbc32065f4b6ddd83a64e42aa12a10e0d16c85a92c3263aa152519a"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250118/forc-binaries-0.66.5%2Bnightly.20250118.9cd1b3913d-linux_amd64.tar.gz"
hash = "738be4b015abb68b9071a4556b73789e94629e57a2eb2446286974848f16b029"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250118/forc-binaries-0.66.5%2Bnightly.20250118.9cd1b3913d-linux_arm64.tar.gz"
hash = "52a850ca7e0c364f603bae9fc257b1ab3d1980ba8f2fe25e2c35fa48ee930665"

[pkg.forc-wallet]
version = "0.11.1+nightly.20250118.f6f0ff07c8"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250118/forc-wallet-0.11.1%2Bnightly.20250118.f6f0ff07c8-aarch64-apple-darwin.tar.gz"
hash = "ef812e3f1f9e51a3e81b77119175d95aee4b824cd5460debe02bc0ecd5b69dda"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250118/forc-wallet-0.11.1%2Bnightly.20250118.f6f0ff07c8-aarch64-unknown-linux-gnu.tar.gz"
hash = "9786cdd0eb425fc8a47fb0ee5e60ed3942ca94e3755deb06414d5490ae640e78"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250118/forc-wallet-0.11.1%2Bnightly.20250118.f6f0ff07c8-x86_64-apple-darwin.tar.gz"
hash = "68be6fce280f9b104f15099caada9389014473cd1197b3669f9d8428c74b3b10"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250118/forc-wallet-0.11.1%2Bnightly.20250118.f6f0ff07c8-x86_64-unknown-linux-gnu.tar.gz"
hash = "8e426735c999aa5347e98eb7ef1ad3a8f28db92a2d82dae3b262e3b7a699f33c"

[pkg.fuel-core]
version = "0.41.0+nightly.20250118.dfc7fd7c0d"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250118/fuel-core-0.41.0%2Bnightly.20250118.dfc7fd7c0d-aarch64-apple-darwin.tar.gz"
hash = "c985834389d30bf3a72c556468dcd2d4c039d24b46f20ef57ee7f9ad162a0cef"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250118/fuel-core-0.41.0%2Bnightly.20250118.dfc7fd7c0d-aarch64-unknown-linux-gnu.tar.gz"
hash = "62e8ea9f11f2f4f901bbe56e7c0a62ecfab4b40653987be836ce65397293a373"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250118/fuel-core-0.41.0%2Bnightly.20250118.dfc7fd7c0d-x86_64-apple-darwin.tar.gz"
hash = "f09b616bb512ef886f55d6e53c579f73e946b98f303a297fd0f05b36b7a4ffa8"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250118/fuel-core-0.41.0%2Bnightly.20250118.dfc7fd7c0d-x86_64-unknown-linux-gnu.tar.gz"
hash = "bcb10a99b4caa95b0f268f46730a9003088ae71041b4e712505f4877fd4b2085"

[pkg.fuel-core-keygen]
version = "0.41.0+nightly.20250118.dfc7fd7c0d"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250118/fuel-core-0.41.0%2Bnightly.20250118.dfc7fd7c0d-aarch64-apple-darwin.tar.gz"
hash = "c985834389d30bf3a72c556468dcd2d4c039d24b46f20ef57ee7f9ad162a0cef"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250118/fuel-core-0.41.0%2Bnightly.20250118.dfc7fd7c0d-aarch64-unknown-linux-gnu.tar.gz"
hash = "62e8ea9f11f2f4f901bbe56e7c0a62ecfab4b40653987be836ce65397293a373"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250118/fuel-core-0.41.0%2Bnightly.20250118.dfc7fd7c0d-x86_64-apple-darwin.tar.gz"
hash = "f09b616bb512ef886f55d6e53c579f73e946b98f303a297fd0f05b36b7a4ffa8"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250118/fuel-core-0.41.0%2Bnightly.20250118.dfc7fd7c0d-x86_64-unknown-linux-gnu.tar.gz"
hash = "bcb10a99b4caa95b0f268f46730a9003088ae71041b4e712505f4877fd4b2085"
