published_by = "https://github.com/FuelLabs/fuelup/actions/runs/10051055650"
date = "2024-07-23"

[pkg.forc]
version = "0.62.0+nightly.20240723.508554547f"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240723/forc-binaries-0.62.0%2Bnightly.20240723.508554547f-darwin_amd64.tar.gz"
hash = "1d7ae6d94e1529e9c89f67d93cedac09bdf4043d67b366125ee0783446d06eb9"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240723/forc-binaries-0.62.0%2Bnightly.20240723.508554547f-darwin_arm64.tar.gz"
hash = "b43a13210205191844214de6170784549721f3eb43e96e3b3fb8488121c8dd74"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240723/forc-binaries-0.62.0%2Bnightly.20240723.508554547f-linux_amd64.tar.gz"
hash = "6add0312dc172df15c00e61a94401feb92a7a78584ae298b02e3e27626c32e9a"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240723/forc-binaries-0.62.0%2Bnightly.20240723.508554547f-linux_arm64.tar.gz"
hash = "bdc1ae9bd5d6beba165f8a02eb66939286f422844d903bff44e11f8f94d1c5ff"

[pkg.forc-wallet]
version = "0.8.2+nightly.20240723.76e9796cbe"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240723/forc-wallet-0.8.2%2Bnightly.20240723.76e9796cbe-aarch64-apple-darwin.tar.gz"
hash = "ac8df7f374c68cc1de9e2bc2ff6a01d0e8658cb9208c5f68f5b0feea4173046e"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240723/forc-wallet-0.8.2%2Bnightly.20240723.76e9796cbe-aarch64-unknown-linux-gnu.tar.gz"
hash = "65d9f22d5ac65c06cce1e27764e01e5bb0389fd51c39e4805bd75747ac7ffbc1"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240723/forc-wallet-0.8.2%2Bnightly.20240723.76e9796cbe-x86_64-apple-darwin.tar.gz"
hash = "57e405b5cab117c1b91f0f7c088ac34bee145909c4e2aa97d9fa125b624ab881"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240723/forc-wallet-0.8.2%2Bnightly.20240723.76e9796cbe-x86_64-unknown-linux-gnu.tar.gz"
hash = "30ebeccea021ec1f666d326c9ac3a2256dc3ddbd26ee7f445775a1c27ccc34eb"

[pkg.fuel-core]
version = "0.31.0+nightly.20240723.ab5a937fdf"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240723/fuel-core-0.31.0%2Bnightly.20240723.ab5a937fdf-aarch64-apple-darwin.tar.gz"
hash = "9e56f3c6c365fcb3840e20a671aa0a4bda1d623eed32366a717c17c91e00922a"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240723/fuel-core-0.31.0%2Bnightly.20240723.ab5a937fdf-aarch64-unknown-linux-gnu.tar.gz"
hash = "572ef039e0e18612430cfcb930500f64fd84f50a80123d9f56e09ee67718c9dc"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240723/fuel-core-0.31.0%2Bnightly.20240723.ab5a937fdf-x86_64-apple-darwin.tar.gz"
hash = "3f07c2bbcb412a34c5bfeb19024e8a975bf2ab9b5eb5bd89ca9b1ca9a64c728b"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240723/fuel-core-0.31.0%2Bnightly.20240723.ab5a937fdf-x86_64-unknown-linux-gnu.tar.gz"
hash = "12d6222ab5cfc634708527892d19929ad8c04c2d1debfd59fc3bfe8141770886"

[pkg.fuel-core-keygen]
version = "0.31.0+nightly.20240723.ab5a937fdf"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240723/fuel-core-0.31.0%2Bnightly.20240723.ab5a937fdf-aarch64-apple-darwin.tar.gz"
hash = "9e56f3c6c365fcb3840e20a671aa0a4bda1d623eed32366a717c17c91e00922a"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240723/fuel-core-0.31.0%2Bnightly.20240723.ab5a937fdf-aarch64-unknown-linux-gnu.tar.gz"
hash = "572ef039e0e18612430cfcb930500f64fd84f50a80123d9f56e09ee67718c9dc"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240723/fuel-core-0.31.0%2Bnightly.20240723.ab5a937fdf-x86_64-apple-darwin.tar.gz"
hash = "3f07c2bbcb412a34c5bfeb19024e8a975bf2ab9b5eb5bd89ca9b1ca9a64c728b"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240723/fuel-core-0.31.0%2Bnightly.20240723.ab5a937fdf-x86_64-unknown-linux-gnu.tar.gz"
hash = "12d6222ab5cfc634708527892d19929ad8c04c2d1debfd59fc3bfe8141770886"
