published_by = "https://github.com/FuelLabs/fuelup/actions/runs/14950974782"
date = "2025-05-11"

[pkg.forc]
version = "0.68.2+nightly.20250511.dffa29c599"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250511/forc-binaries-0.68.2%2Bnightly.20250511.dffa29c599-darwin_amd64.tar.gz"
hash = "5c16260864777da5e44c1d1bec571c14af90d913b529da393a151c2a7e5f9621"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250511/forc-binaries-0.68.2%2Bnightly.20250511.dffa29c599-darwin_arm64.tar.gz"
hash = "cb950c090d31c7c70f7bdecdf6235408303a3b1710222e4597d9969be258c023"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250511/forc-binaries-0.68.2%2Bnightly.20250511.dffa29c599-linux_amd64.tar.gz"
hash = "5fb7430bb4d20ea5171c333fa41bf8b306803d51e3fd6989e72b5c96291139cb"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250511/forc-binaries-0.68.2%2Bnightly.20250511.dffa29c599-linux_arm64.tar.gz"
hash = "8ae81111dd64c1b7490b3303fa07809d378ba69b2b995b5ce66fee0882c50cd7"

[pkg.forc-wallet]
version = "0.14.0+nightly.20250511.24883eb126"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250511/forc-wallet-0.14.0%2Bnightly.20250511.24883eb126-aarch64-apple-darwin.tar.gz"
hash = "6efb73d9b7a36ac694eceef6d71b8856338cc12f6dbbf6622450f7eb03b30418"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250511/forc-wallet-0.14.0%2Bnightly.20250511.24883eb126-aarch64-unknown-linux-gnu.tar.gz"
hash = "72c91220ebe81e59717c747ea3eced929ba6c2fb9bdc61c7102b35615c64dacf"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250511/forc-wallet-0.14.0%2Bnightly.20250511.24883eb126-x86_64-apple-darwin.tar.gz"
hash = "d3e64e88b35c45d95d0f54fa7394e7361ec7a91dc862fd669b5726b56844f018"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250511/forc-wallet-0.14.0%2Bnightly.20250511.24883eb126-x86_64-unknown-linux-gnu.tar.gz"
hash = "551d6d2afbcfaee54354662f689a346ff6ba55af98fd76d8d72126c8b3aaea7b"

[pkg.fuel-core]
version = "0.43.0+nightly.20250511.af4e7b7d25"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250511/fuel-core-0.43.0%2Bnightly.20250511.af4e7b7d25-aarch64-apple-darwin.tar.gz"
hash = "8c5da054d5d98a15db5df79654e5e8e5d24ba8708bc8bb1a3a30c4bc6b3ca12f"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250511/fuel-core-0.43.0%2Bnightly.20250511.af4e7b7d25-aarch64-unknown-linux-gnu.tar.gz"
hash = "e9e2904ffb8fbc0bdc602b9fa2aba39413d473f9b06d56ea1012cdba49ed1a57"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250511/fuel-core-0.43.0%2Bnightly.20250511.af4e7b7d25-x86_64-unknown-linux-gnu.tar.gz"
hash = "ae119f144e3c3c5e55fa04ee83219191d794c8e98e5acf1371e2626534346a16"

[pkg.fuel-core-keygen]
version = "0.43.0+nightly.20250511.af4e7b7d25"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250511/fuel-core-0.43.0%2Bnightly.20250511.af4e7b7d25-aarch64-apple-darwin.tar.gz"
hash = "8c5da054d5d98a15db5df79654e5e8e5d24ba8708bc8bb1a3a30c4bc6b3ca12f"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250511/fuel-core-0.43.0%2Bnightly.20250511.af4e7b7d25-aarch64-unknown-linux-gnu.tar.gz"
hash = "e9e2904ffb8fbc0bdc602b9fa2aba39413d473f9b06d56ea1012cdba49ed1a57"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250511/fuel-core-0.43.0%2Bnightly.20250511.af4e7b7d25-x86_64-unknown-linux-gnu.tar.gz"
hash = "ae119f144e3c3c5e55fa04ee83219191d794c8e98e5acf1371e2626534346a16"
