published_by = "https://github.com/FuelLabs/fuelup/actions/runs/19588102209"
date = "2025-11-22"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251122.74d8ce58f0"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251122/forc-wallet-0.15.2%2Bnightly.20251122.74d8ce58f0-aarch64-apple-darwin.tar.gz"
hash = "e0dbac1941612a945c8f58168265b7cf9c723860fe067e34b0d321fb6803b99a"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251122/forc-wallet-0.15.2%2Bnightly.20251122.74d8ce58f0-aarch64-unknown-linux-gnu.tar.gz"
hash = "334deffc467cba044db6b70a659b5da64293aae248c038d0bb14e4e341f9e5ee"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251122/forc-wallet-0.15.2%2Bnightly.20251122.74d8ce58f0-x86_64-apple-darwin.tar.gz"
hash = "9f64ff5a18040af1dc47e07c36030bc4e2cc53b219abad536e33548f1e724b46"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251122/forc-wallet-0.15.2%2Bnightly.20251122.74d8ce58f0-x86_64-unknown-linux-gnu.tar.gz"
hash = "5ef807c83eedebeb03298474552a1518d2442a61bc2c76d8cba0b5988fda1f6b"
