published_by = "https://github.com/FuelLabs/fuelup/actions/runs/16243963788"
date = "2025-07-13"

[pkg.forc]
version = "0.69.0+nightly.20250713.74092cbbcd"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250713/forc-binaries-0.69.0%2Bnightly.20250713.74092cbbcd-darwin_amd64.tar.gz"
hash = "5a8ac7a975c7e8002c0fa6f358e52bf32a18c467e65b9cab9856f3c1b1b3e425"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250713/forc-binaries-0.69.0%2Bnightly.20250713.74092cbbcd-darwin_arm64.tar.gz"
hash = "7326e9c237c85ef04727dd2f749bba2f584c80900f9a26d9dc77abe1202f4000"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250713/forc-binaries-0.69.0%2Bnightly.20250713.74092cbbcd-linux_amd64.tar.gz"
hash = "06b77def3ff9d15f59d060cc21264bc6f2a1236074e9cbcd6202f94f5d4b8dfa"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250713/forc-binaries-0.69.0%2Bnightly.20250713.74092cbbcd-linux_arm64.tar.gz"
hash = "b85c0a1faada7da6e3d9a94db74a63645f59c0aadb26482b013cd9557cb4cc19"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250713.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250713/forc-wallet-0.15.1%2Bnightly.20250713.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "aee16b535d39a661e3b8d586f42c45d37f530d22ceebfef15e9dd75ec4693178"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250713/forc-wallet-0.15.1%2Bnightly.20250713.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "d2386559724fb6a668abc943a967439fe7663159535c51204eecfca239613d07"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250713/forc-wallet-0.15.1%2Bnightly.20250713.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "d34d9251f0701d2e310e762593d2fb9a2257c11eb584af146a4b0039d06acd13"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250713/forc-wallet-0.15.1%2Bnightly.20250713.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "49b5768254e5289d9bc231931dab2e4c83b0209a0f5ccbaefc6538d4874b8a59"

[pkg.fuel-core]
version = "0.44.0+nightly.20250713.a08b48499c"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250713/fuel-core-0.44.0%2Bnightly.20250713.a08b48499c-aarch64-apple-darwin.tar.gz"
hash = "0ee4402f41f7757a56fe66e8525540c3c51fab2c8cb9958fc263a4428c14d51b"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250713/fuel-core-0.44.0%2Bnightly.20250713.a08b48499c-aarch64-unknown-linux-gnu.tar.gz"
hash = "ce512cf06777248641b7f444da520ad111f9db9df716f2c8f691260f476410a9"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250713/fuel-core-0.44.0%2Bnightly.20250713.a08b48499c-x86_64-unknown-linux-gnu.tar.gz"
hash = "fed4577539a64ba2961d4a3059a502b8157b3f6ba6284099734379c8b3fe69dd"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250713.a08b48499c"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250713/fuel-core-0.44.0%2Bnightly.20250713.a08b48499c-aarch64-apple-darwin.tar.gz"
hash = "0ee4402f41f7757a56fe66e8525540c3c51fab2c8cb9958fc263a4428c14d51b"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250713/fuel-core-0.44.0%2Bnightly.20250713.a08b48499c-aarch64-unknown-linux-gnu.tar.gz"
hash = "ce512cf06777248641b7f444da520ad111f9db9df716f2c8f691260f476410a9"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250713/fuel-core-0.44.0%2Bnightly.20250713.a08b48499c-x86_64-unknown-linux-gnu.tar.gz"
hash = "fed4577539a64ba2961d4a3059a502b8157b3f6ba6284099734379c8b3fe69dd"
