published_by = "https://github.com/FuelLabs/fuelup/actions/runs/12131701542"
date = "2024-12-03"

[pkg.forc]
version = "0.66.5+nightly.20241203.5423c56c0c"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241203/forc-binaries-0.66.5%2Bnightly.20241203.5423c56c0c-darwin_amd64.tar.gz"
hash = "20e20b9549cd791ebbdec3258037c868ef756469f4309adbc9e7cf3986f4bf18"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241203/forc-binaries-0.66.5%2Bnightly.20241203.5423c56c0c-darwin_arm64.tar.gz"
hash = "9ea9c069b56fc697099c8a29ad798438babcaec4fd45fc62a58d56e799c67e81"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241203/forc-binaries-0.66.5%2Bnightly.20241203.5423c56c0c-linux_amd64.tar.gz"
hash = "d374420f5984bd6d3dad154c999914453f4fc52ea023424e2429a0754ea969ee"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241203/forc-binaries-0.66.5%2Bnightly.20241203.5423c56c0c-linux_arm64.tar.gz"
hash = "f5e67318c1c43ec4542981bad97cbc7eabba66a7ff6d85fc346dc44256b4b081"

[pkg.forc-wallet]
version = "0.11.1+nightly.20241203.f4052012e0"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241203/forc-wallet-0.11.1%2Bnightly.20241203.f4052012e0-aarch64-apple-darwin.tar.gz"
hash = "fed274c18a8c150840f59ddc3deaeabde64723dd5adcb093ec5e2356c454f531"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241203/forc-wallet-0.11.1%2Bnightly.20241203.f4052012e0-aarch64-unknown-linux-gnu.tar.gz"
hash = "84d7c6ed657dc797ee10f7cbb61d5dede84cd2785a6ea52def996f9628159e4d"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241203/forc-wallet-0.11.1%2Bnightly.20241203.f4052012e0-x86_64-apple-darwin.tar.gz"
hash = "f9ef304312882b2292154c13a336236190a0c2613b81d6332e22ab8da671ced3"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241203/forc-wallet-0.11.1%2Bnightly.20241203.f4052012e0-x86_64-unknown-linux-gnu.tar.gz"
hash = "1a945603947bf9a85fcf064fa5b88335c6d82a0c1be1d00dac669c5a9118a840"

[pkg.fuel-core]
version = "0.40.0+nightly.20241203.791b79c9a4"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241203/fuel-core-0.40.0%2Bnightly.20241203.791b79c9a4-aarch64-apple-darwin.tar.gz"
hash = "5c51c61968f583b3869fbd198d865f31e149a5bce9785a548a34e3d7f519d4c3"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241203/fuel-core-0.40.0%2Bnightly.20241203.791b79c9a4-aarch64-unknown-linux-gnu.tar.gz"
hash = "2edb4176968dc22ce8a61b10cbab913d54e721de2c4cd03ba129fbc2f25cc748"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241203/fuel-core-0.40.0%2Bnightly.20241203.791b79c9a4-x86_64-apple-darwin.tar.gz"
hash = "efd479140a46b87c03f6b95f915b10e90a69750e026ac62b15caa2b4f1842941"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241203/fuel-core-0.40.0%2Bnightly.20241203.791b79c9a4-x86_64-unknown-linux-gnu.tar.gz"
hash = "1cfe44c00b25e145224b4fa004efb81f8d725dfde143031a6288cbdda019c61b"

[pkg.fuel-core-keygen]
version = "0.40.0+nightly.20241203.791b79c9a4"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241203/fuel-core-0.40.0%2Bnightly.20241203.791b79c9a4-aarch64-apple-darwin.tar.gz"
hash = "5c51c61968f583b3869fbd198d865f31e149a5bce9785a548a34e3d7f519d4c3"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241203/fuel-core-0.40.0%2Bnightly.20241203.791b79c9a4-aarch64-unknown-linux-gnu.tar.gz"
hash = "2edb4176968dc22ce8a61b10cbab913d54e721de2c4cd03ba129fbc2f25cc748"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241203/fuel-core-0.40.0%2Bnightly.20241203.791b79c9a4-x86_64-apple-darwin.tar.gz"
hash = "efd479140a46b87c03f6b95f915b10e90a69750e026ac62b15caa2b4f1842941"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241203/fuel-core-0.40.0%2Bnightly.20241203.791b79c9a4-x86_64-unknown-linux-gnu.tar.gz"
hash = "1cfe44c00b25e145224b4fa004efb81f8d725dfde143031a6288cbdda019c61b"
