published_by = "https://github.com/FuelLabs/fuelup/actions/runs/11189260353"
date = "2024-10-05"

[pkg.forc]
version = "0.64.0+nightly.20241005.d39958053d"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241005/forc-binaries-0.64.0%2Bnightly.20241005.d39958053d-darwin_amd64.tar.gz"
hash = "80a347437c3c26110880343bd8d0bf4310929a35ecad66eeaa1bd408e4b53d68"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241005/forc-binaries-0.64.0%2Bnightly.20241005.d39958053d-darwin_arm64.tar.gz"
hash = "e1fb52a2be08046bcb3df271c8bb53ba8e0a33745188f8dc81d870f6dcae31b4"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241005/forc-binaries-0.64.0%2Bnightly.20241005.d39958053d-linux_amd64.tar.gz"
hash = "7f5ba550573c5dfdd693170115e64eb7b006435da8a5b5aac1369e07f88832c0"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241005/forc-binaries-0.64.0%2Bnightly.20241005.d39958053d-linux_arm64.tar.gz"
hash = "325d2101099f720ffad1d46445249e0eb40b537fcacd5a2f326cb2dedd36a785"

[pkg.forc-wallet]
version = "0.9.1+nightly.20241005.c49415c671"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241005/forc-wallet-0.9.1%2Bnightly.20241005.c49415c671-aarch64-apple-darwin.tar.gz"
hash = "6416aa61f1146b103c5c52f94471437c649ad2258fe7b315a54ce3e7b53c420d"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241005/forc-wallet-0.9.1%2Bnightly.20241005.c49415c671-aarch64-unknown-linux-gnu.tar.gz"
hash = "7835e87b06c9ef625caf4ee9435c63ad2f564a6623854a5c328bb8299d969dac"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241005/forc-wallet-0.9.1%2Bnightly.20241005.c49415c671-x86_64-apple-darwin.tar.gz"
hash = "32b10178f4d968bb4921a6c535b8b7d43bc022a8ad550b5a84ce11820299507d"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241005/forc-wallet-0.9.1%2Bnightly.20241005.c49415c671-x86_64-unknown-linux-gnu.tar.gz"
hash = "73b0f4e9308d5260d4a9382924171d666ff89dee5bd3485b5f64170ccb7fcc57"

[pkg.fuel-core]
version = "0.35.0+nightly.20241005.b5d5ff8d13"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241005/fuel-core-0.35.0%2Bnightly.20241005.b5d5ff8d13-aarch64-apple-darwin.tar.gz"
hash = "9a8c519f39b7c9e6bfe70465e1605b482aad54d6ba0cf9c4649caa464b1b103f"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241005/fuel-core-0.35.0%2Bnightly.20241005.b5d5ff8d13-aarch64-unknown-linux-gnu.tar.gz"
hash = "a8681e7d0bf684207a7d2bd0ffae4feb128998275afd6cf1482307a8e40eec3e"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241005/fuel-core-0.35.0%2Bnightly.20241005.b5d5ff8d13-x86_64-unknown-linux-gnu.tar.gz"
hash = "d5cfd657cec5778be52a434293b9421459a7270f65e4f66750fb2103cdaaaf76"

[pkg.fuel-core-keygen]
version = "0.35.0+nightly.20241005.b5d5ff8d13"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241005/fuel-core-0.35.0%2Bnightly.20241005.b5d5ff8d13-aarch64-apple-darwin.tar.gz"
hash = "9a8c519f39b7c9e6bfe70465e1605b482aad54d6ba0cf9c4649caa464b1b103f"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241005/fuel-core-0.35.0%2Bnightly.20241005.b5d5ff8d13-aarch64-unknown-linux-gnu.tar.gz"
hash = "a8681e7d0bf684207a7d2bd0ffae4feb128998275afd6cf1482307a8e40eec3e"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241005/fuel-core-0.35.0%2Bnightly.20241005.b5d5ff8d13-x86_64-unknown-linux-gnu.tar.gz"
hash = "d5cfd657cec5778be52a434293b9421459a7270f65e4f66750fb2103cdaaaf76"
