published_by = "https://github.com/FuelLabs/fuelup/actions/runs/13126398783"
date = "2025-02-04"

[pkg.forc-wallet]
version = "0.12.0+nightly.20250204.8d59dbc462"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250204/forc-wallet-0.12.0%2Bnightly.20250204.8d59dbc462-x86_64-unknown-linux-gnu.tar.gz"
hash = "35e101e5ef85ba7f6f986d33dd8086c2ee6522b4ebf95daa9a9a84e93fedd638"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250204/forc-wallet-0.12.0%2Bnightly.20250204.8d59dbc462-aarch64-unknown-linux-gnu.tar.gz"
hash = "c5dec8e7e12fa4ada18d9ab85ebfd7ef0a6b8da01b75ff64e9384d354c756431"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250204/forc-wallet-0.12.0%2Bnightly.20250204.8d59dbc462-x86_64-apple-darwin.tar.gz"
hash = "168b081055ea7479297222bf8886cd34f122043dda7be46de9cf55009a5c321e"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250204/forc-wallet-0.12.0%2Bnightly.20250204.8d59dbc462-aarch64-apple-darwin.tar.gz"
hash = "5966793d82615ecb59c77d82bc9d63afd8ae35ac5c05fd30a4b2c899d4782790"

[pkg.forc]
version = "0.66.6+nightly.20250204.9df66cea21"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250204/forc-binaries-0.66.6%2Bnightly.20250204.9df66cea21-linux_amd64.tar.gz"
hash = "941de31b51f6e676cc568b814832bf3feb532f9cb8e52c9a2e995af3c38677b5"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250204/forc-binaries-0.66.6%2Bnightly.20250204.9df66cea21-darwin_arm64.tar.gz"
hash = "3850b7cf292e8ea4fc80e1a9f706ebe0bed7e6e7d23c2f0ca1beaca3f7811131"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250204/forc-binaries-0.66.6%2Bnightly.20250204.9df66cea21-linux_arm64.tar.gz"
hash = "ceefda675036979889e8ed74c8244a1deea558bc4f8b3eb6e832a6dc142f5013"

[pkg.fuel-core]
version = "0.41.5+nightly.20250204.ea46e9fd08"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250204/fuel-core-0.41.5%2Bnightly.20250204.ea46e9fd08-aarch64-unknown-linux-gnu.tar.gz"
hash = "9ccb04e3b1706645d66393b1fff05feed80ed6b9c06fe1b2a3e93061edae9ec7"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250204/fuel-core-0.41.5%2Bnightly.20250204.ea46e9fd08-aarch64-apple-darwin.tar.gz"
hash = "1638634c4a81a79dc2f99192705c6ff76e13328d7bdab0e9000fc7d87d2e7414"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250204/fuel-core-0.41.5%2Bnightly.20250204.ea46e9fd08-x86_64-apple-darwin.tar.gz"
hash = "2b7b14b478baa793bac21edd2ebfa307141a01c67c995c72c7b08f7b91b36b53"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250204/fuel-core-0.41.5%2Bnightly.20250204.ea46e9fd08-x86_64-unknown-linux-gnu.tar.gz"
hash = "c5b3940a1b9621a113618514c0ad7542a9b910067f263acf92e0ecd89f258b83"

[pkg.fuel-core-keygen]
version = "0.41.5+nightly.20250204.ea46e9fd08"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250204/fuel-core-0.41.5%2Bnightly.20250204.ea46e9fd08-aarch64-unknown-linux-gnu.tar.gz"
hash = "9ccb04e3b1706645d66393b1fff05feed80ed6b9c06fe1b2a3e93061edae9ec7"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250204/fuel-core-0.41.5%2Bnightly.20250204.ea46e9fd08-aarch64-apple-darwin.tar.gz"
hash = "1638634c4a81a79dc2f99192705c6ff76e13328d7bdab0e9000fc7d87d2e7414"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250204/fuel-core-0.41.5%2Bnightly.20250204.ea46e9fd08-x86_64-apple-darwin.tar.gz"
hash = "2b7b14b478baa793bac21edd2ebfa307141a01c67c995c72c7b08f7b91b36b53"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250204/fuel-core-0.41.5%2Bnightly.20250204.ea46e9fd08-x86_64-unknown-linux-gnu.tar.gz"
hash = "c5b3940a1b9621a113618514c0ad7542a9b910067f263acf92e0ecd89f258b83"
