published_by = "https://github.com/FuelLabs/fuelup/actions/runs/21103913981"
date = "2026-01-18"

[pkg.forc]
version = "0.70.1+nightly.20260118.20b32cfb44"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/forc-binaries-0.70.1%2Bnightly.20260118.20b32cfb44-darwin_amd64.tar.gz"
hash = "5d8045be4726a7bc6b0055fbb9e6ff556c572227b5caf6b60b322a1d96182dce"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/forc-binaries-0.70.1%2Bnightly.20260118.20b32cfb44-darwin_arm64.tar.gz"
hash = "963707ba1539beddecb67434cb370ba5f0c4e13a531c8f713bf1aad2b45740dd"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/forc-binaries-0.70.1%2Bnightly.20260118.20b32cfb44-linux_amd64.tar.gz"
hash = "a8763d0f5603abeff549f1a73a3440befbfd78828c2a9a9ba8a3001bee2992d1"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/forc-binaries-0.70.1%2Bnightly.20260118.20b32cfb44-linux_arm64.tar.gz"
hash = "81cf98947c7a2c74599fad354d01391b6f7cc6fd3b1f015ccceb0232e9ba269e"

[pkg.forc-crypto]
version = "0.71.0+nightly.20260118.54cf9da7d3"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/forc-crypto-0.71.0%2Bnightly.20260118.54cf9da7d3-darwin_amd64.tar.gz"
hash = "308fbc845a6155f5ff879de4fe7ceb0cb98dfb96943e42fa1069c2fa724ed224"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/forc-crypto-0.71.0%2Bnightly.20260118.54cf9da7d3-darwin_arm64.tar.gz"
hash = "9e3011a0e728b0b11d9a637715b73bd37c59006bf72c05d033373a76a9ffdb08"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/forc-crypto-0.71.0%2Bnightly.20260118.54cf9da7d3-linux_amd64.tar.gz"
hash = "1a0fadcf8d5674125d3b95e08a7f8c787b85fdf264b1c60b396df3dac1bbded5"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/forc-crypto-0.71.0%2Bnightly.20260118.54cf9da7d3-linux_arm64.tar.gz"
hash = "83e570c0b08525cf2d8bc863c5d397e885194cdfcf4001ae01f3102501b85a1c"

[pkg.forc-node]
version = "0.71.2+nightly.20260118.54cf9da7d3"

[pkg.forc-node.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/forc-node-0.71.2%2Bnightly.20260118.54cf9da7d3-darwin_amd64.tar.gz"
hash = "dac91b4f26bedf6a3e4c7d112c430ad2ef2383772f78bc521c702d75f92031dd"

[pkg.forc-node.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/forc-node-0.71.2%2Bnightly.20260118.54cf9da7d3-darwin_arm64.tar.gz"
hash = "eebf74c9dfbdb712081e2046391c437116582bf8c9137834fc4608e106ff3739"

[pkg.forc-node.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/forc-node-0.71.2%2Bnightly.20260118.54cf9da7d3-linux_amd64.tar.gz"
hash = "e795913a5ac117e9ec20f4e6dd66f08674f4200ed9e890631466a0abdb798e5a"

[pkg.forc-node.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/forc-node-0.71.2%2Bnightly.20260118.54cf9da7d3-linux_arm64.tar.gz"
hash = "9e317d203c98dda7646bd8f52c80f6286a66b31874f392b4266247ee35ca6760"

[pkg.forc-wallet]
version = "0.16.2+nightly.20260118.54cf9da7d3"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/forc-wallet-0.16.2%2Bnightly.20260118.54cf9da7d3-darwin_amd64.tar.gz"
hash = "d709421ae75167b48d772ab9f7c974082e9f12ac6a5a751ed90ae8c71bb5ae0b"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/forc-wallet-0.16.2%2Bnightly.20260118.54cf9da7d3-darwin_arm64.tar.gz"
hash = "b00b8960bba2b30aed39654eebc24485174b6fe8fcee477efb4394614fd91f52"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/forc-wallet-0.16.2%2Bnightly.20260118.54cf9da7d3-linux_amd64.tar.gz"
hash = "9a7900ac9c17e685d48820e2abf82e263494dc69a74afd7033fd479e37672c68"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/forc-wallet-0.16.2%2Bnightly.20260118.54cf9da7d3-linux_arm64.tar.gz"
hash = "30c049c1ff63d967b900c5b08a5fef3b5cb97c181769de3fad804e36808a85e2"

[pkg.fuel-core]
version = "0.47.1+nightly.20260118.6889ed156b"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/fuel-core-0.47.1%2Bnightly.20260118.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "28b6fda472a8a0bd40f75170e1dc78665355f9824484a6ae9a78b08063dda9ea"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/fuel-core-0.47.1%2Bnightly.20260118.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "3feefd7c4adcfa71ddaac400956b490e9b854c63c3cd602be686eba686dcee88"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/fuel-core-0.47.1%2Bnightly.20260118.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "1d9d67cfbcd2864ee154573199c84e9395e3b11493ba774063ffcf7d92fdc09d"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/fuel-core-0.47.1%2Bnightly.20260118.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "aa9a417c9475f8ce6a8a7b6450f28b8b7c6361914cf958a064af78b30f3b4d15"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20260118.6889ed156b"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/fuel-core-0.47.1%2Bnightly.20260118.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "28b6fda472a8a0bd40f75170e1dc78665355f9824484a6ae9a78b08063dda9ea"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/fuel-core-0.47.1%2Bnightly.20260118.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "3feefd7c4adcfa71ddaac400956b490e9b854c63c3cd602be686eba686dcee88"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/fuel-core-0.47.1%2Bnightly.20260118.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "1d9d67cfbcd2864ee154573199c84e9395e3b11493ba774063ffcf7d92fdc09d"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260118/fuel-core-0.47.1%2Bnightly.20260118.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "aa9a417c9475f8ce6a8a7b6450f28b8b7c6361914cf958a064af78b30f3b4d15"
