published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15524754536"
date = "2025-06-09"

[pkg.forc]
version = "0.68.7+nightly.20250609.fe8a3ef37a"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250609/forc-binaries-0.68.7%2Bnightly.20250609.fe8a3ef37a-darwin_amd64.tar.gz"
hash = "33164d1d3fea55de4ec8d982b5b1fe37d9dfd9605346d88419a007ad1214be20"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250609/forc-binaries-0.68.7%2Bnightly.20250609.fe8a3ef37a-darwin_arm64.tar.gz"
hash = "2c5820c7bf5987104928a7a6bbffe022e36a970c8b86a084143aafdc09a7d098"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250609/forc-binaries-0.68.7%2Bnightly.20250609.fe8a3ef37a-linux_amd64.tar.gz"
hash = "d13f75413268e22981ddc88bcd09c320ce83925a1d90cdf1ba6a2575b12490c7"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250609/forc-binaries-0.68.7%2Bnightly.20250609.fe8a3ef37a-linux_arm64.tar.gz"
hash = "1adae54a8bb51a647701b43b5938b06c4d639067b46c6d9eab6222154611f4a4"

[pkg.forc-wallet]
version = "0.14.0+nightly.20250609.24883eb126"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250609/forc-wallet-0.14.0%2Bnightly.20250609.24883eb126-aarch64-apple-darwin.tar.gz"
hash = "0c64b5ec768a6bef3f8a7fba5fe2d2c1c09931bf4ad31dc5c73a9a56200cf8e9"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250609/forc-wallet-0.14.0%2Bnightly.20250609.24883eb126-aarch64-unknown-linux-gnu.tar.gz"
hash = "5a4077ff61965989684dde12b2480c7db0fe1cb444aee0b1fc3624cb2caf27be"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250609/forc-wallet-0.14.0%2Bnightly.20250609.24883eb126-x86_64-apple-darwin.tar.gz"
hash = "ed278be81643f4eb6c212c38a5bbdaac35cb64e66a80ed6cf0b76f2c7ff2515b"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250609/forc-wallet-0.14.0%2Bnightly.20250609.24883eb126-x86_64-unknown-linux-gnu.tar.gz"
hash = "8b144ecff6745bd0290436de822aa4ce50d5f4d61fc687368591c3f880e77938"

[pkg.fuel-core]
version = "0.44.0+nightly.20250609.49d0309dd1"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250609/fuel-core-0.44.0%2Bnightly.20250609.49d0309dd1-aarch64-apple-darwin.tar.gz"
hash = "9ab7e2078a9582c620dbcdc7be1c9fc2e472982ee23f4edc950b3afdd3f6f5af"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250609/fuel-core-0.44.0%2Bnightly.20250609.49d0309dd1-aarch64-unknown-linux-gnu.tar.gz"
hash = "71c7e0bc96d2f9d06a0ecb9fa494ea9ca3d41eeb95c3957c5bc5ad23d1b8b2e9"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250609.49d0309dd1"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250609/fuel-core-0.44.0%2Bnightly.20250609.49d0309dd1-aarch64-apple-darwin.tar.gz"
hash = "9ab7e2078a9582c620dbcdc7be1c9fc2e472982ee23f4edc950b3afdd3f6f5af"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250609/fuel-core-0.44.0%2Bnightly.20250609.49d0309dd1-aarch64-unknown-linux-gnu.tar.gz"
hash = "71c7e0bc96d2f9d06a0ecb9fa494ea9ca3d41eeb95c3957c5bc5ad23d1b8b2e9"
