published_by = "https://github.com/FuelLabs/fuelup/actions/runs/16980656503"
date = "2025-08-15"

[pkg.forc]
version = "0.69.1+nightly.20250815.fe9bbe39b9"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250815/forc-binaries-0.69.1%2Bnightly.20250815.fe9bbe39b9-darwin_amd64.tar.gz"
hash = "fb46fe8d458a46a16e9c8c533f0e5399b37b7c7cc012b89b678d1177a0998baf"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250815/forc-binaries-0.69.1%2Bnightly.20250815.fe9bbe39b9-darwin_arm64.tar.gz"
hash = "6b385c383cc2ef7115225bb61f585a8045f56dfaf8e933d44c3f193c0f8372d9"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250815/forc-binaries-0.69.1%2Bnightly.20250815.fe9bbe39b9-linux_amd64.tar.gz"
hash = "78bc8a1d3e7b9455d8fa1b69dfe4f0481e433844077febb41fd8eddff7c2fd3f"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250815/forc-binaries-0.69.1%2Bnightly.20250815.fe9bbe39b9-linux_arm64.tar.gz"
hash = "81e7f48d6021774687daf701adcacd917eeec05b9dd388d676bdc218aac43afb"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250815.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250815/forc-wallet-0.15.1%2Bnightly.20250815.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "0dd6b57adbb05e990c8731698f00c86832737c78b60c4c32b34de4e3847a4af3"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250815/forc-wallet-0.15.1%2Bnightly.20250815.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "018cc857bbd32ec05184567dbb01b18b8f199c3fa81584c774d3157e9fc441fe"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250815/forc-wallet-0.15.1%2Bnightly.20250815.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "b1b694a295d7f700da554a75b6c1e6bce245234a595d474299dae39acb9b2e34"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250815/forc-wallet-0.15.1%2Bnightly.20250815.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "c8387014ae51b3271f029f7ef0926b2c20eef8f1198b205002e60594dc6d67c1"

[pkg.fuel-core]
version = "0.46.0+nightly.20250815.33238c6e10"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250815/fuel-core-0.46.0%2Bnightly.20250815.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "c20890e11ecd59958a29f5b0fbb1659053f14ad0df705c5cc5e2bc8dfbc56517"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250815/fuel-core-0.46.0%2Bnightly.20250815.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "39f472971d43e56fb7213e02638399b51d36d9a876d6125eb0e0b45da6997731"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250815/fuel-core-0.46.0%2Bnightly.20250815.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "292ee4a8f593f46f0b490217ed2a2d892801d83834e14d18b9e7dc3d4ebfc6ae"

[pkg.fuel-core-keygen]
version = "0.46.0+nightly.20250815.33238c6e10"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250815/fuel-core-0.46.0%2Bnightly.20250815.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "c20890e11ecd59958a29f5b0fbb1659053f14ad0df705c5cc5e2bc8dfbc56517"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250815/fuel-core-0.46.0%2Bnightly.20250815.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "39f472971d43e56fb7213e02638399b51d36d9a876d6125eb0e0b45da6997731"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250815/fuel-core-0.46.0%2Bnightly.20250815.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "292ee4a8f593f46f0b490217ed2a2d892801d83834e14d18b9e7dc3d4ebfc6ae"
