published_by = "https://github.com/FuelLabs/fuelup/actions/runs/10764889321"
date = "2024-09-09"

[pkg.forc]
version = "0.63.5+nightly.20240909.31a1d6f983"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240909/forc-binaries-0.63.5%2Bnightly.20240909.31a1d6f983-darwin_amd64.tar.gz"
hash = "6b57bfd1d71aac78dd22ec5f73e43d03670ee460e50ac3366b8772862e9cba48"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240909/forc-binaries-0.63.5%2Bnightly.20240909.31a1d6f983-darwin_arm64.tar.gz"
hash = "eeb346b4cc76577b8942089de5bf6afedbc3d81d8595f26b870c515d07ddd4f0"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240909/forc-binaries-0.63.5%2Bnightly.20240909.31a1d6f983-linux_amd64.tar.gz"
hash = "0f41e164211eee593f8db8195737c619730f65b7e2bd5b210a7089eb976c67a4"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240909/forc-binaries-0.63.5%2Bnightly.20240909.31a1d6f983-linux_arm64.tar.gz"
hash = "512a1ea5f583b796295ebd26be783287872ab90e77a6bf01e3634a6fa8c57f4c"

[pkg.forc-wallet]
version = "0.9.0+nightly.20240909.29d9b25c2c"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240909/forc-wallet-0.9.0%2Bnightly.20240909.29d9b25c2c-aarch64-apple-darwin.tar.gz"
hash = "9df72209da6fdcbc8c725939d2078480e2e859356eff4246d41d007af96dc1d3"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240909/forc-wallet-0.9.0%2Bnightly.20240909.29d9b25c2c-aarch64-unknown-linux-gnu.tar.gz"
hash = "eb4d1d6342ee5076a91dbafe823b1d44ee7b7d365c1713fcd7db2efa2ee3399b"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240909/forc-wallet-0.9.0%2Bnightly.20240909.29d9b25c2c-x86_64-apple-darwin.tar.gz"
hash = "46472574f539babf2e49531493511ef1b2ee6e15f87305210f16971c5adfaa04"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240909/forc-wallet-0.9.0%2Bnightly.20240909.29d9b25c2c-x86_64-unknown-linux-gnu.tar.gz"
hash = "274a722eee236e0b4431ea56ef58186da87b222def579e7ce995bd160fb178f7"

[pkg.fuel-core]
version = "0.35.0+nightly.20240909.a952ff44e0"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240909/fuel-core-0.35.0%2Bnightly.20240909.a952ff44e0-aarch64-apple-darwin.tar.gz"
hash = "1d64a4d476ba81f80517a7f03bd8a3e3e45ca0bebb1e78df95d3ccc5841518b1"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240909/fuel-core-0.35.0%2Bnightly.20240909.a952ff44e0-aarch64-unknown-linux-gnu.tar.gz"
hash = "f464e952d7515e6bdebfac8f5cba77ba0e1cad22458a83a09b296ef2b7dfc00d"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240909/fuel-core-0.35.0%2Bnightly.20240909.a952ff44e0-x86_64-unknown-linux-gnu.tar.gz"
hash = "8d182944c2f4c712f775912456b4851aa032d4782d9c6222656dd904b0027614"

[pkg.fuel-core-keygen]
version = "0.35.0+nightly.20240909.a952ff44e0"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240909/fuel-core-0.35.0%2Bnightly.20240909.a952ff44e0-aarch64-apple-darwin.tar.gz"
hash = "1d64a4d476ba81f80517a7f03bd8a3e3e45ca0bebb1e78df95d3ccc5841518b1"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240909/fuel-core-0.35.0%2Bnightly.20240909.a952ff44e0-aarch64-unknown-linux-gnu.tar.gz"
hash = "f464e952d7515e6bdebfac8f5cba77ba0e1cad22458a83a09b296ef2b7dfc00d"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240909/fuel-core-0.35.0%2Bnightly.20240909.a952ff44e0-x86_64-unknown-linux-gnu.tar.gz"
hash = "8d182944c2f4c712f775912456b4851aa032d4782d9c6222656dd904b0027614"
