published_by = "https://github.com/FuelLabs/fuelup/actions/runs/17689789970"
date = "2025-09-13"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250913.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250913/forc-wallet-0.15.1%2Bnightly.20250913.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "9f4e2696d339e733a5475923ff34b2ebe92cf754050ec948ff66f8a3e5b6c9a2"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250913/forc-wallet-0.15.1%2Bnightly.20250913.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "9a87e356befe7a567bf0824e72a403e388ceb5c0567470e88f02fa6fa96d5b6d"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250913/forc-wallet-0.15.1%2Bnightly.20250913.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "c5d6acba7b9da0a96483131a412c892e521b0f3d15ba14f00d11d77ced45b298"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250913/forc-wallet-0.15.1%2Bnightly.20250913.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "04df5bed274dd1dcf04cf0246562f4e251b2e4cdf957fd6f644281e4ecac1cfa"
