published_by = "https://github.com/FuelLabs/fuelup/actions/runs/12800229156"
date = "2025-01-16"

[pkg.forc]
version = "0.66.5+nightly.20250116.37235f2e7d"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250116/forc-binaries-0.66.5%2Bnightly.20250116.37235f2e7d-darwin_amd64.tar.gz"
hash = "9ca70c6a41487026b39b5fcaa7e9515747b5450ef696dd9b598999e8d6d30836"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250116/forc-binaries-0.66.5%2Bnightly.20250116.37235f2e7d-darwin_arm64.tar.gz"
hash = "7314c11a2adc0246f6e7719d843dfd8838641d9990166a9a543216f3a2193eb8"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250116/forc-binaries-0.66.5%2Bnightly.20250116.37235f2e7d-linux_amd64.tar.gz"
hash = "1633d335ed81441779db6c2a4dd223ef93cb9228565e12e878abeb580b24fe39"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250116/forc-binaries-0.66.5%2Bnightly.20250116.37235f2e7d-linux_arm64.tar.gz"
hash = "0acf7d83d89229268174585e4ca606a17a9226d271b0c481a65ddb707bdc477c"

[pkg.forc-wallet]
version = "0.11.1+nightly.20250116.f6f0ff07c8"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250116/forc-wallet-0.11.1%2Bnightly.20250116.f6f0ff07c8-aarch64-apple-darwin.tar.gz"
hash = "1a2926542d6c2a2dbf21cdacf2c1fe5b2215ae3a775dcdef63a02e57cbf12cf8"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250116/forc-wallet-0.11.1%2Bnightly.20250116.f6f0ff07c8-aarch64-unknown-linux-gnu.tar.gz"
hash = "00ca0fdf340d0c29469b838840ea3185ba088654931bebe7c3c5916d93649bb9"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250116/forc-wallet-0.11.1%2Bnightly.20250116.f6f0ff07c8-x86_64-apple-darwin.tar.gz"
hash = "f787a4bdef94831dda5279cd4df6b45d82ff2c990ab60946f82c0bc13bfc65e6"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250116/forc-wallet-0.11.1%2Bnightly.20250116.f6f0ff07c8-x86_64-unknown-linux-gnu.tar.gz"
hash = "f67dff84719faddccf58d41f8556df972128c751a4854ea8056502664cbc862d"

[pkg.fuel-core]
version = "0.41.0+nightly.20250116.dfc7fd7c0d"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250116/fuel-core-0.41.0%2Bnightly.20250116.dfc7fd7c0d-aarch64-apple-darwin.tar.gz"
hash = "522d722e2979abd1dfd42eb350d8b2760cdf36f39096c7d734ea50e30c90935a"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250116/fuel-core-0.41.0%2Bnightly.20250116.dfc7fd7c0d-aarch64-unknown-linux-gnu.tar.gz"
hash = "170bba175adb0577bb5bfcb0d23f5029ea8c9cb361050c155ce318676183f64f"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250116/fuel-core-0.41.0%2Bnightly.20250116.dfc7fd7c0d-x86_64-apple-darwin.tar.gz"
hash = "223990d5f37eaed323d15b0fbb51491fdac1049d2777fdee741449169b568ef4"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250116/fuel-core-0.41.0%2Bnightly.20250116.dfc7fd7c0d-x86_64-unknown-linux-gnu.tar.gz"
hash = "82496a539ef6da3940cc26580fb699818fc0e5af5e6baa40823976ae3c2e4e6d"

[pkg.fuel-core-keygen]
version = "0.41.0+nightly.20250116.dfc7fd7c0d"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250116/fuel-core-0.41.0%2Bnightly.20250116.dfc7fd7c0d-aarch64-apple-darwin.tar.gz"
hash = "522d722e2979abd1dfd42eb350d8b2760cdf36f39096c7d734ea50e30c90935a"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250116/fuel-core-0.41.0%2Bnightly.20250116.dfc7fd7c0d-aarch64-unknown-linux-gnu.tar.gz"
hash = "170bba175adb0577bb5bfcb0d23f5029ea8c9cb361050c155ce318676183f64f"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250116/fuel-core-0.41.0%2Bnightly.20250116.dfc7fd7c0d-x86_64-apple-darwin.tar.gz"
hash = "223990d5f37eaed323d15b0fbb51491fdac1049d2777fdee741449169b568ef4"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250116/fuel-core-0.41.0%2Bnightly.20250116.dfc7fd7c0d-x86_64-unknown-linux-gnu.tar.gz"
hash = "82496a539ef6da3940cc26580fb699818fc0e5af5e6baa40823976ae3c2e4e6d"
