published_by = "https://github.com/FuelLabs/fuelup/actions/runs/12171986852"
date = "2024-12-05"

[pkg.forc]
version = "0.66.5+nightly.20241205.0ccf47bbf9"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241205/forc-binaries-0.66.5%2Bnightly.20241205.0ccf47bbf9-darwin_amd64.tar.gz"
hash = "d8dad6aa358b5e4276fa328ca6e5528d872b472fd1351e041f05a0cdded382f9"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241205/forc-binaries-0.66.5%2Bnightly.20241205.0ccf47bbf9-darwin_arm64.tar.gz"
hash = "a696f95df0dfc20f25b885c120b53ef2c8b43547d1a6f033c684acbdd9428d55"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241205/forc-binaries-0.66.5%2Bnightly.20241205.0ccf47bbf9-linux_amd64.tar.gz"
hash = "7f157438242253c6e69352f2d4155665cce1ee18635aed839529b2f609828f0d"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241205/forc-binaries-0.66.5%2Bnightly.20241205.0ccf47bbf9-linux_arm64.tar.gz"
hash = "38505b5a17c587f220c078cb6c9b63249a90e53c4549a84c744387492699097b"

[pkg.forc-wallet]
version = "0.11.1+nightly.20241205.f4052012e0"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241205/forc-wallet-0.11.1%2Bnightly.20241205.f4052012e0-aarch64-apple-darwin.tar.gz"
hash = "adca33680ac5f1d9383d9e8defdaac54907801c9213710eb5d5a52037bc3815d"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241205/forc-wallet-0.11.1%2Bnightly.20241205.f4052012e0-aarch64-unknown-linux-gnu.tar.gz"
hash = "dbbe136f33359677d115660b6a96d7c1c4e49ce66eaf721957aa82f3ce22f8fa"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241205/forc-wallet-0.11.1%2Bnightly.20241205.f4052012e0-x86_64-apple-darwin.tar.gz"
hash = "daa015b7f32f86c5b005a0334f25cea0a7f2ecb892ddfea33478569e7c182d9f"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241205/forc-wallet-0.11.1%2Bnightly.20241205.f4052012e0-x86_64-unknown-linux-gnu.tar.gz"
hash = "a9a3feb2ba2fe794b2db2ef175de207bc1be74356a16d6ec711de1dd0c38bd1b"

[pkg.fuel-core]
version = "0.40.0+nightly.20241205.791b79c9a4"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241205/fuel-core-0.40.0%2Bnightly.20241205.791b79c9a4-aarch64-apple-darwin.tar.gz"
hash = "12f54aab71a64e840f6178b2e44ca16e227133c22a3f8c76d14ed921af7d6f4d"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241205/fuel-core-0.40.0%2Bnightly.20241205.791b79c9a4-aarch64-unknown-linux-gnu.tar.gz"
hash = "059b3c8bc4102a91bb5a33add20d06c6339f2708719cddccb4e335d503c82cbc"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241205/fuel-core-0.40.0%2Bnightly.20241205.791b79c9a4-x86_64-apple-darwin.tar.gz"
hash = "568b1cfd5e59c4172c27bf9240a7fffc2f8c9bd86ec085870c565a67a0570fa0"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241205/fuel-core-0.40.0%2Bnightly.20241205.791b79c9a4-x86_64-unknown-linux-gnu.tar.gz"
hash = "2a5e1f3a78e2632df107bb87f03cd974304ce22f5157765bf995f22cfe47766c"

[pkg.fuel-core-keygen]
version = "0.40.0+nightly.20241205.791b79c9a4"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241205/fuel-core-0.40.0%2Bnightly.20241205.791b79c9a4-aarch64-apple-darwin.tar.gz"
hash = "12f54aab71a64e840f6178b2e44ca16e227133c22a3f8c76d14ed921af7d6f4d"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241205/fuel-core-0.40.0%2Bnightly.20241205.791b79c9a4-aarch64-unknown-linux-gnu.tar.gz"
hash = "059b3c8bc4102a91bb5a33add20d06c6339f2708719cddccb4e335d503c82cbc"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241205/fuel-core-0.40.0%2Bnightly.20241205.791b79c9a4-x86_64-apple-darwin.tar.gz"
hash = "568b1cfd5e59c4172c27bf9240a7fffc2f8c9bd86ec085870c565a67a0570fa0"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241205/fuel-core-0.40.0%2Bnightly.20241205.791b79c9a4-x86_64-unknown-linux-gnu.tar.gz"
hash = "2a5e1f3a78e2632df107bb87f03cd974304ce22f5157765bf995f22cfe47766c"
