published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15721704153"
date = "2025-06-18"

[pkg.forc]
version = "0.68.7+nightly.20250618.cd89f62ece"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250618/forc-binaries-0.68.7%2Bnightly.20250618.cd89f62ece-darwin_amd64.tar.gz"
hash = "947f79319c61cc8eb8bb7c613b8566cb24d0e916270b1deee6f50c3ba626f53e"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250618/forc-binaries-0.68.7%2Bnightly.20250618.cd89f62ece-darwin_arm64.tar.gz"
hash = "3e7a6260b7cccdbf3d892e8125a47fc4ed2e61ac2e784c0fe77742e7508e707d"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250618/forc-binaries-0.68.7%2Bnightly.20250618.cd89f62ece-linux_amd64.tar.gz"
hash = "91d49e52b3346310ecbbc9fd528089ac2de912a6ec002b2acac246f7ad17d519"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250618/forc-binaries-0.68.7%2Bnightly.20250618.cd89f62ece-linux_arm64.tar.gz"
hash = "98f4312232bcba89360b84fc7025ece1e218b15ea276da0aed15a75c3542a560"

[pkg.forc-wallet]
version = "0.15.0+nightly.20250618.bddda681d3"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250618/forc-wallet-0.15.0%2Bnightly.20250618.bddda681d3-aarch64-apple-darwin.tar.gz"
hash = "187c21e9550fe801168774225352c524e88a3016296117973b0e98a4775c7169"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250618/forc-wallet-0.15.0%2Bnightly.20250618.bddda681d3-aarch64-unknown-linux-gnu.tar.gz"
hash = "bf7159bd8e52d881b32b6f7bad1a834a53780cf2b8b45d5b76b826b45f55c138"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250618/forc-wallet-0.15.0%2Bnightly.20250618.bddda681d3-x86_64-apple-darwin.tar.gz"
hash = "a419373a318b4cd66b9d12d5dd9a7aea3a208157b97530325f1de81d2921ef06"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250618/forc-wallet-0.15.0%2Bnightly.20250618.bddda681d3-x86_64-unknown-linux-gnu.tar.gz"
hash = "cafc0810ab20de40ba2db964e9480d5e7206e1e66697d4b824e2f871cabc9317"

[pkg.fuel-core]
version = "0.44.0+nightly.20250618.eee60aff3b"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250618/fuel-core-0.44.0%2Bnightly.20250618.eee60aff3b-aarch64-apple-darwin.tar.gz"
hash = "4fe27f6eafcb2804d2fec87dba4dd631006d2a54ef80de26b8769a594f1f8195"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250618/fuel-core-0.44.0%2Bnightly.20250618.eee60aff3b-aarch64-unknown-linux-gnu.tar.gz"
hash = "0c86c24cf35d77c8e4125de133ad7570a5a8d3f635355bd78c66f34ba645359e"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250618/fuel-core-0.44.0%2Bnightly.20250618.eee60aff3b-x86_64-unknown-linux-gnu.tar.gz"
hash = "8ae592006dcfc309b37a67d38b2014859b7b1fb62b89c0986285dfaba0894be6"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250618.eee60aff3b"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250618/fuel-core-0.44.0%2Bnightly.20250618.eee60aff3b-aarch64-apple-darwin.tar.gz"
hash = "4fe27f6eafcb2804d2fec87dba4dd631006d2a54ef80de26b8769a594f1f8195"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250618/fuel-core-0.44.0%2Bnightly.20250618.eee60aff3b-aarch64-unknown-linux-gnu.tar.gz"
hash = "0c86c24cf35d77c8e4125de133ad7570a5a8d3f635355bd78c66f34ba645359e"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250618/fuel-core-0.44.0%2Bnightly.20250618.eee60aff3b-x86_64-unknown-linux-gnu.tar.gz"
hash = "8ae592006dcfc309b37a67d38b2014859b7b1fb62b89c0986285dfaba0894be6"
