published_by = "https://github.com/FuelLabs/fuelup/actions/runs/17536941646"
date = "2025-09-08"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250908.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250908/forc-wallet-0.15.1%2Bnightly.20250908.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "9ac7685ffc38bcb2f34daeffff58febbdbed394f34dc1bd913f67cf90b727d09"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250908/forc-wallet-0.15.1%2Bnightly.20250908.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "5402d8b0bacee9370688b1531f1a02bdc22607e9f4f34cee319025f33b9e2ead"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250908/forc-wallet-0.15.1%2Bnightly.20250908.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "c9739e8bc30e4e3245e8a2d3257ab887970d7036d47d0dc4e6a94c10922f5928"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250908/forc-wallet-0.15.1%2Bnightly.20250908.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "d5458af4cadce257d70e3c441f2e915613bfd6ac08ac73b6e5d064ab9c171a1c"
