published_by = "https://github.com/FuelLabs/fuelup/actions/runs/11265769931"
date = "2024-10-10"

[pkg.forc]
version = "0.65.2+nightly.20241010.f5fd2e63a6"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241010/forc-binaries-0.65.2%2Bnightly.20241010.f5fd2e63a6-darwin_amd64.tar.gz"
hash = "60df0f89e3781ef6f904659c8ea517bd4c782c60863128e49c3c35babc73f907"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241010/forc-binaries-0.65.2%2Bnightly.20241010.f5fd2e63a6-darwin_arm64.tar.gz"
hash = "037c2f04d96e73157d678e3e12974b221c8fdbf2ce380d28d53fd854bdfef84d"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241010/forc-binaries-0.65.2%2Bnightly.20241010.f5fd2e63a6-linux_amd64.tar.gz"
hash = "8b995c6ad7fd85b489afd052faec04d16507050bdf251334bf849fcbdbfdf7f3"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241010/forc-binaries-0.65.2%2Bnightly.20241010.f5fd2e63a6-linux_arm64.tar.gz"
hash = "a7736fe7e3dda87179c3497753756362f9c6a65e9a31d7247c514661f7128e4d"

[pkg.forc-wallet]
version = "0.10.0+nightly.20241010.ee49fcbace"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241010/forc-wallet-0.10.0%2Bnightly.20241010.ee49fcbace-aarch64-apple-darwin.tar.gz"
hash = "2b47e7cbc96e32d86d79dce7dee9f6b205b040e92e3dc7d3b1d8814b6485e936"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241010/forc-wallet-0.10.0%2Bnightly.20241010.ee49fcbace-aarch64-unknown-linux-gnu.tar.gz"
hash = "ca29b74cf6fdc9fa29999aa67f9f56272c27413e826770af50182db0611fe44b"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241010/forc-wallet-0.10.0%2Bnightly.20241010.ee49fcbace-x86_64-apple-darwin.tar.gz"
hash = "9a399f264b7776d46302edd556c1e133e3e0d1532e4e4ee6808cd1971f4d915c"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241010/forc-wallet-0.10.0%2Bnightly.20241010.ee49fcbace-x86_64-unknown-linux-gnu.tar.gz"
hash = "f18c97339a8f78193406d8dbda5f7c2ab449919f7180d3ba19f23fb3fae45440"

[pkg.fuel-core]
version = "0.36.0+nightly.20241010.3fcf78ca61"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241010/fuel-core-0.36.0%2Bnightly.20241010.3fcf78ca61-aarch64-apple-darwin.tar.gz"
hash = "1524ddb3c2cc8bb579291531ec7c54a87af3aca9b2b2f75e1931991c953c132e"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241010/fuel-core-0.36.0%2Bnightly.20241010.3fcf78ca61-aarch64-unknown-linux-gnu.tar.gz"
hash = "78a8ef3666fa51453cba822f93fe991a6d0c298826c83d7e3fa9668d48981210"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241010/fuel-core-0.36.0%2Bnightly.20241010.3fcf78ca61-x86_64-unknown-linux-gnu.tar.gz"
hash = "faf9267d6cb39420161c026694506599798daf2aba3e135b19c71f7acf9ba6bf"

[pkg.fuel-core-keygen]
version = "0.36.0+nightly.20241010.3fcf78ca61"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241010/fuel-core-0.36.0%2Bnightly.20241010.3fcf78ca61-aarch64-apple-darwin.tar.gz"
hash = "1524ddb3c2cc8bb579291531ec7c54a87af3aca9b2b2f75e1931991c953c132e"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241010/fuel-core-0.36.0%2Bnightly.20241010.3fcf78ca61-aarch64-unknown-linux-gnu.tar.gz"
hash = "78a8ef3666fa51453cba822f93fe991a6d0c298826c83d7e3fa9668d48981210"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241010/fuel-core-0.36.0%2Bnightly.20241010.3fcf78ca61-x86_64-unknown-linux-gnu.tar.gz"
hash = "faf9267d6cb39420161c026694506599798daf2aba3e135b19c71f7acf9ba6bf"
