published_by = "https://github.com/FuelLabs/fuelup/actions/runs/16819675532"
date = "2025-08-08"

[pkg.forc]
version = "0.69.1+nightly.20250808.fb6ea52a96"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250808/forc-binaries-0.69.1%2Bnightly.20250808.fb6ea52a96-darwin_amd64.tar.gz"
hash = "fb859ff048c608f60405e927bacbe27cc045024575d7acf1747f167dfc990a7b"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250808/forc-binaries-0.69.1%2Bnightly.20250808.fb6ea52a96-darwin_arm64.tar.gz"
hash = "08393700d77e2dc6bd4155da70f2f91b83b4b8466d1a4082e3465cb35beb18d1"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250808/forc-binaries-0.69.1%2Bnightly.20250808.fb6ea52a96-linux_amd64.tar.gz"
hash = "866ca6b6c23994bfb307ed1c200a6a8718ff5342c695567c95e6be206d3c05df"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250808/forc-binaries-0.69.1%2Bnightly.20250808.fb6ea52a96-linux_arm64.tar.gz"
hash = "ea21c969ef29d54acc6850f8682f35b0c0155a3c1f3ef8f1c7ec5ca168713707"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250808.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250808/forc-wallet-0.15.1%2Bnightly.20250808.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "baed51dc5362fde6cb5265605b4a0cad1dd9747e0cbdf91e037fc5d0197fc5c7"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250808/forc-wallet-0.15.1%2Bnightly.20250808.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "ca4d124e3a437c289b8e38249389c7bbb3a6a4b56d446fede28561df08aed039"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250808/forc-wallet-0.15.1%2Bnightly.20250808.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "0bc3d983c26b8c5284f5c21c7ac3e4c29f97ff6ee8b4f14777348983eefb0d2d"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250808/forc-wallet-0.15.1%2Bnightly.20250808.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "91208c925e1b2221c73ecc1540b44cca8c7ec18ea3ba732ca61aa4db3e4966fd"

[pkg.fuel-core]
version = "0.46.0+nightly.20250808.e295b23307"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250808/fuel-core-0.46.0%2Bnightly.20250808.e295b23307-aarch64-apple-darwin.tar.gz"
hash = "93b8e921ea945256fd83cf0705958f23d6859a9b64727516b4e59395f0233870"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250808/fuel-core-0.46.0%2Bnightly.20250808.e295b23307-aarch64-unknown-linux-gnu.tar.gz"
hash = "f5fb5d35f968376a6b8893d6079a4a61376c4e3becea584b18240cc7f5bb8d54"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250808/fuel-core-0.46.0%2Bnightly.20250808.e295b23307-x86_64-unknown-linux-gnu.tar.gz"
hash = "23a9be869c3e26437f7b887d1603e2077c29ea944efe4d519fd6f2a94f6b0a64"

[pkg.fuel-core-keygen]
version = "0.46.0+nightly.20250808.e295b23307"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250808/fuel-core-0.46.0%2Bnightly.20250808.e295b23307-aarch64-apple-darwin.tar.gz"
hash = "93b8e921ea945256fd83cf0705958f23d6859a9b64727516b4e59395f0233870"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250808/fuel-core-0.46.0%2Bnightly.20250808.e295b23307-aarch64-unknown-linux-gnu.tar.gz"
hash = "f5fb5d35f968376a6b8893d6079a4a61376c4e3becea584b18240cc7f5bb8d54"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250808/fuel-core-0.46.0%2Bnightly.20250808.e295b23307-x86_64-unknown-linux-gnu.tar.gz"
hash = "23a9be869c3e26437f7b887d1603e2077c29ea944efe4d519fd6f2a94f6b0a64"
