published_by = "https://github.com/FuelLabs/fuelup/actions/runs/16083175903"
date = "2025-07-05"

[pkg.forc]
version = "0.69.0+nightly.20250705.b54fce7727"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250705/forc-binaries-0.69.0%2Bnightly.20250705.b54fce7727-darwin_amd64.tar.gz"
hash = "f156a1f59034d6f538632f6e18a41026ce0d91f7fd47d0472a5e5afede28ba40"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250705/forc-binaries-0.69.0%2Bnightly.20250705.b54fce7727-darwin_arm64.tar.gz"
hash = "55806f7aa00353163a266d2e1b274984643dfee0e9c29b4765c6c6d72ef4ac0e"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250705/forc-binaries-0.69.0%2Bnightly.20250705.b54fce7727-linux_amd64.tar.gz"
hash = "d170864aac9babbf79f0620199f25691fdac0b1d84f48952f132344056a572e0"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250705/forc-binaries-0.69.0%2Bnightly.20250705.b54fce7727-linux_arm64.tar.gz"
hash = "4eef0ce9f7cfa57b5d5ec20e7309ae5a80899387b4ff3898355034cf18243753"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250705.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250705/forc-wallet-0.15.1%2Bnightly.20250705.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "34d1d639a4fa2395fd9edca968990461cb191a6bd5a8a0747f81811a2714e34f"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250705/forc-wallet-0.15.1%2Bnightly.20250705.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "e3d0326518ee3732e248eb46b5f7b9aba9431e595aa3c62abb7f5edb78eed146"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250705/forc-wallet-0.15.1%2Bnightly.20250705.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "c8a4319adcf58fc5c5397e0aa1ad8f23bbf1cc8cc11ae9bf6d876dbc867c8304"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250705/forc-wallet-0.15.1%2Bnightly.20250705.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "ed5657a8e224254b12bb082d0aa4182a9c0485c9bc78ecb690e4b987b53ede17"

[pkg.fuel-core]
version = "0.44.0+nightly.20250705.a08b48499c"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250705/fuel-core-0.44.0%2Bnightly.20250705.a08b48499c-aarch64-apple-darwin.tar.gz"
hash = "9a979d42c6c6136b71af44d4a699bb740caf7eddbdfc2ee43631e4bcbbf40570"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250705/fuel-core-0.44.0%2Bnightly.20250705.a08b48499c-aarch64-unknown-linux-gnu.tar.gz"
hash = "72b120b1143e7f0116dd87ac833f9ba722c47af61ceae69a3da50f7dffe7c37f"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250705/fuel-core-0.44.0%2Bnightly.20250705.a08b48499c-x86_64-unknown-linux-gnu.tar.gz"
hash = "6e69d0d6f72110e9d66074d74736e0854558c00c422ce76067f49281e60aeed0"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250705.a08b48499c"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250705/fuel-core-0.44.0%2Bnightly.20250705.a08b48499c-aarch64-apple-darwin.tar.gz"
hash = "9a979d42c6c6136b71af44d4a699bb740caf7eddbdfc2ee43631e4bcbbf40570"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250705/fuel-core-0.44.0%2Bnightly.20250705.a08b48499c-aarch64-unknown-linux-gnu.tar.gz"
hash = "72b120b1143e7f0116dd87ac833f9ba722c47af61ceae69a3da50f7dffe7c37f"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250705/fuel-core-0.44.0%2Bnightly.20250705.a08b48499c-x86_64-unknown-linux-gnu.tar.gz"
hash = "6e69d0d6f72110e9d66074d74736e0854558c00c422ce76067f49281e60aeed0"
