published_by = "https://github.com/FuelLabs/fuelup/actions/runs/11431926424"
date = "2024-10-21"

[pkg.forc]
version = "0.66.2+nightly.20241021.029c593b5f"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241021/forc-binaries-0.66.2%2Bnightly.20241021.029c593b5f-darwin_amd64.tar.gz"
hash = "f14e0d76b8e15872cc9a1ff59a03880ebd5fd6f3ac825ade470deb4ba15a09ff"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241021/forc-binaries-0.66.2%2Bnightly.20241021.029c593b5f-darwin_arm64.tar.gz"
hash = "0920c81706f86bc8b1212f49aae2d7385c69f0f0f06749affc73d198d0d00ed1"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241021/forc-binaries-0.66.2%2Bnightly.20241021.029c593b5f-linux_amd64.tar.gz"
hash = "6006a3a35b3345199c503fa80ad5927de4d8db2dc0386c9634d55bf5817ba2ed"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241021/forc-binaries-0.66.2%2Bnightly.20241021.029c593b5f-linux_arm64.tar.gz"
hash = "13362428c23f1aea9518be1831953f3bfde338e9d9ea90156138d1ae872178f6"

[pkg.forc-wallet]
version = "0.11.0+nightly.20241021.152bfb48c3"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241021/forc-wallet-0.11.0%2Bnightly.20241021.152bfb48c3-aarch64-apple-darwin.tar.gz"
hash = "75fd0c100ad80849a7cf0e02f12b7ed1bc70c74f1ac3762e55dde72faee0264a"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241021/forc-wallet-0.11.0%2Bnightly.20241021.152bfb48c3-aarch64-unknown-linux-gnu.tar.gz"
hash = "33bab8d248f593b638ea3963a14c4d434cd6e5038bfec6ee161a7d64c8d9840a"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241021/forc-wallet-0.11.0%2Bnightly.20241021.152bfb48c3-x86_64-apple-darwin.tar.gz"
hash = "944a22351bb4219d689c1ec1118bcdd246038a9e50da94eb25668ec300768ec6"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241021/forc-wallet-0.11.0%2Bnightly.20241021.152bfb48c3-x86_64-unknown-linux-gnu.tar.gz"
hash = "7c5b36bb219d91c32470fdc3cc3ca6a7b28cbfc9fd2d9f7f4ac8706bedbc3f2e"

[pkg.fuel-core]
version = "0.40.0+nightly.20241021.eea8c60525"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241021/fuel-core-0.40.0%2Bnightly.20241021.eea8c60525-aarch64-apple-darwin.tar.gz"
hash = "35a3a66eca758c0b49d5bef1f5e31437dabe40369c9334086ddd947ff612b75c"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241021/fuel-core-0.40.0%2Bnightly.20241021.eea8c60525-aarch64-unknown-linux-gnu.tar.gz"
hash = "ae40a2ad3e7c922cc0387fab2e84ffb67ed72aecf05e86a72b2d37052f703295"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241021/fuel-core-0.40.0%2Bnightly.20241021.eea8c60525-x86_64-unknown-linux-gnu.tar.gz"
hash = "a2b0a55fbb4a1383218e54461037347b07d2218b7bceebb53995a8de7e5f9d42"

[pkg.fuel-core-keygen]
version = "0.40.0+nightly.20241021.eea8c60525"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241021/fuel-core-0.40.0%2Bnightly.20241021.eea8c60525-aarch64-apple-darwin.tar.gz"
hash = "35a3a66eca758c0b49d5bef1f5e31437dabe40369c9334086ddd947ff612b75c"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241021/fuel-core-0.40.0%2Bnightly.20241021.eea8c60525-aarch64-unknown-linux-gnu.tar.gz"
hash = "ae40a2ad3e7c922cc0387fab2e84ffb67ed72aecf05e86a72b2d37052f703295"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241021/fuel-core-0.40.0%2Bnightly.20241021.eea8c60525-x86_64-unknown-linux-gnu.tar.gz"
hash = "a2b0a55fbb4a1383218e54461037347b07d2218b7bceebb53995a8de7e5f9d42"
