published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15056870905"
date = "2025-05-15"

[pkg.forc]
version = "0.68.4+nightly.20250515.39251b665b"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250515/forc-binaries-0.68.4%2Bnightly.20250515.39251b665b-darwin_amd64.tar.gz"
hash = "2cab967da2715a175923bc095086935d82cf0469380bc0876cb05e7770b7fafa"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250515/forc-binaries-0.68.4%2Bnightly.20250515.39251b665b-darwin_arm64.tar.gz"
hash = "55a55d319a0952430d4425520fa1f1ef31eb8f64921c18a118a944350071c11e"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250515/forc-binaries-0.68.4%2Bnightly.20250515.39251b665b-linux_amd64.tar.gz"
hash = "53dbfdd19ea96c9df4459da3befca3d638f52820884f710a3934d30f2369dec2"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250515/forc-binaries-0.68.4%2Bnightly.20250515.39251b665b-linux_arm64.tar.gz"
hash = "666ea249ba0f4fd5568ba9e15de4ebe6cd7742a81f1a04ae81a6ef9b61967615"

[pkg.forc-wallet]
version = "0.14.0+nightly.20250515.24883eb126"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250515/forc-wallet-0.14.0%2Bnightly.20250515.24883eb126-aarch64-apple-darwin.tar.gz"
hash = "b10029b353a6d0e54d6d3f9b393c6e0dffbfe6b61fdb5c60e01451d86837fcc4"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250515/forc-wallet-0.14.0%2Bnightly.20250515.24883eb126-aarch64-unknown-linux-gnu.tar.gz"
hash = "177038a785e14487a8ba15f2d82f679703b14ee6a367e8e4a05b40aa14aea8ad"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250515/forc-wallet-0.14.0%2Bnightly.20250515.24883eb126-x86_64-apple-darwin.tar.gz"
hash = "01d325bd58e5f2015a6e11c382b5af56c4bf6cf17bb662ffb8effdab9bf13032"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250515/forc-wallet-0.14.0%2Bnightly.20250515.24883eb126-x86_64-unknown-linux-gnu.tar.gz"
hash = "bca726bc724fe5d4d4fa4570100b6f94258e36f0d385ef5740a25775fd9f81c2"

[pkg.fuel-core]
version = "0.43.0+nightly.20250515.5c0d1fe98f"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250515/fuel-core-0.43.0%2Bnightly.20250515.5c0d1fe98f-aarch64-apple-darwin.tar.gz"
hash = "d75f2d3dab5c43ded6eb33f7b0ce5b93415c365600b0d5df31fa74bf08008fb2"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250515/fuel-core-0.43.0%2Bnightly.20250515.5c0d1fe98f-aarch64-unknown-linux-gnu.tar.gz"
hash = "f31499c99e331978715e92518f9fbc8957c5539c1251210573f2365b071a8b89"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250515/fuel-core-0.43.0%2Bnightly.20250515.5c0d1fe98f-x86_64-unknown-linux-gnu.tar.gz"
hash = "ce4fbef5234f3a676c665b9e1ee4d74f6ec42a3b5da6664a045481be75975205"

[pkg.fuel-core-keygen]
version = "0.43.0+nightly.20250515.5c0d1fe98f"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250515/fuel-core-0.43.0%2Bnightly.20250515.5c0d1fe98f-aarch64-apple-darwin.tar.gz"
hash = "d75f2d3dab5c43ded6eb33f7b0ce5b93415c365600b0d5df31fa74bf08008fb2"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250515/fuel-core-0.43.0%2Bnightly.20250515.5c0d1fe98f-aarch64-unknown-linux-gnu.tar.gz"
hash = "f31499c99e331978715e92518f9fbc8957c5539c1251210573f2365b071a8b89"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250515/fuel-core-0.43.0%2Bnightly.20250515.5c0d1fe98f-x86_64-unknown-linux-gnu.tar.gz"
hash = "ce4fbef5234f3a676c665b9e1ee4d74f6ec42a3b5da6664a045481be75975205"
