published_by = "https://github.com/FuelLabs/fuelup/actions/runs/10104127311"
date = "2024-07-26"

[pkg.forc]
version = "0.62.0+nightly.20240726.62e734201a"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240726/forc-binaries-0.62.0%2Bnightly.20240726.62e734201a-darwin_amd64.tar.gz"
hash = "a4af2327f363886aafad48856c07a57e4b5914e8f054863de422177874b5d71f"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240726/forc-binaries-0.62.0%2Bnightly.20240726.62e734201a-darwin_arm64.tar.gz"
hash = "7c56da0719b6ea50e5c8f4e3b98a2e3558733ec9bc41f73e0a47be3cb144dff1"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240726/forc-binaries-0.62.0%2Bnightly.20240726.62e734201a-linux_amd64.tar.gz"
hash = "a541d20e1bbaf55e7e90833accee3cbac23f08af68d5480a77303209e7c33de9"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240726/forc-binaries-0.62.0%2Bnightly.20240726.62e734201a-linux_arm64.tar.gz"
hash = "f9318ac7c8a4eaa6e4a6056bbe45d9648a55113b263cd9d7b9af5c97ae190f30"

[pkg.forc-wallet]
version = "0.8.2+nightly.20240726.76e9796cbe"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240726/forc-wallet-0.8.2%2Bnightly.20240726.76e9796cbe-aarch64-apple-darwin.tar.gz"
hash = "1d576a0f20efef2f072f87b06ff981c0283abb07fbb0eaa6d18c51ead52d5868"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240726/forc-wallet-0.8.2%2Bnightly.20240726.76e9796cbe-aarch64-unknown-linux-gnu.tar.gz"
hash = "290151b8a9ad31f03193a3a68a0a31b1263dce41a876dee7c5955645fdafc0cd"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240726/forc-wallet-0.8.2%2Bnightly.20240726.76e9796cbe-x86_64-apple-darwin.tar.gz"
hash = "9059694c3fae51f576899a25acc48600deecb4b8e7e924b069a22ef7913e2972"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240726/forc-wallet-0.8.2%2Bnightly.20240726.76e9796cbe-x86_64-unknown-linux-gnu.tar.gz"
hash = "f02a4825e57409c673745018a36383313cc8da59a5fb0f87cf29f0c8b5d4dd54"

[pkg.fuel-core]
version = "0.31.0+nightly.20240726.25f269eab6"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240726/fuel-core-0.31.0%2Bnightly.20240726.25f269eab6-aarch64-apple-darwin.tar.gz"
hash = "cd959aaa92e1bbc9b4186cef656d7fb5c3d64a3758910ad669984641a2a067e4"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240726/fuel-core-0.31.0%2Bnightly.20240726.25f269eab6-aarch64-unknown-linux-gnu.tar.gz"
hash = "adfd7b93f7044974a112e167de9e75450b23cbc13dba18ceebb4d1f1a4e5636c"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240726/fuel-core-0.31.0%2Bnightly.20240726.25f269eab6-x86_64-apple-darwin.tar.gz"
hash = "7eea241d416dd2a7bf9240c5bb141a8b680e22984a473469b3b160297545b5b1"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240726/fuel-core-0.31.0%2Bnightly.20240726.25f269eab6-x86_64-unknown-linux-gnu.tar.gz"
hash = "77a03360533b70eec09671a1ac759deb293d740c38c3e30b90f8b1e22240bc30"

[pkg.fuel-core-keygen]
version = "0.31.0+nightly.20240726.25f269eab6"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240726/fuel-core-0.31.0%2Bnightly.20240726.25f269eab6-aarch64-apple-darwin.tar.gz"
hash = "cd959aaa92e1bbc9b4186cef656d7fb5c3d64a3758910ad669984641a2a067e4"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240726/fuel-core-0.31.0%2Bnightly.20240726.25f269eab6-aarch64-unknown-linux-gnu.tar.gz"
hash = "adfd7b93f7044974a112e167de9e75450b23cbc13dba18ceebb4d1f1a4e5636c"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240726/fuel-core-0.31.0%2Bnightly.20240726.25f269eab6-x86_64-apple-darwin.tar.gz"
hash = "7eea241d416dd2a7bf9240c5bb141a8b680e22984a473469b3b160297545b5b1"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240726/fuel-core-0.31.0%2Bnightly.20240726.25f269eab6-x86_64-unknown-linux-gnu.tar.gz"
hash = "77a03360533b70eec09671a1ac759deb293d740c38c3e30b90f8b1e22240bc30"
