published_by = "https://github.com/FuelLabs/fuelup/actions/runs/17568939463"
date = "2025-09-09"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250909.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250909/forc-wallet-0.15.1%2Bnightly.20250909.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "8bdca59442584499b9b712fc283b3b4ab0ecbc5cfed902c52a5d272ca762d908"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250909/forc-wallet-0.15.1%2Bnightly.20250909.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "30594f1aae0c30a90ad66db3b5aea930e12359578c4840be91d7099fe9a92057"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250909/forc-wallet-0.15.1%2Bnightly.20250909.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "951cdd3ecac437f8e0b598c64393c02d79215007a0a9c2bd2a18370767583c41"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250909/forc-wallet-0.15.1%2Bnightly.20250909.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "4f532b6e6051e98185a41b6d67407dacd9f6499ab59dea5379d59ebeceeb6621"
