published_by = "https://github.com/FuelLabs/fuelup/actions/runs/12759251274"
date = "2025-01-14"

[pkg.forc]
version = "0.66.5+nightly.20250114.e40ebf4157"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250114/forc-binaries-0.66.5%2Bnightly.20250114.e40ebf4157-darwin_amd64.tar.gz"
hash = "28b0ba2d1258edb91a08fae744ec6c4613d5278bac018911307c0b6ae69c15b0"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250114/forc-binaries-0.66.5%2Bnightly.20250114.e40ebf4157-darwin_arm64.tar.gz"
hash = "742135e9190ffada6fccbc0cc936f3687bf7f32a465fc1b6b8b03aba7c1f9520"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250114/forc-binaries-0.66.5%2Bnightly.20250114.e40ebf4157-linux_amd64.tar.gz"
hash = "6f11c239e27eb5862af74b05aa3de4c0faeda893dae1d78a620df330c03d1346"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250114/forc-binaries-0.66.5%2Bnightly.20250114.e40ebf4157-linux_arm64.tar.gz"
hash = "2ff0c75d95efe368a1de3677383ffcae11866a450999793f6a791a422047578f"

[pkg.forc-wallet]
version = "0.11.1+nightly.20250114.f6f0ff07c8"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250114/forc-wallet-0.11.1%2Bnightly.20250114.f6f0ff07c8-aarch64-apple-darwin.tar.gz"
hash = "2d3f7d012be15d30b7bec4f48b4394b9457aca793256b0a452e40b36b0a413c2"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250114/forc-wallet-0.11.1%2Bnightly.20250114.f6f0ff07c8-aarch64-unknown-linux-gnu.tar.gz"
hash = "1189c8e02824b794b9d292370dca4cc7093d66a01de7b242edb811afeb1384ca"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250114/forc-wallet-0.11.1%2Bnightly.20250114.f6f0ff07c8-x86_64-apple-darwin.tar.gz"
hash = "118b49c6b8fdaa0152273323823e4cbdddd1c055577a22ae89b55b0bcb887145"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250114/forc-wallet-0.11.1%2Bnightly.20250114.f6f0ff07c8-x86_64-unknown-linux-gnu.tar.gz"
hash = "9f232b643ad7855555ef4398d9829116937abe906bba124ab8285f1e250516ba"

[pkg.fuel-core]
version = "0.40.0+nightly.20250114.a9557084b4"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250114/fuel-core-0.40.0%2Bnightly.20250114.a9557084b4-aarch64-apple-darwin.tar.gz"
hash = "ff341ec0f9a1d91e98a1ae30749e59036ad812df56a4f4dc613b56aaafae977b"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250114/fuel-core-0.40.0%2Bnightly.20250114.a9557084b4-aarch64-unknown-linux-gnu.tar.gz"
hash = "5a9fce553a2a73d5d6b9f1de5aa147f03940271ee7678360836f3d7b88820ad8"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250114/fuel-core-0.40.0%2Bnightly.20250114.a9557084b4-x86_64-apple-darwin.tar.gz"
hash = "d31811b17094593dad0bbe26d1257a65b2cca36fbe7db58501704809843e6a2f"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250114/fuel-core-0.40.0%2Bnightly.20250114.a9557084b4-x86_64-unknown-linux-gnu.tar.gz"
hash = "3a9ec6ca7bd6659842e5a059f75ad3de65761198096648cfb64e93ae3548d77f"

[pkg.fuel-core-keygen]
version = "0.40.0+nightly.20250114.a9557084b4"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250114/fuel-core-0.40.0%2Bnightly.20250114.a9557084b4-aarch64-apple-darwin.tar.gz"
hash = "ff341ec0f9a1d91e98a1ae30749e59036ad812df56a4f4dc613b56aaafae977b"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250114/fuel-core-0.40.0%2Bnightly.20250114.a9557084b4-aarch64-unknown-linux-gnu.tar.gz"
hash = "5a9fce553a2a73d5d6b9f1de5aa147f03940271ee7678360836f3d7b88820ad8"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250114/fuel-core-0.40.0%2Bnightly.20250114.a9557084b4-x86_64-apple-darwin.tar.gz"
hash = "d31811b17094593dad0bbe26d1257a65b2cca36fbe7db58501704809843e6a2f"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250114/fuel-core-0.40.0%2Bnightly.20250114.a9557084b4-x86_64-unknown-linux-gnu.tar.gz"
hash = "3a9ec6ca7bd6659842e5a059f75ad3de65761198096648cfb64e93ae3548d77f"
