published_by = "https://github.com/FuelLabs/fuelup/actions/runs/18811095081"
date = "2025-10-26"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251026.279124d992"

[pkg.forc-wallet.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251026/forc-wallet-0.15.2%2Bnightly.20251026.279124d992-aarch64-apple-darwin.tar.gz"
hash = "3864a6fec48761ed2132f4b3705ce63ed442a6f63f7bb1db4c2f6a6277da7f80"

[pkg.forc-wallet.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251026/forc-wallet-0.15.2%2Bnightly.20251026.279124d992-aarch64-unknown-linux-gnu.tar.gz"
hash = "57216e0f102f64bc26cecb12ffd83cdada9d2b4aaecc8adc8b4480909a560e62"

[pkg.forc-wallet.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251026/forc-wallet-0.15.2%2Bnightly.20251026.279124d992-x86_64-apple-darwin.tar.gz"
hash = "a463aac77f0ed97160900e796e0395e10b0312a465cd7fe758c2265b77faebac"

[pkg.forc-wallet.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251026/forc-wallet-0.15.2%2Bnightly.20251026.279124d992-x86_64-unknown-linux-gnu.tar.gz"
hash = "40a83c721f6afa5d157b5065440a10862c68789eca7a192bea0bd6bae2e8e462"
