published_by = "https://github.com/FuelLabs/fuelup/actions/runs/14849723567"
date = "2025-05-06"

[pkg.forc]
version = "0.68.2+nightly.20250506.804d6df0d9"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250506/forc-binaries-0.68.2%2Bnightly.20250506.804d6df0d9-darwin_amd64.tar.gz"
hash = "7e5f70d2b8b0383d41e9658d237eb4123c5bf5c4d8162985ea7f375efa05a126"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250506/forc-binaries-0.68.2%2Bnightly.20250506.804d6df0d9-darwin_arm64.tar.gz"
hash = "d91788ab4ac87d45cf03d82508afdd4659f1d70e54f36c0cec6ee2082761f69d"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250506/forc-binaries-0.68.2%2Bnightly.20250506.804d6df0d9-linux_amd64.tar.gz"
hash = "a288bd3d357dceef952ed4161b58a7a4c0a2a941b814f312c7a3256a5e5f285f"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250506/forc-binaries-0.68.2%2Bnightly.20250506.804d6df0d9-linux_arm64.tar.gz"
hash = "d10871fd01a904c6141c273de921347ffc937b44b9ea538e6ed666976d0d8940"

[pkg.forc-wallet]
version = "0.14.0+nightly.20250506.24883eb126"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250506/forc-wallet-0.14.0%2Bnightly.20250506.24883eb126-aarch64-apple-darwin.tar.gz"
hash = "9a08ec0748bcc89e0b0c990034c3e9e723684d2ed2f89d6026e0d0e2aa128390"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250506/forc-wallet-0.14.0%2Bnightly.20250506.24883eb126-aarch64-unknown-linux-gnu.tar.gz"
hash = "910d548359996f10bb6f8a1d53a6753d46ced905b9d92a3c07462c8c113a1c58"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250506/forc-wallet-0.14.0%2Bnightly.20250506.24883eb126-x86_64-apple-darwin.tar.gz"
hash = "dc1df18dcbde27b8a6fbf5fb042f88b7811fb9feb8080cdfee70a8ff5085b1b7"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250506/forc-wallet-0.14.0%2Bnightly.20250506.24883eb126-x86_64-unknown-linux-gnu.tar.gz"
hash = "27005f01704145cd6c471cd5ddd34f3671035011d288650e885b7f3ce6b9fb66"

[pkg.fuel-core]
version = "0.43.0+nightly.20250506.6403b73c5b"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250506/fuel-core-0.43.0%2Bnightly.20250506.6403b73c5b-aarch64-apple-darwin.tar.gz"
hash = "2e03d7f84fcaea4cd81bc87e603671e82a25287d351fc746760c34f4c1a43bca"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250506/fuel-core-0.43.0%2Bnightly.20250506.6403b73c5b-aarch64-unknown-linux-gnu.tar.gz"
hash = "29401ac5d8adc0555655d0f0aee1e20d0604b887c95f682276cc7a43415cbeaf"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250506/fuel-core-0.43.0%2Bnightly.20250506.6403b73c5b-x86_64-unknown-linux-gnu.tar.gz"
hash = "76e3961b0396004d7762ee0961d18b8ef62b5e9e0007fe8307cb9b5214720636"

[pkg.fuel-core-keygen]
version = "0.43.0+nightly.20250506.6403b73c5b"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250506/fuel-core-0.43.0%2Bnightly.20250506.6403b73c5b-aarch64-apple-darwin.tar.gz"
hash = "2e03d7f84fcaea4cd81bc87e603671e82a25287d351fc746760c34f4c1a43bca"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250506/fuel-core-0.43.0%2Bnightly.20250506.6403b73c5b-aarch64-unknown-linux-gnu.tar.gz"
hash = "29401ac5d8adc0555655d0f0aee1e20d0604b887c95f682276cc7a43415cbeaf"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250506/fuel-core-0.43.0%2Bnightly.20250506.6403b73c5b-x86_64-unknown-linux-gnu.tar.gz"
hash = "76e3961b0396004d7762ee0961d18b8ef62b5e9e0007fe8307cb9b5214720636"
