published_by = "https://github.com/FuelLabs/fuelup/actions/runs/21306772526"
date = "2026-01-24"

[pkg.forc]
version = "0.70.1+nightly.20260124.20b32cfb44"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/forc-binaries-0.70.1%2Bnightly.20260124.20b32cfb44-darwin_amd64.tar.gz"
hash = "fb41436468b991e9dfd8f2ccdda6f8442c87ae18a47dbf9231023245ba1b5bd5"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/forc-binaries-0.70.1%2Bnightly.20260124.20b32cfb44-darwin_arm64.tar.gz"
hash = "bfc138bb91db443e68850dee14665f979fe36ab5eb470a985255ad7ff3321936"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/forc-binaries-0.70.1%2Bnightly.20260124.20b32cfb44-linux_amd64.tar.gz"
hash = "43925d0f98f4f482e57d001978c34278fd65b66c984a27c4393f8228efc5f5fb"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/forc-binaries-0.70.1%2Bnightly.20260124.20b32cfb44-linux_arm64.tar.gz"
hash = "e13c2387748517b6a15594ff344b574431e79614801a2ef775c1607a862a015e"

[pkg.forc-crypto]
version = "0.71.0+nightly.20260124.54cf9da7d3"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/forc-crypto-0.71.0%2Bnightly.20260124.54cf9da7d3-darwin_amd64.tar.gz"
hash = "6740b12062557618bc9a4006516f6f9fe1d9db37bb55f7b6d965b26bc2a21b76"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/forc-crypto-0.71.0%2Bnightly.20260124.54cf9da7d3-darwin_arm64.tar.gz"
hash = "5766b812ece1d279f7c168d99c5cdf61ea8cfca223d9e5e9b1f480e1707801c8"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/forc-crypto-0.71.0%2Bnightly.20260124.54cf9da7d3-linux_amd64.tar.gz"
hash = "695d7ea9c76bbaabb7f00c7e8b29e0505b17e7dcd406f0b66eda7358a087cda3"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/forc-crypto-0.71.0%2Bnightly.20260124.54cf9da7d3-linux_arm64.tar.gz"
hash = "a9118ad3d83f53b221dff0a32867566092971e3c7f5f1d5d9137154ee7f69033"

[pkg.forc-node]
version = "0.71.2+nightly.20260124.54cf9da7d3"

[pkg.forc-node.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/forc-node-0.71.2%2Bnightly.20260124.54cf9da7d3-darwin_amd64.tar.gz"
hash = "b375c90b19c907c6a6842a6328151fc543d9b27e147d9c4c487af58e67d78e05"

[pkg.forc-node.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/forc-node-0.71.2%2Bnightly.20260124.54cf9da7d3-darwin_arm64.tar.gz"
hash = "996a521ca8fc1317a7c9ee23fd9846fbb86b2c0ace954d3cbc4079ea662346ea"

[pkg.forc-node.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/forc-node-0.71.2%2Bnightly.20260124.54cf9da7d3-linux_amd64.tar.gz"
hash = "6dc44c38f8994204f195254609df82ef44bb2f1a35e9a6e862f50538cce0cdac"

[pkg.forc-node.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/forc-node-0.71.2%2Bnightly.20260124.54cf9da7d3-linux_arm64.tar.gz"
hash = "5d6ba2f1feff7b8d0d00a9070b2b29176c9e9d295d8914eac8de484de5b7fcf4"

[pkg.forc-wallet]
version = "0.16.2+nightly.20260124.54cf9da7d3"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/forc-wallet-0.16.2%2Bnightly.20260124.54cf9da7d3-darwin_amd64.tar.gz"
hash = "cc3aac1756c502f4b49335409214696577b390f60109d5d64d8910c250b6d9c9"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/forc-wallet-0.16.2%2Bnightly.20260124.54cf9da7d3-darwin_arm64.tar.gz"
hash = "455b2b8c107f5e8cff6f3c55ccfdf63532a1c22ba3e4a0db5af46e3e0bac2855"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/forc-wallet-0.16.2%2Bnightly.20260124.54cf9da7d3-linux_amd64.tar.gz"
hash = "037fca88eccfb8bedc085b1c9e10e837f6026c20a6ebb911ff9c1f8ff13a177b"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/forc-wallet-0.16.2%2Bnightly.20260124.54cf9da7d3-linux_arm64.tar.gz"
hash = "b20e20f70bfa9ba578b35883a9e548755b574b8cc340d52ddabc20beb4898ecd"

[pkg.fuel-core]
version = "0.47.1+nightly.20260124.579e1c2d78"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/fuel-core-0.47.1%2Bnightly.20260124.579e1c2d78-aarch64-apple-darwin.tar.gz"
hash = "a2f3286a9fd8910d7d3405669ffc8ba8b44a42b346df5d38fa28172ae7b37caa"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/fuel-core-0.47.1%2Bnightly.20260124.579e1c2d78-aarch64-unknown-linux-gnu.tar.gz"
hash = "200becec13904bf2c70a8ba0084a3606b61813753c90014787ad9698ccb0df39"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/fuel-core-0.47.1%2Bnightly.20260124.579e1c2d78-x86_64-unknown-linux-gnu.tar.gz"
hash = "cef70c92ce15c51b2d0f84eadb68a6ed1b951371a6099a17d89e97eae58dc832"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20260124.579e1c2d78"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/fuel-core-0.47.1%2Bnightly.20260124.579e1c2d78-aarch64-apple-darwin.tar.gz"
hash = "a2f3286a9fd8910d7d3405669ffc8ba8b44a42b346df5d38fa28172ae7b37caa"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/fuel-core-0.47.1%2Bnightly.20260124.579e1c2d78-aarch64-unknown-linux-gnu.tar.gz"
hash = "200becec13904bf2c70a8ba0084a3606b61813753c90014787ad9698ccb0df39"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260124/fuel-core-0.47.1%2Bnightly.20260124.579e1c2d78-x86_64-unknown-linux-gnu.tar.gz"
hash = "cef70c92ce15c51b2d0f84eadb68a6ed1b951371a6099a17d89e97eae58dc832"
