published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15406404966"
date = "2025-06-03"

[pkg.forc]
version = "0.68.6+nightly.20250603.e1e51fd81f"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250603/forc-binaries-0.68.6%2Bnightly.20250603.e1e51fd81f-darwin_amd64.tar.gz"
hash = "fd59ad52b6bed1b06f26733852dc2c81fea7c666976332697b7fbedb6123e533"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250603/forc-binaries-0.68.6%2Bnightly.20250603.e1e51fd81f-darwin_arm64.tar.gz"
hash = "704afa8c37180a35ce96bb4d3e857646da22d06dc467c828ee59b21d3beee6ec"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250603/forc-binaries-0.68.6%2Bnightly.20250603.e1e51fd81f-linux_amd64.tar.gz"
hash = "7b4b7ad0c8e4889a3985eab4c3a04ee27e2c791b0919b784df0f368b97c77c49"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250603/forc-binaries-0.68.6%2Bnightly.20250603.e1e51fd81f-linux_arm64.tar.gz"
hash = "999f6e2a993e50fb8a5091cce638897369b4c109c55010edda82b031c1055d95"

[pkg.forc-wallet]
version = "0.14.0+nightly.20250603.24883eb126"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250603/forc-wallet-0.14.0%2Bnightly.20250603.24883eb126-aarch64-apple-darwin.tar.gz"
hash = "e303f499d4a1e43aa8377ab4a49771b9a8ec399b4462ccef61a2c9c7506c9359"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250603/forc-wallet-0.14.0%2Bnightly.20250603.24883eb126-aarch64-unknown-linux-gnu.tar.gz"
hash = "a518489c03207d4e9e7f4029a63744cdb7e8fb4eae3d9926e2b96189e95f98c2"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250603/forc-wallet-0.14.0%2Bnightly.20250603.24883eb126-x86_64-apple-darwin.tar.gz"
hash = "e697a9603b96043858bbb986acdfc01dc3193a47703b6e97f3ac340dbc705f4e"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250603/forc-wallet-0.14.0%2Bnightly.20250603.24883eb126-x86_64-unknown-linux-gnu.tar.gz"
hash = "51664c9071318742e04a91869c03ccc86546ae4b12fada2513d9b0cec84935fe"

[pkg.fuel-core]
version = "0.44.0+nightly.20250603.49d0309dd1"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250603/fuel-core-0.44.0%2Bnightly.20250603.49d0309dd1-aarch64-apple-darwin.tar.gz"
hash = "627482263a9370507e56c70b020f44a8031bf76a1d19b0825addde79b17d2105"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250603/fuel-core-0.44.0%2Bnightly.20250603.49d0309dd1-aarch64-unknown-linux-gnu.tar.gz"
hash = "719c311e6cc5d678660e7d1e1007ce99e88d82ee5605a9e47dc04de4fb375bc9"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250603.49d0309dd1"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250603/fuel-core-0.44.0%2Bnightly.20250603.49d0309dd1-aarch64-apple-darwin.tar.gz"
hash = "627482263a9370507e56c70b020f44a8031bf76a1d19b0825addde79b17d2105"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250603/fuel-core-0.44.0%2Bnightly.20250603.49d0309dd1-aarch64-unknown-linux-gnu.tar.gz"
hash = "719c311e6cc5d678660e7d1e1007ce99e88d82ee5605a9e47dc04de4fb375bc9"
