published_by = "https://github.com/FuelLabs/fuelup/actions/runs/11656900918"
date = "2024-11-04"

[pkg.forc]
version = "0.66.4+nightly.20241104.d7dd104dac"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241104/forc-binaries-0.66.4%2Bnightly.20241104.d7dd104dac-darwin_amd64.tar.gz"
hash = "af035fef32070046fc6c1bd590a5d796e7b44574578d49ec39e435bee589cfce"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241104/forc-binaries-0.66.4%2Bnightly.20241104.d7dd104dac-darwin_arm64.tar.gz"
hash = "d8a0ed6168ee7dfe83138378e260525d63c517c11a9e6a65c4e17c2eb5ae674b"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241104/forc-binaries-0.66.4%2Bnightly.20241104.d7dd104dac-linux_amd64.tar.gz"
hash = "edc3b82d99447b8b70094d16274ed029fbbe9909817b419bf4d9ff2e2283e149"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241104/forc-binaries-0.66.4%2Bnightly.20241104.d7dd104dac-linux_arm64.tar.gz"
hash = "096c38554c7570b033767a8705ee1f9b207fa307970e253f67375c9898dc3646"

[pkg.forc-wallet]
version = "0.11.1+nightly.20241104.f4052012e0"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241104/forc-wallet-0.11.1%2Bnightly.20241104.f4052012e0-aarch64-apple-darwin.tar.gz"
hash = "57d3561f4ab71a3841bfff924adbbee4859d90cf1aa26966a2465bfb9582414f"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241104/forc-wallet-0.11.1%2Bnightly.20241104.f4052012e0-aarch64-unknown-linux-gnu.tar.gz"
hash = "117ee5bc67cd2941e1e59f0779044b4c959857fb6c052250b03affe9c2dfc4bf"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241104/forc-wallet-0.11.1%2Bnightly.20241104.f4052012e0-x86_64-apple-darwin.tar.gz"
hash = "d4460d8374724f8a4432a91d510634841ddc31ab9a97cfd1e6037d368e40b70e"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241104/forc-wallet-0.11.1%2Bnightly.20241104.f4052012e0-x86_64-unknown-linux-gnu.tar.gz"
hash = "8117e2a3f6fdc1a3df7e26cc32ff708188d1055bb1f75307b0e4d649e66e7b7c"

[pkg.fuel-core]
version = "0.40.0+nightly.20241104.676ca8f683"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241104/fuel-core-0.40.0%2Bnightly.20241104.676ca8f683-aarch64-apple-darwin.tar.gz"
hash = "ed25bb2fc7ab0b0bd9d368cb1b79e2848d51a7180dadfc334d1c027b72e79cbd"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241104/fuel-core-0.40.0%2Bnightly.20241104.676ca8f683-aarch64-unknown-linux-gnu.tar.gz"
hash = "c29e36c0f0438d0d2a73c7d94ff38762453373b9976fa0c497191e1df05cf8db"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241104/fuel-core-0.40.0%2Bnightly.20241104.676ca8f683-x86_64-unknown-linux-gnu.tar.gz"
hash = "f9d5ef93d1258647b3663e9e7ea371bcde2476e4c641b7499b8f008c6792c687"

[pkg.fuel-core-keygen]
version = "0.40.0+nightly.20241104.676ca8f683"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241104/fuel-core-0.40.0%2Bnightly.20241104.676ca8f683-aarch64-apple-darwin.tar.gz"
hash = "ed25bb2fc7ab0b0bd9d368cb1b79e2848d51a7180dadfc334d1c027b72e79cbd"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241104/fuel-core-0.40.0%2Bnightly.20241104.676ca8f683-aarch64-unknown-linux-gnu.tar.gz"
hash = "c29e36c0f0438d0d2a73c7d94ff38762453373b9976fa0c497191e1df05cf8db"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241104/fuel-core-0.40.0%2Bnightly.20241104.676ca8f683-x86_64-unknown-linux-gnu.tar.gz"
hash = "f9d5ef93d1258647b3663e9e7ea371bcde2476e4c641b7499b8f008c6792c687"
