published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15232860672"
date = "2025-05-25"

[pkg.forc]
version = "0.68.5+nightly.20250525.c8625a029c"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250525/forc-binaries-0.68.5%2Bnightly.20250525.c8625a029c-darwin_amd64.tar.gz"
hash = "80c5e79d76e268a4f0170860cf69945562ea279b1c8cf37438c4531d5273c45c"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250525/forc-binaries-0.68.5%2Bnightly.20250525.c8625a029c-darwin_arm64.tar.gz"
hash = "88f6ee19f6f2752d36482919b1aa92764e9126778199e466078e09928eb05b98"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250525/forc-binaries-0.68.5%2Bnightly.20250525.c8625a029c-linux_amd64.tar.gz"
hash = "4fb9a0c9eb11a2d3c497e005d96c08f57f4138b1486c9996f05a61995423e714"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250525/forc-binaries-0.68.5%2Bnightly.20250525.c8625a029c-linux_arm64.tar.gz"
hash = "b6ee982034f0d50c65f8bf19b9158d7ba7b56596e86eb6e5a0ed1bf9a4c074eb"

[pkg.forc-wallet]
version = "0.14.0+nightly.20250525.24883eb126"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250525/forc-wallet-0.14.0%2Bnightly.20250525.24883eb126-aarch64-apple-darwin.tar.gz"
hash = "aa7e56eeacaec8e98a1d1ab57911133a6c70db78ada20e38dd0982e27d185004"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250525/forc-wallet-0.14.0%2Bnightly.20250525.24883eb126-aarch64-unknown-linux-gnu.tar.gz"
hash = "9289b5fe6e840dbf763d49c18d122c663ba6431440582a51bc172204dd34fe1e"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250525/forc-wallet-0.14.0%2Bnightly.20250525.24883eb126-x86_64-apple-darwin.tar.gz"
hash = "d78e4f4cec9af5ece5368acac384e58e7a2ee594f2d15fc51e0f854f9dace863"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250525/forc-wallet-0.14.0%2Bnightly.20250525.24883eb126-x86_64-unknown-linux-gnu.tar.gz"
hash = "18550636e4db6d7a5c4359b468c2357b8065af86085341299908e2b527cb2c87"

[pkg.fuel-core]
version = "0.43.0+nightly.20250525.9165b82ca3"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250525/fuel-core-0.43.0%2Bnightly.20250525.9165b82ca3-aarch64-apple-darwin.tar.gz"
hash = "4fc2f8a11b0b455c79eae27327d3e9048096e5ee81d4957eb13f604cbb97130f"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250525/fuel-core-0.43.0%2Bnightly.20250525.9165b82ca3-aarch64-unknown-linux-gnu.tar.gz"
hash = "e415a810c9cdb1cf8be334c11c95e580221375e8a384fa502d37e59b195aecaa"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250525/fuel-core-0.43.0%2Bnightly.20250525.9165b82ca3-x86_64-unknown-linux-gnu.tar.gz"
hash = "b721a33f77331a641ee6ffad232ebd5c509a5d10ace2288f6810479a4614bf4f"

[pkg.fuel-core-keygen]
version = "0.43.0+nightly.20250525.9165b82ca3"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250525/fuel-core-0.43.0%2Bnightly.20250525.9165b82ca3-aarch64-apple-darwin.tar.gz"
hash = "4fc2f8a11b0b455c79eae27327d3e9048096e5ee81d4957eb13f604cbb97130f"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250525/fuel-core-0.43.0%2Bnightly.20250525.9165b82ca3-aarch64-unknown-linux-gnu.tar.gz"
hash = "e415a810c9cdb1cf8be334c11c95e580221375e8a384fa502d37e59b195aecaa"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250525/fuel-core-0.43.0%2Bnightly.20250525.9165b82ca3-x86_64-unknown-linux-gnu.tar.gz"
hash = "b721a33f77331a641ee6ffad232ebd5c509a5d10ace2288f6810479a4614bf4f"
