published_by = "https://github.com/FuelLabs/fuelup/actions/runs/13169922239"
date = "2025-02-06"

[pkg.forc]
version = "0.66.7+nightly.20250206.5ed7cec6db"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250206/forc-binaries-0.66.7%2Bnightly.20250206.5ed7cec6db-darwin_amd64.tar.gz"
hash = "125660ba677afeaeb5804cd451e0b98941173d55bc25b1df9a66fcc4b555fb5d"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250206/forc-binaries-0.66.7%2Bnightly.20250206.5ed7cec6db-darwin_arm64.tar.gz"
hash = "73cb576bd1884502aa857b8f59e099256bc3045c47a36bff1d87df395af969cf"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250206/forc-binaries-0.66.7%2Bnightly.20250206.5ed7cec6db-linux_amd64.tar.gz"
hash = "cbdbd906293a2521d32cb2994dd0a3412e89364b56cd4b1717ed8919f4d7dea2"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250206/forc-binaries-0.66.7%2Bnightly.20250206.5ed7cec6db-linux_arm64.tar.gz"
hash = "667ad2c33047d3beef248ca0a2a55e32ea1902b8fe9ff0b13ff97b10378b995f"

[pkg.forc-wallet]
version = "0.12.0+nightly.20250206.8d59dbc462"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250206/forc-wallet-0.12.0%2Bnightly.20250206.8d59dbc462-aarch64-apple-darwin.tar.gz"
hash = "cce5fdd1a47c92d2d28a4866dc83507422f1937797a4869791a10397adec8a3b"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250206/forc-wallet-0.12.0%2Bnightly.20250206.8d59dbc462-aarch64-unknown-linux-gnu.tar.gz"
hash = "a70d428accb4698fc2390ec520e0bbc46929b8d565382c7c7ec39d38f2ddf3d5"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250206/forc-wallet-0.12.0%2Bnightly.20250206.8d59dbc462-x86_64-apple-darwin.tar.gz"
hash = "77374f0cd9cab2158daa1ac528daef8c25067eba1423f1d01d68a5416c12162f"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250206/forc-wallet-0.12.0%2Bnightly.20250206.8d59dbc462-x86_64-unknown-linux-gnu.tar.gz"
hash = "c559e599d433dbbb7e61d964b6ee6c9a5af0bac7e1c531b422751ba3702a9063"

[pkg.fuel-core]
version = "0.41.6+nightly.20250206.4ff324b021"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250206/fuel-core-0.41.6%2Bnightly.20250206.4ff324b021-aarch64-apple-darwin.tar.gz"
hash = "8700a4ad0ba749922710b1c2eb99b6536ed7e5b37d85cc58facb1053734cbb3c"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250206/fuel-core-0.41.6%2Bnightly.20250206.4ff324b021-aarch64-unknown-linux-gnu.tar.gz"
hash = "f77f94216a9a7ae85a93d0ce5db0ed0de954634dfbb8d9ca7be55cf71c994fb8"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250206/fuel-core-0.41.6%2Bnightly.20250206.4ff324b021-x86_64-apple-darwin.tar.gz"
hash = "627cfa3c41ca5cff6d735076509c9efc41dc308921b55ea5ec599528c408e904"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250206/fuel-core-0.41.6%2Bnightly.20250206.4ff324b021-x86_64-unknown-linux-gnu.tar.gz"
hash = "be23aa3a73ad7617bf61180b4b54510fa8d8244df2bc7a331372480862fab16a"

[pkg.fuel-core-keygen]
version = "0.41.6+nightly.20250206.4ff324b021"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250206/fuel-core-0.41.6%2Bnightly.20250206.4ff324b021-aarch64-apple-darwin.tar.gz"
hash = "8700a4ad0ba749922710b1c2eb99b6536ed7e5b37d85cc58facb1053734cbb3c"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250206/fuel-core-0.41.6%2Bnightly.20250206.4ff324b021-aarch64-unknown-linux-gnu.tar.gz"
hash = "f77f94216a9a7ae85a93d0ce5db0ed0de954634dfbb8d9ca7be55cf71c994fb8"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250206/fuel-core-0.41.6%2Bnightly.20250206.4ff324b021-x86_64-apple-darwin.tar.gz"
hash = "627cfa3c41ca5cff6d735076509c9efc41dc308921b55ea5ec599528c408e904"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250206/fuel-core-0.41.6%2Bnightly.20250206.4ff324b021-x86_64-unknown-linux-gnu.tar.gz"
hash = "be23aa3a73ad7617bf61180b4b54510fa8d8244df2bc7a331372480862fab16a"
