published_by = "https://github.com/FuelLabs/fuelup/actions/runs/10294338541"
date = "2024-08-08"

[pkg.forc]
version = "0.62.0+nightly.20240808.2332025661"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240808/forc-binaries-0.62.0%2Bnightly.20240808.2332025661-darwin_amd64.tar.gz"
hash = "ab04156e81b22fb884734970f382111948d37cb020093631cd2740ee23600556"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240808/forc-binaries-0.62.0%2Bnightly.20240808.2332025661-darwin_arm64.tar.gz"
hash = "b7b0ac1d36478e96d8aab1a22a62ce9ec77c409309b884396b3db9bed6fdba9f"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240808/forc-binaries-0.62.0%2Bnightly.20240808.2332025661-linux_amd64.tar.gz"
hash = "5183c473c972b6ac11fab10c99c70109964e82a4edf4ddbd87982d4e8832e2df"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240808/forc-binaries-0.62.0%2Bnightly.20240808.2332025661-linux_arm64.tar.gz"
hash = "54edce22b3915c25d670d335c3c0b3cada9c30242a586a466dd733e17d1dc02d"

[pkg.forc-wallet]
version = "0.8.2+nightly.20240808.76e9796cbe"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240808/forc-wallet-0.8.2%2Bnightly.20240808.76e9796cbe-aarch64-apple-darwin.tar.gz"
hash = "f25e67d55e848a2c2141fd2969d2544acc77c5165274c30ae83f4ff06adad3b0"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240808/forc-wallet-0.8.2%2Bnightly.20240808.76e9796cbe-aarch64-unknown-linux-gnu.tar.gz"
hash = "c5ed4fb428f438ad3c52b624f7052dd001f03a86ad94cc4e8daf682f2811a2b9"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240808/forc-wallet-0.8.2%2Bnightly.20240808.76e9796cbe-x86_64-apple-darwin.tar.gz"
hash = "e318ff50f42936fb4a35b6c7f22427da6b2e23d8f922f09923f01ddf56d3016a"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240808/forc-wallet-0.8.2%2Bnightly.20240808.76e9796cbe-x86_64-unknown-linux-gnu.tar.gz"
hash = "3c0e34cc3ce7a47dfa76793e0ee561eb3ec7ea875c48803aa80809fa82924362"

[pkg.fuel-core]
version = "0.32.0+nightly.20240808.ecf5d23e86"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240808/fuel-core-0.32.0%2Bnightly.20240808.ecf5d23e86-aarch64-apple-darwin.tar.gz"
hash = "86000ff2931915d178cfdb9072f60f4b50cb88c1b7a95b9288dba60becd9f393"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240808/fuel-core-0.32.0%2Bnightly.20240808.ecf5d23e86-aarch64-unknown-linux-gnu.tar.gz"
hash = "02a52da93036fd87f8b7f74900406f133d6616a9877c0b02f3815aace87c6003"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240808/fuel-core-0.32.0%2Bnightly.20240808.ecf5d23e86-x86_64-apple-darwin.tar.gz"
hash = "2ba43ff6d7f472529a7eb09f531f7e82ed499c8fa30bbafb3f14811e0555dc64"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240808/fuel-core-0.32.0%2Bnightly.20240808.ecf5d23e86-x86_64-unknown-linux-gnu.tar.gz"
hash = "c89ccd5b5c95a6ee20c877bed263354c2056024baade5d40e406a4826b83b947"

[pkg.fuel-core-keygen]
version = "0.32.0+nightly.20240808.ecf5d23e86"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240808/fuel-core-0.32.0%2Bnightly.20240808.ecf5d23e86-aarch64-apple-darwin.tar.gz"
hash = "86000ff2931915d178cfdb9072f60f4b50cb88c1b7a95b9288dba60becd9f393"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240808/fuel-core-0.32.0%2Bnightly.20240808.ecf5d23e86-aarch64-unknown-linux-gnu.tar.gz"
hash = "02a52da93036fd87f8b7f74900406f133d6616a9877c0b02f3815aace87c6003"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240808/fuel-core-0.32.0%2Bnightly.20240808.ecf5d23e86-x86_64-apple-darwin.tar.gz"
hash = "2ba43ff6d7f472529a7eb09f531f7e82ed499c8fa30bbafb3f14811e0555dc64"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240808/fuel-core-0.32.0%2Bnightly.20240808.ecf5d23e86-x86_64-unknown-linux-gnu.tar.gz"
hash = "c89ccd5b5c95a6ee20c877bed263354c2056024baade5d40e406a4826b83b947"
