published_by = "https://github.com/FuelLabs/fuelup/actions/runs/12591266576"
date = "2025-01-03"

[pkg.forc]
version = "0.66.5+nightly.20250103.cf7b6664b5"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250103/forc-binaries-0.66.5%2Bnightly.20250103.cf7b6664b5-darwin_amd64.tar.gz"
hash = "e9ce2ca69ae4191e2750e64b20b624c7e44cfe0cd24039a2a8e0552d3505726c"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250103/forc-binaries-0.66.5%2Bnightly.20250103.cf7b6664b5-darwin_arm64.tar.gz"
hash = "604a03d6ef852d214ffa2dea21f377f0c3ba5748e5366440568c92797eb3d927"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250103/forc-binaries-0.66.5%2Bnightly.20250103.cf7b6664b5-linux_amd64.tar.gz"
hash = "9ed66a4d86f5a76ae9e1b47784f610c7e1775a148273743bdeb64104c2193ee4"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250103/forc-binaries-0.66.5%2Bnightly.20250103.cf7b6664b5-linux_arm64.tar.gz"
hash = "c410c981586669a707377d59b65c08a5348c942324c4c9a6fabb8ff34db42ec1"

[pkg.forc-wallet]
version = "0.11.1+nightly.20250103.f4052012e0"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250103/forc-wallet-0.11.1%2Bnightly.20250103.f4052012e0-aarch64-apple-darwin.tar.gz"
hash = "b934969e34f6891801526b6a798b852f3b3175a5577929af1755f81ef16047f2"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250103/forc-wallet-0.11.1%2Bnightly.20250103.f4052012e0-aarch64-unknown-linux-gnu.tar.gz"
hash = "ac4a6e9fe29fb2ad87e51386e37833354430f5fd20cc1b6a9e0dba6fa1e9f2b6"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250103/forc-wallet-0.11.1%2Bnightly.20250103.f4052012e0-x86_64-apple-darwin.tar.gz"
hash = "6d1c3bc9db2e0b27c2d7f337739aa0d4e30d794a7528253a8e3e94c8f1c17df7"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250103/forc-wallet-0.11.1%2Bnightly.20250103.f4052012e0-x86_64-unknown-linux-gnu.tar.gz"
hash = "a169de53fcf788998d1807962f5815ef2b73c17ee9e82566870775baf6c4c432"

[pkg.fuel-core]
version = "0.40.0+nightly.20250103.d84306f9a8"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250103/fuel-core-0.40.0%2Bnightly.20250103.d84306f9a8-aarch64-apple-darwin.tar.gz"
hash = "ddf50f8f23827f206452342f3a43abcc7ea201db5cd8a9815d9f159d412ca86e"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250103/fuel-core-0.40.0%2Bnightly.20250103.d84306f9a8-aarch64-unknown-linux-gnu.tar.gz"
hash = "3d4be2041a83272287cf254c9ab589c1bf2336eb0b4581038ac2f3621a56eea8"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250103/fuel-core-0.40.0%2Bnightly.20250103.d84306f9a8-x86_64-apple-darwin.tar.gz"
hash = "5fcb7319c96c1037b69ec6d33d383b2ecd1a9d969fc8526c898cd32c4f933bc7"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250103/fuel-core-0.40.0%2Bnightly.20250103.d84306f9a8-x86_64-unknown-linux-gnu.tar.gz"
hash = "2e78a02186dd13dc66dfbb50d8ccf1c6f386e723e76d92b2448bc139a25ae713"

[pkg.fuel-core-keygen]
version = "0.40.0+nightly.20250103.d84306f9a8"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250103/fuel-core-0.40.0%2Bnightly.20250103.d84306f9a8-aarch64-apple-darwin.tar.gz"
hash = "ddf50f8f23827f206452342f3a43abcc7ea201db5cd8a9815d9f159d412ca86e"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250103/fuel-core-0.40.0%2Bnightly.20250103.d84306f9a8-aarch64-unknown-linux-gnu.tar.gz"
hash = "3d4be2041a83272287cf254c9ab589c1bf2336eb0b4581038ac2f3621a56eea8"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250103/fuel-core-0.40.0%2Bnightly.20250103.d84306f9a8-x86_64-apple-darwin.tar.gz"
hash = "5fcb7319c96c1037b69ec6d33d383b2ecd1a9d969fc8526c898cd32c4f933bc7"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250103/fuel-core-0.40.0%2Bnightly.20250103.d84306f9a8-x86_64-unknown-linux-gnu.tar.gz"
hash = "2e78a02186dd13dc66dfbb50d8ccf1c6f386e723e76d92b2448bc139a25ae713"
