published_by = "https://github.com/FuelLabs/fuelup/actions/runs/19121798724"
date = "2025-11-06"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251106.279124d992"

[pkg.forc-wallet.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251106/forc-wallet-0.15.2%2Bnightly.20251106.279124d992-aarch64-apple-darwin.tar.gz"
hash = "082c4d373622f1d39e871870909b31bb0cca282ddf69b2261a68e27eb73b382a"

[pkg.forc-wallet.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251106/forc-wallet-0.15.2%2Bnightly.20251106.279124d992-aarch64-unknown-linux-gnu.tar.gz"
hash = "94e0627864e7766ef3834a5d3533b03a915a33d68d2780347eb6e461c2ba4057"

[pkg.forc-wallet.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251106/forc-wallet-0.15.2%2Bnightly.20251106.279124d992-x86_64-apple-darwin.tar.gz"
hash = "6110cb66275f449c13bbcf1de99c640908101c37eec33604b4304cd12229771e"

[pkg.forc-wallet.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251106/forc-wallet-0.15.2%2Bnightly.20251106.279124d992-x86_64-unknown-linux-gnu.tar.gz"
hash = "39697a75b16f0b207a9292a71d9eac6d7bc5ebb360c1e04f062f8966b136731a"
