published_by = "https://github.com/FuelLabs/fuelup/actions/runs/19655072120"
date = "2025-11-25"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251125.74d8ce58f0"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251125/forc-wallet-0.15.2%2Bnightly.20251125.74d8ce58f0-aarch64-apple-darwin.tar.gz"
hash = "132502b653de67a2d48537f7ef40abad508942680e5b09ea9a9755a86d5547b3"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251125/forc-wallet-0.15.2%2Bnightly.20251125.74d8ce58f0-aarch64-unknown-linux-gnu.tar.gz"
hash = "6c2d96eb0fbc3056338e1b5d4ef83e1220c8b29b04fe53c6d3dd57c0d812bf90"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251125/forc-wallet-0.15.2%2Bnightly.20251125.74d8ce58f0-x86_64-apple-darwin.tar.gz"
hash = "5e8b0a57c41b45f3dfdcaebbcd0807022e95e9d2604f86aeb9b1b76008d82647"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251125/forc-wallet-0.15.2%2Bnightly.20251125.74d8ce58f0-x86_64-unknown-linux-gnu.tar.gz"
hash = "254ce4b23f7221333aa34722ab8d268d3ef290b95c35e4c8c18991e8c9f6c815"
