published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15573891447"
date = "2025-06-11"

[pkg.forc]
version = "0.68.7+nightly.20250611.14dc752754"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250611/forc-binaries-0.68.7%2Bnightly.20250611.14dc752754-darwin_amd64.tar.gz"
hash = "41a84d63608f4ab89a3bef2c814175d29cb14cb151dded91970e16187c59ea66"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250611/forc-binaries-0.68.7%2Bnightly.20250611.14dc752754-darwin_arm64.tar.gz"
hash = "c40a85710c378b7717d76a69fb54537227d3062a3018e38663f5b9cba4455dd6"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250611/forc-binaries-0.68.7%2Bnightly.20250611.14dc752754-linux_amd64.tar.gz"
hash = "2e6677c636c7707a84ca13cf0c5b87d711fcc9d37b9848a63e9c4ba0ff203983"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250611/forc-binaries-0.68.7%2Bnightly.20250611.14dc752754-linux_arm64.tar.gz"
hash = "3df88da6fdc05bb89ea18bb900ea83566e145679087d73e4a1b4b57118696e39"

[pkg.forc-wallet]
version = "0.14.0+nightly.20250611.24883eb126"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250611/forc-wallet-0.14.0%2Bnightly.20250611.24883eb126-aarch64-apple-darwin.tar.gz"
hash = "2673699b20b40f90518401e921b56b5432713a7cfc698f5af0060ffd7cad23e8"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250611/forc-wallet-0.14.0%2Bnightly.20250611.24883eb126-aarch64-unknown-linux-gnu.tar.gz"
hash = "b617b249d6eceabe98b5f34bc6d1f488867842bfe681908ef9cd7655ed992b27"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250611/forc-wallet-0.14.0%2Bnightly.20250611.24883eb126-x86_64-apple-darwin.tar.gz"
hash = "4034ec6417d8c95ac5b40d46a6a9ae0e622fdadeef07f11fae89172651837b9e"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250611/forc-wallet-0.14.0%2Bnightly.20250611.24883eb126-x86_64-unknown-linux-gnu.tar.gz"
hash = "70db93aa3da2f4ec9be1eaca3d62047a5d7e392c1702ff478b5796ee9522cc3b"

[pkg.fuel-core]
version = "0.44.0+nightly.20250611.188211bb0e"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250611/fuel-core-0.44.0%2Bnightly.20250611.188211bb0e-aarch64-apple-darwin.tar.gz"
hash = "1febe92b64e691cd217e4b0ee3870cc159b7c4f9bdde6eec544f48b78ec9627d"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250611/fuel-core-0.44.0%2Bnightly.20250611.188211bb0e-aarch64-unknown-linux-gnu.tar.gz"
hash = "b5adcdd936ec2ed93e7031aea39aa2eda8c45486d360ff62bc376392b0dc5c29"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250611.188211bb0e"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250611/fuel-core-0.44.0%2Bnightly.20250611.188211bb0e-aarch64-apple-darwin.tar.gz"
hash = "1febe92b64e691cd217e4b0ee3870cc159b7c4f9bdde6eec544f48b78ec9627d"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250611/fuel-core-0.44.0%2Bnightly.20250611.188211bb0e-aarch64-unknown-linux-gnu.tar.gz"
hash = "b5adcdd936ec2ed93e7031aea39aa2eda8c45486d360ff62bc376392b0dc5c29"
