published_by = "https://github.com/FuelLabs/fuelup/actions/runs/18267414601"
date = "2025-10-06"

[pkg.forc-wallet]
version = "0.15.1+nightly.20251006.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251006/forc-wallet-0.15.1%2Bnightly.20251006.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "63f93e46a51119356c585a31edd1316bc75a5e786413d6f4a612ba0ab3c824c6"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251006/forc-wallet-0.15.1%2Bnightly.20251006.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "8f2a832fa20f4792dc6e247b236c01a7881d0ebcfe47a63d5a6bade9a5b4f82e"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251006/forc-wallet-0.15.1%2Bnightly.20251006.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "875c59935407cead38e482301e1dcaaa0f8fcffebd26502ecaef28f7152e3179"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251006/forc-wallet-0.15.1%2Bnightly.20251006.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "391ca2453d6edbe4965572b8774ff95f797f2bf48809b692259bcd3b0cea5077"
