published_by = "https://github.com/FuelLabs/fuelup/actions/runs/11451927480"
date = "2024-10-22"

[pkg.forc]
version = "0.66.2+nightly.20241022.79170dbecb"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241022/forc-binaries-0.66.2%2Bnightly.20241022.79170dbecb-darwin_amd64.tar.gz"
hash = "ddf6be89838c5ee3f367f4054f80078f890af43e32a670edabbd46dce708cc82"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241022/forc-binaries-0.66.2%2Bnightly.20241022.79170dbecb-darwin_arm64.tar.gz"
hash = "d0d7c99af173a015a102850c15d07ce5e5abbd0ff83e7cd5d75c5252c0da6bef"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241022/forc-binaries-0.66.2%2Bnightly.20241022.79170dbecb-linux_amd64.tar.gz"
hash = "e851f8bc19618493192fa7daa2fceaf606239127f6804fae4ea35c0314e7ee70"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241022/forc-binaries-0.66.2%2Bnightly.20241022.79170dbecb-linux_arm64.tar.gz"
hash = "baf85cb330a05ea934bf938c83a3a4fcb57644339846f7e0d8d0e4ac643edb04"

[pkg.forc-wallet]
version = "0.11.0+nightly.20241022.152bfb48c3"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241022/forc-wallet-0.11.0%2Bnightly.20241022.152bfb48c3-aarch64-apple-darwin.tar.gz"
hash = "dec2614dd60ddbdc9c25a2c53798d76d369c2393e5f7b4c5bdb3d16f1b757f21"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241022/forc-wallet-0.11.0%2Bnightly.20241022.152bfb48c3-aarch64-unknown-linux-gnu.tar.gz"
hash = "dbe1c7c6ba790ecba42c94d04dd5a924752af6f6ce3d86ca855965b068a12773"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241022/forc-wallet-0.11.0%2Bnightly.20241022.152bfb48c3-x86_64-apple-darwin.tar.gz"
hash = "404cbe3b133d5848382102e1f255aaa7d32baab0c337d0b7fe13478612380c3a"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241022/forc-wallet-0.11.0%2Bnightly.20241022.152bfb48c3-x86_64-unknown-linux-gnu.tar.gz"
hash = "d4416e53e5d66fcd39c8b142770d134ba6792103ab2200d548ed05b0e4d9a686"

[pkg.fuel-core]
version = "0.40.0+nightly.20241022.eea8c60525"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241022/fuel-core-0.40.0%2Bnightly.20241022.eea8c60525-aarch64-apple-darwin.tar.gz"
hash = "4b25cd76f8758d05a092b306660c21e3fc7a6fa1e068f3ff1039ec44207cfdb1"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241022/fuel-core-0.40.0%2Bnightly.20241022.eea8c60525-aarch64-unknown-linux-gnu.tar.gz"
hash = "ff77ce96243425383cc05c87dd206cb6fc5092d8c0cb2dad89f69a6d97a2415e"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241022/fuel-core-0.40.0%2Bnightly.20241022.eea8c60525-x86_64-unknown-linux-gnu.tar.gz"
hash = "397790614273d0aad0d6e1b715ea8979413863d68a2820629cf12b8dbe27cf68"

[pkg.fuel-core-keygen]
version = "0.40.0+nightly.20241022.eea8c60525"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241022/fuel-core-0.40.0%2Bnightly.20241022.eea8c60525-aarch64-apple-darwin.tar.gz"
hash = "4b25cd76f8758d05a092b306660c21e3fc7a6fa1e068f3ff1039ec44207cfdb1"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241022/fuel-core-0.40.0%2Bnightly.20241022.eea8c60525-aarch64-unknown-linux-gnu.tar.gz"
hash = "ff77ce96243425383cc05c87dd206cb6fc5092d8c0cb2dad89f69a6d97a2415e"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241022/fuel-core-0.40.0%2Bnightly.20241022.eea8c60525-x86_64-unknown-linux-gnu.tar.gz"
hash = "397790614273d0aad0d6e1b715ea8979413863d68a2820629cf12b8dbe27cf68"
