published_by = "https://github.com/FuelLabs/fuelup/actions/runs/14698308328"
date = "2025-04-28"

[pkg.forc]
version = "0.68.1+nightly.20250428.eb57cbf284"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250428/forc-binaries-0.68.1%2Bnightly.20250428.eb57cbf284-darwin_amd64.tar.gz"
hash = "795eeb3893b16359379d29244a18f163cdaafc5f6d67f482070acb46ea8a3432"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250428/forc-binaries-0.68.1%2Bnightly.20250428.eb57cbf284-darwin_arm64.tar.gz"
hash = "5c9c223b1781ba6a01edbd1a5878099564d59684b817b7fcd16a6b5e773a3f31"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250428/forc-binaries-0.68.1%2Bnightly.20250428.eb57cbf284-linux_amd64.tar.gz"
hash = "74f04f99473b484d75835ff1de6dcdfb66320ef5ad806a29d7ede20821c6c30c"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250428/forc-binaries-0.68.1%2Bnightly.20250428.eb57cbf284-linux_arm64.tar.gz"
hash = "80a80cc34d99302cee8c8f3d8fb4432350dd5408c82658c50cef41c5a71170c6"

[pkg.forc-wallet]
version = "0.14.0+nightly.20250428.9015e09f45"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250428/forc-wallet-0.14.0%2Bnightly.20250428.9015e09f45-aarch64-apple-darwin.tar.gz"
hash = "1a4a85b1a2369d60e7f0520ba3c65b17fe04a044ee6a340f125e57b07d00e1e8"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250428/forc-wallet-0.14.0%2Bnightly.20250428.9015e09f45-aarch64-unknown-linux-gnu.tar.gz"
hash = "8636bbc87520bee24093e1f6251b45757b0511dce8642a1320aa90cdc297c838"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250428/forc-wallet-0.14.0%2Bnightly.20250428.9015e09f45-x86_64-apple-darwin.tar.gz"
hash = "6b2075fd0dc5d4b741a3e31eadb17da7f0b6870a40cc5b3c6f5e9d897650df4d"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250428/forc-wallet-0.14.0%2Bnightly.20250428.9015e09f45-x86_64-unknown-linux-gnu.tar.gz"
hash = "e260522b70d5812a8ea2826b45099c6bc1e129a2d2bed3d87798cc59e07bf7ab"

[pkg.fuel-core]
version = "0.43.0+nightly.20250428.47b84ca7f6"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250428/fuel-core-0.43.0%2Bnightly.20250428.47b84ca7f6-aarch64-apple-darwin.tar.gz"
hash = "11ac93f3e887a4d2934270738894dac60f733e48b94045f6a086932071da339f"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250428/fuel-core-0.43.0%2Bnightly.20250428.47b84ca7f6-aarch64-unknown-linux-gnu.tar.gz"
hash = "a8e7afc386f30b125769c3692c4b0f8e784bf2aacea56caa3e9ae458728f072f"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250428/fuel-core-0.43.0%2Bnightly.20250428.47b84ca7f6-x86_64-unknown-linux-gnu.tar.gz"
hash = "39d4663c24a9cec0d541f2937810f69bc6f9f257b4117f806fe0d7aba259d005"

[pkg.fuel-core-keygen]
version = "0.43.0+nightly.20250428.47b84ca7f6"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250428/fuel-core-0.43.0%2Bnightly.20250428.47b84ca7f6-aarch64-apple-darwin.tar.gz"
hash = "11ac93f3e887a4d2934270738894dac60f733e48b94045f6a086932071da339f"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250428/fuel-core-0.43.0%2Bnightly.20250428.47b84ca7f6-aarch64-unknown-linux-gnu.tar.gz"
hash = "a8e7afc386f30b125769c3692c4b0f8e784bf2aacea56caa3e9ae458728f072f"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250428/fuel-core-0.43.0%2Bnightly.20250428.47b84ca7f6-x86_64-unknown-linux-gnu.tar.gz"
hash = "39d4663c24a9cec0d541f2937810f69bc6f9f257b4117f806fe0d7aba259d005"
