published_by = "https://github.com/FuelLabs/fuelup/actions/runs/22082784077"
date = "2026-02-17"

[pkg.forc]
version = "0.70.1+nightly.20260217.0d8fbc8cef"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-binaries-0.70.1%2Bnightly.20260217.0d8fbc8cef-darwin_amd64.tar.gz"
hash = "369d6105e240b71464d46588a6a037db3bf82d78a303a9cde24bf017f6f18b43"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-binaries-0.70.1%2Bnightly.20260217.0d8fbc8cef-darwin_arm64.tar.gz"
hash = "48e48be1d641c0bfc4ea4c598c5997eabffae1243b7a764b7906b6403f4aab8a"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-binaries-0.70.1%2Bnightly.20260217.0d8fbc8cef-linux_amd64.tar.gz"
hash = "e16fd6340e162bbdb175a0ce7df5bb0207969d657f8a5f51db57b9bffabe7dc0"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-binaries-0.70.1%2Bnightly.20260217.0d8fbc8cef-linux_arm64.tar.gz"
hash = "aed3d9e597230ac8bb7e4a5c3162774022c6f0c125378f54543f210af3a8ff23"

[pkg.forc-client]
version = "0.71.1+nightly.20260217.063e4c5c49"

[pkg.forc-client.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-client-0.71.1%2Bnightly.20260217.063e4c5c49-darwin_amd64.tar.gz"
hash = "bfbe01cf1e202fb256a36d661773860a7ef17aaf0d25b510537c866359e9f5db"

[pkg.forc-client.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-client-0.71.1%2Bnightly.20260217.063e4c5c49-darwin_arm64.tar.gz"
hash = "8b533760f3f272a318cc49f0e1cbc0f9ef9cf6beea67ee63fb5f52ecd8558d70"

[pkg.forc-client.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-client-0.71.1%2Bnightly.20260217.063e4c5c49-linux_amd64.tar.gz"
hash = "9fd860a2e3531b5cf098f52bcc0bf3e4776d74819290f98b96991c3c38f31075"

[pkg.forc-client.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-client-0.71.1%2Bnightly.20260217.063e4c5c49-linux_arm64.tar.gz"
hash = "38c7c15c6c287da0872ffce1adf848be2aed4257c4c5f67095b89b9bdc7be5a4"

[pkg.forc-crypto]
version = "0.71.0+nightly.20260217.063e4c5c49"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-crypto-0.71.0%2Bnightly.20260217.063e4c5c49-darwin_amd64.tar.gz"
hash = "be8b0abcdac54abc2bc94f4649f85c9952f2c74ed38e7ffaeabb53a807cc4a26"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-crypto-0.71.0%2Bnightly.20260217.063e4c5c49-darwin_arm64.tar.gz"
hash = "8293318b833522f9a5a1798d9b810ddc4eced394cc2140461feb1c813e7cb065"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-crypto-0.71.0%2Bnightly.20260217.063e4c5c49-linux_amd64.tar.gz"
hash = "fbf5692b709f991d9ff1fbae638e3c893bd66b93530d60a86284beef872aa962"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-crypto-0.71.0%2Bnightly.20260217.063e4c5c49-linux_arm64.tar.gz"
hash = "a639d29f48bd47cc865f8ad7ee4b2128965d6e33698b43b5124f36c3c0c75291"

[pkg.forc-node]
version = "0.71.2+nightly.20260217.063e4c5c49"

[pkg.forc-node.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-node-0.71.2%2Bnightly.20260217.063e4c5c49-darwin_amd64.tar.gz"
hash = "83a0be02b18cb94320f5d8ace7485ab7ba59b5adaa0655696c65c8f066dcb09f"

[pkg.forc-node.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-node-0.71.2%2Bnightly.20260217.063e4c5c49-darwin_arm64.tar.gz"
hash = "9dc349f61b4fec7d6c593120dadadc185f93e1cb6be1c92ea30b443fec51c02c"

[pkg.forc-node.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-node-0.71.2%2Bnightly.20260217.063e4c5c49-linux_amd64.tar.gz"
hash = "6b4e9008ffdb15c9c62bc60d712e451387d48b46364532be2be9d30022165fff"

[pkg.forc-node.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-node-0.71.2%2Bnightly.20260217.063e4c5c49-linux_arm64.tar.gz"
hash = "f9112e1eb80cc71c8c8ccdefd4b9cc32edf231b572c9a0644d1ad71c6e01cd63"

[pkg.forc-wallet]
version = "0.16.2+nightly.20260217.063e4c5c49"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-wallet-0.16.2%2Bnightly.20260217.063e4c5c49-darwin_amd64.tar.gz"
hash = "74b1d906284b8bb8ea6636dbde97c42f5f47fc30e522cdd0b31f43a5a0bfe3bf"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-wallet-0.16.2%2Bnightly.20260217.063e4c5c49-darwin_arm64.tar.gz"
hash = "8e8d0676d728204e8b88cac390b5517fc80709b2cb57c4a1f33359c95e571f07"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-wallet-0.16.2%2Bnightly.20260217.063e4c5c49-linux_amd64.tar.gz"
hash = "3e58b8367038194c90e0f2584fc51bd67021f967252ca6a79b020a82fedab2e2"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/forc-wallet-0.16.2%2Bnightly.20260217.063e4c5c49-linux_arm64.tar.gz"
hash = "0f2a1490618fe6b87a98c917549c933360739b5d7b088fa16369163fbf446632"

[pkg.fuel-core]
version = "0.47.1+nightly.20260217.697e692a08"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/fuel-core-0.47.1%2Bnightly.20260217.697e692a08-aarch64-apple-darwin.tar.gz"
hash = "cd1f35cd298b07398cdae6741b14d4abda2add2e677d348ed3640b17c6da18fc"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/fuel-core-0.47.1%2Bnightly.20260217.697e692a08-aarch64-unknown-linux-gnu.tar.gz"
hash = "6f79839f8368ee3f3cc10c8f03ffe8eb307e59724e2575b006daf0889a2c1f59"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/fuel-core-0.47.1%2Bnightly.20260217.697e692a08-x86_64-apple-darwin.tar.gz"
hash = "3cc48b6b33225c3413da3cf3c90b575f3d7cbc9f836b189c5f5dde14ac71c0a5"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/fuel-core-0.47.1%2Bnightly.20260217.697e692a08-x86_64-unknown-linux-gnu.tar.gz"
hash = "cf7062937e744e99210c19440ab15dcb66713d66c57e67b671ad8f56e1a65fbe"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20260217.697e692a08"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/fuel-core-0.47.1%2Bnightly.20260217.697e692a08-aarch64-apple-darwin.tar.gz"
hash = "cd1f35cd298b07398cdae6741b14d4abda2add2e677d348ed3640b17c6da18fc"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/fuel-core-0.47.1%2Bnightly.20260217.697e692a08-aarch64-unknown-linux-gnu.tar.gz"
hash = "6f79839f8368ee3f3cc10c8f03ffe8eb307e59724e2575b006daf0889a2c1f59"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/fuel-core-0.47.1%2Bnightly.20260217.697e692a08-x86_64-apple-darwin.tar.gz"
hash = "3cc48b6b33225c3413da3cf3c90b575f3d7cbc9f836b189c5f5dde14ac71c0a5"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260217/fuel-core-0.47.1%2Bnightly.20260217.697e692a08-x86_64-unknown-linux-gnu.tar.gz"
hash = "cf7062937e744e99210c19440ab15dcb66713d66c57e67b671ad8f56e1a65fbe"
