published_by = "https://github.com/FuelLabs/fuelup/actions/runs/19556875968"
date = "2025-11-21"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251121.74d8ce58f0"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251121/forc-wallet-0.15.2%2Bnightly.20251121.74d8ce58f0-aarch64-apple-darwin.tar.gz"
hash = "7a41b7140aa767d1384388b2ef5fafac4a32f6d87ce8b9c36a3a3569123d7d06"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251121/forc-wallet-0.15.2%2Bnightly.20251121.74d8ce58f0-aarch64-unknown-linux-gnu.tar.gz"
hash = "a94b206b88b2b5d8edc3dceab5d83600ba77a1cbdab29050031fecc72670f29e"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251121/forc-wallet-0.15.2%2Bnightly.20251121.74d8ce58f0-x86_64-apple-darwin.tar.gz"
hash = "2b9cb193239e846739b60ee2d196884dec3f0b1029dd9575adc8d2b2cd04034d"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251121/forc-wallet-0.15.2%2Bnightly.20251121.74d8ce58f0-x86_64-unknown-linux-gnu.tar.gz"
hash = "dde41268a98801420efcb655b0c1b5fb01dd0a855db905d031647e9f7cba7038"
