published_by = "https://github.com/FuelLabs/fuelup/actions/runs/14506029919"
date = "2025-04-17"

[pkg.forc]
version = "0.67.0+nightly.20250417.8c2af95cc3"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250417/forc-binaries-0.67.0%2Bnightly.20250417.8c2af95cc3-darwin_amd64.tar.gz"
hash = "63c886e4d82db881ef4c418564b95305cd9b9c233f8c335f71c634587e4b50e8"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250417/forc-binaries-0.67.0%2Bnightly.20250417.8c2af95cc3-darwin_arm64.tar.gz"
hash = "c66ab375cbc06200afcf988073b719bbc509bb5d5241de0c22c160203be276f2"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250417/forc-binaries-0.67.0%2Bnightly.20250417.8c2af95cc3-linux_amd64.tar.gz"
hash = "36cd38d749a3353deb21ad0a4ef413168316c0cd9a7c3b92df12cf4135d17149"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250417/forc-binaries-0.67.0%2Bnightly.20250417.8c2af95cc3-linux_arm64.tar.gz"
hash = "b43a2e56189aa13ca44ec926f5b6b733c773538dbac92d32f277636ad0454db6"

[pkg.forc-wallet]
version = "0.13.0+nightly.20250417.90a8cb2dc4"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250417/forc-wallet-0.13.0%2Bnightly.20250417.90a8cb2dc4-aarch64-apple-darwin.tar.gz"
hash = "efd6f076edfcabbb09de91ba5682b38956ca96f8d3055bd8964f4c8e61ebabb5"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250417/forc-wallet-0.13.0%2Bnightly.20250417.90a8cb2dc4-aarch64-unknown-linux-gnu.tar.gz"
hash = "0b5ed3eff4e2beaffdc03c8b284608aac472089a307cfca57fa6c29bfb762bda"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250417/forc-wallet-0.13.0%2Bnightly.20250417.90a8cb2dc4-x86_64-apple-darwin.tar.gz"
hash = "8cb216c5a7a52d28d1dfe5f78e961babdc18f2fb854d02a13b0723a1d486fb0e"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250417/forc-wallet-0.13.0%2Bnightly.20250417.90a8cb2dc4-x86_64-unknown-linux-gnu.tar.gz"
hash = "5835214c49ae4e8c8109c508daf1466f5d35f86632a421cebfa0ae2577d3121e"

[pkg.fuel-core]
version = "0.43.0+nightly.20250417.b5d72dd7e5"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250417/fuel-core-0.43.0%2Bnightly.20250417.b5d72dd7e5-aarch64-apple-darwin.tar.gz"
hash = "9e333cdd0836f317edafba529a66ec32c117e740123c325bcba7d0247fff78bb"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250417/fuel-core-0.43.0%2Bnightly.20250417.b5d72dd7e5-aarch64-unknown-linux-gnu.tar.gz"
hash = "a06c6fc3009919d2c480c4bfa9b5a70b6dbfaf460a498f25652525b7f5fd09b3"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250417/fuel-core-0.43.0%2Bnightly.20250417.b5d72dd7e5-x86_64-unknown-linux-gnu.tar.gz"
hash = "f9a93270dc1d9442af53023fcd6ee756908394c67ad7e504a41bf66b63df4d88"

[pkg.fuel-core-keygen]
version = "0.43.0+nightly.20250417.b5d72dd7e5"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250417/fuel-core-0.43.0%2Bnightly.20250417.b5d72dd7e5-aarch64-apple-darwin.tar.gz"
hash = "9e333cdd0836f317edafba529a66ec32c117e740123c325bcba7d0247fff78bb"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250417/fuel-core-0.43.0%2Bnightly.20250417.b5d72dd7e5-aarch64-unknown-linux-gnu.tar.gz"
hash = "a06c6fc3009919d2c480c4bfa9b5a70b6dbfaf460a498f25652525b7f5fd09b3"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250417/fuel-core-0.43.0%2Bnightly.20250417.b5d72dd7e5-x86_64-unknown-linux-gnu.tar.gz"
hash = "f9a93270dc1d9442af53023fcd6ee756908394c67ad7e504a41bf66b63df4d88"
