published_by = "https://github.com/FuelLabs/fuelup/actions/runs/12554087979"
date = "2024-12-31"

[pkg.forc]
version = "0.66.5+nightly.20241231.cf7b6664b5"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241231/forc-binaries-0.66.5%2Bnightly.20241231.cf7b6664b5-darwin_amd64.tar.gz"
hash = "4ffba838a5be5d9a662400c12c0ea5b44d6bdd3d6d542e95b7e45b93ab879493"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241231/forc-binaries-0.66.5%2Bnightly.20241231.cf7b6664b5-darwin_arm64.tar.gz"
hash = "31e0c7411745b3f7ba39ba583907a7eb045a34a5e26e07563d3552e08c9074e7"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241231/forc-binaries-0.66.5%2Bnightly.20241231.cf7b6664b5-linux_amd64.tar.gz"
hash = "aaa989f0bc31e4276ccc0787679a250eab938a75dca95307eda22953ef3d2416"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241231/forc-binaries-0.66.5%2Bnightly.20241231.cf7b6664b5-linux_arm64.tar.gz"
hash = "a77c93e4f72fc4a7a75eec2325da7c3c831191d6817ec064cff46428f8e8283b"

[pkg.forc-wallet]
version = "0.11.1+nightly.20241231.f4052012e0"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241231/forc-wallet-0.11.1%2Bnightly.20241231.f4052012e0-aarch64-apple-darwin.tar.gz"
hash = "3362ecd7037910a25bafa74c6ac107d9a3dfbd59d062c1d11d248c7494896640"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241231/forc-wallet-0.11.1%2Bnightly.20241231.f4052012e0-aarch64-unknown-linux-gnu.tar.gz"
hash = "ea91380432ed9fb421fef9c59892aafe73a4a36c03770182b3e8edf2b7ba4c32"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241231/forc-wallet-0.11.1%2Bnightly.20241231.f4052012e0-x86_64-apple-darwin.tar.gz"
hash = "c31277e70c97939e387d79084ac059a9c832d3230dfc7a9b017c91b17b447b0a"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241231/forc-wallet-0.11.1%2Bnightly.20241231.f4052012e0-x86_64-unknown-linux-gnu.tar.gz"
hash = "2629593954b95e127aaf7fb76e0862f9bc9a3e5d13cc5bf4587a49e01ba7ec00"

[pkg.fuel-core]
version = "0.40.0+nightly.20241231.df0283c2fc"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241231/fuel-core-0.40.0%2Bnightly.20241231.df0283c2fc-aarch64-apple-darwin.tar.gz"
hash = "ff941b5bf1ba01289820808f76a2966edc2ec2e6ecd407c26e1903228680b7fc"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241231/fuel-core-0.40.0%2Bnightly.20241231.df0283c2fc-aarch64-unknown-linux-gnu.tar.gz"
hash = "facd78ca27a30493b6e32a457cd50e216faf92859d28b79350bd55211c0b591d"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241231/fuel-core-0.40.0%2Bnightly.20241231.df0283c2fc-x86_64-apple-darwin.tar.gz"
hash = "8171ee11f1f070b144f70c1f7328c530c824fea1c56e81557541f6bbceca5d1f"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241231/fuel-core-0.40.0%2Bnightly.20241231.df0283c2fc-x86_64-unknown-linux-gnu.tar.gz"
hash = "afeb63ae88ed7c897c116f51767bdd45c3a7c9482c5d737c79c9b7595231382f"

[pkg.fuel-core-keygen]
version = "0.40.0+nightly.20241231.df0283c2fc"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241231/fuel-core-0.40.0%2Bnightly.20241231.df0283c2fc-aarch64-apple-darwin.tar.gz"
hash = "ff941b5bf1ba01289820808f76a2966edc2ec2e6ecd407c26e1903228680b7fc"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241231/fuel-core-0.40.0%2Bnightly.20241231.df0283c2fc-aarch64-unknown-linux-gnu.tar.gz"
hash = "facd78ca27a30493b6e32a457cd50e216faf92859d28b79350bd55211c0b591d"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241231/fuel-core-0.40.0%2Bnightly.20241231.df0283c2fc-x86_64-apple-darwin.tar.gz"
hash = "8171ee11f1f070b144f70c1f7328c530c824fea1c56e81557541f6bbceca5d1f"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241231/fuel-core-0.40.0%2Bnightly.20241231.df0283c2fc-x86_64-unknown-linux-gnu.tar.gz"
hash = "afeb63ae88ed7c897c116f51767bdd45c3a7c9482c5d737c79c9b7595231382f"
