published_by = "https://github.com/FuelLabs/fuelup/actions/runs/17350884323"
date = "2025-08-31"

[pkg.forc]
version = "0.69.1+nightly.20250831.0aef56aa59"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250831/forc-binaries-0.69.1%2Bnightly.20250831.0aef56aa59-darwin_amd64.tar.gz"
hash = "6cf03aef8af9292bc39a25fd48c49d1febbdcdf729e7c013ac1c09b939a6f33a"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250831/forc-binaries-0.69.1%2Bnightly.20250831.0aef56aa59-darwin_arm64.tar.gz"
hash = "160279bc3de955c625c75374d115a698b3ce5daff0454204a06385a1780c19fa"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250831/forc-binaries-0.69.1%2Bnightly.20250831.0aef56aa59-linux_amd64.tar.gz"
hash = "0a83410f14c9a3b57c00f959794a879e79bcd13859bf4eab9ba24fcf818e4506"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250831/forc-binaries-0.69.1%2Bnightly.20250831.0aef56aa59-linux_arm64.tar.gz"
hash = "2fe618d16b91ce62bddfd7800dbe6861a4bc65299950e8d008dadbaa962fa18d"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250831.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250831/forc-wallet-0.15.1%2Bnightly.20250831.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "3bddb2e7e576bcb0410c13a24094b34766069416c391f222167d89d351b7fd40"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250831/forc-wallet-0.15.1%2Bnightly.20250831.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "0af2af05e929577437c919dc70497b52e09113bf18eaee4263cc945bb463c5ac"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250831/forc-wallet-0.15.1%2Bnightly.20250831.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "b8759106dae404fe305531a51ac164973b6a877d5ec54db56912dd28c9efffeb"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250831/forc-wallet-0.15.1%2Bnightly.20250831.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "79d0e7f1773d124cf48c0719863027f8afd4c7aae03c945936afd6855bf73576"

[pkg.fuel-core]
version = "0.46.0+nightly.20250831.33238c6e10"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250831/fuel-core-0.46.0%2Bnightly.20250831.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "3df9a52039ca9657d300a45f495ab9e8fc37617da14b0b11a4ab91619582e0b0"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250831/fuel-core-0.46.0%2Bnightly.20250831.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "dbc49441454f67231a871ba790309e96a53e3e274bc3c299d631de39de0152aa"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250831/fuel-core-0.46.0%2Bnightly.20250831.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "43cdc1c0a1af1e06370f634a4377df65a6993ad623a78e6ea24b1624a2edbcd0"

[pkg.fuel-core-keygen]
version = "0.46.0+nightly.20250831.33238c6e10"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250831/fuel-core-0.46.0%2Bnightly.20250831.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "3df9a52039ca9657d300a45f495ab9e8fc37617da14b0b11a4ab91619582e0b0"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250831/fuel-core-0.46.0%2Bnightly.20250831.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "dbc49441454f67231a871ba790309e96a53e3e274bc3c299d631de39de0152aa"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250831/fuel-core-0.46.0%2Bnightly.20250831.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "43cdc1c0a1af1e06370f634a4377df65a6993ad623a78e6ea24b1624a2edbcd0"
