published_by = "https://github.com/FuelLabs/fuelup/actions/runs/14827289564"
date = "2025-05-05"

[pkg.forc]
version = "0.68.2+nightly.20250505.324f04fbab"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250505/forc-binaries-0.68.2%2Bnightly.20250505.324f04fbab-darwin_amd64.tar.gz"
hash = "c4579c6b1bdfee4e5780939c89283ed3c850a7f10699efeb96feb489c8447650"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250505/forc-binaries-0.68.2%2Bnightly.20250505.324f04fbab-darwin_arm64.tar.gz"
hash = "4760455c43dfbf6716fa5aa7f669730c45ea69fdfc9eba16ccb585ede974bccc"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250505/forc-binaries-0.68.2%2Bnightly.20250505.324f04fbab-linux_amd64.tar.gz"
hash = "ae1bcbf018cc0bb3009e231c434a02fef90f51da7f502bad9818509283a5c5d1"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250505/forc-binaries-0.68.2%2Bnightly.20250505.324f04fbab-linux_arm64.tar.gz"
hash = "325505a92d63570228916459f1ee2963c7cd7b80caa2e759d24e93ee1bdd34f3"

[pkg.forc-wallet]
version = "0.14.0+nightly.20250505.24883eb126"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250505/forc-wallet-0.14.0%2Bnightly.20250505.24883eb126-aarch64-apple-darwin.tar.gz"
hash = "dabd2abbe983ed3ca132e9f70fe2ea67dc13443c7a739a32d91500c415fa3e77"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250505/forc-wallet-0.14.0%2Bnightly.20250505.24883eb126-aarch64-unknown-linux-gnu.tar.gz"
hash = "130eca15453597465af7e428bb07b65b460ea8eb3c3110882ed36e5e78161099"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250505/forc-wallet-0.14.0%2Bnightly.20250505.24883eb126-x86_64-apple-darwin.tar.gz"
hash = "0cc67363b6e004266a724cd31cff76f643fdaeb54af23c39bef47ad5777ba0fd"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250505/forc-wallet-0.14.0%2Bnightly.20250505.24883eb126-x86_64-unknown-linux-gnu.tar.gz"
hash = "fe45ac4aa8b189708d9dd815fcb0e5a85034b415d834a1d03dd71d5eca9e6d48"

[pkg.fuel-core]
version = "0.43.0+nightly.20250505.6403b73c5b"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250505/fuel-core-0.43.0%2Bnightly.20250505.6403b73c5b-aarch64-apple-darwin.tar.gz"
hash = "313d6f881ea56c52da3c504eef8d3bde8cede32e5acc749be174e5bc90ec8bbc"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250505/fuel-core-0.43.0%2Bnightly.20250505.6403b73c5b-aarch64-unknown-linux-gnu.tar.gz"
hash = "28ce1512375ffa6bdccd63ac46636c8cf1af4bdd726e4fae159a84c4a0f88473"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250505/fuel-core-0.43.0%2Bnightly.20250505.6403b73c5b-x86_64-unknown-linux-gnu.tar.gz"
hash = "0fba0a629a874a4b665045628e734bd6f8e0c2b346d68abc2f93768554a5ea17"

[pkg.fuel-core-keygen]
version = "0.43.0+nightly.20250505.6403b73c5b"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250505/fuel-core-0.43.0%2Bnightly.20250505.6403b73c5b-aarch64-apple-darwin.tar.gz"
hash = "313d6f881ea56c52da3c504eef8d3bde8cede32e5acc749be174e5bc90ec8bbc"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250505/fuel-core-0.43.0%2Bnightly.20250505.6403b73c5b-aarch64-unknown-linux-gnu.tar.gz"
hash = "28ce1512375ffa6bdccd63ac46636c8cf1af4bdd726e4fae159a84c4a0f88473"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250505/fuel-core-0.43.0%2Bnightly.20250505.6403b73c5b-x86_64-unknown-linux-gnu.tar.gz"
hash = "0fba0a629a874a4b665045628e734bd6f8e0c2b346d68abc2f93768554a5ea17"
