published_by = "https://github.com/FuelLabs/fuelup/actions/runs/14919435012"
date = "2025-05-09"

[pkg.forc]
version = "0.68.2+nightly.20250509.bd3813606a"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250509/forc-binaries-0.68.2%2Bnightly.20250509.bd3813606a-darwin_amd64.tar.gz"
hash = "ef8c2c9102274b426af17b65bf3965257217d88fca7beca57daade7ba2419e14"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250509/forc-binaries-0.68.2%2Bnightly.20250509.bd3813606a-darwin_arm64.tar.gz"
hash = "4d5f87bd50187b3069424a176ee613c2c0cc09138812e9af3750d34aa73b329e"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250509/forc-binaries-0.68.2%2Bnightly.20250509.bd3813606a-linux_amd64.tar.gz"
hash = "085ef7db922bf4f3c4c5aeb5028266786c074a6ea0c75a2de9d4e4569ad61349"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250509/forc-binaries-0.68.2%2Bnightly.20250509.bd3813606a-linux_arm64.tar.gz"
hash = "3c293bf0e381b4400dff69ed389d4b39204dc237f01c900d90d95d5b6340c2f8"

[pkg.forc-wallet]
version = "0.14.0+nightly.20250509.24883eb126"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250509/forc-wallet-0.14.0%2Bnightly.20250509.24883eb126-aarch64-apple-darwin.tar.gz"
hash = "b3e2f25be029ae50278f658c415f40a2a5fbd5090bbe9adf3a308ce280ede847"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250509/forc-wallet-0.14.0%2Bnightly.20250509.24883eb126-aarch64-unknown-linux-gnu.tar.gz"
hash = "88aff192f9f51c916150dc6858e42a8b2607308f17c3476605e18e3b8e2c8aea"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250509/forc-wallet-0.14.0%2Bnightly.20250509.24883eb126-x86_64-apple-darwin.tar.gz"
hash = "5ab13412b917dcaa2ea7dc78f5b4f1d3aad5e4e86b4ee3edb02de5300bc114c8"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250509/forc-wallet-0.14.0%2Bnightly.20250509.24883eb126-x86_64-unknown-linux-gnu.tar.gz"
hash = "047b27d2e969a9ec84c17859b04600c3aa43bab630909540b8706033ef14faa8"

[pkg.fuel-core]
version = "0.43.0+nightly.20250509.af4e7b7d25"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250509/fuel-core-0.43.0%2Bnightly.20250509.af4e7b7d25-aarch64-apple-darwin.tar.gz"
hash = "af9643db056e78674a164c5aafcfa2d286eec6ce5637575c197dfe46651d3ed2"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250509/fuel-core-0.43.0%2Bnightly.20250509.af4e7b7d25-aarch64-unknown-linux-gnu.tar.gz"
hash = "1e6b7c302a863760cce8a17b9d4946ca964c3fa4353974483d8d1eb40a9d97e9"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250509/fuel-core-0.43.0%2Bnightly.20250509.af4e7b7d25-x86_64-unknown-linux-gnu.tar.gz"
hash = "625953c506cf97e7700f2c1d032e2b8eb066fe4272669981fc61e32ef3e2a2ba"

[pkg.fuel-core-keygen]
version = "0.43.0+nightly.20250509.af4e7b7d25"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250509/fuel-core-0.43.0%2Bnightly.20250509.af4e7b7d25-aarch64-apple-darwin.tar.gz"
hash = "af9643db056e78674a164c5aafcfa2d286eec6ce5637575c197dfe46651d3ed2"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250509/fuel-core-0.43.0%2Bnightly.20250509.af4e7b7d25-aarch64-unknown-linux-gnu.tar.gz"
hash = "1e6b7c302a863760cce8a17b9d4946ca964c3fa4353974483d8d1eb40a9d97e9"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250509/fuel-core-0.43.0%2Bnightly.20250509.af4e7b7d25-x86_64-unknown-linux-gnu.tar.gz"
hash = "625953c506cf97e7700f2c1d032e2b8eb066fe4272669981fc61e32ef3e2a2ba"
