published_by = "https://github.com/FuelLabs/fuelup/actions/runs/21324790915"
date = "2026-01-25"

[pkg.forc]
version = "0.70.1+nightly.20260125.20b32cfb44"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/forc-binaries-0.70.1%2Bnightly.20260125.20b32cfb44-darwin_amd64.tar.gz"
hash = "870895679212dc8fb1082d08a636b987202eae2f8a9f7dd7397783728fff6370"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/forc-binaries-0.70.1%2Bnightly.20260125.20b32cfb44-darwin_arm64.tar.gz"
hash = "b375aa2421c1ac8b26048876afa49e0bf6eedde267afde21b54cb86d8adb06f6"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/forc-binaries-0.70.1%2Bnightly.20260125.20b32cfb44-linux_amd64.tar.gz"
hash = "1e495e68f4fa7c839d70471e7ad056fc52fdcf790256402b11b41e55743b9a5f"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/forc-binaries-0.70.1%2Bnightly.20260125.20b32cfb44-linux_arm64.tar.gz"
hash = "f353ca85f865d92470a680f90edc71f9d430a920283da92e4a47e65454e3155a"

[pkg.forc-crypto]
version = "0.71.0+nightly.20260125.54cf9da7d3"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/forc-crypto-0.71.0%2Bnightly.20260125.54cf9da7d3-darwin_amd64.tar.gz"
hash = "a99547ef5a6e839bc2ee07cb52531d3dcec32ab69f3b52245033fafa65bf33e2"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/forc-crypto-0.71.0%2Bnightly.20260125.54cf9da7d3-darwin_arm64.tar.gz"
hash = "2927152c5f28a704045a524a8f9fe15e502cb6217c4f49c89763eca5a2499409"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/forc-crypto-0.71.0%2Bnightly.20260125.54cf9da7d3-linux_amd64.tar.gz"
hash = "da1e41c9a26641b1ef462dbe83cec6b7d7a1b4a3f84f6b3662dcf8186837f38b"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/forc-crypto-0.71.0%2Bnightly.20260125.54cf9da7d3-linux_arm64.tar.gz"
hash = "a7e6ada1c3b1a14ec1e9d90dcd459bb809419805ac5b85f16bec7293b3c03c46"

[pkg.forc-node]
version = "0.71.2+nightly.20260125.54cf9da7d3"

[pkg.forc-node.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/forc-node-0.71.2%2Bnightly.20260125.54cf9da7d3-darwin_amd64.tar.gz"
hash = "89c8ddc74d70af3157d0691c9a08ae0d5cf6b19390feeb01daa1d7377a89c98f"

[pkg.forc-node.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/forc-node-0.71.2%2Bnightly.20260125.54cf9da7d3-darwin_arm64.tar.gz"
hash = "4167f5fede4e0fa10f1ca5f9875912bd5f65e58900cb6003fda6c0ddc5670f62"

[pkg.forc-node.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/forc-node-0.71.2%2Bnightly.20260125.54cf9da7d3-linux_amd64.tar.gz"
hash = "90718bd764e8e85adad340bef856abb0715e0795ca14aecd4f124da54e964e56"

[pkg.forc-node.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/forc-node-0.71.2%2Bnightly.20260125.54cf9da7d3-linux_arm64.tar.gz"
hash = "2c5e74fffe8647e4b3a3ed155f8b2522d50f0b5798cdd0156fc38929d7ec69f0"

[pkg.forc-wallet]
version = "0.16.2+nightly.20260125.54cf9da7d3"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/forc-wallet-0.16.2%2Bnightly.20260125.54cf9da7d3-darwin_amd64.tar.gz"
hash = "272161450a5f73beb2da060a3a3f4281e7c94e68b989adc9a77263cb56887066"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/forc-wallet-0.16.2%2Bnightly.20260125.54cf9da7d3-darwin_arm64.tar.gz"
hash = "e08db68e6ec3bead62a3f24efdef491dc904ee519b60521e81dc14f81724bc30"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/forc-wallet-0.16.2%2Bnightly.20260125.54cf9da7d3-linux_amd64.tar.gz"
hash = "72de66bd84b74652b78f71172ed0aedcfb422dc34eae7adaa1fe3d575328ac5a"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/forc-wallet-0.16.2%2Bnightly.20260125.54cf9da7d3-linux_arm64.tar.gz"
hash = "585462a12f5b8ae05e53557745f97ba1e2fd84ec3604f23f298c154eb19a2985"

[pkg.fuel-core]
version = "0.47.1+nightly.20260125.579e1c2d78"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/fuel-core-0.47.1%2Bnightly.20260125.579e1c2d78-aarch64-apple-darwin.tar.gz"
hash = "d6ff137f9349263cf6a84669164f7bc1c43bc61fbf8427a517ff1208d65b00ce"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/fuel-core-0.47.1%2Bnightly.20260125.579e1c2d78-aarch64-unknown-linux-gnu.tar.gz"
hash = "6b79a4bfed509a36485c15b1b90b88a35bccd3f34b5d00d64b0b81f416664dcf"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/fuel-core-0.47.1%2Bnightly.20260125.579e1c2d78-x86_64-apple-darwin.tar.gz"
hash = "22e1f2f40a268574513eb846e85bad7c3e530a1cd078e4aafcfb86268044686a"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/fuel-core-0.47.1%2Bnightly.20260125.579e1c2d78-x86_64-unknown-linux-gnu.tar.gz"
hash = "c4e37e217013f12b0687eb34525bc549c380ecb02abbb4c51bdb37f1e30f38c6"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20260125.579e1c2d78"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/fuel-core-0.47.1%2Bnightly.20260125.579e1c2d78-aarch64-apple-darwin.tar.gz"
hash = "d6ff137f9349263cf6a84669164f7bc1c43bc61fbf8427a517ff1208d65b00ce"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/fuel-core-0.47.1%2Bnightly.20260125.579e1c2d78-aarch64-unknown-linux-gnu.tar.gz"
hash = "6b79a4bfed509a36485c15b1b90b88a35bccd3f34b5d00d64b0b81f416664dcf"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/fuel-core-0.47.1%2Bnightly.20260125.579e1c2d78-x86_64-apple-darwin.tar.gz"
hash = "22e1f2f40a268574513eb846e85bad7c3e530a1cd078e4aafcfb86268044686a"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260125/fuel-core-0.47.1%2Bnightly.20260125.579e1c2d78-x86_64-unknown-linux-gnu.tar.gz"
hash = "c4e37e217013f12b0687eb34525bc549c380ecb02abbb4c51bdb37f1e30f38c6"
