published_by = "https://github.com/FuelLabs/fuelup/actions/runs/12820834823"
date = "2025-01-17"

[pkg.forc]
version = "0.66.5+nightly.20250117.37235f2e7d"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250117/forc-binaries-0.66.5%2Bnightly.20250117.37235f2e7d-darwin_amd64.tar.gz"
hash = "ac858a9e4f3f16a46f7c4ecd425132f46392170ad9c5f9c74b957de25bda0724"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250117/forc-binaries-0.66.5%2Bnightly.20250117.37235f2e7d-darwin_arm64.tar.gz"
hash = "2faa9dd107310935187b1b0c58474a2b6ea307b3a738145a0cc80fcc3eb80e24"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250117/forc-binaries-0.66.5%2Bnightly.20250117.37235f2e7d-linux_amd64.tar.gz"
hash = "442035f29d5f49a7e1d0a48512dff16044bbfdb29436ffd94358c3a97b31e14e"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250117/forc-binaries-0.66.5%2Bnightly.20250117.37235f2e7d-linux_arm64.tar.gz"
hash = "6da11eaf7f07fac292fff8539b1bfa363799237f7963c6a52fa210caedabb520"

[pkg.forc-wallet]
version = "0.11.1+nightly.20250117.f6f0ff07c8"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250117/forc-wallet-0.11.1%2Bnightly.20250117.f6f0ff07c8-aarch64-apple-darwin.tar.gz"
hash = "2e7537c31fdff39284f24a541cca137386e2b0eddc19fe5dff8a66ac34415018"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250117/forc-wallet-0.11.1%2Bnightly.20250117.f6f0ff07c8-aarch64-unknown-linux-gnu.tar.gz"
hash = "b52d43dd768bb0b87947210408b9e8e347863bd31689d7657e6c31f4adbaf27b"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250117/forc-wallet-0.11.1%2Bnightly.20250117.f6f0ff07c8-x86_64-apple-darwin.tar.gz"
hash = "50cc0cf3f2efeb6e130ba1625f7cf1027af9fdb710eb2c057b017d7d4d5260c0"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250117/forc-wallet-0.11.1%2Bnightly.20250117.f6f0ff07c8-x86_64-unknown-linux-gnu.tar.gz"
hash = "4519d86ad973d2db466269d42c236f5567784d935f6e75f72840da84576bde82"

[pkg.fuel-core]
version = "0.41.0+nightly.20250117.dfc7fd7c0d"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250117/fuel-core-0.41.0%2Bnightly.20250117.dfc7fd7c0d-aarch64-apple-darwin.tar.gz"
hash = "157f3adfc24b981b7811057797456bec9cfb273e9132bc7835479dcb34bcf9c5"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250117/fuel-core-0.41.0%2Bnightly.20250117.dfc7fd7c0d-aarch64-unknown-linux-gnu.tar.gz"
hash = "f6fe048e0c65dc5b996ab6bbe962864b28ef68e87656d0cf0503d002c1cbf67c"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250117/fuel-core-0.41.0%2Bnightly.20250117.dfc7fd7c0d-x86_64-apple-darwin.tar.gz"
hash = "0c4210282d9d484aef55186eab3406423000edf38a4f8ef7d523560f657c2006"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250117/fuel-core-0.41.0%2Bnightly.20250117.dfc7fd7c0d-x86_64-unknown-linux-gnu.tar.gz"
hash = "f4860b394fb53babb7680fd5738320a49cf2b100b85638bcc575def56afc59a7"

[pkg.fuel-core-keygen]
version = "0.41.0+nightly.20250117.dfc7fd7c0d"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250117/fuel-core-0.41.0%2Bnightly.20250117.dfc7fd7c0d-aarch64-apple-darwin.tar.gz"
hash = "157f3adfc24b981b7811057797456bec9cfb273e9132bc7835479dcb34bcf9c5"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250117/fuel-core-0.41.0%2Bnightly.20250117.dfc7fd7c0d-aarch64-unknown-linux-gnu.tar.gz"
hash = "f6fe048e0c65dc5b996ab6bbe962864b28ef68e87656d0cf0503d002c1cbf67c"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250117/fuel-core-0.41.0%2Bnightly.20250117.dfc7fd7c0d-x86_64-apple-darwin.tar.gz"
hash = "0c4210282d9d484aef55186eab3406423000edf38a4f8ef7d523560f657c2006"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250117/fuel-core-0.41.0%2Bnightly.20250117.dfc7fd7c0d-x86_64-unknown-linux-gnu.tar.gz"
hash = "f4860b394fb53babb7680fd5738320a49cf2b100b85638bcc575def56afc59a7"
