published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15865145893"
date = "2025-06-25"

[pkg.forc]
version = "0.69.0+nightly.20250625.5c22e33987"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250625/forc-binaries-0.69.0%2Bnightly.20250625.5c22e33987-darwin_amd64.tar.gz"
hash = "bb31f1a5e4f4df14ae943452a1618e1cb8f152d0c506ba5fd0abed8f5ca274b0"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250625/forc-binaries-0.69.0%2Bnightly.20250625.5c22e33987-darwin_arm64.tar.gz"
hash = "ee0ecb4431efcc74c4eba8517aeb6c6b8327187d5bbb589dd4d57e13581d3998"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250625/forc-binaries-0.69.0%2Bnightly.20250625.5c22e33987-linux_amd64.tar.gz"
hash = "16d41350b2a94471762dfc3f73c256227190f2be934f33f99de021b93d628a7c"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250625/forc-binaries-0.69.0%2Bnightly.20250625.5c22e33987-linux_arm64.tar.gz"
hash = "346b4b129e2385635ec2191a11f4a5c40c891cdb839bbd62db3344dd16d0cb3d"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250625.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250625/forc-wallet-0.15.1%2Bnightly.20250625.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "6674f8f00224434fa788abc746f76f0ead0bfd5e122991599dd2950d396ec114"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250625/forc-wallet-0.15.1%2Bnightly.20250625.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "d74549e83a0a0897e10d399dbed061e7c89c4e9309bee78326e9fbec4d9928c4"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250625/forc-wallet-0.15.1%2Bnightly.20250625.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "54b8d06a84cbaa011eadf398335f87d4cd5ae589b81dc2911eb78d7a5a204af0"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250625/forc-wallet-0.15.1%2Bnightly.20250625.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "9c38376b200d4bbf28acd7805947ca6821696783f3d779b1c6348e0618cf9ae7"

[pkg.fuel-core]
version = "0.44.0+nightly.20250625.5dae42bafd"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250625/fuel-core-0.44.0%2Bnightly.20250625.5dae42bafd-aarch64-apple-darwin.tar.gz"
hash = "35fc21b448fd01efc704b9ecbb9f50e4b249a89ba62939464e3042b658535383"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250625/fuel-core-0.44.0%2Bnightly.20250625.5dae42bafd-aarch64-unknown-linux-gnu.tar.gz"
hash = "3b199b08f220578cd543812ff8bdb93bcb407971305359d7fab019d9a95290ea"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250625/fuel-core-0.44.0%2Bnightly.20250625.5dae42bafd-x86_64-unknown-linux-gnu.tar.gz"
hash = "b82e60accc7b0e4a0121ddfae889de9ebbb3d8c72ad47d88d0e5e940a3dbe529"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250625.5dae42bafd"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250625/fuel-core-0.44.0%2Bnightly.20250625.5dae42bafd-aarch64-apple-darwin.tar.gz"
hash = "35fc21b448fd01efc704b9ecbb9f50e4b249a89ba62939464e3042b658535383"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250625/fuel-core-0.44.0%2Bnightly.20250625.5dae42bafd-aarch64-unknown-linux-gnu.tar.gz"
hash = "3b199b08f220578cd543812ff8bdb93bcb407971305359d7fab019d9a95290ea"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250625/fuel-core-0.44.0%2Bnightly.20250625.5dae42bafd-x86_64-unknown-linux-gnu.tar.gz"
hash = "b82e60accc7b0e4a0121ddfae889de9ebbb3d8c72ad47d88d0e5e940a3dbe529"
