published_by = "https://github.com/FuelLabs/fuelup/actions/runs/15916038308"
date = "2025-06-27"

[pkg.forc]
version = "0.69.0+nightly.20250627.5c22e33987"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250627/forc-binaries-0.69.0%2Bnightly.20250627.5c22e33987-darwin_amd64.tar.gz"
hash = "76c6424bdcd9366a8fcc2087983154119278acdc51777be2d2866be79c9ac9cf"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250627/forc-binaries-0.69.0%2Bnightly.20250627.5c22e33987-darwin_arm64.tar.gz"
hash = "1bde8c90354283f4be8db1c5c404524285badf4b3e6d4feabeac07ca706e6906"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250627/forc-binaries-0.69.0%2Bnightly.20250627.5c22e33987-linux_amd64.tar.gz"
hash = "d506591ba197333a9e7e471442421d272122e13ce0e18390e1438d46620d4d6c"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250627/forc-binaries-0.69.0%2Bnightly.20250627.5c22e33987-linux_arm64.tar.gz"
hash = "6cf2a0f44b1d0ab9fe4dbfbd465caf463d4477db180414d1b1d8b2479504d1fd"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250627.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250627/forc-wallet-0.15.1%2Bnightly.20250627.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "29391abd601ff82ec0ddd564875759b3bed5c1dab53584c5d575b4ec1efbe4a1"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250627/forc-wallet-0.15.1%2Bnightly.20250627.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "c820a063c8073ad8c77febaec8d79439545c83d8f87a17b22e8c449485f7657a"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250627/forc-wallet-0.15.1%2Bnightly.20250627.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "1f68e37f520fd7a14904a98e7679871e9020598c940dde9d9f6b5a141690ba14"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250627/forc-wallet-0.15.1%2Bnightly.20250627.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "6655cea06a7aae7b6d9f3cda3472d8ced66bf70c130e08de145777d428b73270"

[pkg.fuel-core]
version = "0.44.0+nightly.20250627.cee716ff92"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250627/fuel-core-0.44.0%2Bnightly.20250627.cee716ff92-aarch64-apple-darwin.tar.gz"
hash = "e29603863c98053bf42dfd171396dc9ae6b6106983fce993bc021e578bdae206"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250627/fuel-core-0.44.0%2Bnightly.20250627.cee716ff92-aarch64-unknown-linux-gnu.tar.gz"
hash = "dc9368284df473c10332b7bfdb86f44f1d96b4e70899ff6d6ff5ec0bc79e8626"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250627/fuel-core-0.44.0%2Bnightly.20250627.cee716ff92-x86_64-unknown-linux-gnu.tar.gz"
hash = "96a2937bc4d5b1cabfa9bc7db4d20244cdb615c08f1915aade43ce922c3ef91b"

[pkg.fuel-core-keygen]
version = "0.44.0+nightly.20250627.cee716ff92"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250627/fuel-core-0.44.0%2Bnightly.20250627.cee716ff92-aarch64-apple-darwin.tar.gz"
hash = "e29603863c98053bf42dfd171396dc9ae6b6106983fce993bc021e578bdae206"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250627/fuel-core-0.44.0%2Bnightly.20250627.cee716ff92-aarch64-unknown-linux-gnu.tar.gz"
hash = "dc9368284df473c10332b7bfdb86f44f1d96b4e70899ff6d6ff5ec0bc79e8626"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250627/fuel-core-0.44.0%2Bnightly.20250627.cee716ff92-x86_64-unknown-linux-gnu.tar.gz"
hash = "96a2937bc4d5b1cabfa9bc7db4d20244cdb615c08f1915aade43ce922c3ef91b"
