published_by = "https://github.com/FuelLabs/fuelup/actions/runs/18734694704"
date = "2025-10-23"

[pkg.forc-wallet]
version = "0.15.2+nightly.20251023.279124d992"

[pkg.forc-wallet.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251023/forc-wallet-0.15.2%2Bnightly.20251023.279124d992-aarch64-apple-darwin.tar.gz"
hash = "912baf26e574c4acf0acab42b5f8f5dcd660b8c71c854ca6f144d02a3ba39593"

[pkg.forc-wallet.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251023/forc-wallet-0.15.2%2Bnightly.20251023.279124d992-aarch64-unknown-linux-gnu.tar.gz"
hash = "eb7b981e83a267703eca09c0f0075e9a049a1bf55b6d1765789a6ea908127e29"

[pkg.forc-wallet.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251023/forc-wallet-0.15.2%2Bnightly.20251023.279124d992-x86_64-apple-darwin.tar.gz"
hash = "86296425357c66cc29834c6be319a05660329c4d28b7952937d4fccd914eb882"

[pkg.forc-wallet.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251023/forc-wallet-0.15.2%2Bnightly.20251023.279124d992-x86_64-unknown-linux-gnu.tar.gz"
hash = "b21db8ca6ec40cee34bc7159acae7e4dd13241aefc6ca2dd0a424a225a4b1528"
