published_by = "https://github.com/FuelLabs/fuelup/actions/runs/12498232466"
date = "2024-12-26"

[pkg.forc]
version = "0.66.5+nightly.20241226.cf7b6664b5"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241226/forc-binaries-0.66.5%2Bnightly.20241226.cf7b6664b5-darwin_amd64.tar.gz"
hash = "6233f593aec0c34aae0786f7306d97c4486d6d05b9d5cd32839ee7cd4e26596f"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241226/forc-binaries-0.66.5%2Bnightly.20241226.cf7b6664b5-darwin_arm64.tar.gz"
hash = "c594133900c4c99b409982408967af2e210c421001cd863c314a766054ae9fe0"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241226/forc-binaries-0.66.5%2Bnightly.20241226.cf7b6664b5-linux_amd64.tar.gz"
hash = "7cd2b000b288937a75f8ea723b7444eb8b1c9afa48cfc9d5955abcd0242f94e7"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241226/forc-binaries-0.66.5%2Bnightly.20241226.cf7b6664b5-linux_arm64.tar.gz"
hash = "c2deafb136b125f9d72f62a0b8670221630d223f169e85e4f223d1f0789048c3"

[pkg.forc-wallet]
version = "0.11.1+nightly.20241226.f4052012e0"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241226/forc-wallet-0.11.1%2Bnightly.20241226.f4052012e0-aarch64-apple-darwin.tar.gz"
hash = "f8952c91d8afafaa513eb1175e7281889e0bc2d2c31316ef7b644257761ccda3"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241226/forc-wallet-0.11.1%2Bnightly.20241226.f4052012e0-aarch64-unknown-linux-gnu.tar.gz"
hash = "3a6ddd5d18dfa09b2eb41f1139250cf7e60c6c362d6ce3a6d2a7a8d9abf26ee1"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241226/forc-wallet-0.11.1%2Bnightly.20241226.f4052012e0-x86_64-apple-darwin.tar.gz"
hash = "4b4cb2a75edab4036912a9226bd0f8423850e663723c24cdd2eff896a8637802"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241226/forc-wallet-0.11.1%2Bnightly.20241226.f4052012e0-x86_64-unknown-linux-gnu.tar.gz"
hash = "3d13374e13cd3c5be07b4b0b28b93af76501216d210aa922be760fd6e2f9fdfd"

[pkg.fuel-core]
version = "0.40.0+nightly.20241226.d6e4bb9e33"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241226/fuel-core-0.40.0%2Bnightly.20241226.d6e4bb9e33-aarch64-apple-darwin.tar.gz"
hash = "7a5606ebcaf0f1497d4f93714bbea1aff0bd6e3d10fc5490788cf2d349ba2320"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241226/fuel-core-0.40.0%2Bnightly.20241226.d6e4bb9e33-aarch64-unknown-linux-gnu.tar.gz"
hash = "90d5b169aa740a67c9e18f967ba58e6813c9a9fb4cdd3bda496c33ce64dce5c6"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241226/fuel-core-0.40.0%2Bnightly.20241226.d6e4bb9e33-x86_64-apple-darwin.tar.gz"
hash = "8e2b4697b9d16742579d0834e9c67fcdef43e1996cf4e8060ebd62816c3660b1"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241226/fuel-core-0.40.0%2Bnightly.20241226.d6e4bb9e33-x86_64-unknown-linux-gnu.tar.gz"
hash = "0919e707bab0bca199072d5d4ac79a2a1a663c271ec728d9421a4ea3394426e1"

[pkg.fuel-core-keygen]
version = "0.40.0+nightly.20241226.d6e4bb9e33"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241226/fuel-core-0.40.0%2Bnightly.20241226.d6e4bb9e33-aarch64-apple-darwin.tar.gz"
hash = "7a5606ebcaf0f1497d4f93714bbea1aff0bd6e3d10fc5490788cf2d349ba2320"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241226/fuel-core-0.40.0%2Bnightly.20241226.d6e4bb9e33-aarch64-unknown-linux-gnu.tar.gz"
hash = "90d5b169aa740a67c9e18f967ba58e6813c9a9fb4cdd3bda496c33ce64dce5c6"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241226/fuel-core-0.40.0%2Bnightly.20241226.d6e4bb9e33-x86_64-apple-darwin.tar.gz"
hash = "8e2b4697b9d16742579d0834e9c67fcdef43e1996cf4e8060ebd62816c3660b1"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241226/fuel-core-0.40.0%2Bnightly.20241226.d6e4bb9e33-x86_64-unknown-linux-gnu.tar.gz"
hash = "0919e707bab0bca199072d5d4ac79a2a1a663c271ec728d9421a4ea3394426e1"
