published_by = "https://github.com/FuelLabs/fuelup/actions/runs/13448093091"
date = "2025-02-21"

[pkg.forc]
version = "0.66.7+nightly.20250221.b07d0cab4a"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250221/forc-binaries-0.66.7%2Bnightly.20250221.b07d0cab4a-darwin_amd64.tar.gz"
hash = "0e9ac25789cc1f5c8dd94f35704c0e0159493e580ff68bcb19672c8bd3febc45"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250221/forc-binaries-0.66.7%2Bnightly.20250221.b07d0cab4a-darwin_arm64.tar.gz"
hash = "433679a5e5a0b4bf16ebfb5b379b0d96acb3837634e0a6efad7d90585a112bad"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250221/forc-binaries-0.66.7%2Bnightly.20250221.b07d0cab4a-linux_amd64.tar.gz"
hash = "c67fc38285f0697df77f69b48517fad323c42f4b98fa5bb0626550c43e2b89c3"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250221/forc-binaries-0.66.7%2Bnightly.20250221.b07d0cab4a-linux_arm64.tar.gz"
hash = "f3d160b508b667a29416abb736a138327aeba058c57a265cef338e01a67bc55e"

[pkg.forc-wallet]
version = "0.12.0+nightly.20250221.8d59dbc462"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250221/forc-wallet-0.12.0%2Bnightly.20250221.8d59dbc462-aarch64-apple-darwin.tar.gz"
hash = "b24218bccbcbdc819584cbb19c41e20680b0e4d44d27873cc88bc24158161431"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250221/forc-wallet-0.12.0%2Bnightly.20250221.8d59dbc462-aarch64-unknown-linux-gnu.tar.gz"
hash = "3d11ac7f4a45bcf5197880d324c85ceffd0332995215b3feac252084c4d5ab0a"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250221/forc-wallet-0.12.0%2Bnightly.20250221.8d59dbc462-x86_64-apple-darwin.tar.gz"
hash = "a7ca6586ec5cf8461f6e0d6739a73eb80e0ece55f9bba31a66a4388172bb0451"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250221/forc-wallet-0.12.0%2Bnightly.20250221.8d59dbc462-x86_64-unknown-linux-gnu.tar.gz"
hash = "822ade2298c3525598cb7dbc553d15a13352207f575f669c987952bea29ac650"

[pkg.fuel-core]
version = "0.41.6+nightly.20250221.2471df626e"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250221/fuel-core-0.41.6%2Bnightly.20250221.2471df626e-aarch64-apple-darwin.tar.gz"
hash = "8660e876fef8d9af5949d2ff5d6aef3364ed6fc9be3bbdcb4a6405b0acfcc7e7"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250221/fuel-core-0.41.6%2Bnightly.20250221.2471df626e-aarch64-unknown-linux-gnu.tar.gz"
hash = "2749cdd06b6e9ed018c3911cc202ab2608af8cba7f6109f36e6c999930ba43c3"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250221/fuel-core-0.41.6%2Bnightly.20250221.2471df626e-x86_64-apple-darwin.tar.gz"
hash = "111f3228c94fb94211600d484b791f71ab7e3076e125ff967a737ef8d3fe2e1a"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250221/fuel-core-0.41.6%2Bnightly.20250221.2471df626e-x86_64-unknown-linux-gnu.tar.gz"
hash = "b5efa8a71c9025a9588a7aabf7ec8a79b6544800208b2e8209b1a2e259694ceb"

[pkg.fuel-core-keygen]
version = "0.41.6+nightly.20250221.2471df626e"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250221/fuel-core-0.41.6%2Bnightly.20250221.2471df626e-aarch64-apple-darwin.tar.gz"
hash = "8660e876fef8d9af5949d2ff5d6aef3364ed6fc9be3bbdcb4a6405b0acfcc7e7"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250221/fuel-core-0.41.6%2Bnightly.20250221.2471df626e-aarch64-unknown-linux-gnu.tar.gz"
hash = "2749cdd06b6e9ed018c3911cc202ab2608af8cba7f6109f36e6c999930ba43c3"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250221/fuel-core-0.41.6%2Bnightly.20250221.2471df626e-x86_64-apple-darwin.tar.gz"
hash = "111f3228c94fb94211600d484b791f71ab7e3076e125ff967a737ef8d3fe2e1a"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250221/fuel-core-0.41.6%2Bnightly.20250221.2471df626e-x86_64-unknown-linux-gnu.tar.gz"
hash = "b5efa8a71c9025a9588a7aabf7ec8a79b6544800208b2e8209b1a2e259694ceb"
