published_by = "https://github.com/FuelLabs/fuelup/actions/runs/20084174287"
date = "2025-12-10"

[pkg.forc]
version = "0.70.1+nightly.20251210.8103f0d02f"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251210/forc-binaries-0.70.1%2Bnightly.20251210.8103f0d02f-darwin_amd64.tar.gz"
hash = "2e53e75c8b1415aba1b2354a942b1bb1dd000ee0ad4a767f21ba05282f5bd6da"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251210/forc-binaries-0.70.1%2Bnightly.20251210.8103f0d02f-darwin_arm64.tar.gz"
hash = "9ffc8df3f9cf1347ee10cfd6a5a9251742f02663b2919ad732002bb6ae32dc79"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251210/forc-binaries-0.70.1%2Bnightly.20251210.8103f0d02f-linux_amd64.tar.gz"
hash = "e402db11c13effb2d049c1b6942e62ee6b6a6906e5e3a449f54b474acca4bb9b"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251210/forc-binaries-0.70.1%2Bnightly.20251210.8103f0d02f-linux_arm64.tar.gz"
hash = "9edbf913299dc36b7739c82d490d491af6ee3a32f8492d5ab7f15815d14d2a4d"

[pkg.forc-wallet]
version = "0.16.2+nightly.20251210.c10463b0cb"

[pkg.forc-wallet.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251210/forc-wallet-0.16.2%2Bnightly.20251210.c10463b0cb-aarch64-apple-darwin.tar.gz"
hash = "e4dc4bcfc032e18a4b262db395d761aa664420697e606b573519e8b02106aa90"

[pkg.forc-wallet.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251210/forc-wallet-0.16.2%2Bnightly.20251210.c10463b0cb-aarch64-unknown-linux-gnu.tar.gz"
hash = "808e984c820f62e99d635ffc0c74696f72d14b6980802fecb87a5d407e47421f"

[pkg.forc-wallet.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251210/forc-wallet-0.16.2%2Bnightly.20251210.c10463b0cb-x86_64-apple-darwin.tar.gz"
hash = "53229a7809c66814c6775e216649eac665233eeb65690359713037e0abeb19e0"

[pkg.forc-wallet.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251210/forc-wallet-0.16.2%2Bnightly.20251210.c10463b0cb-x86_64-unknown-linux-gnu.tar.gz"
hash = "f28c2da934e8fc82528e093ccf96edf6150fea549a017c0d21a1512ff51825b1"

[pkg.fuel-core]
version = "0.47.1+nightly.20251210.6889ed156b"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251210/fuel-core-0.47.1%2Bnightly.20251210.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "d9fca969313604fc0e61e0f89444493d50022c8b07e69eac7c10f8900491f8e9"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251210/fuel-core-0.47.1%2Bnightly.20251210.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "92914ad40842d42755e2dc95004c3e1235b8ebf83e7131a1a578209e74cedcf7"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251210/fuel-core-0.47.1%2Bnightly.20251210.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "eeb00ee64624014942d0c23f18c88430203b0c223e05f6258282f3be8be8a6b2"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251210/fuel-core-0.47.1%2Bnightly.20251210.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "f7dc519bce6ac89fd3fda6f2e373583823fb1807658f5e07d4fd90c6ca6dfc31"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20251210.6889ed156b"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251210/fuel-core-0.47.1%2Bnightly.20251210.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "d9fca969313604fc0e61e0f89444493d50022c8b07e69eac7c10f8900491f8e9"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251210/fuel-core-0.47.1%2Bnightly.20251210.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "92914ad40842d42755e2dc95004c3e1235b8ebf83e7131a1a578209e74cedcf7"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251210/fuel-core-0.47.1%2Bnightly.20251210.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "eeb00ee64624014942d0c23f18c88430203b0c223e05f6258282f3be8be8a6b2"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251210/fuel-core-0.47.1%2Bnightly.20251210.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "f7dc519bce6ac89fd3fda6f2e373583823fb1807658f5e07d4fd90c6ca6dfc31"
