published_by = "https://github.com/FuelLabs/fuelup/actions/runs/20562526997"
date = "2025-12-29"

[pkg.forc]
version = "0.70.1+nightly.20251229.cc8f867043"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/forc-binaries-0.70.1%2Bnightly.20251229.cc8f867043-darwin_amd64.tar.gz"
hash = "788ac9209859beab4b3499b21d0bd6ef12fda6285b62a40fb0e253e487abe76e"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/forc-binaries-0.70.1%2Bnightly.20251229.cc8f867043-darwin_arm64.tar.gz"
hash = "98f7ab28f63dbe5b9136e87294409847636995e8ee58aae8617d62e2409f17cb"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/forc-binaries-0.70.1%2Bnightly.20251229.cc8f867043-linux_amd64.tar.gz"
hash = "7f4b0c05a20ae2e5d780bba150d8018d07a39101357c1c3a1ed1e35a2a473551"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/forc-binaries-0.70.1%2Bnightly.20251229.cc8f867043-linux_arm64.tar.gz"
hash = "86164ed0c422640b1a907b85ed74d09651e89a8517422520d34255b69d06b20d"

[pkg.forc-crypto]
version = "0.71.0+nightly.20251229.c10463b0cb"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/forc-crypto-0.71.0%2Bnightly.20251229.c10463b0cb-darwin_amd64.tar.gz"
hash = "f42db147150492f07c3be56986b422115c38a35675f643311811ee826ee44124"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/forc-crypto-0.71.0%2Bnightly.20251229.c10463b0cb-darwin_arm64.tar.gz"
hash = "e51c44bd41ba741d189baf505af28d196a1fb1ac9743ed64eb4bcbe9a3841fa0"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/forc-crypto-0.71.0%2Bnightly.20251229.c10463b0cb-linux_amd64.tar.gz"
hash = "def63dcaf8d0596d9603740d37507952f1f8a5a98a642b27dd846dbe15139c90"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/forc-crypto-0.71.0%2Bnightly.20251229.c10463b0cb-linux_arm64.tar.gz"
hash = "32e0a31b85623fa2eb8bc3e34f910ca03f5a64d3040429455f621a90078ec4bf"

[pkg.forc-wallet]
version = "0.16.2+nightly.20251229.c10463b0cb"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/forc-wallet-0.16.2%2Bnightly.20251229.c10463b0cb-darwin_amd64.tar.gz"
hash = "cabf9057baa46e3694add761443ee1e19a3c7c8c544b481fc94c5d1926a095ed"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/forc-wallet-0.16.2%2Bnightly.20251229.c10463b0cb-darwin_arm64.tar.gz"
hash = "52483bb5ae740d8f757cabd3ff83ccd74dd76ce5248513be3670269128a1ba25"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/forc-wallet-0.16.2%2Bnightly.20251229.c10463b0cb-linux_amd64.tar.gz"
hash = "d3f7f7d86be6f7204ce9a84b6db8749835ad7569af6af81462f1527a2fe71524"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/forc-wallet-0.16.2%2Bnightly.20251229.c10463b0cb-linux_arm64.tar.gz"
hash = "e90ad10013d49963a91b272cabff8daf12bd9e257c56a51d6a7e8e6785e398e9"

[pkg.fuel-core]
version = "0.47.1+nightly.20251229.6889ed156b"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/fuel-core-0.47.1%2Bnightly.20251229.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "20b3f5a56a34ac056a6d21548c7cf8627c0e2ee4986b6704382d9d586c2598c8"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/fuel-core-0.47.1%2Bnightly.20251229.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "02dbcd887a8c7df1bea81b29f059a0a283bc60731f4592d52898b3fc896c3b71"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/fuel-core-0.47.1%2Bnightly.20251229.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "2e7b5a6b4481253670e2be8281ff686486f0d8c4180343ba9c5c24bc3ebf103a"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/fuel-core-0.47.1%2Bnightly.20251229.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "067cc14a2d8d827cec5ee796f445b104c22b6a45db5406c4524ed1b15679a5fc"

[pkg.fuel-core-keygen]
version = "0.47.1+nightly.20251229.6889ed156b"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/fuel-core-0.47.1%2Bnightly.20251229.6889ed156b-aarch64-apple-darwin.tar.gz"
hash = "20b3f5a56a34ac056a6d21548c7cf8627c0e2ee4986b6704382d9d586c2598c8"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/fuel-core-0.47.1%2Bnightly.20251229.6889ed156b-aarch64-unknown-linux-gnu.tar.gz"
hash = "02dbcd887a8c7df1bea81b29f059a0a283bc60731f4592d52898b3fc896c3b71"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/fuel-core-0.47.1%2Bnightly.20251229.6889ed156b-x86_64-apple-darwin.tar.gz"
hash = "2e7b5a6b4481253670e2be8281ff686486f0d8c4180343ba9c5c24bc3ebf103a"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20251229/fuel-core-0.47.1%2Bnightly.20251229.6889ed156b-x86_64-unknown-linux-gnu.tar.gz"
hash = "067cc14a2d8d827cec5ee796f445b104c22b6a45db5406c4524ed1b15679a5fc"
