published_by = "https://github.com/FuelLabs/fuelup/actions/runs/11284680244"
date = "2024-10-11"

[pkg.forc]
version = "0.65.2+nightly.20241011.f5fd2e63a6"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241011/forc-binaries-0.65.2%2Bnightly.20241011.f5fd2e63a6-darwin_amd64.tar.gz"
hash = "887c6e58af9f3bff8bad5afecc22232e0a7f37e4de7900bdc182cb02179d9f8e"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241011/forc-binaries-0.65.2%2Bnightly.20241011.f5fd2e63a6-darwin_arm64.tar.gz"
hash = "70bd49ce1a972bd4a3769710639a3b3c2d021d71e2e9f6c55d5b70aa27a1de87"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241011/forc-binaries-0.65.2%2Bnightly.20241011.f5fd2e63a6-linux_amd64.tar.gz"
hash = "95510ba77083a8c4862983fddd4ff3913731a2cc4cbf2bde29c4bd68d3f0a034"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241011/forc-binaries-0.65.2%2Bnightly.20241011.f5fd2e63a6-linux_arm64.tar.gz"
hash = "94b48bb869240e71e1700cf471ce3edfb2fdd8d515bf5e9061e5964bf21ab5b7"

[pkg.forc-wallet]
version = "0.10.0+nightly.20241011.ee49fcbace"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241011/forc-wallet-0.10.0%2Bnightly.20241011.ee49fcbace-aarch64-apple-darwin.tar.gz"
hash = "69f311f63bb84d502d239b9b7645427a64aae40d0a7feab06ddcb7c7c56c870d"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241011/forc-wallet-0.10.0%2Bnightly.20241011.ee49fcbace-aarch64-unknown-linux-gnu.tar.gz"
hash = "00a7b8cf8743a39e12b8a63ab0aeff824e9deecee3cd449c20c872c7b87f8938"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241011/forc-wallet-0.10.0%2Bnightly.20241011.ee49fcbace-x86_64-apple-darwin.tar.gz"
hash = "5680ba7647cc462d4a7b317dd60dbdfa3e6842039399d4d2f4508fdfebb3dcb9"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241011/forc-wallet-0.10.0%2Bnightly.20241011.ee49fcbace-x86_64-unknown-linux-gnu.tar.gz"
hash = "4d9046d2136fd0f6681078ed54a721dd8046142940d954b172e8ae34955cb95a"

[pkg.fuel-core]
version = "0.37.1+nightly.20241011.4d40e88a76"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241011/fuel-core-0.37.1%2Bnightly.20241011.4d40e88a76-aarch64-apple-darwin.tar.gz"
hash = "6b1ea539b8e1dbd002d78ccfed96b4822b1b23773567b4f3366e659a61a27fd0"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241011/fuel-core-0.37.1%2Bnightly.20241011.4d40e88a76-aarch64-unknown-linux-gnu.tar.gz"
hash = "b3bb849ca96e7c9d8dd5d82a320190e86774b9f7c9b5ddb423a1ba27bd04a3dd"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241011/fuel-core-0.37.1%2Bnightly.20241011.4d40e88a76-x86_64-unknown-linux-gnu.tar.gz"
hash = "a54c7f88d445bea1d296627adaac5e8d556be827983d1007b65805a69b563f1e"

[pkg.fuel-core-keygen]
version = "0.37.1+nightly.20241011.4d40e88a76"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241011/fuel-core-0.37.1%2Bnightly.20241011.4d40e88a76-aarch64-apple-darwin.tar.gz"
hash = "6b1ea539b8e1dbd002d78ccfed96b4822b1b23773567b4f3366e659a61a27fd0"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241011/fuel-core-0.37.1%2Bnightly.20241011.4d40e88a76-aarch64-unknown-linux-gnu.tar.gz"
hash = "b3bb849ca96e7c9d8dd5d82a320190e86774b9f7c9b5ddb423a1ba27bd04a3dd"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241011/fuel-core-0.37.1%2Bnightly.20241011.4d40e88a76-x86_64-unknown-linux-gnu.tar.gz"
hash = "a54c7f88d445bea1d296627adaac5e8d556be827983d1007b65805a69b563f1e"
