published_by = "https://github.com/FuelLabs/fuelup/actions/runs/10344449366"
date = "2024-08-12"

[pkg.forc]
version = "0.62.0+nightly.20240812.360fcf5fbd"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240812/forc-binaries-0.62.0%2Bnightly.20240812.360fcf5fbd-darwin_amd64.tar.gz"
hash = "85d2559ac7cc631674d0848dc72149999a2ebcc21607d331dc5eacddfac5ca02"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240812/forc-binaries-0.62.0%2Bnightly.20240812.360fcf5fbd-darwin_arm64.tar.gz"
hash = "2dc83b2e1e7ed071a3f0d004aec4251825a60615b08b891925209663e3de6a15"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240812/forc-binaries-0.62.0%2Bnightly.20240812.360fcf5fbd-linux_amd64.tar.gz"
hash = "6191f5a0a4d5dbb6b870463d38297e368df370c99eb033393b001e28d8760b2b"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240812/forc-binaries-0.62.0%2Bnightly.20240812.360fcf5fbd-linux_arm64.tar.gz"
hash = "f88e63778a9d5f8fc1d19b915e3b5e754c250f3de960879067ef6db180715013"

[pkg.forc-wallet]
version = "0.8.2+nightly.20240812.76e9796cbe"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240812/forc-wallet-0.8.2%2Bnightly.20240812.76e9796cbe-aarch64-apple-darwin.tar.gz"
hash = "d6dc49ca266c93883fadf8781919ba27b3e014b109716937e44a30ebdd6663ff"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240812/forc-wallet-0.8.2%2Bnightly.20240812.76e9796cbe-aarch64-unknown-linux-gnu.tar.gz"
hash = "bd91c66f9cbae4fd958c15758f5be82dc793e5929adf4fb075c25d34b36823b7"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240812/forc-wallet-0.8.2%2Bnightly.20240812.76e9796cbe-x86_64-apple-darwin.tar.gz"
hash = "098b760467c3b4b8c527bec40cdd05aa89d8f20079e213f6ef34bf1b887aa498"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240812/forc-wallet-0.8.2%2Bnightly.20240812.76e9796cbe-x86_64-unknown-linux-gnu.tar.gz"
hash = "112d73576ddb3c29fc5fdad728686d6318853c5ebd039a06ad45d3bbb3f9caef"

[pkg.fuel-core]
version = "0.32.1+nightly.20240812.a9e5e89f5f"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240812/fuel-core-0.32.1%2Bnightly.20240812.a9e5e89f5f-aarch64-apple-darwin.tar.gz"
hash = "31c082af80645b3a9a09373a11c9fc3172869937e9b58c5749aab40c0aad2b9b"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240812/fuel-core-0.32.1%2Bnightly.20240812.a9e5e89f5f-x86_64-apple-darwin.tar.gz"
hash = "8de94b220ae8be494f01993fd405fc450d6787f73560abc3f2b0a9ff078ba60d"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240812/fuel-core-0.32.1%2Bnightly.20240812.a9e5e89f5f-x86_64-unknown-linux-gnu.tar.gz"
hash = "1b8bff5a031aa0beea8b391e71a914c0627e1e579bef41cef7329c503efaa7af"

[pkg.fuel-core-keygen]
version = "0.32.1+nightly.20240812.a9e5e89f5f"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240812/fuel-core-0.32.1%2Bnightly.20240812.a9e5e89f5f-aarch64-apple-darwin.tar.gz"
hash = "31c082af80645b3a9a09373a11c9fc3172869937e9b58c5749aab40c0aad2b9b"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240812/fuel-core-0.32.1%2Bnightly.20240812.a9e5e89f5f-x86_64-apple-darwin.tar.gz"
hash = "8de94b220ae8be494f01993fd405fc450d6787f73560abc3f2b0a9ff078ba60d"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20240812/fuel-core-0.32.1%2Bnightly.20240812.a9e5e89f5f-x86_64-unknown-linux-gnu.tar.gz"
hash = "1b8bff5a031aa0beea8b391e71a914c0627e1e579bef41cef7329c503efaa7af"
