published_by = "https://github.com/FuelLabs/fuelup/actions/runs/16557869470"
date = "2025-07-28"

[pkg.forc]
version = "0.69.1+nightly.20250728.4c9c4c29bf"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250728/forc-binaries-0.69.1%2Bnightly.20250728.4c9c4c29bf-darwin_amd64.tar.gz"
hash = "11c1c82272e2f859278e97fff7faf0ebb9a3cd076dd8ef14c2fd46949bc9d821"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250728/forc-binaries-0.69.1%2Bnightly.20250728.4c9c4c29bf-darwin_arm64.tar.gz"
hash = "9c562061980ab23b78b20ec755b25781c0a4078887583e00633b331433b0818c"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250728/forc-binaries-0.69.1%2Bnightly.20250728.4c9c4c29bf-linux_amd64.tar.gz"
hash = "d4839e04155c3a4b3a52c3d510c67d6fc49088e9f30381c6ea3acb779787605b"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250728/forc-binaries-0.69.1%2Bnightly.20250728.4c9c4c29bf-linux_arm64.tar.gz"
hash = "a9908f4d2b4d6e51d85dda3be32df8d14b1b2f56476321d48b50b44a14779b7f"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250728.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250728/forc-wallet-0.15.1%2Bnightly.20250728.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "c45e295875692f76074e3889ad55fdd71aa3bd9b2ae38a9ad0241f696601c61c"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250728/forc-wallet-0.15.1%2Bnightly.20250728.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "20e94d01cfc08bad54988b6b39d29e762d9dca4e028e3f8fd04fd739fe347760"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250728/forc-wallet-0.15.1%2Bnightly.20250728.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "3a09aac21ee6b710bb70e966d75688c332b95bf8189a606c0d87e393849919c7"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250728/forc-wallet-0.15.1%2Bnightly.20250728.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "36f2fc40dc63ef3070ddab22293044341a9cb1903d1ea073c13fca8c93cb0b79"

[pkg.fuel-core]
version = "0.45.1+nightly.20250728.8e34930a63"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250728/fuel-core-0.45.1%2Bnightly.20250728.8e34930a63-aarch64-apple-darwin.tar.gz"
hash = "beb7855ed9ec17313aa66d5769d5031dc5318816a03a8242d2b48a0e35f84125"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250728/fuel-core-0.45.1%2Bnightly.20250728.8e34930a63-aarch64-unknown-linux-gnu.tar.gz"
hash = "13cf8f0c94caa00ecdbf53f0fce22b2d83333bd07c0da5263d350d38daa62c19"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250728/fuel-core-0.45.1%2Bnightly.20250728.8e34930a63-x86_64-unknown-linux-gnu.tar.gz"
hash = "f1d5e051b72df3169a51cbcdfa709826143a80a03a808ba6bf1c3f1308eca35f"

[pkg.fuel-core-keygen]
version = "0.45.1+nightly.20250728.8e34930a63"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250728/fuel-core-0.45.1%2Bnightly.20250728.8e34930a63-aarch64-apple-darwin.tar.gz"
hash = "beb7855ed9ec17313aa66d5769d5031dc5318816a03a8242d2b48a0e35f84125"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250728/fuel-core-0.45.1%2Bnightly.20250728.8e34930a63-aarch64-unknown-linux-gnu.tar.gz"
hash = "13cf8f0c94caa00ecdbf53f0fce22b2d83333bd07c0da5263d350d38daa62c19"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250728/fuel-core-0.45.1%2Bnightly.20250728.8e34930a63-x86_64-unknown-linux-gnu.tar.gz"
hash = "f1d5e051b72df3169a51cbcdfa709826143a80a03a808ba6bf1c3f1308eca35f"
