published_by = "https://github.com/FuelLabs/fuelup/actions/runs/11396185067"
date = "2024-10-18"

[pkg.forc]
version = "0.66.2+nightly.20241018.029c593b5f"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241018/forc-binaries-0.66.2%2Bnightly.20241018.029c593b5f-darwin_amd64.tar.gz"
hash = "c9422cc376eef0605757c157e60e82858daaf8f59e70589dbe2b231aae40fdb4"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241018/forc-binaries-0.66.2%2Bnightly.20241018.029c593b5f-darwin_arm64.tar.gz"
hash = "1f10c36d49a9b31c341586dbc2c62dd14a393669631673ad9b8ad89a9980131a"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241018/forc-binaries-0.66.2%2Bnightly.20241018.029c593b5f-linux_amd64.tar.gz"
hash = "79ef2f4fe526d74ca155d7e715a04732c26f930bf9869aa0cab2aa8ed792aa52"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241018/forc-binaries-0.66.2%2Bnightly.20241018.029c593b5f-linux_arm64.tar.gz"
hash = "097dd64f1c2cd33f0de7d339a07f271e99dea99323710083da67ec0f77305c6f"

[pkg.forc-wallet]
version = "0.11.0+nightly.20241018.152bfb48c3"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241018/forc-wallet-0.11.0%2Bnightly.20241018.152bfb48c3-aarch64-apple-darwin.tar.gz"
hash = "dd9f667f17612165f1f2cd8a4cdb8bdb47d1a41616ecd97ed42a944fddc3d4d0"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241018/forc-wallet-0.11.0%2Bnightly.20241018.152bfb48c3-aarch64-unknown-linux-gnu.tar.gz"
hash = "d80bdd734cdc67032376ee8c41217bb0887b0e2146182cfa1b7e5507af94216c"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241018/forc-wallet-0.11.0%2Bnightly.20241018.152bfb48c3-x86_64-apple-darwin.tar.gz"
hash = "596922572f3a947960d52fcaa0c68b4c5ba104e27b95cbb9985bd0198b3d12e5"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241018/forc-wallet-0.11.0%2Bnightly.20241018.152bfb48c3-x86_64-unknown-linux-gnu.tar.gz"
hash = "db0e7827a80104087a2ca6ec677a9bae34b32d4cdafdbbff6b755e6eec0867f3"

[pkg.fuel-core]
version = "0.40.0+nightly.20241018.eea8c60525"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241018/fuel-core-0.40.0%2Bnightly.20241018.eea8c60525-aarch64-apple-darwin.tar.gz"
hash = "f14a02a1fd83bbe381af2c074f37347114f797a7ca5e4833803a1341b5fdbabb"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241018/fuel-core-0.40.0%2Bnightly.20241018.eea8c60525-aarch64-unknown-linux-gnu.tar.gz"
hash = "ccc4ffaa106d294fd2964934f2a3a0f4c2f26321b6da39123cfa2a405e9b2b6b"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241018/fuel-core-0.40.0%2Bnightly.20241018.eea8c60525-x86_64-unknown-linux-gnu.tar.gz"
hash = "a3f0d92e4f7109233eed0ee1e3c2bd0be63aa5732a3daa924936dcc276988443"

[pkg.fuel-core-keygen]
version = "0.40.0+nightly.20241018.eea8c60525"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241018/fuel-core-0.40.0%2Bnightly.20241018.eea8c60525-aarch64-apple-darwin.tar.gz"
hash = "f14a02a1fd83bbe381af2c074f37347114f797a7ca5e4833803a1341b5fdbabb"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241018/fuel-core-0.40.0%2Bnightly.20241018.eea8c60525-aarch64-unknown-linux-gnu.tar.gz"
hash = "ccc4ffaa106d294fd2964934f2a3a0f4c2f26321b6da39123cfa2a405e9b2b6b"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241018/fuel-core-0.40.0%2Bnightly.20241018.eea8c60525-x86_64-unknown-linux-gnu.tar.gz"
hash = "a3f0d92e4f7109233eed0ee1e3c2bd0be63aa5732a3daa924936dcc276988443"
