published_by = "https://github.com/FuelLabs/fuelup/actions/runs/13754824110"
date = "2025-03-10"

[pkg.forc]
version = "0.66.8+nightly.20250310.9739ec7d66"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250310/forc-binaries-0.66.8%2Bnightly.20250310.9739ec7d66-darwin_amd64.tar.gz"
hash = "ed70c931061639a331e44fec436f926b64ee935e2c067e02dba3a7bcdcf41364"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250310/forc-binaries-0.66.8%2Bnightly.20250310.9739ec7d66-darwin_arm64.tar.gz"
hash = "ed3ec04f2fd491fba37da6009fed9174110080a8baf82c5229299ed9eeb5c7b4"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250310/forc-binaries-0.66.8%2Bnightly.20250310.9739ec7d66-linux_amd64.tar.gz"
hash = "513d6db9842b9f0f95633fd2d131fa9c7d89b7656ff1c351212a5db3209a9678"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250310/forc-binaries-0.66.8%2Bnightly.20250310.9739ec7d66-linux_arm64.tar.gz"
hash = "96e388d4bb63c4954632c742b37ab41c2fdfa169ef82e5df1c7d3475f615bb1f"

[pkg.forc-wallet]
version = "0.12.0+nightly.20250310.8d59dbc462"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250310/forc-wallet-0.12.0%2Bnightly.20250310.8d59dbc462-aarch64-apple-darwin.tar.gz"
hash = "61f388c4a05092e27b3cb96056efce03300ff2f5c9904bc3783552db8f2cfc00"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250310/forc-wallet-0.12.0%2Bnightly.20250310.8d59dbc462-aarch64-unknown-linux-gnu.tar.gz"
hash = "8e34f71f6051b51aef848cd80e6e5363f85bdcca7a28e147e4ab410cb159633b"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250310/forc-wallet-0.12.0%2Bnightly.20250310.8d59dbc462-x86_64-apple-darwin.tar.gz"
hash = "3ca4f7ee82076db31a2328e2da77d4ede216fbd53cb004572c6e57d3c80b10bb"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250310/forc-wallet-0.12.0%2Bnightly.20250310.8d59dbc462-x86_64-unknown-linux-gnu.tar.gz"
hash = "729eb56d8737c273af3caabef6e0ae1609a3178f1a7a575fcd4b4517ee1f15f8"

[pkg.fuel-core]
version = "0.41.6+nightly.20250310.8e2e5bfc2b"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250310/fuel-core-0.41.6%2Bnightly.20250310.8e2e5bfc2b-aarch64-apple-darwin.tar.gz"
hash = "e2badea37c14721be68fadff7d885f3e69c6d37e519a9ff654a5e647f924bf7d"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250310/fuel-core-0.41.6%2Bnightly.20250310.8e2e5bfc2b-aarch64-unknown-linux-gnu.tar.gz"
hash = "36c3d92295ba21be779365beb82e2bce6ac7007ba3ad85cfba8b79a436a8941c"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250310/fuel-core-0.41.6%2Bnightly.20250310.8e2e5bfc2b-x86_64-apple-darwin.tar.gz"
hash = "696c737ae7911be3a8b57b6775686f66745fd35e407d796582078e002ccb6391"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250310/fuel-core-0.41.6%2Bnightly.20250310.8e2e5bfc2b-x86_64-unknown-linux-gnu.tar.gz"
hash = "66322985d83d0282b058eb26249fd677a42a058a28213002a522e7b2fb8a8a20"

[pkg.fuel-core-keygen]
version = "0.41.6+nightly.20250310.8e2e5bfc2b"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250310/fuel-core-0.41.6%2Bnightly.20250310.8e2e5bfc2b-aarch64-apple-darwin.tar.gz"
hash = "e2badea37c14721be68fadff7d885f3e69c6d37e519a9ff654a5e647f924bf7d"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250310/fuel-core-0.41.6%2Bnightly.20250310.8e2e5bfc2b-aarch64-unknown-linux-gnu.tar.gz"
hash = "36c3d92295ba21be779365beb82e2bce6ac7007ba3ad85cfba8b79a436a8941c"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250310/fuel-core-0.41.6%2Bnightly.20250310.8e2e5bfc2b-x86_64-apple-darwin.tar.gz"
hash = "696c737ae7911be3a8b57b6775686f66745fd35e407d796582078e002ccb6391"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250310/fuel-core-0.41.6%2Bnightly.20250310.8e2e5bfc2b-x86_64-unknown-linux-gnu.tar.gz"
hash = "66322985d83d0282b058eb26249fd677a42a058a28213002a522e7b2fb8a8a20"
