published_by = "https://github.com/FuelLabs/fuelup/actions/runs/12729268944"
date = "2025-01-12"

[pkg.forc]
version = "0.66.5+nightly.20250112.1192b3f134"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250112/forc-binaries-0.66.5%2Bnightly.20250112.1192b3f134-darwin_amd64.tar.gz"
hash = "8d0de8bfaee3667b0cc02fd5d5c65fa0fba29ea404b25eb158777df4b824aab5"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250112/forc-binaries-0.66.5%2Bnightly.20250112.1192b3f134-darwin_arm64.tar.gz"
hash = "d69125f1f126a8693e54cc17dcb449d50c7b98754c0dfa376ea6c11c9292848d"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250112/forc-binaries-0.66.5%2Bnightly.20250112.1192b3f134-linux_amd64.tar.gz"
hash = "d299c77f553572f11906c49689606f0396fe94eb30508d7e11f81959f82753ca"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250112/forc-binaries-0.66.5%2Bnightly.20250112.1192b3f134-linux_arm64.tar.gz"
hash = "16dc70c2d3ce3a53800a479a08f53ea0db33c341cef7ec8c4bee5a7edba043f9"

[pkg.forc-wallet]
version = "0.11.1+nightly.20250112.f4052012e0"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250112/forc-wallet-0.11.1%2Bnightly.20250112.f4052012e0-aarch64-apple-darwin.tar.gz"
hash = "ac6927335fc7fd47b0477887fae4413359efde88273b9f87cf16869b1968a1dc"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250112/forc-wallet-0.11.1%2Bnightly.20250112.f4052012e0-aarch64-unknown-linux-gnu.tar.gz"
hash = "aa65f48040010f6f48322c4b3354dae35285f90bc5b1ead7f6b85d0b4bd26cce"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250112/forc-wallet-0.11.1%2Bnightly.20250112.f4052012e0-x86_64-apple-darwin.tar.gz"
hash = "a6f36c39fe0a31d4abc4c2144d915e489843c03ef179555d2d1f309f905ef537"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250112/forc-wallet-0.11.1%2Bnightly.20250112.f4052012e0-x86_64-unknown-linux-gnu.tar.gz"
hash = "9eae49de6cf18fbb1515542ce257787ce523d70068d5bf602e7f07b13b566a0a"

[pkg.fuel-core]
version = "0.40.0+nightly.20250112.bc91cb5d5b"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250112/fuel-core-0.40.0%2Bnightly.20250112.bc91cb5d5b-aarch64-apple-darwin.tar.gz"
hash = "0cb0b534f5d879cc7adc18c933e47a0930c6345b2a8c832ae4f26f3f53218975"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250112/fuel-core-0.40.0%2Bnightly.20250112.bc91cb5d5b-aarch64-unknown-linux-gnu.tar.gz"
hash = "c609e04824733b7db6d9fc0e283eee8c9f1f935aea201a2dbf299601539e33c2"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250112/fuel-core-0.40.0%2Bnightly.20250112.bc91cb5d5b-x86_64-apple-darwin.tar.gz"
hash = "ec4ebf59a13ff063096f1dff934b9eab87d63cf7c78c9b8aee7116474017421e"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250112/fuel-core-0.40.0%2Bnightly.20250112.bc91cb5d5b-x86_64-unknown-linux-gnu.tar.gz"
hash = "01fdab10376c3fb2c633cba438bab555a99c9c0edeb8cb697ea15ca358504a8a"

[pkg.fuel-core-keygen]
version = "0.40.0+nightly.20250112.bc91cb5d5b"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250112/fuel-core-0.40.0%2Bnightly.20250112.bc91cb5d5b-aarch64-apple-darwin.tar.gz"
hash = "0cb0b534f5d879cc7adc18c933e47a0930c6345b2a8c832ae4f26f3f53218975"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250112/fuel-core-0.40.0%2Bnightly.20250112.bc91cb5d5b-aarch64-unknown-linux-gnu.tar.gz"
hash = "c609e04824733b7db6d9fc0e283eee8c9f1f935aea201a2dbf299601539e33c2"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250112/fuel-core-0.40.0%2Bnightly.20250112.bc91cb5d5b-x86_64-apple-darwin.tar.gz"
hash = "ec4ebf59a13ff063096f1dff934b9eab87d63cf7c78c9b8aee7116474017421e"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250112/fuel-core-0.40.0%2Bnightly.20250112.bc91cb5d5b-x86_64-unknown-linux-gnu.tar.gz"
hash = "01fdab10376c3fb2c633cba438bab555a99c9c0edeb8cb697ea15ca358504a8a"
