published_by = "https://github.com/FuelLabs/fuelup/actions/runs/12450065584"
date = "2024-12-22"

[pkg.forc]
version = "0.66.5+nightly.20241222.cf7b6664b5"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241222/forc-binaries-0.66.5%2Bnightly.20241222.cf7b6664b5-darwin_amd64.tar.gz"
hash = "f3c538742ab41e2ff5eddaa696b51e1fbe98e52d6c6196f9e5e3069452027565"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241222/forc-binaries-0.66.5%2Bnightly.20241222.cf7b6664b5-darwin_arm64.tar.gz"
hash = "da4b37100c4eee387e41fdc11dbaffabcd7ca7f2d859fadfbe80293673593a31"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241222/forc-binaries-0.66.5%2Bnightly.20241222.cf7b6664b5-linux_amd64.tar.gz"
hash = "1e0704046924a24bb16909018c2fecc3f718ca529488c9eddb4a1db00912efcb"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241222/forc-binaries-0.66.5%2Bnightly.20241222.cf7b6664b5-linux_arm64.tar.gz"
hash = "f195ea7cb9fd1696df3e8d58fb50b938e9b8a8e7d757b47f863dbbfabe286c81"

[pkg.forc-wallet]
version = "0.11.1+nightly.20241222.f4052012e0"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241222/forc-wallet-0.11.1%2Bnightly.20241222.f4052012e0-aarch64-apple-darwin.tar.gz"
hash = "28184cb2f279b4e3655475413cc793364310067f30a8a1141f1a332264bb157f"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241222/forc-wallet-0.11.1%2Bnightly.20241222.f4052012e0-aarch64-unknown-linux-gnu.tar.gz"
hash = "8c9d31edbab030e9f63b36e4744ba500c733a0849fe335bb298b6524f606274e"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241222/forc-wallet-0.11.1%2Bnightly.20241222.f4052012e0-x86_64-apple-darwin.tar.gz"
hash = "7d4c8b6e7be0750b6a5a2c7d8f5b50158e9e504ac52cb9935d5c28bfc485a98b"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241222/forc-wallet-0.11.1%2Bnightly.20241222.f4052012e0-x86_64-unknown-linux-gnu.tar.gz"
hash = "15faa1f8a7e3a044f8d1b80d5340700a3449936cad9cb58f9295241bce9e276c"

[pkg.fuel-core]
version = "0.40.0+nightly.20241222.4bf049d5e1"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241222/fuel-core-0.40.0%2Bnightly.20241222.4bf049d5e1-aarch64-apple-darwin.tar.gz"
hash = "3699a7160895ed97ad23601bdf402f50ba5406de7d6b3029117b22e064d06a19"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241222/fuel-core-0.40.0%2Bnightly.20241222.4bf049d5e1-aarch64-unknown-linux-gnu.tar.gz"
hash = "292699e4485a5de996ddf9a43cdcc6e5afd211401327c2cb9ded4dd3a57df340"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241222/fuel-core-0.40.0%2Bnightly.20241222.4bf049d5e1-x86_64-apple-darwin.tar.gz"
hash = "aafd3cc828e915d72fd9479dab84384bcf7d63c3103064c9469eb41a44f162a7"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241222/fuel-core-0.40.0%2Bnightly.20241222.4bf049d5e1-x86_64-unknown-linux-gnu.tar.gz"
hash = "0bfae254428f9c6b3699a18ea1e452fc293f7759330ef0304c4d0dbbc7315fe2"

[pkg.fuel-core-keygen]
version = "0.40.0+nightly.20241222.4bf049d5e1"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241222/fuel-core-0.40.0%2Bnightly.20241222.4bf049d5e1-aarch64-apple-darwin.tar.gz"
hash = "3699a7160895ed97ad23601bdf402f50ba5406de7d6b3029117b22e064d06a19"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241222/fuel-core-0.40.0%2Bnightly.20241222.4bf049d5e1-aarch64-unknown-linux-gnu.tar.gz"
hash = "292699e4485a5de996ddf9a43cdcc6e5afd211401327c2cb9ded4dd3a57df340"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241222/fuel-core-0.40.0%2Bnightly.20241222.4bf049d5e1-x86_64-apple-darwin.tar.gz"
hash = "aafd3cc828e915d72fd9479dab84384bcf7d63c3103064c9469eb41a44f162a7"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20241222/fuel-core-0.40.0%2Bnightly.20241222.4bf049d5e1-x86_64-unknown-linux-gnu.tar.gz"
hash = "0bfae254428f9c6b3699a18ea1e452fc293f7759330ef0304c4d0dbbc7315fe2"
