published_by = "https://github.com/FuelLabs/fuelup/actions/runs/17225258560"
date = "2025-08-26"

[pkg.forc]
version = "0.69.1+nightly.20250826.a347631478"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250826/forc-binaries-0.69.1%2Bnightly.20250826.a347631478-darwin_amd64.tar.gz"
hash = "974a2fb08ddebb2c4963d9691a402c01e00e69ee1a1839cfad3b96683ae2b25a"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250826/forc-binaries-0.69.1%2Bnightly.20250826.a347631478-darwin_arm64.tar.gz"
hash = "3e803d5f0d72152506f6dcd53dc727cb1b6fc672a50688d8ec49d8d5b0bcdce6"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250826/forc-binaries-0.69.1%2Bnightly.20250826.a347631478-linux_amd64.tar.gz"
hash = "38575f5d916bfafbd38bac4e92b94fbbfc34800340b9d29f0bbafc382efd5964"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250826/forc-binaries-0.69.1%2Bnightly.20250826.a347631478-linux_arm64.tar.gz"
hash = "e97b36702b962370a506faf3908624f48aa5d0b150fd4a6fcdb6fa2b90c22582"

[pkg.forc-wallet]
version = "0.15.1+nightly.20250826.9fea98d095"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250826/forc-wallet-0.15.1%2Bnightly.20250826.9fea98d095-aarch64-apple-darwin.tar.gz"
hash = "e169dc97ab579602844d498a2680addf5849a91a7a0908052e5ff94ac00370ef"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250826/forc-wallet-0.15.1%2Bnightly.20250826.9fea98d095-aarch64-unknown-linux-gnu.tar.gz"
hash = "a01db5411db9a7531e96cfd8b962b786fa0730cae30f7e5c42c4d63f4d98b31a"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250826/forc-wallet-0.15.1%2Bnightly.20250826.9fea98d095-x86_64-apple-darwin.tar.gz"
hash = "76aa2e011f271e9a3d160216deef0532980e67f5fff71cc08af53dae39d12c27"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250826/forc-wallet-0.15.1%2Bnightly.20250826.9fea98d095-x86_64-unknown-linux-gnu.tar.gz"
hash = "04970706a209639ab9069755d797aa85e5268ccda7ad733d25362d638980bed6"

[pkg.fuel-core]
version = "0.46.0+nightly.20250826.33238c6e10"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250826/fuel-core-0.46.0%2Bnightly.20250826.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "03efaaf148ca67cb89d90e2f3fd185da460e28e34f7bb9a1cdb0c59b44eb70fd"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250826/fuel-core-0.46.0%2Bnightly.20250826.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "4e9eb56b0bc07509d6ffef0963d61d5de016c310077a13b74d2440cb61fd290d"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250826/fuel-core-0.46.0%2Bnightly.20250826.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "6e8ab6b4cb751cee6ecea3aaa53c9ab9ec7066e3dcc139fa6bdfbb5146b3e3d1"

[pkg.fuel-core-keygen]
version = "0.46.0+nightly.20250826.33238c6e10"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250826/fuel-core-0.46.0%2Bnightly.20250826.33238c6e10-aarch64-apple-darwin.tar.gz"
hash = "03efaaf148ca67cb89d90e2f3fd185da460e28e34f7bb9a1cdb0c59b44eb70fd"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250826/fuel-core-0.46.0%2Bnightly.20250826.33238c6e10-aarch64-unknown-linux-gnu.tar.gz"
hash = "4e9eb56b0bc07509d6ffef0963d61d5de016c310077a13b74d2440cb61fd290d"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250826/fuel-core-0.46.0%2Bnightly.20250826.33238c6e10-x86_64-unknown-linux-gnu.tar.gz"
hash = "6e8ab6b4cb751cee6ecea3aaa53c9ab9ec7066e3dcc139fa6bdfbb5146b3e3d1"
