name: Publish fuelup-init.sh

on:
  release:
    types: [published]

env:
  FUELUP_INIT_DIR: ./fuelup-init.sh.d/
  FUELUP_VERSION_DIR: ./fuelup-version.d/

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  deploy:
    needs: cancel-previous-runs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy fuelup-init.sh
        run: |
          mkdir -p ${{ env.FUELUP_INIT_DIR }}
          cp fuelup-init.sh ${{ env.FUELUP_INIT_DIR }}

      - name: Deploy latest fuelup init
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_dir: ${{ env.FUELUP_INIT_DIR }}
          destination_dir: ./

      - name: Get latest tag
        run: |
          mkdir -p ${{ env.FUELUP_VERSION_DIR }}
          echo ${GITHUB_REF#refs/tags/} >> fuelup-version
          cp fuelup-version ${{ env.FUELUP_VERSION_DIR }}

      - name: Deploy latest fuelup version
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_dir: ${{ env.FUELUP_VERSION_DIR }}
          destination_dir: ./
