published_by = "https://github.com/FuelLabs/fuelup/actions/runs/14544318679"
date = "2025-04-19"

[pkg.forc]
version = "0.67.0+nightly.20250419.3afc5c18c8"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250419/forc-binaries-0.67.0%2Bnightly.20250419.3afc5c18c8-darwin_amd64.tar.gz"
hash = "f7f631009b19c59cbf39f2205cd2cc12cb517719f833c87daa92a37645754725"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250419/forc-binaries-0.67.0%2Bnightly.20250419.3afc5c18c8-darwin_arm64.tar.gz"
hash = "7947da2c9792aea859f8bab3c4dc9e5fc3c356ae353553bf6ff3672aa6e82667"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250419/forc-binaries-0.67.0%2Bnightly.20250419.3afc5c18c8-linux_amd64.tar.gz"
hash = "d077cebc8134bdb5cc9eaed5b0d32485402a2381d56431f617ea6bb949185e10"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250419/forc-binaries-0.67.0%2Bnightly.20250419.3afc5c18c8-linux_arm64.tar.gz"
hash = "29fb0be95833f9743f6592854451d40792ed0b1b485bfd75e1e74a3c58d3ee87"

[pkg.forc-wallet]
version = "0.13.0+nightly.20250419.90a8cb2dc4"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250419/forc-wallet-0.13.0%2Bnightly.20250419.90a8cb2dc4-aarch64-apple-darwin.tar.gz"
hash = "6ff19b2924f3e4fd2733d7818fa96eacb4bc2b03d04cca0b223363dbc6ab4451"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250419/forc-wallet-0.13.0%2Bnightly.20250419.90a8cb2dc4-aarch64-unknown-linux-gnu.tar.gz"
hash = "84d8a3ea848ffe99a7db016fe2d94d9ef4dcec73ddf12d3f91b31cb9f6ce7e4b"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250419/forc-wallet-0.13.0%2Bnightly.20250419.90a8cb2dc4-x86_64-apple-darwin.tar.gz"
hash = "44a052d08f2be7b25f360bb38ca6ed8a1f57393fca716edf8db9115014b7b2fc"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250419/forc-wallet-0.13.0%2Bnightly.20250419.90a8cb2dc4-x86_64-unknown-linux-gnu.tar.gz"
hash = "38700744fe8591c7e7df36bc108f7a1e5a12ced2c4eae741d872d181e26c826d"

[pkg.fuel-core]
version = "0.43.0+nightly.20250419.926b50bcb7"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250419/fuel-core-0.43.0%2Bnightly.20250419.926b50bcb7-aarch64-apple-darwin.tar.gz"
hash = "e283c202a601ae25e8ce22e45a10ab4cf9a6875d5e57b7b1457773ac44434907"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250419/fuel-core-0.43.0%2Bnightly.20250419.926b50bcb7-aarch64-unknown-linux-gnu.tar.gz"
hash = "c1d6961cb15ec41fb71b1ff70010a084712f0b8fac34353bdfc5546cd3dc9454"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250419/fuel-core-0.43.0%2Bnightly.20250419.926b50bcb7-x86_64-unknown-linux-gnu.tar.gz"
hash = "b74d4962a7359e53d9aa0442eeebe0459f985298602cfb00741c55418572d722"

[pkg.fuel-core-keygen]
version = "0.43.0+nightly.20250419.926b50bcb7"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250419/fuel-core-0.43.0%2Bnightly.20250419.926b50bcb7-aarch64-apple-darwin.tar.gz"
hash = "e283c202a601ae25e8ce22e45a10ab4cf9a6875d5e57b7b1457773ac44434907"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250419/fuel-core-0.43.0%2Bnightly.20250419.926b50bcb7-aarch64-unknown-linux-gnu.tar.gz"
hash = "c1d6961cb15ec41fb71b1ff70010a084712f0b8fac34353bdfc5546cd3dc9454"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20250419/fuel-core-0.43.0%2Bnightly.20250419.926b50bcb7-x86_64-unknown-linux-gnu.tar.gz"
hash = "b74d4962a7359e53d9aa0442eeebe0459f985298602cfb00741c55418572d722"
